import {meta} from '../catalog';
import type {Lesson} from '../types';

const r = String.raw;

const lesson: Lesson = {
  ...meta(2),
  topics: ['Desmos asoslari', 'Grafik bilan yechish', 'Sistemalar', 'SPR qoidalari', 'Tuzoqlar'],
  cover: [
    r`Assalomu alaykum! SAT Math kursining ikkinchi darsiga xush kelibsiz. Bugungi mavzu — Desmos kalkulyatori va javob kiritish qoidalari.`,
    r`Desmos bilan tenglama va sistemalarni grafik orqali yechishni, qaysi savolda Desmos foydali ekanini va SPR savollariga javobni qanday to'g'ri kiritishni o'rganamiz.`,
  ],
  goals: [
    r`Desmos'da grafik chizish va nuqtalarni topish`,
    r`Tenglama va sistemalarni grafik orqali yechish`,
    r`Desmos qachon foydali, qachon emasligini bilish`,
    r`SPR javoblarini xatosiz kiritish`,
  ],
  goalsSay: [
    r`Bu darsning to'rtta maqsadi bor.`,
    r`Birinchidan, Desmos'da grafik chizishni va muhim nuqtalarni — ildizlar, kesishishlar, uchlarni — topishni o'rganasiz.`,
    r`Ikkinchidan, tenglama va tenglamalar sistemasini algebrasiz, grafik orqali bir necha soniyada yechishni ko'rasiz.`,
    r`Uchinchidan, Desmos qaysi savolda vaqtni tejashini, qaysi savolda esa aksincha, vaqtni yeyishini bilib olasiz.`,
    r`To'rtinchidan, javobni o'zingiz yozadigan SPR savollarida ball yo'qotmaslik uchun kiritish qoidalarini o'rganasiz.`,
    r`Natijada Desmos sizning eng kuchli yordamchingizga aylanadi va kiritishdagi kulgili xatolar bilan ball yo'qotmaysiz.`,
  ],
  goalsResult: r`Desmos — tezlik, to'g'ri kiritish — ishonchli ball`,
  slides: [
    {
      type: 'cards',
      kicker: 'DESMOS',
      title: 'Desmos nimalar qila oladi?',
      cards: [
        {title: 'Grafik chizish', text: r`Tenglamani yozing — grafik darhol paydo bo'ladi`, icon: 'chart'},
        {title: 'Nuqtalarni topish', text: r`Ildiz, kesishish yoki uchni bosing — koordinatalar chiqadi`, icon: 'target'},
        {title: 'Hisoblash', text: r`Kasr, daraja, ildiz: $\sqrt{50}$, $2^{10}$, $\frac{7}{8}$`, icon: 'calc'},
        {title: 'Slayder', text: r`$y=mx+b$ yozing — $m$ va $b$ ni surib ko'ring`, icon: 'bolt'},
      ],
      banner: r`Desmos vaqtni tejaydi, lekin fikrlashni almashtirmaydi`,
      say: [
        r`Desmos — test ichidagi grafik kalkulyator. U to'rtta asosiy ishni bajaradi.`,
        r`Birinchi: grafik chizadi. Tenglamani yozasiz, grafik darhol ekranda paydo bo'ladi.`,
        r`Ikkinchi: muhim nuqtalarni ko'rsatadi. Grafikdagi ildiz, kesishish nuqtasi yoki parabolaning uchini bossangiz, uning koordinatalari chiqadi.`,
        r`Uchinchi: oddiy kalkulyator kabi hisoblaydi — kasrlar, darajalar, ildizlar bilan.`,
        r`To'rtinchi: slayder. Masalan, y teng m x plyus b deb yozsangiz, Desmos m va b uchun slayder taklif qiladi va ularni o'zgartirib, grafik qanday o'zgarishini ko'rasiz.`,
        r`Lekin yodda tuting: Desmos vaqtni tejaydi, ammo savolni tushunish va to'g'ri tenglama tuzish baribir sizning ishingiz.`,
      ],
    },
    {
      type: 'graph',
      kicker: 'GRAFIK BILAN YECHISH',
      title: r`$x^2-5x+6=0$ ni Desmos'da yechamiz`,
      x: [-1, 6],
      y: [-2, 7],
      items: [
        {kind: 'fn', f: (x) => x * x - 5 * x + 6, label: r`$y=x^2-5x+6$`, note: r`1. Chap tomonni $y=$ qilib yozamiz — parabola chiqadi`},
        {kind: 'point', x: 2, y: 0, label: r`$(2,\,0)$`, color: '#22C55E', note: r`2. $x$ o'qi bilan birinchi kesishish: $x=2$`},
        {kind: 'point', x: 3, y: 0, label: r`$(3,\,0)$`, color: '#22C55E', note: r`3. Ikkinchi kesishish: $x=3$`},
        {kind: 'note', note: r`Ildizlar — grafik $x$ o'qini kesib o'tgan nuqtalar: $x=2$ va $x=3$`},
      ],
      say: [
        r`Keling, birinchi tenglamani Desmos bilan yechamiz: x kvadrat minus besh x plyus olti teng nol.`,
        r`Tenglamaning chap tomonini y teng deb yozamiz. Ekranda parabola paydo bo'ladi.`,
        r`Tenglamaning yechimi — bu y nolga teng bo'lgan nuqtalar, ya'ni grafik x o'qini kesib o'tgan joylar. Birinchi nuqtani bosamiz: x teng ikki.`,
        r`Ikkinchi nuqta: x teng uch.`,
        r`Demak, tenglamaning ildizlari ikki va uch. Hech qanday ko'paytuvchilarga ajratish yoki formula kerak bo'lmadi — bor-yo'g'i o'n soniya.`,
      ],
    },
    {
      type: 'graph',
      kicker: 'SISTEMALAR',
      title: 'Sistemaning yechimi — kesishish nuqtasi',
      x: [-2, 8],
      y: [-2, 10],
      items: [
        {kind: 'fn', f: (x) => 2 * x + 1, label: r`$y=2x+1$`, note: r`Birinchi tenglamani yozamiz: $y=2x+1$`},
        {kind: 'fn', f: (x) => -x + 7, label: r`$y=-x+7$`, note: r`Ikkinchisini yozamiz: $y=-x+7$`},
        {kind: 'point', x: 2, y: 5, label: r`$(2,\,5)$`, color: '#FFFFFF', note: r`Kesishish nuqtasini bosamiz: $x=2,\ y=5$`},
        {kind: 'note', note: r`Tekshiruv: $2\cdot2+1=5$ va $-2+7=5$ ✓`},
      ],
      say: [
        r`Endi tenglamalar sistemasini yechamiz: y teng ikki x plyus bir va y teng minus x plyus yetti.`,
        r`Birinchi tenglamani Desmos'ga yozamiz — to'g'ri chiziq chiqadi.`,
        r`Ikkinchi tenglamani yangi qatorga yozamiz — ikkinchi to'g'ri chiziq.`,
        r`Sistemaning yechimi — ikkala chiziq kesishgan nuqta. Uni bossak, koordinatalar chiqadi: x teng ikki, y teng besh.`,
        r`Tekshirib ko'ramiz: ikki karra ikki plyus bir — besh; minus ikki plyus yetti — ham besh. To'g'ri. Agar sistema y ga nisbatan yechilmagan bo'lsa ham, masalan uch x plyus ikki y teng o'n ikki, Desmos uni shundayligicha qabul qiladi.`,
      ],
    },
    {
      type: 'compare',
      kicker: 'STRATEGIYA',
      title: 'Desmos qachon foydali?',
      cards: [
        {title: 'Desmos — eng tez', rule: 'Kvadrat tenglama, sistema, kesishish nuqtasi', example: r`$x^2+2x=8$ — ikkala tomonni chizing`},
        {title: 'Ikkalasi ham', rule: 'Ekvivalent ifoda, tengsizlik, tekshiruv', example: r`Ikkala ifodani chizing: ustma-ust tushsa — teng`},
        {title: 'Qo\'lda — tezroq', rule: 'Bir-ikki qadamli tenglama, matnli masalani tuzish', example: r`$3x=12$ — boshda 2 soniya`},
      ],
      say: [
        r`Desmos har doim ham eng tez yo'l emas. Savollarni uch guruhga ajratamiz.`,
        r`Birinchi guruh — Desmos eng tez ishlaydigan savollar: kvadrat tenglamalar, sistemalar, kesishish nuqtalari. Bu yerda grafik chizish algebradan ancha tez.`,
        r`Ikkinchi guruh — ikkala usul ham yaxshi: ekvivalent ifodalar, tengsizliklar va javobni tekshirish. Masalan, ikki ifoda tengmi degan savolda ikkalasini chizasiz: grafiklar ustma-ust tushsa, ular ekvivalent.`,
        r`Uchinchi guruh — qo'lda tezroq: uch x teng o'n ikki kabi bir-ikki qadamli tenglamalar va matnli masalada tenglamani tuzish. Desmos tenglamani siz uchun tuzib bermaydi.`,
      ],
    },
    {
      type: 'cards',
      kicker: 'DESMOS',
      title: "Desmos'da xato qilmaslik uchun 4 qoida",
      cards: [
        {title: 'Ko\'paytirishni aniq yozing', text: r`$2(x+1)$ — to'g'ri; qavslarni unutmang`},
        {title: 'Kasrni "/" bilan', text: r`$\frac{x+1}{3}$ uchun: (x+1)/3 — surat qavsda`},
        {title: 'Grafik ko\'rinmasa', text: r`Zoom yoki uy belgisini bosing — nuqtalar ekrandan tashqarida bo'lishi mumkin`},
        {title: 'Nuqtani bosing', text: r`Koordinatalarni ko'z bilan taxmin qilmang — kulrang nuqtani bosing`},
      ],
      say: [
        r`Desmos'da ham xato qilish mumkin. To'rtta qoidani eslab qoling.`,
        r`Birinchi: ko'paytirish va qavslarni aniq yozing. Ikki karra x plyus bir uchun qavs albatta kerak.`,
        r`Ikkinchi: kasrni yozganda suratni qavsga oling. x plyus bir, bo'lingan uchga — qavs bo'lmasa, Desmos faqat birni uchga bo'ladi.`,
        r`Uchinchi: grafik yoki nuqta ko'rinmasa, kattalashtiring yoki kichraytiring. Ba'zan kesishish nuqtasi ekrandan tashqarida bo'ladi.`,
        r`To'rtinchi: koordinatalarni hech qachon ko'z bilan taxmin qilmang. Nuqtani bosing — aniq qiymat chiqadi.`,
      ],
    },
    {
      type: 'example',
      kicker: 'SAT MISOLI',
      title: 'Desmos bilan test savoli',
      question: r`Which of the following is a solution to $x^2+2x=8$?`,
      choices: [r`$-2$`, r`$1$`, r`$2$`, r`$4$`],
      steps: [
        {m: r`y=x^2+2x,\quad y=8`, note: r`ikkala tomonni alohida chizamiz`},
        {m: r`x=-4,\quad x=2`, note: r`kesishish nuqtalari`},
        {m: r`x=2\ \Rightarrow\ \text{C}`, note: r`variantlarda faqat $2$ bor`},
      ],
      answer: r`C`,
      tip: r`Ikki tomonli tenglamada chap va o'ng tomonni alohida $y=$ qilib chizing — kesishishlar yechim bo'ladi.`,
      say: [
        r`Endi haqiqiy SAT savoli: which of the following is a solution to x kvadrat plyus ikki x teng sakkiz? Variantlar: minus ikki, bir, ikki va to'rt.`,
        r`Tenglamani nolga keltirib o'tirmaymiz. Chap tomonni y teng x kvadrat plyus ikki x, o'ng tomonni y teng sakkiz deb ikkita grafik chizamiz.`,
        r`Ular ikki nuqtada kesishadi: x teng minus to'rt va x teng ikki.`,
        r`Variantlarga qaraymiz: minus to'rt yo'q, ikki esa bor.`,
        r`Demak, javob C.`,
        r`Maslahat: tenglamaning ikkala tomonida ham x bo'lsa, ularni alohida grafik qilib chizing. Kesishish nuqtalarining x koordinatalari — tenglamaning yechimlari.`,
      ],
    },
    {
      type: 'example',
      kicker: 'SAT MISOLI',
      title: 'Ekvivalent ifodani Desmos bilan topish',
      question: r`Which expression is equivalent to $(x+3)^2-9$?`,
      choices: [r`$x^2+9$`, r`$x^2+6x$`, r`$x^2-6x$`, r`$x^2+6x+18$`],
      steps: [
        {m: r`y=(x+3)^2-9`, note: r`berilgan ifodani chizamiz`},
        {m: r`y=x^2+6x`, note: r`variantlarni birma-bir chizamiz`},
        {m: r`\text{grafiklar ustma-ust}`, note: r`faqat B to'liq mos tushadi`},
      ],
      answer: r`B`,
      tip: r`Algebra bilan tekshiruv: $(x+3)^2-9=x^2+6x+9-9=x^2+6x$.`,
      say: [
        r`Desmos ekvivalent ifodalar savolida ham yordam beradi. Which expression is equivalent to x plyus uch, kvadrat, minus to'qqiz?`,
        r`Avval berilgan ifodani y teng deb Desmos'ga yozamiz — parabola chiqadi.`,
        r`Endi variantlarni bittadan yangi qatorga yozamiz. B variant — x kvadrat plyus olti x — yozilganda, yangi grafik eskisining ustiga aniq tushadi.`,
        r`Boshqa variantlarning grafiklari boshqa joydan o'tadi. Ekvivalent ifodalarning grafiklari doim butunlay ustma-ust tushadi.`,
        r`Demak, javob B.`,
        r`Algebra bilan ham tekshirish oson: qavsni ochsak, x kvadrat plyus olti x plyus to'qqiz, minus to'qqiz — x kvadrat plyus olti x. Qaysi usul siz uchun tezroq bo'lsa, o'shani tanlang.`,
      ],
    },
    {
      type: 'table',
      kicker: 'JAVOB KIRITISH',
      title: 'SPR: javobni qanday kiritish kerak',
      head: ['Holat', "To'g'ri", "Noto'g'ri"],
      rows: [
        [r`Kasr`, r`$7/2$ yoki $3.5$`, r`$3\ 1/2$ (aralash son)`],
        [r`Manfiy son`, r`$-4$, $-3/5$`, r`minus belgisini tushirib qoldirish`],
        [r`Cheksiz o'nli kasr`, r`$2/3$, $.6666$, $.6667$`, r`$0.66$, $0.67$`],
        [r`Birlik va belgi`, r`$25$`, r`$25\%$, 25 sm, 25 dollar`],
        [r`Uzunlik`, r`musbat: 5 belgigacha, manfiy: 6 belgigacha`, r`$1/3$ ni $0.3$ deb yozish`],
      ],
      banner: r`Bir nechta to'g'ri javob bo'lsa — faqat bittasini kiriting`,
      say: [
        r`Endi javob kiritish qoidalari. SPR savollarida javobni o'zingiz yozasiz va bu yerda kichik xato butun ballni olib ketadi.`,
        r`Birinchi qoida: kasrni oddiy kasr yoki o'nli kasr shaklida yozish mumkin — yetti ikkidan yoki uch butun o'ndan besh. Lekin aralash son — uch butun ikkidan bir — qabul qilinmaydi, chunki tizim uni o'ttiz bir ikkidan deb o'qiydi.`,
        r`Ikkinchi: manfiy javobda minus belgisini albatta qo'ying.`,
        r`Uchinchi: cheksiz o'nli kasr. Ikki uchdan birni oddiy kasr qilib yozing, yoki maydonni to'liq to'ldiring: nuqta olti olti olti olti yoki nuqta olti olti olti yetti. Nol butun oltmish olti yoki oltmish yetti — noto'g'ri, chunki aniqlik yetarli emas.`,
        r`To'rtinchi: birlik va belgilarni yozmang — foiz, santimetr yoki dollar emas, faqat son.`,
        r`Beshinchi: musbat javob uchun maydonga beshtagacha, manfiy javob uchun minus bilan birga oltitagacha belgi sig'adi.`,
        r`Va nihoyat: agar savolning bir nechta to'g'ri javobi bo'lsa, ulardan faqat bittasini kiriting.`,
      ],
    },
    {
      type: 'example',
      kicker: 'SPR MISOLI',
      title: 'Kasr javobni kiritish',
      label: 'SPR SAVOLI',
      question: r`If $6x+1=5$, what is the value of $x$?`,
      steps: [
        {m: r`6x=4`, note: r`ikkala tomondan $1$ ni ayiramiz`},
        {m: r`x=\frac{4}{6}=\frac{2}{3}`, note: r`$6$ ga bo'lamiz va qisqartiramiz`},
        {m: r`2/3,\ \ .6666,\ \ .6667`, note: r`uchala kiritish ham to'g'ri`},
      ],
      answer: r`$2/3$`,
      tip: r`$0.67$ — **noto'g'ri**: o'nli kasr maydonni to'liq to'ldirishi kerak. Eng xavfsizi — oddiy kasr.`,
      say: [
        r`Bir misolda ko'ramiz. If six x plus one equals five, what is the value of x?`,
        r`Ikkala tomondan birni ayiramiz: olti x teng to'rt.`,
        r`Oltiga bo'lamiz: x teng to'rt oltidan, qisqartirsak, ikki uchdan bir.`,
        r`Endi kiritish. Ikki slesh uch, nuqta olti olti olti olti yoki nuqta olti olti olti yetti — uchalasi ham qabul qilinadi.`,
        r`Javob: ikki uchdan bir.`,
        r`Lekin nol butun oltmish yetti deb yozsangiz, javob noto'g'ri hisoblanadi. Eng xavfsiz yo'l — javobni oddiy kasr ko'rinishida kiritish.`,
      ],
    },
    {
      type: 'example',
      kicker: 'SPR MISOLI',
      title: 'Manfiy javobni kiritish',
      label: 'SPR SAVOLI',
      question: r`If $3(x+4)=x$, what is the value of $x$?`,
      steps: [
        {m: r`3x+12=x`, note: r`qavsni ochamiz`},
        {m: r`2x=-12`, note: r`$x$ larni bir tomonga yig'amiz`},
        {m: r`x=-6`, note: r`$2$ ga bo'lamiz`},
      ],
      answer: r`$-6$`,
      tip: r`Kiritishda minus belgisini unutmang: **-6**. Tekshiruv: $3(-6+4)=-6$ ✓`,
      say: [
        r`Yana bir SPR misoli. If three times x plus four equals x, what is the value of x?`,
        r`Qavsni ochamiz: uch x plyus o'n ikki teng x.`,
        r`x larni bir tomonga yig'amiz: ikki x teng minus o'n ikki.`,
        r`Ikkiga bo'lamiz: x teng minus olti.`,
        r`Javob: minus olti.`,
        r`Kiritishda minus belgisini albatta qo'ying — minussiz olti butunlay boshqa javob. Va tekshiring: minus olti plyus to'rt — minus ikki, uchga ko'paytirsak — minus olti. To'g'ri.`,
      ],
    },
    {
      type: 'trap',
      title: 'Foiz belgisi',
      question: r`What percent of $80$ is $20$? (SPR)`,
      wrong: r`$25\%$`,
      why: r`Maydonga $\%$ belgisini kiritib bo'lmaydi — savol "percent" deb aytib bo'lgan.`,
      right: r`Faqat **25** ni kiriting: savoldagi birlik (percent) allaqachon berilgan.`,
      say: [
        r`Endi ko'p uchraydigan tuzoq. What percent of eighty is twenty? Bu SPR savoli.`,
        r`Ko'p o'quvchilar yigirma besh foiz deb, foiz belgisi bilan yozishga harakat qiladi. Lekin maydonga foiz belgisini kiritib bo'lmaydi. Savolning o'zi "percent" deb so'rab turibdi — birlik allaqachon berilgan.`,
        r`To'g'ri javob: faqat yigirma besh soni. Xuddi shunday, dollar, santimetr yoki gradus so'ralganda ham faqat sonni yozasiz.`,
      ],
    },
  ],
  recap: [
    r`Desmos: kvadrat tenglama, sistema va kesishishlar uchun eng tez yo'l`,
    r`Koordinatalarni taxmin qilmang — nuqtani bosing`,
    r`SPR: faqat son; aralash son, birlik va $\%$ yo'q; bitta javob kiriting`,
  ],
  homework: r`platformada 10 ta savolni Desmos bilan yeching`,
  recapSay: [
    r`Darsni xulosa qilamiz.`,
    r`Desmos — kvadrat tenglamalar, sistemalar va kesishish nuqtalari uchun eng tez yo'l.`,
    r`Koordinatalarni hech qachon taxmin qilmang — nuqtani bosing.`,
    r`SPR savollarida faqat son yozing: aralash son, birlik va foiz belgisisiz, bir nechta javob bo'lsa — faqat bittasini.`,
    r`Hozir platformada o'nta savolni Desmos yordamida yeching. Keyingi darsda bir noma'lumli chiziqli tenglamalarni o'rganamiz.`,
    r`Ko'rishguncha!`,
  ],
};

export default lesson;
