import {meta} from '../catalog';
import type {Lesson} from '../types';

const r = String.raw;

const lesson: Lesson = {
  ...meta(3),
  topics: ['Oltin qoida', 'Yechish algoritmi', 'Kasrli tenglamalar', 'Ifodani topish', 'Matnli masala'],
  cover: [
    r`Assalomu alaykum! Uchinchi darsga xush kelibsiz. Bugun Algebra moduliga kiramiz va eng asosiy mavzudan boshlaymiz — bir noma'lumli chiziqli tenglamalar.`,
    r`Yechish algoritmini, kasrli va o'nli tenglamalarni, SAT'ning sevimli hiylasi — x ni emas, ifodani so'rashni va matnli masalalarni ko'rib chiqamiz.`,
  ],
  goals: [
    r`Chiziqli tenglamani 4 qadamda yechish`,
    r`Kasr va o'nli kasrli tenglamalarni tez soddalashtirish`,
    r`$x$ ni topmasdan so'ralgan ifodani topish`,
    r`Matnli masaladan tenglama tuzish`,
  ],
  goalsSay: [
    r`Bugungi darsning to'rtta maqsadi.`,
    r`Birinchi: har qanday chiziqli tenglamani to'rt qadamli algoritm bilan xatosiz yechish.`,
    r`Ikkinchi: kasrli va o'nli kasrli tenglamalarni bir harakat bilan butun sonli tenglamaga aylantirish.`,
    r`Uchinchi: SAT ko'pincha x ni emas, x qatnashgan ifodani so'raydi. Bunday savollarni x ni topmasdan, bir qadamda yechishni o'rganamiz.`,
    r`To'rtinchi: matnli masaladagi gaplarni tenglamaga aylantirish.`,
    r`Bu mavzu Algebra domenining poydevori: undan keyingi barcha darslarda shu ko'nikmalar ishlatiladi.`,
  ],
  goalsResult: r`Algebra savollarining poydevori — tez va xatosiz`,
  slides: [
    {
      type: 'cards',
      kicker: 'ASOSIY TUSHUNCHA',
      title: 'Chiziqli tenglama nima?',
      cards: [
        {title: "Ko'rinishi", text: r`$ax+b=c$ — $x$ faqat birinchi darajada qatnashadi`, icon: 'book'},
        {title: 'Maqsad', text: r`$x$ ni bir tomonda yolg'iz qoldirish: $x=\ldots$`, icon: 'target'},
        {title: 'Oltin qoida', text: r`Ikkala tomonga **bir xil** amal: qo'shish, ayirish, ko'paytirish, bo'lish`, icon: 'bulb'},
      ],
      banner: r`Tenglama — tarozi: bir pallaga nima qilsangiz, ikkinchisiga ham shuni qiling`,
      say: [
        r`Avval chiziqli tenglama nima ekanini aniqlab olaylik.`,
        r`Chiziqli tenglamada noma'lum x faqat birinchi darajada qatnashadi: x kvadrat ham, bir bo'lingan x ham yo'q. Umumiy ko'rinishi: a x plyus b teng c.`,
        r`Bizning maqsadimiz — x ni tenglamaning bir tomonida yolg'iz qoldirish, ya'ni x teng qandaydir son ko'rinishiga keltirish.`,
        r`Buning uchun bitta oltin qoida bor: tenglamaning ikkala tomoniga bir xil amalni bajaramiz — bir xil son qo'shamiz, ayiramiz, ko'paytiramiz yoki bo'lamiz.`,
        r`Tenglamani tarozi deb tasavvur qiling: bir pallaga nima qilsangiz, ikkinchisiga ham xuddi shuni qilishingiz kerak, aks holda muvozanat buziladi.`,
      ],
    },
    {
      type: 'cards',
      kicker: 'ALGORITM',
      title: 'Chiziqli tenglamani yechish: 4 qadam',
      cards: [
        {title: 'Qavslarni oching', text: r`$3(x-2)=3x-6$ — har bir hadga ko'paytiring`},
        {title: 'Kasrlardan qutuling', text: r`Ikkala tomonni umumiy maxrajga ko'paytiring`},
        {title: "Hadlarni yig'ing", text: r`$x$ li hadlar — bir tomonga, sonlar — ikkinchi tomonga`},
        {title: "Bo'ling va tekshiring", text: r`Koeffitsiyentga bo'ling, javobni tenglamaga qo'ying`},
      ],
      say: [
        r`Har qanday chiziqli tenglamani yechish uchun to'rt qadamli algoritm.`,
        r`Birinchi qadam: qavslarni oching. Qavs oldidagi sonni qavs ichidagi har bir hadga ko'paytiring — minus belgilarga ayniqsa e'tibor bering.`,
        r`Ikkinchi qadam: agar kasrlar bo'lsa, ulardan qutuling. Buning uchun ikkala tomonni barcha maxrajlarning umumiy karralisiga ko'paytiring.`,
        r`Uchinchi qadam: x qatnashgan hadlarni bir tomonga, oddiy sonlarni ikkinchi tomonga yig'ing. Had tomondan tomonga o'tganda ishorasi o'zgaradi.`,
        r`To'rtinchi qadam: x oldidagi koeffitsiyentga bo'ling va topilgan javobni dastlabki tenglamaga qo'yib tekshiring.`,
      ],
    },
    {
      type: 'example',
      kicker: '1-MISOL',
      title: 'Qavsli tenglama',
      label: 'MISOL',
      question: r`Solve $5(x-2)=3x+4$.`,
      steps: [
        {m: r`5x-10=3x+4`, note: r`qavsni ochamiz`},
        {m: r`5x-3x=4+10`, note: r`hadlarni yig'amiz`},
        {m: r`2x=14`, note: r`soddalashtiramiz`},
        {m: r`x=7`, note: r`$2$ ga bo'lamiz`},
      ],
      answer: r`$x=7$`,
      tip: r`Tekshiruv: $5(7-2)=25$ va $3\cdot7+4=25$ ✓`,
      say: [
        r`Birinchi misol: besh karra, x minus ikki, teng uch x plyus to'rt.`,
        r`Qavsni ochamiz: besh x minus o'n teng uch x plyus to'rt.`,
        r`Uch x ni chapga, minus o'nni o'ngga o'tkazamiz — ishoralar o'zgaradi: besh x minus uch x teng to'rt plyus o'n.`,
        r`Soddalashtirsak: ikki x teng o'n to'rt.`,
        r`Ikkiga bo'lamiz: x teng yetti.`,
        r`Javob: x teng yetti.`,
        r`Tekshiramiz: chap tomon besh karra besh — yigirma besh; o'ng tomon yigirma bir plyus to'rt — ham yigirma besh. To'g'ri.`,
      ],
    },
    {
      type: 'example',
      kicker: '2-MISOL',
      title: 'Kasrli tenglama',
      label: 'MISOL',
      question: r`Solve $\dfrac{x}{3}+\dfrac{x}{4}=7$.`,
      steps: [
        {m: r`12\cdot\frac{x}{3}+12\cdot\frac{x}{4}=12\cdot7`, note: r`umumiy maxraj — $12$`},
        {m: r`4x+3x=84`, note: r`kasrlar yo'qoldi`},
        {m: r`7x=84`},
        {m: r`x=12`},
      ],
      answer: r`$x=12$`,
      tip: r`Har bir hadni ko'paytirishni unutmang — o'ng tomondagi $7$ ham $12$ ga ko'paytiriladi!`,
      say: [
        r`Ikkinchi misol: x uchdan plyus x to'rtdan teng yetti.`,
        r`Maxrajlar uch va to'rt, ularning umumiy karralisi o'n ikki. Tenglamaning har bir hadini o'n ikkiga ko'paytiramiz.`,
        r`O'n ikki x uchdan — to'rt x; o'n ikki x to'rtdan — uch x; o'ng tomonda o'n ikki karra yetti — sakson to'rt. Kasrlar yo'qoldi.`,
        r`Chap tomonni qo'shamiz: yetti x teng sakson to'rt.`,
        r`Yettiga bo'lamiz: x teng o'n ikki.`,
        r`Javob: o'n ikki.`,
        r`Eng ko'p uchraydigan xato — o'ng tomondagi sonni ko'paytirishni unutish. Har bir had, har ikkala tomonda, ko'paytiriladi.`,
      ],
    },
    {
      type: 'example',
      kicker: '3-MISOL',
      title: "O'nli kasrli tenglama",
      label: 'SPR SAVOLI',
      question: r`If $0.2(x+5)=1.4$, what is the value of $x$?`,
      steps: [
        {m: r`2(x+5)=14`, note: r`ikkala tomonni $10$ ga ko'paytiramiz`},
        {m: r`x+5=7`, note: r`$2$ ga bo'lamiz`},
        {m: r`x=2`},
      ],
      answer: r`$2$`,
      say: [
        r`Uchinchi misol: nol butun o'ndan ikki karra x plyus besh teng bir butun o'ndan to'rt.`,
        r`O'nli kasrlar bilan ishlash noqulay. Ikkala tomonni o'nga ko'paytiramiz: ikki karra x plyus besh teng o'n to'rt.`,
        r`Qavsni ochish shart emas — ikkala tomonni ikkiga bo'lamiz: x plyus besh teng yetti.`,
        r`Beshni ayiramiz: x teng ikki.`,
        r`Javob: ikki. O'nli kasrlarni ko'rganingizda avval o'n yoki yuzga ko'paytirib, butun sonlarga o'ting.`,
      ],
    },
    {
      type: 'example',
      kicker: 'SAT HIYLASI',
      title: "$x$ ni emas, ifodani so'rashadi",
      question: r`If $3x-5=16$, what is the value of $6x-10$?`,
      choices: [r`$7$`, r`$21$`, r`$32$`, r`$42$`],
      steps: [
        {m: r`6x-10=2(3x-5)`, note: r`ifoda — berilganning ikki baravari`},
        {m: r`=2\cdot16`},
        {m: r`=32`},
      ],
      answer: r`C`,
      tip: r`Avval $x$ ni topishga shoshilmang: so'ralgan ifoda berilgan ifodaning karralisi emasmi — tekshiring.`,
      say: [
        r`Endi SAT'ning sevimli hiylasi. If three x minus five equals sixteen, what is the value of six x minus ten?`,
        r`X ni topish mumkin, lekin bunga hojat yo'q. Olti x minus o'n — bu uch x minus beshning aynan ikki baravari.`,
        r`Uch x minus besh o'n oltiga teng ekanini bilamiz, demak ifoda ikki karra o'n olti.`,
        r`Ya'ni o'ttiz ikki.`,
        r`Javob: C. Bu usul bilan savol besh soniyada yechiladi.`,
        r`Shuning uchun har doim so'ralgan ifodaga qarang: u berilgan ifodaning karralisi yoki unga yaqin emasmi? Agar shunday bo'lsa, x ni topish shart emas.`,
      ],
    },
    {
      type: 'trap',
      title: "Savol oxirini o'qing",
      question: r`If $4x+7=31$, what is the value of $x+2$?`,
      wrong: r`$6$`,
      why: r`$6$ — bu $x$ ning qiymati. Savol esa $x+2$ ni so'rayapti, va $6$ variantlar ichida atayin berilgan.`,
      right: r`$4x=24$, $x=6$, demak $x+2=$ **8**. Javobni belgilashdan oldin savolning oxirgi qatorini qayta o'qing.`,
      say: [
        r`Bunga o'xshash tuzoq. If four x plus seven equals thirty one, what is the value of x plus two?`,
        r`O'quvchi tenglamani yechadi, x teng olti chiqadi va shoshilib oltini belgilaydi. Lekin olti — bu x ning qiymati, savol esa x plyus ikkini so'rayapti. SAT bunday noto'g'ri javobni variantlar ichiga atayin qo'yadi.`,
        r`To'g'ri yechim: to'rt x teng yigirma to'rt, x teng olti, demak x plyus ikki — sakkiz. Javobni belgilashdan oldin savolning oxirgi qatorini har doim qayta o'qing.`,
      ],
    },
    {
      type: 'example',
      kicker: 'MATNLI MASALA',
      title: 'Gapdan tenglamaga',
      question: r`A plumber charges a fixed fee of 60 dollars plus 45 dollars per hour. A customer's bill was 285 dollars. For how many hours did the plumber work?`,
      steps: [
        {m: r`60+45h=285`, note: r`$h$ — soatlar soni`},
        {m: r`45h=225`, note: r`$60$ ni ayiramiz`},
        {m: r`h=5`, note: r`$45$ ga bo'lamiz`},
      ],
      answer: r`$5$ soat`,
      tip: r`"fixed fee" — o'zgarmas son, "per hour" — soatlar soniga ko'paytiriladigan son.`,
      say: [
        r`Endi matnli masala. Santexnik chaqiruv uchun oltmish dollar oladi va har bir soat uchun yana qirq besh dollar. Mijozning hisobi ikki yuz sakson besh dollar bo'ldi. Santexnik necha soat ishlagan?`,
        r`Noma'lumni belgilaymiz: h — soatlar soni. Umumiy narx: oltmish plyus qirq besh h, va u ikki yuz sakson beshga teng.`,
        r`Oltmishni ayiramiz: qirq besh h teng ikki yuz yigirma besh.`,
        r`Qirq beshga bo'lamiz: h teng besh.`,
        r`Javob: besh soat.`,
        r`Matnli masalalarda kalit so'zlarni toping: fixed fee — o'zgarmas qism, per hour, per item, each — bular noma'lumga ko'paytiriladigan qism.`,
      ],
    },
    {
      type: 'cards',
      kicker: 'TEKSHIRUV',
      title: 'Javobni tekshirishning 3 usuli',
      cards: [
        {title: "Qo'yib ko'rish", text: r`Topilgan $x$ ni dastlabki tenglamaga qo'ying`, icon: 'check'},
        {title: 'Desmos', text: r`Ikkala tomonni $y=$ qilib chizing — kesishish $x$ i javob`, icon: 'calc'},
        {title: 'Variantlardan', text: r`Test savolida variantlarni tenglamaga qo'yib ko'ring`, icon: 'flag'},
      ],
      say: [
        r`Va nihoyat, javobni tekshirishning uchta usuli.`,
        r`Birinchi: topilgan x ni dastlabki tenglamaga qo'yish. Eng ishonchli usul.`,
        r`Ikkinchi: Desmos. Tenglamaning chap va o'ng tomonini alohida grafik qilib chizing — kesishish nuqtasining x koordinatasi javob bo'ladi.`,
        r`Uchinchi: test savolida variantlarning o'zini tenglamaga qo'yib ko'rish mumkin. Bu ayniqsa murakkab tenglamalarda vaqt tejaydi.`,
      ],
    },
    {
      type: 'example',
      kicker: 'SAT MISOLI',
      title: 'Guruhlab yechish',
      question: r`If $7(x+2)-3(x+2)=20$, what is the value of $x+2$?`,
      choices: [r`$3$`, r`$5$`, r`$7$`, r`$20$`],
      steps: [
        {m: r`4(x+2)=20`, note: r`$(x+2)$ ni bitta "blok" deb olamiz`},
        {m: r`x+2=5`, note: r`$4$ ga bo'lamiz`},
      ],
      answer: r`B`,
      tip: r`Qavslarni ochishdan oldin qarang: bir xil ifoda takrorlanayaptimi? Uni bitta harf deb hisoblang.`,
      say: [
        r`Yana bir SAT misoli. If seven times x plus two minus three times x plus two equals twenty, what is the value of x plus two?`,
        r`Qavslarni ochib o'tirmaymiz. X plyus ikkini bitta blok deb olamiz: yetti blok minus uch blok — to'rt blok. To'rt karra x plyus ikki teng yigirma.`,
        r`To'rtga bo'lamiz: x plyus ikki teng besh. Savol aynan shuni so'rayapti.`,
        r`Javob: B.`,
        r`Agar tenglamada bir xil ifoda bir necha marta takrorlansa, uni bitta harf deb hisoblang — bu ko'p vaqt tejaydi.`,
      ],
    },
    {
      type: 'example',
      kicker: 'MUSTAQIL MASHQ',
      title: "O'zingiz yeching",
      label: 'MASHQ',
      question: r`If $\dfrac{2x-1}{3}=x-4$, what is the value of $x$?`,
      steps: [
        {m: r`2x-1=3x-12`, note: r`ikkala tomonni $3$ ga ko'paytiramiz`},
        {m: r`-1+12=3x-2x`, note: r`hadlarni yig'amiz`},
        {m: r`x=11`},
      ],
      answer: r`$11$`,
      say: [
        r`Endi o'zingiz yeching. Videoni to'xtating va bu tenglamani yeching: ikki x minus bir, bo'lingan uchga, teng x minus to'rt. Tayyor bo'lsangiz, davom ettiring.`,
        r`Ikkala tomonni uchga ko'paytiramiz: ikki x minus bir teng uch x minus o'n ikki. O'ng tomonda qavs bor deb tasavvur qiling — uchga x ham, minus to'rt ham ko'paytiriladi.`,
        r`Hadlarni yig'amiz: minus bir plyus o'n ikki teng uch x minus ikki x.`,
        r`Demak, x teng o'n bir.`,
        r`Javob: o'n bir. Agar sizda boshqa javob chiqqan bo'lsa, eng ko'p uchraydigan xato — o'ng tomonda faqat x ni uchga ko'paytirib, to'rtni unutish.`,
      ],
    },
  ],
  recap: [
    r`Oltin qoida: ikkala tomonga bir xil amal`,
    r`Kasr va o'nli kasrdan — ko'paytirib qutuling`,
    r`So'ralgan ifodaga qarang: $6x-10=2(3x-5)$`,
  ],
  homework: r`platformada chiziqli tenglamalar bo'yicha 15 ta savol`,
  recapSay: [
    r`Xulosa qilamiz.`,
    r`Chiziqli tenglamani yechishning oltin qoidasi: ikkala tomonga bir xil amal.`,
    r`Kasrli va o'nli tenglamalarda avval umumiy maxrajga yoki o'nga ko'paytirib, butun sonlarga o'ting.`,
    r`Va har doim so'ralgan ifodaga qarang — ko'pincha x ni topish shart emas.`,
    r`Hozir platformada chiziqli tenglamalar bo'yicha o'n beshta savolni yeching. Keyingi darsda tenglamaning nechta yechimi bo'lishini va parametrli tenglamalarni o'rganamiz.`,
    r`Ko'rishguncha!`,
  ],
};

export default lesson;
