import {meta} from '../catalog';
import type {Lesson} from '../types';

const r = String.raw;

const lesson: Lesson = {
  ...meta(4),
  topics: ['3 holat', 'Koeffitsiyent qoidasi', 'Parametr', 'Formuladan ifodalash', 'Grafik ma\'nosi'],
  cover: [
    r`Assalomu alaykum! To'rtinchi darsga xush kelibsiz. Bugungi mavzu — tenglamalar: yechimlar soni va parametrlar.`,
    r`Tenglamaning bitta, umuman yo'q yoki cheksiz ko'p yechimi bo'lishini, parametrni topishni va formuladan kerakli o'zgaruvchini ifodalashni o'rganamiz.`,
  ],
  goals: [
    r`Tenglamaning yechimlar sonini 10 soniyada aniqlash`,
    r`"No solution" va "infinitely many" savollarida parametr topish`,
    r`Formuladan kerakli o'zgaruvchini ifodalash`,
    r`Yechimlar sonining grafik ma'nosini tushunish`,
  ],
  goalsSay: [
    r`Bugungi darsning maqsadlari.`,
    r`Birinchi: tenglamani to'liq yechmasdan, uning nechta yechimi borligini o'n soniyada aniqlash.`,
    r`Ikkinchi: SAT'da juda ko'p uchraydigan savol turi — tenglama yechimga ega emas yoki cheksiz ko'p yechimga ega bo'lsa, noma'lum o'zgarmasni topish.`,
    r`Uchinchi: formuladan kerakli o'zgaruvchini ifodalash — inglizcha "in terms of" savollari.`,
    r`To'rtinchi: bularning hammasini grafikda ko'rish — ikki to'g'ri chiziq qachon kesishadi, qachon kesishmaydi.`,
    r`Bu savollar ko'pincha qiyin hisoblanadi, lekin aslida bitta qoidaga asoslanadi.`,
  ],
  goalsResult: r`"How many solutions?" savollari — kafolatlangan ball`,
  slides: [
    {
      type: 'compare',
      kicker: '3 HOLAT',
      title: 'Chiziqli tenglamaning nechta yechimi bor?',
      cards: [
        {title: 'Bitta yechim', rule: r`$x$ lar qoladi, $x=\ldots$ chiqadi`, example: r`$3x+1=x+5\Rightarrow x=2$`},
        {title: "Yechim yo'q", rule: r`$x$ lar qisqaradi va **yolg'on** tenglik qoladi`, example: r`$2x+5=2x+7\Rightarrow 5=7$ ✗`},
        {title: 'Cheksiz ko\'p', rule: r`$x$ lar qisqaradi va **rost** tenglik qoladi`, example: r`$2(x+3)=2x+6\Rightarrow 6=6$ ✓`},
      ],
      say: [
        r`Chiziqli tenglama yechilganda faqat uchta holat bo'lishi mumkin.`,
        r`Birinchi holat: x lar qoladi va x teng qandaydir son chiqadi. Bu — bitta yechim. Masalan, uch x plyus bir teng x plyus besh: x teng ikki.`,
        r`Ikkinchi holat: soddalashtirganda x lar butunlay qisqarib ketadi va besh teng yetti kabi yolg'on tenglik qoladi. Demak, hech qanday x bu tenglikni bajarmaydi — yechim yo'q.`,
        r`Uchinchi holat: x lar qisqaradi, lekin olti teng olti kabi har doim rost tenglik qoladi. Demak, x ning istalgan qiymati to'g'ri — cheksiz ko'p yechim.`,
      ],
    },
    {
      type: 'formula',
      kicker: 'QOIDA',
      title: r`$ax+b=cx+d$ uchun tezkor qoida`,
      formulas: [
        {label: 'Bitta yechim', tex: r`a\neq c`, note: r`$x$ oldidagi sonlar har xil`},
        {label: "Yechim yo'q", tex: r`a=c,\quad b\neq d`, note: r`qiyalik bir xil, ozod had har xil`},
        {label: "Cheksiz ko'p", tex: r`a=c,\quad b=d`, note: r`ikki tomon aynan bir xil`},
      ],
      banner: r`Avval ikkala tomonni $ax+b$ ko'rinishiga keltiring, keyin faqat solishtiring`,
      say: [
        r`Endi buni bitta qoidaga aylantiramiz. Tenglama a x plyus b teng c x plyus d ko'rinishida bo'lsin.`,
        r`Agar x oldidagi sonlar, ya'ni a va c, har xil bo'lsa — tenglama doim bitta yechimga ega.`,
        r`Agar a teng c, lekin ozod hadlar b va d har xil bo'lsa — yechim yo'q.`,
        r`Agar a teng c va b teng d bo'lsa, ya'ni ikki tomon aynan bir xil ifoda bo'lsa — cheksiz ko'p yechim.`,
        r`Muhim: qoidani qo'llashdan oldin qavslarni ochib, ikkala tomonni a x plyus b ko'rinishiga keltiring. Shundan keyin faqat ikkita juft sonni solishtirasiz.`,
      ],
    },
    {
      type: 'example',
      kicker: '1-MISOL',
      title: 'Nechta yechim?',
      question: r`How many solutions does the equation $4(x-1)=2(2x+3)$ have?`,
      choices: [r`Zero`, r`Exactly one`, r`Exactly two`, r`Infinitely many`],
      steps: [
        {m: r`4x-4=4x+6`, note: r`qavslarni ochamiz`},
        {m: r`a=c=4,\quad -4\neq6`, note: r`koeffitsiyent bir xil, ozod had har xil`},
        {m: r`-4=6\ \text{— yolg'on}`},
      ],
      answer: r`A`,
      tip: r`"Exactly two" — chiziqli tenglamada hech qachon bo'lmaydi. Bu variantni darhol chiqarib tashlang.`,
      say: [
        r`Birinchi misol. How many solutions does the equation four times x minus one equals two times two x plus three have?`,
        r`Qavslarni ochamiz: to'rt x minus to'rt teng to'rt x plyus olti.`,
        r`X oldidagi sonlar bir xil — to'rt va to'rt. Ozod hadlar esa har xil — minus to'rt va olti.`,
        r`Agar to'rt x larni ayirsak, minus to'rt teng olti degan yolg'on tenglik qoladi.`,
        r`Demak, yechim yo'q. Javob A — zero.`,
        r`E'tibor bering: "exactly two" varianti chiziqli tenglama uchun hech qachon to'g'ri bo'lmaydi. Ikki yechim faqat kvadrat tenglamalarda uchraydi.`,
      ],
    },
    {
      type: 'example',
      kicker: '2-MISOL',
      title: "Parametr: yechim yo'q",
      label: 'SPR SAVOLI',
      question: r`In the equation $kx+3=5x-7$, $k$ is a constant. If the equation has no solution, what is the value of $k$?`,
      steps: [
        {m: r`a=k,\ \ c=5`, note: r`$x$ oldidagi sonlar`},
        {m: r`k=5`, note: r`yechim yo'q $\Rightarrow$ $a=c$`},
        {m: r`3\neq-7\ \checkmark`, note: r`ozod hadlar har xil — shart bajarildi`},
      ],
      answer: r`$5$`,
      say: [
        r`Ikkinchi misol, SPR savoli. In the equation k x plus three equals five x minus seven, k is a constant. If the equation has no solution, what is the value of k?`,
        r`Qoidaga qaraymiz: chap tomonda x oldida k, o'ng tomonda besh.`,
        r`Yechim yo'q bo'lishi uchun x oldidagi sonlar teng bo'lishi kerak: k teng besh.`,
        r`Va ozod hadlar har xil bo'lishi kerak: uch va minus yetti — haqiqatan har xil. Shart bajarildi.`,
        r`Javob: besh. Hech qanday hisob-kitob kerak bo'lmadi — faqat solishtirish.`,
      ],
    },
    {
      type: 'example',
      kicker: '3-MISOL',
      title: "Parametr: cheksiz ko'p yechim",
      label: 'SPR SAVOLI',
      question: r`The equation $3(ax+2)=12x+b$ has infinitely many solutions, where $a$ and $b$ are constants. What is the value of $a+b$?`,
      steps: [
        {m: r`3ax+6=12x+b`, note: r`qavsni ochamiz`},
        {m: r`3a=12\ \Rightarrow\ a=4`, note: r`$x$ oldidagi sonlar teng`},
        {m: r`b=6`, note: r`ozod hadlar ham teng`},
        {m: r`a+b=10`},
      ],
      answer: r`$10$`,
      say: [
        r`Uchinchi misol. The equation three times a x plus two equals twelve x plus b has infinitely many solutions. What is a plus b?`,
        r`Qavsni ochamiz: uch a x plyus olti teng o'n ikki x plyus b.`,
        r`Cheksiz ko'p yechim uchun ikki tomon aynan bir xil bo'lishi kerak. x oldidagi sonlar: uch a teng o'n ikki, demak a teng to'rt.`,
        r`Ozod hadlar: b teng olti.`,
        r`a plyus b — o'n.`,
        r`Javob: o'n.`,
      ],
    },
    {
      type: 'trap',
      title: "$x$ lar qisqardi — yechim yo'qmi?",
      question: r`How many solutions does $2x+6=2(x+3)$ have?`,
      wrong: r`Zero`,
      why: r`$x$ lar qisqarib ketgani yechim yo'q degani emas. Qolgan tenglikka qarang: $6=6$ — rost!`,
      right: r`Qolgan tenglik **rost** bo'lsa — cheksiz ko'p yechim, **yolg'on** bo'lsa — yechim yo'q. Bu yerda: infinitely many.`,
      say: [
        r`Endi ko'p uchraydigan tuzoq. How many solutions does two x plus six equals two times x plus three have?`,
        r`Ko'p o'quvchilar x lar qisqarib ketganini ko'rib, darhol "yechim yo'q" deb belgilaydi. Lekin qolgan tenglikka qarang: olti teng olti. Bu rost.`,
        r`Qoida: x lar qisqargandan keyin qolgan tenglik rost bo'lsa — cheksiz ko'p yechim, yolg'on bo'lsa — yechim yo'q. Bu misolda javob — infinitely many.`,
      ],
    },
    {
      type: 'graph',
      kicker: "GRAFIK MA'NOSI",
      title: 'Har bir tomon — bitta to\'g\'ri chiziq',
      x: [-5, 5],
      y: [-4, 8],
      items: [
        {kind: 'fn', f: (x) => 2 * x + 1, label: r`$y=2x+1$`, note: r`Tenglamaning chap tomoni — bitta to'g'ri chiziq`},
        {kind: 'fn', f: (x) => 2 * x + 4, label: r`$y=2x+4$`, note: r`Qiyalik bir xil, kesishma har xil — **parallel**: yechim yo'q`},
        {kind: 'fn', f: (x) => -x + 4, label: r`$y=-x+4$`, note: r`Qiyalik har xil — **bitta** kesishish: bitta yechim`},
        {kind: 'note', note: r`Ikki chiziq ustma-ust tushsa — har bir nuqta umumiy: cheksiz ko'p yechim`},
      ],
      say: [
        r`Endi bu qoidani grafikda ko'ramiz. Tenglamaning har bir tomonini alohida to'g'ri chiziq deb tasavvur qiling. Yechim — ikki chiziq kesishgan joy.`,
        r`Chap tomon: y teng ikki x plyus bir.`,
        r`O'ng tomon y teng ikki x plyus to'rt bo'lsa, qiyaliklar bir xil, lekin chiziqlar har xil balandlikda — ular parallel va hech qachon kesishmaydi. Yechim yo'q.`,
        r`O'ng tomon y teng minus x plyus to'rt bo'lsa, qiyaliklar har xil va chiziqlar aniq bitta nuqtada kesishadi. Bitta yechim.`,
        r`Agar ikki tomon bir xil bo'lsa, chiziqlar ustma-ust tushadi va har bir nuqta umumiy bo'ladi — cheksiz ko'p yechim. Bu mantiq keyingi darslarda sistemalarda ham ishlaydi.`,
      ],
    },
    {
      type: 'example',
      kicker: 'IN TERMS OF',
      title: 'Formuladan ifodalash',
      question: r`The perimeter of a rectangle is $P=2l+2w$. Which equation gives $w$ in terms of $P$ and $l$?`,
      choices: [r`$w=P-2l$`, r`$w=\frac{P-2l}{2}$`, r`$w=\frac{P}{2}-2l$`, r`$w=2P-l$`],
      steps: [
        {m: r`P-2l=2w`, note: r`$2l$ ni chapga o'tkazamiz`},
        {m: r`w=\frac{P-2l}{2}`, note: r`$2$ ga bo'lamiz`},
      ],
      answer: r`B`,
      tip: r`"In terms of" — xuddi tenglama yechish: $w$ ni yolg'iz qoldiring, boshqa harflar oddiy son kabi.`,
      say: [
        r`Va nihoyat, "in terms of" savollari. To'g'ri to'rtburchak perimetri P teng ikki l plyus ikki w. Which equation gives w in terms of P and l?`,
        r`Bu oddiy tenglama yechish, faqat sonlar o'rnida harflar. W bor hadni yolg'iz qoldiramiz: ikki l ni chapga o'tkazamiz — P minus ikki l teng ikki w.`,
        r`Ikkiga bo'lamiz: w teng P minus ikki l, bo'lingan ikki.`,
        r`Javob: B.`,
        r`Maslahat: bunday savollarda kerakli harfni x deb, qolgan harflarni oddiy sonlar deb tasavvur qiling va odatdagi algoritmni qo'llang.`,
      ],
    },
    {
      type: 'example',
      kicker: 'SAT MISOLI',
      title: 'Qaysi tenglama bitta yechimga ega?',
      question: r`Which of the following equations has exactly one solution?`,
      choices: [r`$3x+2=3x+5$`, r`$2(x+1)=2x+2$`, r`$4x-1=x+8$`, r`$5x=5x-3$`],
      steps: [
        {m: r`A:\ 3=3,\ \ 2\neq5`, note: r`yechim yo'q`},
        {m: r`B:\ 2x+2=2x+2`, note: r`cheksiz ko'p`},
        {m: r`C:\ 4\neq1`, note: r`koeffitsiyentlar har xil — bitta yechim ($x=3$)`},
      ],
      answer: r`C`,
      tip: r`Har bir variantni yechmang — faqat $x$ oldidagi sonlarni solishtiring.`,
      say: [
        r`SAT misoli. Which of the following equations has exactly one solution?`,
        r`Variantlarni yechmaymiz, faqat x oldidagi sonlarni solishtiramiz. A: uch va uch — bir xil, ozod hadlar ikki va besh — har xil. Yechim yo'q.`,
        r`B: qavsni ochsak, ikki x plyus ikki teng ikki x plyus ikki — aynan bir xil. Cheksiz ko'p yechim.`,
        r`C: to'rt va bir — har xil. Demak, aniq bitta yechim. Tekshirib qo'yamiz: uch x teng to'qqiz, x teng uch.`,
        r`Javob: C.`,
        r`Bunday savolda har bir tenglamani to'liq yechish shart emas — koeffitsiyentlarga bir qarash kifoya.`,
      ],
    },
    {
      type: 'example',
      kicker: 'MUSTAQIL MASHQ',
      title: "O'zingiz yeching",
      label: 'MASHQ',
      question: r`The equation $\tfrac{1}{2}(8x-6)=4x+c$ has infinitely many solutions. What is the value of the constant $c$?`,
      steps: [
        {m: r`4x-3=4x+c`, note: r`qavsni ochamiz`},
        {m: r`4=4\ \checkmark`, note: r`koeffitsiyentlar teng`},
        {m: r`c=-3`, note: r`ozod hadlar ham teng bo'lishi kerak`},
      ],
      answer: r`$-3$`,
      say: [
        r`Endi mustaqil mashq. Videoni to'xtating: yarim karra sakkiz x minus olti teng to'rt x plyus c tenglama cheksiz ko'p yechimga ega. C nimaga teng?`,
        r`Qavsni ochamiz: yarim karra sakkiz x — to'rt x, yarim karra minus olti — minus uch. To'rt x minus uch teng to'rt x plyus c.`,
        r`X oldidagi sonlar allaqachon teng: to'rt va to'rt.`,
        r`Cheksiz ko'p yechim uchun ozod hadlar ham teng bo'lishi kerak: c teng minus uch.`,
        r`Javob: minus uch. SPR savolida minus belgisini kiritishni unutmang.`,
      ],
    },
  ],
  recap: [
    r`$x$ lar qisqarsa: rost tenglik — cheksiz ko'p, yolg'on — yechim yo'q`,
    r`$ax+b=cx+d$: yechim yo'q $\Leftrightarrow a=c,\ b\neq d$`,
    r`"In terms of" — kerakli harfni yolg'iz qoldiring`,
  ],
  homework: r`platformada "number of solutions" bo'yicha 12 ta savol`,
  recapSay: [
    r`Xulosa.`,
    r`Agar x lar qisqarib ketsa: qolgan tenglik rost bo'lsa — cheksiz ko'p yechim, yolg'on bo'lsa — yechim yo'q.`,
    r`Tezkor qoida: a x plyus b teng c x plyus d tenglamada yechim yo'q, faqat a teng c va b teng emas d bo'lganda. Cheksiz ko'p — ikkala juft teng bo'lganda.`,
    r`"In terms of" savollarida kerakli harfni xuddi x kabi yolg'iz qoldiring.`,
    r`Hozir platformada yechimlar soni bo'yicha o'n ikkita savolni yeching. Keyingi darsda chiziqli tengsizliklarni o'rganamiz.`,
    r`Ko'rishguncha!`,
  ],
};

export default lesson;
