import {meta} from '../catalog';
import type {Lesson} from '../types';

const r = String.raw;

const lesson: Lesson = {
  ...meta(6),
  topics: ['Qiyalik formulasi', '$y=mx+b$', 'Kesishmalar', 'Jadvaldan funksiya', "Qiyalik ma'nosi"],
  cover: [
    r`Assalomu alaykum! Oltinchi darsga xush kelibsiz. Bugungi mavzu — chiziqli funksiya: qiyalik va kesishma.`,
    r`Qiyalikni ikki nuqtadan topishni, y teng m x plyus b ko'rinishini, o'qlar bilan kesishishni, jadvaldan funksiyani tiklashni va qiyalikning hayotiy ma'nosini o'rganamiz.`,
  ],
  goals: [
    r`Ikki nuqtadan qiyalikni topish`,
    r`$y=mx+b$ da $m$ va $b$ ni grafikda ko'rish`,
    r`$x$- va $y$-kesishmalarni topish`,
    r`Qiyalik va kesishmaning ma'nosini matnda tushunish`,
  ],
  goalsSay: [
    r`Darsning maqsadlari.`,
    r`Birinchi: ikki nuqta berilganda qiyalikni formula bilan topish.`,
    r`Ikkinchi: y teng m x plyus b ko'rinishida m va b grafikda nimani anglatishini ko'rish.`,
    r`Uchinchi: grafikning x va y o'qlari bilan kesishgan nuqtalarini topish.`,
    r`To'rtinchi: matnli masalalarda qiyalik va kesishma nimani bildirishini tushunish — SAT bu haqda juda ko'p so'raydi.`,
    r`Chiziqli funksiyalar SAT'dagi eng ko'p uchraydigan mavzulardan biri, shuning uchun bu dars juda muhim.`,
  ],
  goalsResult: r`chiziqli funksiya savollari — tez va ishonchli`,
  slides: [
    {
      type: 'formula',
      kicker: 'FORMULALAR',
      title: 'Qiyalik va chiziq tenglamasi',
      formulas: [
        {label: 'Qiyalik (slope)', tex: r`m=\dfrac{y_2-y_1}{x_2-x_1}=\dfrac{\text{rise}}{\text{run}}`, note: r`$y$ ning o'zgarishi / $x$ ning o'zgarishi`},
        {label: 'Slope-intercept', tex: r`y=mx+b`, note: r`$m$ — qiyalik, $b$ — $y$-kesishma`},
      ],
      banner: r`$b$ — bu $x=0$ bo'lgandagi $y$ qiymati: grafik $y$ o'qini kesgan nuqta $(0,\,b)$`,
      say: [
        r`Ikkita asosiy formula bilan boshlaymiz.`,
        r`Qiyalik — inglizcha slope — y ning o'zgarishini x ning o'zgarishiga bo'lganiga teng: y ikki minus y bir, bo'lingan x ikki minus x bir. Ya'ni ko'tarilish bo'lingan yurish — rise over run.`,
        r`To'g'ri chiziq tenglamasining eng qulay ko'rinishi: y teng m x plyus b. Bu yerda m — qiyalik, b esa y o'qi bilan kesishish nuqtasi.`,
        r`Esda tuting: b — bu x nolga teng bo'lgandagi y qiymati. Grafik y o'qini aynan nol, b nuqtada kesib o'tadi.`,
      ],
    },
    {
      type: 'graph',
      kicker: 'GRAFIKDA',
      title: r`$y=2x-3$: qiyalik va kesishma`,
      x: [-3, 5],
      y: [-5, 6],
      items: [
        {kind: 'fn', f: (x) => 2 * x - 3, label: r`$y=2x-3$`, note: r`Chiziq: $m=2$, $b=-3$`},
        {kind: 'point', x: 0, y: -3, label: r`$(0,\,-3)$`, color: '#22C55E', note: r`$y$-kesishma: $(0,\,b)=(0,\,-3)$`},
        {kind: 'segment', from: [0, -3], to: [2, -3], dashed: true, color: '#F59E0B', label: 'run = 2', note: r`O'ngga $2$ qadam (run)…`},
        {kind: 'segment', from: [2, -3], to: [2, 1], dashed: true, color: '#EC4899', label: 'rise = 4', note: r`…yuqoriga $4$ qadam (rise): $m=\frac{4}{2}=2$`},
      ],
      say: [
        r`Buni grafikda ko'ramiz: y teng ikki x minus uch.`,
        r`Bu chiziqning qiyaligi ikki, y kesishmasi esa minus uch.`,
        r`Grafik y o'qini nol, minus uch nuqtada kesadi — bu aynan b.`,
        r`Endi qiyalik: shu nuqtadan o'ngga ikki qadam yuramiz — bu run.`,
        r`Va chiziqqa qaytish uchun yuqoriga to'rt qadam ko'tarilamiz — bu rise. To'rt bo'lingan ikki — ikki. Qiyalik ikki degani: x bittaga oshsa, y ikkitaga oshadi.`,
      ],
    },
    {
      type: 'compare',
      kicker: 'QIYALIK ISHORASI',
      title: 'Qiyalikning 4 turi',
      cards: [
        {title: 'Musbat', rule: r`$m>0$: chiziq chapdan o'ngga **ko'tariladi**`, example: r`$y=2x+1$`},
        {title: 'Manfiy', rule: r`$m<0$: chiziq chapdan o'ngga **tushadi**`, example: r`$y=-3x+4$`},
        {title: 'Nol', rule: r`$m=0$: gorizontal chiziq`, example: r`$y=5$`},
        {title: 'Aniqlanmagan', rule: r`vertikal chiziq — funksiya emas`, example: r`$x=2$`},
      ],
      say: [
        r`Qiyalikning to'rt turi bor.`,
        r`Musbat qiyalik: chiziq chapdan o'ngga qarab ko'tariladi.`,
        r`Manfiy qiyalik: chiziq chapdan o'ngga qarab tushadi.`,
        r`Nol qiyalik: gorizontal chiziq, masalan y teng besh. Bunda y hech qachon o'zgarmaydi.`,
        r`Vertikal chiziq, masalan x teng ikki: qiyalik aniqlanmagan, chunki run nolga teng va nolga bo'lib bo'lmaydi.`,
      ],
    },
    {
      type: 'example',
      kicker: '1-MISOL',
      title: 'Ikki nuqtadan qiyalik',
      label: 'SPR SAVOLI',
      question: r`A line passes through the points $(-2,\,5)$ and $(4,\,-7)$. What is the slope of the line?`,
      steps: [
        {m: r`m=\frac{-7-5}{4-(-2)}`, note: r`$y$ lar ayirmasi / $x$ lar ayirmasi`},
        {m: r`=\frac{-12}{6}`},
        {m: r`=-2`},
      ],
      answer: r`$-2$`,
      tip: r`Ayirish tartibi bir xil bo'lsin: yuqorida $y_2-y_1$ bo'lsa, pastda ham $x_2-x_1$.`,
      say: [
        r`Birinchi misol. A line passes through the points minus two, five and four, minus seven. What is the slope?`,
        r`Formulaga qo'yamiz: minus yetti minus besh, bo'lingan to'rt minus minus ikki.`,
        r`Surat: minus o'n ikki. Maxraj: olti.`,
        r`Qiyalik minus ikki. Chiziq tushib boradi — ikkinchi nuqta o'ngda, lekin pastda, mantiqan ham to'g'ri.`,
        r`Javob: minus ikki.`,
        r`Muhim: ayirish tartibi surat va maxrajda bir xil bo'lishi kerak. Yuqorida ikkinchi nuqtadan birinchisini ayirsangiz, pastda ham shunday qiling.`,
      ],
    },
    {
      type: 'example',
      kicker: '2-MISOL',
      title: 'Standart ko\'rinishdan kesishmalar',
      label: 'MISOL',
      question: r`Find the $x$- and $y$-intercepts and the slope of the line $3x+4y=12$.`,
      steps: [
        {m: r`y=0:\ 3x=12\Rightarrow x=4`, note: r`$x$-kesishma $(4,\,0)$`},
        {m: r`x=0:\ 4y=12\Rightarrow y=3`, note: r`$y$-kesishma $(0,\,3)$`},
        {m: r`4y=-3x+12\Rightarrow y=-\tfrac34x+3`, note: r`qiyalik $-\tfrac34$`},
      ],
      answer: r`$(4,0)$, $(0,3)$, $m=-\tfrac34$`,
      tip: r`$Ax+By=C$ ko'rinishida qiyalik doim $-\frac{A}{B}$.`,
      say: [
        r`Ikkinchi misol: uch x plyus to'rt y teng o'n ikki. Kesishmalar va qiyalikni topamiz.`,
        r`X kesishma — bu y nol bo'lgan nuqta. Y o'rniga nol qo'yamiz: uch x teng o'n ikki, x teng to'rt. Nuqta: to'rt, nol.`,
        r`Y kesishma — x nol bo'lgan nuqta: to'rt y teng o'n ikki, y teng uch. Nuqta: nol, uch.`,
        r`Qiyalik uchun y ni yolg'iz qoldiramiz: y teng minus to'rtdan uch x plyus uch.`,
        r`Javob: kesishmalar to'rt, nol va nol, uch; qiyalik minus to'rtdan uch.`,
        r`Tezkor qoida: A x plyus B y teng C ko'rinishida qiyalik har doim minus A bo'lingan B ga teng.`,
      ],
    },
    {
      type: 'graph',
      kicker: 'GRAFIKDA',
      title: r`$3x+4y=12$`,
      x: [-2, 7],
      y: [-2, 5],
      items: [
        {kind: 'fn', f: (x) => -0.75 * x + 3, label: r`$3x+4y=12$`, note: r`Chiziq ikki kesishma orqali chiziladi`},
        {kind: 'point', x: 4, y: 0, label: r`$(4,\,0)$`, color: '#22C55E', note: r`$x$-kesishma: $y=0$`},
        {kind: 'point', x: 0, y: 3, label: r`$(0,\,3)$`, color: '#22C55E', note: r`$y$-kesishma: $x=0$`},
      ],
      say: [
        r`Grafikda ko'ramiz.`,
        r`Standart ko'rinishdagi chiziqni chizishning eng tez yo'li — ikki kesishma orqali.`,
        r`X o'qida to'rt, nol nuqtasi.`,
        r`Y o'qida nol, uch nuqtasi. Ikki nuqtani tutashtirsak, chiziq tayyor. Chiziq tushib boradi — qiyalik manfiy, minus to'rtdan uch.`,
      ],
    },
    {
      type: 'example',
      kicker: 'SAT MISOLI',
      title: 'Jadvaldan funksiyani topish',
      question: r`The table shows values of the linear function $f$: $f(1)=7$, $f(3)=13$, $f(5)=19$. Which of the following defines $f$?`,
      choices: [r`$f(x)=3x+4$`, r`$f(x)=6x+1$`, r`$f(x)=3x+7$`, r`$f(x)=2x+5$`],
      steps: [
        {m: r`m=\frac{13-7}{3-1}=3`, note: r`qiyalik`},
        {m: r`7=3\cdot1+b\Rightarrow b=4`, note: r`bitta nuqtani qo'yamiz`},
        {m: r`f(x)=3x+4`},
      ],
      answer: r`A`,
      tip: r`Tezroq: variantlarga $x=1$ ni qo'ying — faqat A $7$ beradi.`,
      say: [
        r`SAT misoli. Jadvalda chiziqli f funksiyaning qiymatlari berilgan: f bir — yetti, f uch — o'n uch, f besh — o'n to'qqiz. Which of the following defines f?`,
        r`Qiyalikni topamiz: o'n uch minus yetti, bo'lingan uch minus bir — olti bo'lingan ikki — uch.`,
        r`B ni topish uchun bitta nuqtani qo'yamiz: yetti teng uch karra bir plyus b, demak b teng to'rt.`,
        r`F x teng uch x plyus to'rt.`,
        r`Javob: A.`,
        r`Undan ham tezroq usul: variantlarga x teng bir ni qo'yib ko'ring. Faqat A variant yetti beradi. Variantlarni tekshirish ko'pincha eng tez yo'l.`,
      ],
    },
    {
      type: 'cards',
      kicker: "MA'NOSI",
      title: 'Matnli masalada $m$ va $b$',
      cards: [
        {title: r`$m$ — o'zgarish tezligi`, text: r`"per hour", "each", "per month": $x$ bittaga oshganda $y$ qanchaga o'zgaradi`, icon: 'chart'},
        {title: r`$b$ — boshlang'ich qiymat`, text: r`$x=0$ dagi qiymat: "initial", "fixed fee", "starting amount"`, icon: 'flag'},
        {title: 'Birliklar', text: r`$m$ ning birligi = $y$ birligi / $x$ birligi: masalan dollar/soat`, icon: 'book'},
      ],
      say: [
        r`SAT juda ko'p so'raydigan savol: tenglamadagi son nimani anglatadi? Ikkita qoidani eslang.`,
        r`Qiyalik m — o'zgarish tezligi. X bittaga oshganda y qanchaga o'zgarishini ko'rsatadi. Matnda u per hour, each, per month kabi iboralar bilan keladi.`,
        r`B — boshlang'ich qiymat, ya'ni x nol bo'lgandagi y. Matnda initial, fixed fee, starting amount kabi so'zlar bilan keladi.`,
        r`Qiyalikning birligi — y birligi bo'lingan x birligi. Masalan, narx dollarda, vaqt soatda bo'lsa, qiyalik — dollar bo'lingan soat.`,
      ],
    },
    {
      type: 'example',
      kicker: 'SAT MISOLI',
      title: "Sonning ma'nosini aniqlash",
      question: r`The cost $C$, in dollars, of renting a bike for $h$ hours is given by $C=12h+8$. What is the best interpretation of $12$ in this context?`,
      choices: [r`The cost per hour`, r`The initial fee`, r`The cost for 8 hours`, r`The number of hours`],
      steps: [
        {m: r`12=m`, note: r`$h$ ga ko'paytirilgan son — qiyalik`},
        {m: r`h\to h+1:\ C\to C+12`, note: r`har soat narx $12$ ga oshadi`},
      ],
      answer: r`A`,
      tip: r`$8$ esa — $h=0$ dagi narx, ya'ni boshlang'ich to'lov (initial fee).`,
      say: [
        r`SAT misoli. Velosipedni h soatga ijaraga olish narxi C teng o'n ikki h plyus sakkiz. What is the best interpretation of twelve in this context?`,
        r`O'n ikki — h ga ko'paytirilgan son, ya'ni qiyalik.`,
        r`Agar h bittaga oshsa, narx o'n ikki dollarga oshadi. Demak, o'n ikki — bir soatlik narx.`,
        r`Javob: A, the cost per hour.`,
        r`Sakkiz esa h nol bo'lgandagi narx — boshlang'ich to'lov. B variant aynan sakkizning ma'nosi, shuning uchun ularni chalkashtirmang.`,
      ],
    },
    {
      type: 'trap',
      title: "Qiyalik formulasida o'rin almashish",
      question: r`What is the slope of the line through $(1,\,4)$ and $(3,\,10)$?`,
      wrong: r`$\tfrac{3-1}{10-4}=\tfrac13$`,
      why: r`$x$ va $y$ o'rni almashtirilgan: bu "run / rise", "rise / run" emas.`,
      right: r`$m=\dfrac{10-4}{3-1}=\dfrac{6}{2}=$ **3**. Yuqorida doim $y$ lar, pastda $x$ lar.`,
      say: [
        r`Tuzoq. What is the slope of the line through one, four and three, ten?`,
        r`Ba'zan o'quvchi x larni suratga, y larni maxrajga qo'yib yuboradi va uchdan bir chiqaradi. Bu variant testda albatta bo'ladi.`,
        r`To'g'risi: o'n minus to'rt, bo'lingan uch minus bir — uch. Eslab qoling: y lar yuqorida, x lar pastda — rise over run.`,
      ],
    },
    {
      type: 'example',
      kicker: 'MUSTAQIL MASHQ',
      title: "O'zingiz yeching",
      label: 'MASHQ',
      question: r`A line has slope $-3$ and passes through $(2,\,5)$. What is its $y$-intercept?`,
      steps: [
        {m: r`y=-3x+b`},
        {m: r`5=-3\cdot2+b`, note: r`nuqtani qo'yamiz`},
        {m: r`b=11`},
      ],
      answer: r`$11$`,
      say: [
        r`Mustaqil mashq. Videoni to'xtating. Chiziqning qiyaligi minus uch va u ikki, besh nuqtasidan o'tadi. Uning y kesishmasi nimaga teng?`,
        r`Tenglamani y teng minus uch x plyus b deb yozamiz.`,
        r`Nuqtani qo'yamiz: besh teng minus uch karra ikki plyus b, ya'ni besh teng minus olti plyus b.`,
        r`B teng o'n bir.`,
        r`Javob: o'n bir. Nuqta va qiyalik berilsa, doim shu usul: nuqtani y teng m x plyus b ga qo'yib, b ni topasiz.`,
      ],
    },
  ],
  recap: [
    r`$m=\frac{y_2-y_1}{x_2-x_1}$ — yuqorida $y$, pastda $x$`,
    r`$y=mx+b$: $b$ — $x=0$ dagi qiymat, $Ax+By=C$ da $m=-\frac AB$`,
    r`Matnda: $m$ — "per…", $b$ — boshlang'ich qiymat`,
  ],
  homework: r`platformada chiziqli funksiyalar bo'yicha 15 ta savol`,
  recapSay: [
    r`Xulosa.`,
    r`Qiyalik: y lar ayirmasi bo'lingan x lar ayirmasi — yuqorida y, pastda x.`,
    r`Y teng m x plyus b ko'rinishida b — x nol bo'lgandagi qiymat. A x plyus B y teng C ko'rinishida qiyalik minus A bo'lingan B.`,
    r`Matnli masalada m — har bir birlikka o'zgarish, b — boshlang'ich qiymat.`,
    r`Hozir platformada chiziqli funksiyalar bo'yicha o'n beshta savolni yeching. Keyingi darsda to'g'ri chiziq tenglamasini turli ma'lumotlardan tuzishni va parallel hamda perpendikulyar chiziqlarni o'rganamiz.`,
    r`Ko'rishguncha!`,
  ],
};

export default lesson;
