import {meta} from '../catalog';
import type {Lesson} from '../types';

const r = String.raw;

const lesson: Lesson = {
  ...meta(7),
  topics: ['Nuqta-qiyalik', 'Ikki nuqtadan', 'Parallel', 'Perpendikulyar', 'Siljitish'],
  cover: [
    r`Assalomu alaykum! Yettinchi darsga xush kelibsiz. Bugungi mavzu — to'g'ri chiziq tenglamasi va grafiklar.`,
    r`Nuqta va qiyalikdan, ikki nuqtadan yoki grafikdan chiziq tenglamasini tuzishni, parallel va perpendikulyar chiziqlarni hamda grafikni siljitishni o'rganamiz.`,
  ],
  goals: [
    r`Har qanday ma'lumotdan chiziq tenglamasini tuzish`,
    r`Grafikdan tenglamani o'qish`,
    r`Parallel va perpendikulyar chiziqlar qiyaligini topish`,
    r`Chiziqni yuqoriga, pastga va yon tomonga siljitish`,
  ],
  goalsSay: [
    r`Darsning maqsadlari.`,
    r`Birinchi: nuqta va qiyalik yoki ikki nuqta berilganda chiziq tenglamasini tez tuzish.`,
    r`Ikkinchi: grafikda chizilgan chiziqning tenglamasini o'qib olish.`,
    r`Uchinchi: parallel va perpendikulyar chiziqlarning qiyaliklari orasidagi bog'lanishni bilish.`,
    r`To'rtinchi: chiziq grafigi siljitilganda tenglama qanday o'zgarishini tushunish.`,
    r`Bu ko'nikmalar keyingi darslarda — sistemalar va modellarda — doimiy ishlatiladi.`,
  ],
  goalsResult: r`istalgan chiziq tenglamasini bir daqiqada tuzish`,
  slides: [
    {
      type: 'formula',
      kicker: 'FORMULALAR',
      title: "To'g'ri chiziq tenglamasining 3 ko'rinishi",
      formulas: [
        {label: 'Slope-intercept', tex: r`y=mx+b`, note: r`qiyalik va $y$-kesishma ko'rinadi`},
        {label: 'Point-slope', tex: r`y-y_1=m(x-x_1)`, note: r`bitta nuqta $(x_1,y_1)$ va qiyalik ma'lum bo'lsa`},
        {label: 'Standard', tex: r`Ax+By=C`, note: r`qiyalik $-\frac{A}{B}$, kesishmalar oson topiladi`},
      ],
      say: [
        r`To'g'ri chiziq tenglamasining uchta ko'rinishi bor va SAT uchalasini ham ishlatadi.`,
        r`Birinchisi — y teng m x plyus b. Unda qiyalik va y kesishma darhol ko'rinadi.`,
        r`Ikkinchisi — nuqta-qiyalik ko'rinishi: y minus y bir teng m karra x minus x bir. Bitta nuqta va qiyalik ma'lum bo'lganda eng qulay.`,
        r`Uchinchisi — standart ko'rinish: A x plyus B y teng C. Unda qiyalik minus A bo'lingan B, kesishmalar esa juda oson topiladi.`,
      ],
    },
    {
      type: 'example',
      kicker: '1-MISOL',
      title: 'Ikki nuqtadan tenglama',
      label: 'MISOL',
      question: r`Find the equation of the line through $(1,\,2)$ and $(3,\,8)$.`,
      steps: [
        {m: r`m=\frac{8-2}{3-1}=3`, note: r`avval qiyalik`},
        {m: r`y-2=3(x-1)`, note: r`point-slope, nuqta $(1,2)$`},
        {m: r`y=3x-1`, note: r`soddalashtiramiz`},
      ],
      answer: r`$y=3x-1$`,
      tip: r`Tekshiruv: ikkinchi nuqta $(3,8)$: $3\cdot3-1=8$ ✓`,
      say: [
        r`Birinchi misol: bir, ikki va uch, sakkiz nuqtalaridan o'tuvchi chiziq.`,
        r`Avval qiyalik: sakkiz minus ikki, bo'lingan uch minus bir — uch.`,
        r`Nuqta-qiyalik ko'rinishiga birinchi nuqtani qo'yamiz: y minus ikki teng uch karra x minus bir.`,
        r`Qavsni ochib, ikkini o'ngga o'tkazsak: y teng uch x minus bir.`,
        r`Javob: y teng uch x minus bir.`,
        r`Ikkinchi nuqta bilan tekshiramiz: uch karra uch minus bir — sakkiz. To'g'ri. Tekshiruv uchun doim foydalanilmagan nuqtani oling.`,
      ],
    },
    {
      type: 'graph',
      kicker: 'GRAFIKDAN',
      title: 'Grafikdan tenglamani o\'qish',
      x: [-3, 5],
      y: [-4, 7],
      items: [
        {kind: 'fn', f: (x) => 2 * x - 2, label: r`?`, note: r`Grafikda aniq nuqtalarni qidiring — panjara kesishmalari`},
        {kind: 'point', x: 0, y: -2, label: r`$(0,\,-2)$`, color: '#22C55E', note: r`$y$-kesishma: $b=-2$`},
        {kind: 'point', x: 3, y: 4, label: r`$(3,\,4)$`, color: '#22C55E', note: r`Ikkinchi aniq nuqta: $(3,\,4)$`},
        {kind: 'note', note: r`$m=\frac{4-(-2)}{3-0}=2\ \Rightarrow\ y=2x-2$`},
      ],
      say: [
        r`Endi grafikdan tenglamani o'qiymiz. SAT ko'pincha chiziqni rasmda beradi va tenglamani so'raydi.`,
        r`Birinchi qoida: faqat panjaraning aniq kesishmalariga tushgan nuqtalardan foydalaning, taxminiy nuqtalardan emas.`,
        r`Chiziq y o'qini nol, minus ikki nuqtasida kesadi — demak, b teng minus ikki.`,
        r`Yana bir aniq nuqta: uch, to'rt.`,
        r`Qiyalik: to'rt minus minus ikki, bo'lingan uch — ikki. Tenglama: y teng ikki x minus ikki.`,
      ],
    },
    {
      type: 'compare',
      kicker: 'PARALLEL VA PERPENDIKULYAR',
      title: 'Ikki chiziq qiyaliklari',
      cards: [
        {title: 'Parallel', rule: r`Qiyaliklar **teng**: $m_1=m_2$`, example: r`$y=2x+1$ va $y=2x-3$`},
        {title: 'Perpendikulyar', rule: r`Qiyaliklar **teskari va qarama-qarshi**: $m_2=-\frac{1}{m_1}$`, example: r`$m_1=\frac23\ \Rightarrow\ m_2=-\frac32$`},
        {title: 'Ustma-ust', rule: r`Qiyalik ham, kesishma ham teng`, example: r`$y=2x+1$ va $2y=4x+2$`},
      ],
      say: [
        r`Ikki chiziq orasidagi munosabatlar.`,
        r`Parallel chiziqlarning qiyaliklari teng. Masalan, y teng ikki x plyus bir va y teng ikki x minus uch — ikkalasining qiyaligi ikki.`,
        r`Perpendikulyar chiziqlarning qiyaliklari bir-biriga teskari va qarama-qarshi ishorali. Ikki uchdan bo'lsa, perpendikulyar qiyalik minus uch ikkidan. Ularning ko'paytmasi doim minus bir.`,
        r`Agar qiyalik ham, kesishma ham teng bo'lsa — bu bitta chiziq, ya'ni ustma-ust tushgan chiziqlar. Tenglama boshqacha yozilgan bo'lishi mumkin, masalan ikki y teng to'rt x plyus ikki.`,
      ],
    },
    {
      type: 'graph',
      kicker: 'GRAFIKDA',
      title: 'Parallel va perpendikulyar',
      x: [-5, 5],
      y: [-5, 6],
      items: [
        {kind: 'fn', f: (x) => 2 * x + 1, label: r`$y=2x+1$`, note: r`Asosiy chiziq: $m=2$`},
        {kind: 'fn', f: (x) => 2 * x - 3, label: r`$y=2x-3$`, note: r`Parallel: $m=2$ — hech qachon kesishmaydi`},
        {kind: 'fn', f: (x) => -0.5 * x + 1, label: r`$y=-\frac12x+1$`, note: r`Perpendikulyar: $m=-\frac12$, to'g'ri burchak ostida kesishadi`},
      ],
      say: [
        r`Grafikda ko'ramiz.`,
        r`Asosiy chiziq: y teng ikki x plyus bir.`,
        r`Unga parallel chiziq: qiyaligi ham ikki, faqat pastroqda. Ular hech qachon kesishmaydi.`,
        r`Perpendikulyar chiziq: qiyaligi minus yarim. Ikki karra minus yarim — minus bir. U asosiy chiziqni to'g'ri burchak ostida kesib o'tadi.`,
      ],
    },
    {
      type: 'example',
      kicker: 'SAT MISOLI',
      title: 'Perpendikulyar chiziq tenglamasi',
      question: r`Line $k$ is perpendicular to the line $y=\tfrac23x-4$ and passes through the point $(2,\,1)$. Which equation defines line $k$?`,
      choices: [r`$y=\frac23x-\frac13$`, r`$y=-\frac32x+4$`, r`$y=-\frac32x-2$`, r`$y=\frac32x-2$`],
      steps: [
        {m: r`m_k=-\frac32`, note: r`teskari va qarama-qarshi`},
        {m: r`1=-\frac32\cdot2+b`, note: r`nuqtani qo'yamiz`},
        {m: r`b=4\ \Rightarrow\ y=-\frac32x+4`},
      ],
      answer: r`B`,
      tip: r`Avval qiyalik bo'yicha variantlarni saralang: faqat B va C da $-\frac32$. Keyin nuqtani tekshiring.`,
      say: [
        r`SAT misoli. Line k is perpendicular to y equals two thirds x minus four and passes through two, one. Which equation defines line k?`,
        r`Perpendikulyar qiyalik: ikki uchdan ga teskari va qarama-qarshi — minus uch ikkidan.`,
        r`Nuqtani qo'yamiz: bir teng minus uch ikkidan karra ikki plyus b, ya'ni bir teng minus uch plyus b.`,
        r`B teng to'rt. Tenglama: y teng minus uch ikkidan x plyus to'rt.`,
        r`Javob: B.`,
        r`Tezroq yo'l: avval qiyalik bo'yicha variantlarni saralang — faqat B va C da minus uch ikkidan. Keyin nuqtani qo'yib, ulardan birini tanlang.`,
      ],
    },
    {
      type: 'cards',
      kicker: 'SILJITISH',
      title: 'Grafikni siljitish',
      cards: [
        {title: 'Yuqoriga $k$ birlik', text: r`$y=mx+b\ \to\ y=mx+b+k$`},
        {title: 'Pastga $k$ birlik', text: r`$y=mx+b\ \to\ y=mx+b-k$`},
        {title: "O'ngga $h$ birlik", text: r`$x$ o'rniga $(x-h)$: $y=m(x-h)+b$`},
        {title: 'Qiyalik o\'zgarmaydi', text: r`Siljitilgan chiziq dastlabkisiga **parallel**`},
      ],
      say: [
        r`Grafikni siljitish.`,
        r`Chiziqni k birlik yuqoriga siljitsak, tenglamaning oxiriga k qo'shiladi.`,
        r`Pastga siljitsak, k ayiriladi.`,
        r`O'ngga h birlik siljitish uchun x o'rniga x minus h yoziladi. E'tibor bering: o'ngga — minus, chapga — plyus. Bu ko'pchilikka teskari tuyuladi.`,
        r`Siljitishda qiyalik o'zgarmaydi — yangi chiziq eskisiga parallel bo'ladi.`,
      ],
    },
    {
      type: 'example',
      kicker: 'SPR MISOLI',
      title: 'Siljitilgan chiziqning kesishmasi',
      label: 'SPR SAVOLI',
      question: r`The graph of $y=4x-1$ is shifted up 3 units. What is the $x$-intercept of the new graph?`,
      steps: [
        {m: r`y=4x-1+3=4x+2`, note: r`yuqoriga — qo'shamiz`},
        {m: r`0=4x+2`, note: r`$x$-kesishmada $y=0$`},
        {m: r`x=-\frac12`},
      ],
      answer: r`$-1/2$ yoki $-.5$`,
      say: [
        r`SPR misoli. The graph of y equals four x minus one is shifted up three units. What is the x-intercept of the new graph?`,
        r`Yuqoriga uch birlik — uchni qo'shamiz: y teng to'rt x plyus ikki.`,
        r`X kesishmada y nolga teng: nol teng to'rt x plyus ikki.`,
        r`X teng minus yarim.`,
        r`Javob: minus bir slesh ikki yoki minus nuqta besh. Ikkala kiritish ham to'g'ri.`,
      ],
    },
    {
      type: 'trap',
      title: 'Perpendikulyar qiyalik',
      question: r`A line has slope $\tfrac34$. What is the slope of a line perpendicular to it?`,
      wrong: r`$-\tfrac34$ yoki $\tfrac43$`,
      why: r`Faqat ishorani yoki faqat kasrni aylantirish yetarli emas — ikkalasini ham qilish kerak.`,
      right: r`Kasrni aylantiramiz **va** ishorani o'zgartiramiz: **$-\frac43$**. Tekshiruv: $\frac34\cdot\left(-\frac43\right)=-1$ ✓`,
      say: [
        r`Tuzoq. A line has slope three fourths. What is the slope of a perpendicular line?`,
        r`Ikki xil xato bor: faqat ishorani o'zgartirib minus uch to'rtdan deyish yoki faqat kasrni aylantirib to'rt uchdan deyish. Ikkala variant ham testda bo'ladi.`,
        r`To'g'risi — ikkalasini birga qilish: minus to'rt uchdan. Tekshiruv: ikki qiyalik ko'paytmasi minus bir bo'lishi kerak.`,
      ],
    },
    {
      type: 'example',
      kicker: 'MUSTAQIL MASHQ',
      title: "O'zingiz yeching",
      label: 'MASHQ',
      question: r`A line is parallel to $2x+y=7$ and passes through $(-1,\,3)$. What is its $y$-intercept?`,
      steps: [
        {m: r`y=-2x+7\Rightarrow m=-2`, note: r`parallel — qiyalik bir xil`},
        {m: r`3=-2(-1)+b`},
        {m: r`b=1`},
      ],
      answer: r`$1$`,
      say: [
        r`Mustaqil mashq. Videoni to'xtating. Chiziq ikki x plyus y teng yetti chiziqqa parallel va minus bir, uch nuqtasidan o'tadi. Uning y kesishmasi qancha?`,
        r`Berilgan chiziqni y ga nisbatan yechamiz: y teng minus ikki x plyus yetti. Qiyalik minus ikki, parallel chiziqniki ham shunday.`,
        r`Nuqtani qo'yamiz: uch teng minus ikki karra minus bir plyus b, ya'ni uch teng ikki plyus b.`,
        r`B teng bir.`,
        r`Javob: bir.`,
      ],
    },
    {
      type: 'cards',
      kicker: 'MAXSUS CHIZIQLAR',
      title: 'Gorizontal va vertikal chiziqlar',
      cards: [
        {title: r`Gorizontal: $y=b$`, text: r`Qiyalik $0$; $x$-o'qiga parallel`},
        {title: r`Vertikal: $x=a$`, text: r`Qiyalik aniqlanmagan; $y$-o'qiga parallel`},
        {title: 'Ikki nuqtada $y$ bir xil', text: r`$(1,5)$ va $(7,5)$ $\Rightarrow$ $y=5$`},
        {title: 'Ikki nuqtada $x$ bir xil', text: r`$(4,-1)$ va $(4,6)$ $\Rightarrow$ $x=4$`},
      ],
      say: [
        r`Ikkita maxsus chiziqni alohida eslab qoling.`,
        r`Gorizontal chiziq: y teng b. Qiyaligi nol, x o'qiga parallel.`,
        r`Vertikal chiziq: x teng a. Qiyaligi aniqlanmagan, y o'qiga parallel. Bu chiziq funksiya emas.`,
        r`Agar ikki nuqtaning y koordinatalari bir xil bo'lsa — chiziq gorizontal: masalan bir, besh va yetti, besh — y teng besh.`,
        r`Agar x koordinatalari bir xil bo'lsa — vertikal: to'rt, minus bir va to'rt, olti — x teng to'rt. Qiyalik formulasiga qo'ysangiz, maxraj nol chiqadi — bu belgi vertikal chiziqni bildiradi.`,
      ],
    },
    {
      type: 'example',
      kicker: 'SAT MISOLI',
      title: 'Vertikal chiziq tenglamasi',
      question: r`A line in the $xy$-plane passes through the points $(4,\,-1)$ and $(4,\,6)$. Which equation defines the line?`,
      choices: [r`$x=4$`, r`$y=4$`, r`$y=x-5$`, r`$y=\frac74x$`],
      steps: [
        {m: r`x_1=x_2=4`, note: r`$x$ o'zgarmaydi`},
        {m: r`m=\frac{6-(-1)}{4-4}=\frac{7}{0}`, note: r`aniqlanmagan — vertikal chiziq`},
      ],
      answer: r`A`,
      tip: r`B variant ($y=4$) — gorizontal chiziq, bu yerda tuzoq.`,
      say: [
        r`SAT misoli. A line passes through four, minus one and four, six. Which equation defines the line?`,
        r`Ikkala nuqtada x bir xil — to'rt. Chiziq bo'ylab x o'zgarmaydi.`,
        r`Qiyalik formulasiga qo'ysak, maxraj nol chiqadi — qiyalik aniqlanmagan, chiziq vertikal.`,
        r`Tenglama: x teng to'rt. Javob A.`,
        r`B variant — y teng to'rt — gorizontal chiziq. X va y ni almashtirib yuborish — bu yerdagi asosiy tuzoq.`,
      ],
    },
  ],
  recap: [
    r`Nuqta va qiyalik: $y-y_1=m(x-x_1)$`,
    r`Parallel: $m$ teng; perpendikulyar: $m_1m_2=-1$`,
    r`Yuqoriga $+k$, o'ngga $x\to x-h$; qiyalik o'zgarmaydi`,
  ],
  homework: r`platformada chiziq tenglamasi bo'yicha 15 ta savol`,
  recapSay: [
    r`Xulosa.`,
    r`Nuqta va qiyalik ma'lum bo'lsa — nuqta-qiyalik formulasi yoki nuqtani y teng m x plyus b ga qo'yish.`,
    r`Parallel chiziqlarning qiyaliklari teng, perpendikulyarlarning ko'paytmasi minus bir.`,
    r`Yuqoriga siljitish — qo'shish, o'ngga siljitish — x o'rniga x minus h. Qiyalik o'zgarmaydi.`,
    r`Hozir platformada chiziq tenglamasi bo'yicha o'n beshta savolni yeching. Keyingi darsda chiziqli modellar va matnli masalalarni o'rganamiz.`,
    r`Ko'rishguncha!`,
  ],
};

export default lesson;
