import {meta} from '../catalog';
import type {Lesson} from '../types';

const r = String.raw;

const lesson: Lesson = {
  ...meta(8),
  topics: ['Model tuzish', 'Jadvaldan model', 'Grafikda model', 'Ikki o\'zgaruvchi', 'Talqin'],
  cover: [
    r`Assalomu alaykum! Sakkizinchi darsga xush kelibsiz. Bugungi mavzu — chiziqli modellar va matnli masalalar.`,
    r`Matndan, jadvaldan va grafikdan chiziqli model tuzishni, ikki o'zgaruvchili cheklovlarni va modeldagi sonlarni talqin qilishni o'rganamiz.`,
  ],
  goals: [
    r`Matndan chiziqli model tuzish`,
    r`Jadval va grafikdan modelni tiklash`,
    r`Ikki o'zgaruvchili cheklov tenglamalarini yechish`,
    r`Modeldagi har bir sonning ma'nosini tushuntirish`,
  ],
  goalsSay: [
    r`Darsning maqsadlari.`,
    r`Birinchi: matnli masaladan chiziqli model — funksiya yoki tenglama — tuzish.`,
    r`Ikkinchi: jadval yoki grafik berilganda modelni tiklash.`,
    r`Uchinchi: chipta, narx, byudjet kabi ikki o'zgaruvchili masalalarni yechish.`,
    r`To'rtinchi: modeldagi har bir son nimani anglatishini aniq tushuntirish.`,
    r`SAT'dagi Algebra savollarining katta qismi aynan matnli modellar shaklida beriladi.`,
  ],
  goalsResult: r`matnli masalalardan qo'rqmaslik`,
  slides: [
    {
      type: 'cards',
      kicker: 'ALGORITM',
      title: 'Chiziqli model tuzish: 4 qadam',
      cards: [
        {title: "O'zgaruvchilar", text: r`Nima noma'lum? $t$ — vaqt, $C$ — narx… harf bilan belgilang`},
        {title: "Boshlang'ich qiymat", text: r`$t=0$ dagi miqdor — bu $b$`},
        {title: "O'zgarish tezligi", text: r`"per", "each", "every" — bu $m$; kamaysa — minus`},
        {title: 'Tenglama va tekshiruv', text: r`$y=b+mt$; oddiy son qo'yib mantiqan tekshiring`},
      ],
      say: [
        r`Chiziqli model tuzish uchun to'rt qadamli algoritm.`,
        r`Birinchi: o'zgaruvchilarni aniqlang va harflar bilan belgilang — masalan t vaqt, C narx.`,
        r`Ikkinchi: boshlang'ich qiymatni toping — vaqt nolga teng bo'lgandagi miqdor. Bu modeldagi b.`,
        r`Uchinchi: o'zgarish tezligini toping — per, each, every so'zlari bilan beriladi. Miqdor kamaysa, tezlik manfiy bo'ladi.`,
        r`To'rtinchi: tenglamani yozing va oddiy bir sonni qo'yib, natija mantiqan to'g'rimi — tekshiring.`,
      ],
    },
    {
      type: 'example',
      kicker: '1-MISOL',
      title: 'Matndan model',
      question: r`A tank contains 500 liters of water. Water drains from the tank at a constant rate of 12 liters per minute. Which function gives the volume $V$, in liters, after $t$ minutes?`,
      choices: [r`$V=500+12t$`, r`$V=12t-500$`, r`$V=500-12t$`, r`$V=488t$`],
      steps: [
        {m: r`b=500`, note: r`boshlang'ich hajm`},
        {m: r`m=-12`, note: r`"drains" — kamayadi`},
        {m: r`V=500-12t`},
      ],
      answer: r`C`,
      tip: r`Tekshiruv: $t=0$ da $V=500$ ✓, $t=1$ da $488$ — haqiqatan $12$ ga kamaydi ✓`,
      say: [
        r`Birinchi misol. Bakda besh yuz litr suv bor. Suv har daqiqada o'n ikki litrdan oqib chiqadi. Which function gives the volume after t minutes?`,
        r`Boshlang'ich qiymat — besh yuz litr.`,
        r`O'zgarish tezligi — o'n ikki litr har daqiqada, lekin suv kamayadi, shuning uchun minus o'n ikki.`,
        r`Model: V teng besh yuz minus o'n ikki t.`,
        r`Javob: C.`,
        r`Tekshiramiz: t nol bo'lsa, besh yuz — to'g'ri. T bir bo'lsa, to'rt yuz sakson sakkiz — haqiqatan o'n ikkiga kamaydi.`,
      ],
    },
    {
      type: 'example',
      kicker: '2-MISOL',
      title: 'Modeldan foydalanish',
      label: 'SPR SAVOLI',
      question: r`Using $V=500-12t$, after how many minutes will the tank contain 140 liters of water?`,
      steps: [
        {m: r`500-12t=140`, note: r`$V$ o'rniga $140$`},
        {m: r`12t=360`},
        {m: r`t=30`},
      ],
      answer: r`$30$`,
      say: [
        r`Davomi: necha daqiqadan keyin bakda bir yuz qirq litr suv qoladi?`,
        r`V o'rniga bir yuz qirqni qo'yamiz: besh yuz minus o'n ikki t teng bir yuz qirq.`,
        r`O'n ikki t teng uch yuz oltmish.`,
        r`T teng o'ttiz.`,
        r`Javob: o'ttiz daqiqa. Modelda qaysi harf nima ekanini bilsangiz, savol oddiy tenglamaga aylanadi.`,
      ],
    },
    {
      type: 'table',
      kicker: 'JADVALDAN MODEL',
      title: 'Jadval berilganda',
      head: ['Yil, $t$', 'Narx, $P$ (dollar)', "O'zgarish"],
      rows: [
        [r`$0$`, r`$1200$`, r`—`],
        [r`$2$`, r`$1500$`, r`$+300$ (2 yilda)`],
        [r`$4$`, r`$1800$`, r`$+300$ (2 yilda)`],
      ],
      banner: r`$m=\frac{300}{2}=150$ dollar/yil, $b=1200$ $\Rightarrow$ $P=1200+150t$`,
      say: [
        r`Jadval berilganda model qanday tiklanadi? Bu jadvalda yillar va narx berilgan.`,
        r`Nol yilda narx bir ming ikki yuz — bu boshlang'ich qiymat.`,
        r`Ikki yilda narx bir ming besh yuzga yetdi — uch yuzga oshdi.`,
        r`To'rtinchi yilda yana uch yuzga oshdi. O'zgarish bir xil — demak model chiziqli.`,
        r`Qiyalik: uch yuz bo'lingan ikki — bir yilda bir yuz ellik dollar. Model: P teng bir ming ikki yuz plyus bir yuz ellik t. E'tibor bering: jadvalda qadam ikki yil, shuning uchun uch yuzni ikkiga bo'lish kerak.`,
      ],
    },
    {
      type: 'graph',
      kicker: 'GRAFIKDA',
      title: r`Model grafigi: $V=500-12t$`,
      x: [0, 45],
      y: [0, 550],
      items: [
        {kind: 'fn', f: (x) => 500 - 12 * x, domain: [0, 41.67], label: r`$V=500-12t$`, note: r`Grafik — tushib boruvchi chiziq`},
        {kind: 'point', x: 0, y: 500, label: r`$(0,\,500)$`, color: '#22C55E', note: r`$V$-kesishma: boshlang'ich hajm`},
        {kind: 'point', x: 30, y: 140, label: r`$(30,\,140)$`, color: '#FFFFFF', note: r`$30$ daqiqada $140$ litr`},
        {kind: 'point', x: 41.67, y: 0, label: r`$t\approx41.7$`, color: '#EC4899', note: r`$t$-kesishma: bak bo'shaydi`},
      ],
      say: [
        r`Modelni grafikda ko'ramiz.`,
        r`Grafik — pastga tushib boruvchi to'g'ri chiziq, chunki qiyalik manfiy.`,
        r`Vertikal o'q bilan kesishish — boshlang'ich hajm, besh yuz litr.`,
        r`O'ttiz daqiqada — bir yuz qirq litr, biz hisoblagan nuqta.`,
        r`Gorizontal o'q bilan kesishish — bak bo'shagan payt: besh yuzni o'n ikkiga bo'lsak, taxminan qirq bir butun yetti daqiqa. SAT ko'pincha "what does the t-intercept represent" deb so'raydi — javob: bak bo'shaydigan vaqt.`,
      ],
    },
    {
      type: 'example',
      kicker: 'SAT MISOLI',
      title: "Sonning ma'nosi",
      question: r`The number of books $N$ left to sell at a fair after $d$ days is modeled by $N=250-15d$. What is the best interpretation of $250$?`,
      choices: [r`Books sold per day`, r`Books at the start of the fair`, r`Days the fair lasts`, r`Books left after 15 days`],
      steps: [
        {m: r`d=0\Rightarrow N=250`, note: r`boshlang'ich qiymat`},
        {m: r`15`, note: r`— kuniga sotiladigan kitoblar (A varianti — tuzoq)`},
      ],
      answer: r`B`,
      say: [
        r`SAT misoli. Yarmarkada d kundan keyin sotilmay qolgan kitoblar soni N teng ikki yuz ellik minus o'n besh d. What is the best interpretation of two hundred fifty?`,
        r`D nolga teng bo'lganda N ikki yuz ellik. Demak, ikki yuz ellik — yarmarka boshidagi kitoblar soni.`,
        r`O'n besh esa kuniga sotiladigan kitoblar soni. A variant aynan o'n beshning ma'nosi — chalkashtirish uchun qo'yilgan.`,
        r`Javob: B.`,
      ],
    },
    {
      type: 'compare',
      kicker: 'CHIZIQLIMI?',
      title: 'Qaysi vaziyat chiziqli?',
      cards: [
        {title: 'Chiziqli', rule: r`Har davrda **bir xil son** qo'shiladi/ayiriladi`, example: r`"har oy $+50$ dollar"`},
        {title: 'Chiziqli emas', rule: r`Har davrda **bir xil foiz** o'zgaradi`, example: r`"har oy $+5\%$" — eksponensial`},
        {title: 'Ikki o\'zgaruvchi', rule: r`Ikki xil narsa umumiy cheklovda`, example: r`$12a+7c=605$`},
      ],
      say: [
        r`Qaysi vaziyat chiziqli model bilan ifodalanadi?`,
        r`Agar har bir davrda bir xil son qo'shilsa yoki ayirilsa — chiziqli. Masalan, har oy ellik dollar.`,
        r`Agar har davrda bir xil foiz o'zgarsa — bu chiziqli emas, eksponensial model. Uni keyingi modulda o'rganamiz.`,
        r`Uchinchi tur — ikki xil narsa umumiy cheklovda: masalan kattalar va bolalar chiptalari umumiy summasi. Bu ham chiziqli, lekin ikki o'zgaruvchili tenglama.`,
      ],
    },
    {
      type: 'example',
      kicker: '3-MISOL',
      title: "Ikki o'zgaruvchili cheklov",
      label: 'SPR SAVOLI',
      question: r`Adult tickets cost 12 dollars and child tickets cost 7 dollars. A school collected 605 dollars from ticket sales. If 30 adult tickets were sold, how many child tickets were sold?`,
      steps: [
        {m: r`12a+7c=605`, note: r`umumiy model`},
        {m: r`12\cdot30+7c=605`, note: r`$a=30$`},
        {m: r`7c=245`},
        {m: r`c=35`},
      ],
      answer: r`$35$`,
      say: [
        r`Uchinchi misol. Kattalar chiptasi o'n ikki dollar, bolalar chiptasi yetti dollar. Maktab chiptalardan olti yuz besh dollar yig'di. Agar o'ttizta kattalar chiptasi sotilgan bo'lsa, nechta bolalar chiptasi sotilgan?`,
        r`Umumiy model: o'n ikki a plyus yetti c teng olti yuz besh. Bu yerda a — kattalar, c — bolalar chiptalari soni.`,
        r`A o'rniga o'ttizni qo'yamiz: uch yuz oltmish plyus yetti c teng olti yuz besh.`,
        r`Yetti c teng ikki yuz qirq besh.`,
        r`C teng o'ttiz besh.`,
        r`Javob: o'ttiz besh. Chiptalar soni butun son chiqishi kerak — bu ham o'ziga xos tekshiruv.`,
      ],
    },
    {
      type: 'trap',
      title: '"Per day" ni unutish',
      question: r`A car rental costs 40 dollars per day plus 0.25 dollars per mile. What is the cost of renting the car for 3 days and driving 100 miles?`,
      wrong: r`$40+0.25\cdot100=65$`,
      why: r`Kunlik narx kunlar soniga ko'paytirilmagan — "per day" ham o'zgaruvchiga bog'liq.`,
      right: r`$40\cdot3+0.25\cdot100=120+25=$ **145** dollar. Har bir "per" — ko'paytirish.`,
      say: [
        r`Tuzoq. Avtomobil ijarasi kuniga qirq dollar plyus har bir mil uchun yigirma besh sent. Uch kun va yuz mil uchun narx qancha?`,
        r`Ko'p o'quvchi qirqni boshlang'ich to'lov deb o'ylaydi va oltmish besh dollar chiqaradi. Lekin qirq — "per day", ya'ni kunlar soniga ko'paytiriladi.`,
        r`To'g'risi: qirq karra uch — bir yuz yigirma, plyus yigirma besh — bir yuz qirq besh dollar. Qoida: har bir "per" so'zi ko'paytirishni bildiradi.`,
      ],
    },
    {
      type: 'example',
      kicker: 'MUSTAQIL MASHQ',
      title: "O'zingiz yeching",
      label: 'MASHQ',
      question: r`At 6 a.m. the temperature was $75^\circ$F. It dropped by $3^\circ$F per hour. After how many hours was the temperature $51^\circ$F?`,
      steps: [
        {m: r`T=75-3h`, note: r`model`},
        {m: r`75-3h=51`},
        {m: r`h=8`},
      ],
      answer: r`$8$`,
      say: [
        r`Mustaqil mashq. Videoni to'xtating. Ertalab soat oltida harorat yetmish besh daraja edi va har soatda uch darajadan pasaydi. Necha soatdan keyin harorat ellik bir daraja bo'ldi?`,
        r`Model: T teng yetmish besh minus uch h.`,
        r`Ellik birga tenglaymiz: yetmish besh minus uch h teng ellik bir.`,
        r`Uch h teng yigirma to'rt, h teng sakkiz.`,
        r`Javob: sakkiz soat. Agar savol "soat nechada" deb so'rasa — oltiga sakkizni qo'shib, kunduzi soat ikki bo'lardi. Savol aniq nimani so'rayotganiga doim qarang.`,
      ],
    },
    {
      type: 'example',
      kicker: '4-MISOL',
      title: "Ikki ma'lumotdan model",
      label: 'SPR SAVOLI',
      question: r`A plant was 12 cm tall 2 weeks after it was planted and 20 cm tall 6 weeks after it was planted. If the plant grew at a constant rate, how tall, in cm, was it when it was planted?`,
      steps: [
        {m: r`m=\frac{20-12}{6-2}=2`, note: r`sm/hafta`},
        {m: r`12=2\cdot2+b`, note: r`$(2,\,12)$ nuqtani qo'yamiz`},
        {m: r`b=8`, note: r`"when it was planted" — $t=0$`},
      ],
      answer: r`$8$`,
      say: [
        r`To'rtinchi misol. O'simlik ekilgandan ikki hafta keyin o'n ikki santimetr, olti hafta keyin yigirma santimetr bo'ldi. U doimiy tezlikda o'sgan bo'lsa, ekilgan paytda bo'yi qancha edi?`,
        r`Ikki ma'lumotni nuqta deb olamiz: ikki, o'n ikki va olti, yigirma. Qiyalik: sakkiz bo'lingan to'rt — haftasiga ikki santimetr.`,
        r`Bitta nuqtani y teng m x plyus b ga qo'yamiz: o'n ikki teng ikki karra ikki plyus b.`,
        r`B teng sakkiz. "When it was planted" — bu t teng nol, ya'ni aynan b.`,
        r`Javob: sakkiz santimetr. Matnda "initially", "at the start", "when it was planted" kabi iboralar doim b ni so'raydi.`,
      ],
    },
  ],
  recap: [
    r`Model: $y=b+mt$ — $b$ boshlang'ich, $m$ "per…" tezlik`,
    r`Jadvalda: $m=\frac{\Delta y}{\Delta x}$, qadamga e'tibor bering`,
    r`Har bir "per" — ko'paytirish; kamaysa — minus`,
  ],
  homework: r`platformada chiziqli modellar bo'yicha 15 ta savol`,
  recapSay: [
    r`Xulosa.`,
    r`Chiziqli model: y teng b plyus m t. B — boshlang'ich qiymat, m — "per" bilan berilgan o'zgarish tezligi.`,
    r`Jadvaldan model tiklashda y ning o'zgarishini x ning o'zgarishiga bo'ling — jadval qadami birdan katta bo'lishi mumkin.`,
    r`Har bir "per" — ko'paytirish, miqdor kamaysa — tezlik manfiy.`,
    r`Hozir platformada chiziqli modellar bo'yicha o'n beshta savolni yeching. Keyingi darsda ikki noma'lumli tenglamalar sistemasini o'rganamiz.`,
    r`Ko'rishguncha!`,
  ],
};

export default lesson;
