import {meta} from '../catalog';
import type {Lesson} from '../types';

const r = String.raw;

const lesson: Lesson = {
  ...meta(9),
  topics: ["O'rniga qo'yish", "Qo'shish usuli", 'Desmos', 'Matnli sistema', 'Qisqa yo\'llar'],
  cover: [
    r`Assalomu alaykum! To'qqizinchi darsga xush kelibsiz. Bugungi mavzu — ikki noma'lumli tenglamalar sistemasi.`,
    r`Sistemani o'rniga qo'yish, qo'shish va Desmos usullarida yechishni, matnli masaladan sistema tuzishni va SAT'dagi qisqa yo'llarni o'rganamiz.`,
  ],
  goals: [
    r`O'rniga qo'yish usulida yechish`,
    r`Qo'shish (elimination) usulida yechish`,
    r`Matnli masaladan sistema tuzish`,
    r`$x+y$ kabi ifodalarni sistemani to'liq yechmasdan topish`,
  ],
  goalsSay: [
    r`Darsning maqsadlari.`,
    r`Birinchi: o'rniga qo'yish usuli.`,
    r`Ikkinchi: qo'shish usuli — SAT'da eng ko'p ishlatiladigan usul.`,
    r`Uchinchi: matnli masaladan ikki tenglamali sistema tuzish.`,
    r`To'rtinchi: x plyus y kabi ifodalarni sistemani to'liq yechmasdan, bir qadamda topish.`,
    r`Sistemalar har bir SAT testida bir necha marta uchraydi.`,
  ],
  goalsResult: r`har qanday sistemani 1 daqiqada yechish`,
  slides: [
    {
      type: 'cards',
      kicker: 'USULLAR',
      title: 'Sistemani yechishning 3 usuli',
      cards: [
        {title: "O'rniga qo'yish", text: r`Bitta o'zgaruvchini ifodalab, ikkinchi tenglamaga qo'yamiz`, icon: 'bolt'},
        {title: "Qo'shish (elimination)", text: r`Tenglamalarni qo'shib/ayirib, bitta o'zgaruvchini yo'qotamiz`, icon: 'target'},
        {title: 'Desmos', text: r`Ikkala tenglamani chizamiz — kesishish nuqtasi yechim`, icon: 'calc'},
      ],
      banner: r`Yechim — ikkala tenglamani **bir vaqtda** qanoatlantiradigan juftlik $(x,\,y)$`,
      say: [
        r`Tenglamalar sistemasi — bir vaqtda bajarilishi kerak bo'lgan ikki tenglama. Uni yechishning uchta usuli bor.`,
        r`O'rniga qo'yish: bitta tenglamadan bir o'zgaruvchini ifodalab, ikkinchi tenglamaga qo'yamiz.`,
        r`Qo'shish usuli: tenglamalarni qo'shib yoki ayirib, bitta o'zgaruvchini yo'qotamiz.`,
        r`Desmos: ikkala tenglamani chizamiz va kesishish nuqtasini bosamiz.`,
        r`Sistemaning yechimi — ikkala tenglamani bir vaqtda qanoatlantiradigan x va y juftligi.`,
      ],
    },
    {
      type: 'example',
      kicker: '1-USUL',
      title: "O'rniga qo'yish",
      label: 'MISOL',
      question: r`Solve the system: $y=2x-1$ and $3x+2y=12$.`,
      steps: [
        {m: r`3x+2(2x-1)=12`, note: r`$y$ o'rniga $2x-1$`},
        {m: r`7x-2=12`},
        {m: r`x=2`},
        {m: r`y=2\cdot2-1=3`},
      ],
      answer: r`$(2,\,3)$`,
      tip: r`Tekshiruv: $3\cdot2+2\cdot3=12$ ✓. Bitta tenglama allaqachon "$y=\ldots$" bo'lsa — o'rniga qo'yish eng qulay.`,
      say: [
        r`Birinchi usul — o'rniga qo'yish. Sistema: y teng ikki x minus bir va uch x plyus ikki y teng o'n ikki.`,
        r`Birinchi tenglamada y allaqachon ifodalangan. Uni ikkinchi tenglamaga qo'yamiz: uch x plyus ikki karra, ikki x minus bir, teng o'n ikki.`,
        r`Qavsni ochib soddalashtiramiz: yetti x minus ikki teng o'n ikki.`,
        r`X teng ikki.`,
        r`Y ni topamiz: ikki karra ikki minus bir — uch.`,
        r`Javob: ikki, uch.`,
        r`Tekshiruv: uch karra ikki plyus ikki karra uch — o'n ikki. Bitta tenglama allaqachon y teng ko'rinishida bo'lsa, o'rniga qo'yish eng qulay usul.`,
      ],
    },
    {
      type: 'example',
      kicker: '2-USUL',
      title: "Qo'shish usuli",
      label: 'MISOL',
      question: r`Solve the system: $2x+3y=12$ and $4x-3y=6$.`,
      steps: [
        {m: r`6x=18`, note: r`tenglamalarni qo'shamiz: $3y$ va $-3y$ yo'qoladi`},
        {m: r`x=3`},
        {m: r`2\cdot3+3y=12\Rightarrow y=2`},
      ],
      answer: r`$(3,\,2)$`,
      say: [
        r`Ikkinchi usul — qo'shish. Sistema: ikki x plyus uch y teng o'n ikki va to'rt x minus uch y teng olti.`,
        r`Uch y va minus uch y qarama-qarshi. Tenglamalarni qo'shsak, ular yo'qoladi: olti x teng o'n sakkiz.`,
        r`X teng uch.`,
        r`Birinchi tenglamaga qo'yamiz: olti plyus uch y teng o'n ikki, y teng ikki.`,
        r`Javob: uch, ikki.`,
      ],
    },
    {
      type: 'example',
      kicker: '2-USUL',
      title: "Ko'paytirib qo'shish",
      label: 'MISOL',
      question: r`Solve the system: $3x+2y=16$ and $x-y=2$.`,
      steps: [
        {m: r`2x-2y=4`, note: r`ikkinchi tenglamani $2$ ga ko'paytiramiz`},
        {m: r`5x=20`, note: r`birinchisiga qo'shamiz`},
        {m: r`x=4,\ \ y=x-2=2`},
      ],
      answer: r`$(4,\,2)$`,
      tip: r`Koeffitsiyentlar qarama-qarshi bo'lmasa, bir yoki ikkala tenglamani shunday songa ko'paytiringki, ular qarama-qarshi bo'lsin.`,
      say: [
        r`Agar koeffitsiyentlar tayyor qarama-qarshi bo'lmasa-chi? Sistema: uch x plyus ikki y teng o'n olti va x minus y teng ikki.`,
        r`Ikkinchi tenglamani ikkiga ko'paytiramiz: ikki x minus ikki y teng to'rt. Endi y lar qarama-qarshi.`,
        r`Birinchisiga qo'shamiz: besh x teng yigirma.`,
        r`X teng to'rt, va ikkinchi tenglamadan y teng to'rt minus ikki — ikki.`,
        r`Javob: to'rt, ikki.`,
        r`Qoida: bitta yoki ikkala tenglamani shunday songa ko'paytiringki, bitta o'zgaruvchining koeffitsiyentlari qarama-qarshi bo'lib qolsin.`,
      ],
    },
    {
      type: 'graph',
      kicker: '3-USUL',
      title: 'Desmos: kesishish nuqtasi',
      x: [-2, 8],
      y: [-3, 9],
      items: [
        {kind: 'fn', f: (x) => 8 - 1.5 * x, label: r`$3x+2y=16$`, note: r`Birinchi tenglama — Desmos'ga shundayligicha yoziladi`},
        {kind: 'fn', f: (x) => x - 2, label: r`$x-y=2$`, note: r`Ikkinchi tenglama`},
        {kind: 'point', x: 4, y: 2, label: r`$(4,\,2)$`, color: '#FFFFFF', note: r`Kesishish nuqtasi — o'sha javob: $(4,\,2)$`},
      ],
      say: [
        r`Uchinchi usul — Desmos. O'sha sistemani chizamiz.`,
        r`Birinchi tenglamani y ga nisbatan yechish shart emas — Desmos uch x plyus ikki y teng o'n oltini shundayligicha qabul qiladi.`,
        r`Ikkinchi tenglama: x minus y teng ikki.`,
        r`Kesishish nuqtasini bosamiz: to'rt, ikki. Algebraik usul bilan bir xil. Sonlar noqulay, kasrli bo'lganda Desmos ayniqsa foydali.`,
      ],
    },
    {
      type: 'example',
      kicker: 'SAT HIYLASI',
      title: r`$x+y$ ni bir qadamda topish`,
      question: r`If $3x+y=14$ and $x+3y=10$, what is the value of $x+y$?`,
      choices: [r`$4$`, r`$6$`, r`$12$`, r`$24$`],
      steps: [
        {m: r`4x+4y=24`, note: r`ikkala tenglamani qo'shamiz`},
        {m: r`x+y=6`, note: r`$4$ ga bo'lamiz`},
      ],
      answer: r`B`,
      tip: r`Savol $x$ yoki $y$ ni emas, ularning kombinatsiyasini so'rasa — avval tenglamalarni qo'shib yoki ayirib ko'ring.`,
      say: [
        r`SAT hiylasi. If three x plus y equals fourteen and x plus three y equals ten, what is the value of x plus y?`,
        r`X va y ni alohida topish shart emas. Ikkala tenglamani qo'shamiz: to'rt x plyus to'rt y teng yigirma to'rt.`,
        r`To'rtga bo'lamiz: x plyus y teng olti.`,
        r`Javob: B.`,
        r`Savol x plyus y yoki x minus y kabi kombinatsiyani so'rasa, avval tenglamalarni qo'shib yoki ayirib ko'ring. Ko'pincha javob bir qadamda chiqadi. D variant — yigirma to'rt — bo'lishni unutganlar uchun.`,
      ],
    },
    {
      type: 'example',
      kicker: 'MATNLI MASALA',
      title: 'Matndan sistema',
      label: 'SPR SAVOLI',
      question: r`A store sells pens for 2 dollars each and notebooks for 5 dollars each. Mariya bought 12 items and paid 39 dollars. How many notebooks did she buy?`,
      steps: [
        {m: r`p+n=12`, note: r`buyumlar soni`},
        {m: r`2p+5n=39`, note: r`umumiy narx`},
        {m: r`2(12-n)+5n=39`, note: r`$p=12-n$`},
        {m: r`3n=15\Rightarrow n=5`},
      ],
      answer: r`$5$`,
      say: [
        r`Matnli masala. Do'konda ruchka ikki dollar, daftar besh dollar. Mariya o'n ikkita buyum sotib olib, o'ttiz to'qqiz dollar to'ladi. U nechta daftar olgan?`,
        r`Birinchi tenglama — buyumlar soni: p plyus n teng o'n ikki.`,
        r`Ikkinchi tenglama — narx: ikki p plyus besh n teng o'ttiz to'qqiz.`,
        r`Birinchisidan p teng o'n ikki minus n, ikkinchisiga qo'yamiz.`,
        r`Yigirma to'rt plyus uch n teng o'ttiz to'qqiz, uch n teng o'n besh, n teng besh.`,
        r`Javob: besh daftar. Matnli sistemada odatda bitta tenglama "soni", ikkinchisi "narxi" yoki "qiymati" haqida bo'ladi.`,
      ],
    },
    {
      type: 'compare',
      kicker: 'STRATEGIYA',
      title: 'Qaysi usulni tanlash kerak?',
      cards: [
        {title: "O'rniga qo'yish", rule: r`Bitta o'zgaruvchi allaqachon ajratilgan`, example: r`$y=2x-1$`},
        {title: "Qo'shish", rule: r`Koeffitsiyentlar teng yoki qarama-qarshi`, example: r`$3y$ va $-3y$`},
        {title: 'Desmos', rule: r`Kasrli, noqulay sonlar yoki tekshiruv`, example: r`$0.3x+1.7y=4.1$`},
      ],
      say: [
        r`Qaysi usulni qachon tanlash kerak?`,
        r`O'rniga qo'yish — bitta o'zgaruvchi allaqachon ajratilgan bo'lsa, masalan y teng ikki x minus bir.`,
        r`Qo'shish — koeffitsiyentlar teng yoki qarama-qarshi bo'lsa, yoki osongina shunday qilish mumkin bo'lsa.`,
        r`Desmos — sonlar kasrli yoki noqulay bo'lsa, shuningdek, algebraik javobni tekshirish uchun.`,
      ],
    },
    {
      type: 'trap',
      title: 'Qaysi o\'zgaruvchi so\'ralgan?',
      question: r`If $x+y=10$ and $x-y=4$, what is the value of $y$?`,
      wrong: r`$7$`,
      why: r`Qo'shganda birinchi bo'lib $x=7$ chiqadi va o'quvchi shoshilib uni belgilaydi.`,
      right: r`$x=7$, demak $y=10-7=$ **3**. Oxirgi qadamni o'tkazib yubormang.`,
      say: [
        r`Tuzoq. If x plus y equals ten and x minus y equals four, what is the value of y?`,
        r`Tenglamalarni qo'shsak, ikki x teng o'n to'rt, x teng yetti chiqadi. Ko'p o'quvchi shu yerda to'xtab, yettini belgilaydi. Lekin yetti — x.`,
        r`Y teng o'n minus yetti — uch. Sistemada savol qaysi o'zgaruvchini so'rayotganini doim tekshiring.`,
      ],
    },
    {
      type: 'example',
      kicker: 'MUSTAQIL MASHQ',
      title: "O'zingiz yeching",
      label: 'MASHQ',
      question: r`If $5x-2y=4$ and $x+2y=20$, what is the value of $y$?`,
      steps: [
        {m: r`6x=24`, note: r`qo'shamiz`},
        {m: r`x=4`},
        {m: r`4+2y=20\Rightarrow y=8`},
      ],
      answer: r`$8$`,
      say: [
        r`Mustaqil mashq. Videoni to'xtating: besh x minus ikki y teng to'rt va x plyus ikki y teng yigirma. Y nimaga teng?`,
        r`Ikki y va minus ikki y qarama-qarshi — qo'shamiz: olti x teng yigirma to'rt.`,
        r`X teng to'rt.`,
        r`Ikkinchi tenglamaga qo'yamiz: to'rt plyus ikki y teng yigirma, y teng sakkiz.`,
        r`Javob: sakkiz. To'rtni belgilamadingizmi? Savol y ni so'ragan edi.`,
      ],
    },
    {
      type: 'example',
      kicker: '3-MISOL',
      title: 'Ikki "y =" li sistema',
      label: 'SPR SAVOLI',
      question: r`The solution to the system $y=3x-5$ and $y=-2x+10$ is $(a,\,b)$. What is the value of $ab$?`,
      steps: [
        {m: r`3x-5=-2x+10`, note: r`o'ng tomonlarni tenglaymiz`},
        {m: r`5x=15\Rightarrow x=3`},
        {m: r`y=3\cdot3-5=4`},
        {m: r`ab=3\cdot4=12`},
      ],
      answer: r`$12$`,
      say: [
        r`Uchinchi misol. The solution to the system y equals three x minus five and y equals minus two x plus ten is a, b. What is a times b?`,
        r`Ikkala tenglama y ga teng, demak o'ng tomonlarni tenglashimiz mumkin: uch x minus besh teng minus ikki x plyus o'n.`,
        r`Besh x teng o'n besh, x teng uch.`,
        r`Y teng uch karra uch minus besh — to'rt.`,
        r`A karra b — uch karra to'rt — o'n ikki.`,
        r`Javob: o'n ikki. Ikkala tenglama "y teng" ko'rinishida bo'lsa, o'ng tomonlarni tenglash eng tez yo'l.`,
      ],
    },
    {
      type: 'example',
      kicker: 'SAT HIYLASI',
      title: r`$x-y$ ni ayirish orqali topish`,
      label: 'SPR SAVOLI',
      question: r`If $2x+5y=21$ and $5x+2y=7$, what is the value of $x-y$?`,
      steps: [
        {m: r`(5x+2y)-(2x+5y)=7-21`, note: r`ikkinchidan birinchini ayiramiz`},
        {m: r`3x-3y=-14`},
        {m: r`x-y=-\frac{14}{3}`},
      ],
      answer: r`$-14/3$`,
      tip: r`Kiritish: **-14/3** yoki **-4.666** / **-4.667** — manfiy javobda 6 belgigacha.`,
      say: [
        r`Yana bir hiyla. If two x plus five y equals twenty one and five x plus two y equals seven, what is x minus y?`,
        r`Koeffitsiyentlar "almashgan" — ikki va besh. Bunday holatda ayiramiz: ikkinchi tenglamadan birinchisini.`,
        r`Uch x minus uch y teng minus o'n to'rt.`,
        r`Uchga bo'lamiz: x minus y teng minus o'n to'rt uchdan.`,
        r`Javob: minus o'n to'rt uchdan.`,
        r`Kiritishda: minus o'n to'rt slesh uch, yoki minus to'rt nuqta olti olti olti yoki olti olti yetti. Manfiy javobda oltita belgigacha yozish mumkin.`,
      ],
    },
  ],
  recap: [
    r`O'rniga qo'yish — "$y=\ldots$" bo'lsa; qo'shish — qarama-qarshi koeffitsiyentlar`,
    r`$x+y$ so'ralsa — avval tenglamalarni qo'shib/ayirib ko'ring`,
    r`Matnli sistema: "soni" va "narxi" tenglamalari`,
  ],
  homework: r`platformada sistemalar bo'yicha 15 ta savol`,
  recapSay: [
    r`Xulosa.`,
    r`Bitta o'zgaruvchi ajratilgan bo'lsa — o'rniga qo'yish, koeffitsiyentlar qarama-qarshi bo'lsa — qo'shish usuli.`,
    r`Savol x plyus y kabi ifodani so'rasa, avval tenglamalarni qo'shib yoki ayirib ko'ring.`,
    r`Matnli masalalarda odatda bitta tenglama — sonlar haqida, ikkinchisi — narx yoki qiymat haqida.`,
    r`Hozir platformada sistemalar bo'yicha o'n beshta savolni yeching. Keyingi darsda sistemaning yechimlar soni va tengsizliklar sistemasini o'rganamiz.`,
    r`Ko'rishguncha!`,
  ],
};

export default lesson;
