import {meta} from '../catalog';
import type {Lesson} from '../types';

const r = String.raw;

const lesson: Lesson = {
  ...meta(10),
  topics: ['Yechimlar soni', 'Nisbatlar qoidasi', 'Parametr', 'Tengsizliklar sistemasi', 'Nuqtani tekshirish'],
  cover: [
    r`Assalomu alaykum! O'ninchi darsga xush kelibsiz. Bu Algebra modulining yakuniy darsi. Mavzu — sistemalar: yechimlar soni va tengsizliklar sistemasi.`,
    r`Sistemaning nechta yechimi borligini aniqlashni, parametrli sistemalarni, tengsizliklar sistemasini grafikda ko'rishni va nuqtani tekshirishni o'rganamiz.`,
  ],
  goals: [
    r`Sistemaning yechimlar sonini aniqlash`,
    r`"No solution / infinitely many" sistemalarida parametr topish`,
    r`Tengsizliklar sistemasini grafikda o'qish`,
    r`Nuqta sistemaning yechimi ekanini tekshirish`,
  ],
  goalsSay: [
    r`Darsning maqsadlari.`,
    r`Birinchi: sistemani yechmasdan, uning nechta yechimi borligini aniqlash.`,
    r`Ikkinchi: SAT'ning sevimli savoli — sistema yechimga ega emas yoki cheksiz ko'p yechimga ega bo'lsa, o'zgarmasni topish.`,
    r`Uchinchi: tengsizliklar sistemasini grafikda bo'yalgan soha sifatida o'qish.`,
    r`To'rtinchi: berilgan nuqta sistemaning yechimi ekanini tez tekshirish.`,
    r`Bu dars bilan Algebra moduli yakunlanadi — undan keyin siz Algebra savollarining deyarli barcha turlarini bilasiz.`,
  ],
  goalsResult: r`Algebra moduli yakunlandi — 35% savollar sizniki`,
  slides: [
    {
      type: 'compare',
      kicker: '3 HOLAT',
      title: 'Sistemaning nechta yechimi bor?',
      cards: [
        {title: 'Bitta yechim', rule: r`Qiyaliklar **har xil** — chiziqlar kesishadi`, example: r`$y=2x+1,\ y=-x+4$`},
        {title: "Yechim yo'q", rule: r`Qiyaliklar teng, kesishmalar har xil — **parallel**`, example: r`$y=2x+1,\ y=2x-3$`},
        {title: "Cheksiz ko'p", rule: r`Ikkala tenglama — **bitta chiziq**`, example: r`$y=2x+1,\ 2y=4x+2$`},
      ],
      say: [
        r`To'rtinchi darsda bitta tenglama uchun ko'rgan mantiq sistemalarda ham ishlaydi. Har bir tenglama — to'g'ri chiziq.`,
        r`Qiyaliklar har xil bo'lsa, chiziqlar aniq bitta nuqtada kesishadi — bitta yechim.`,
        r`Qiyaliklar teng, lekin kesishmalar har xil bo'lsa, chiziqlar parallel — yechim yo'q.`,
        r`Ikkala tenglama aslida bitta chiziq bo'lsa — cheksiz ko'p yechim. Masalan, ikki y teng to'rt x plyus ikki — bu y teng ikki x plyus birning o'zi, faqat ikkiga ko'paytirilgan.`,
      ],
    },
    {
      type: 'formula',
      kicker: 'TEZKOR QOIDA',
      title: r`$a_1x+b_1y=c_1$ va $a_2x+b_2y=c_2$`,
      formulas: [
        {label: 'Bitta yechim', tex: r`\dfrac{a_1}{a_2}\neq\dfrac{b_1}{b_2}`},
        {label: "Yechim yo'q", tex: r`\dfrac{a_1}{a_2}=\dfrac{b_1}{b_2}\neq\dfrac{c_1}{c_2}`},
        {label: "Cheksiz ko'p", tex: r`\dfrac{a_1}{a_2}=\dfrac{b_1}{b_2}=\dfrac{c_1}{c_2}`},
      ],
      banner: r`Boshqacha aytganda: bir tenglama ikkinchisining karralisi bo'lsa — cheksiz ko'p; faqat chap tomoni karrali bo'lsa — yechim yo'q`,
      say: [
        r`Standart ko'rinishdagi sistema uchun tezkor qoida.`,
        r`X koeffitsiyentlari nisbati y koeffitsiyentlari nisbatiga teng bo'lmasa — bitta yechim.`,
        r`Bu nisbatlar teng, lekin ozod hadlar nisbati boshqacha bo'lsa — yechim yo'q.`,
        r`Uchala nisbat teng bo'lsa — cheksiz ko'p yechim.`,
        r`Oddiyroq qilib aytganda: bir tenglama to'liq ikkinchisining karralisi bo'lsa — cheksiz ko'p yechim. Faqat chap tomoni karrali bo'lib, o'ng tomoni mos kelmasa — yechim yo'q.`,
      ],
    },
    {
      type: 'example',
      kicker: '1-MISOL',
      title: "Parametr: yechim yo'q",
      label: 'SPR SAVOLI',
      question: r`In the system $3x+ky=7$ and $6x+8y=5$, $k$ is a constant. If the system has no solution, what is the value of $k$?`,
      steps: [
        {m: r`\frac{3}{6}=\frac{k}{8}`, note: r`koeffitsiyentlar proporsional`},
        {m: r`k=4`},
        {m: r`\frac{7}{5}\neq\frac12\ \checkmark`, note: r`ozod hadlar proporsional emas`},
      ],
      answer: r`$4$`,
      say: [
        r`Birinchi misol. In the system three x plus k y equals seven and six x plus eight y equals five, k is a constant. If the system has no solution, what is k?`,
        r`Yechim yo'q bo'lishi uchun chap tomonlar proporsional bo'lishi kerak: uch bo'lingan olti teng k bo'lingan sakkiz.`,
        r`K teng to'rt.`,
        r`Tekshiramiz: ozod hadlar nisbati yetti beshdan, bu yarimga teng emas. Demak, chiziqlar parallel va haqiqatan yechim yo'q.`,
        r`Javob: to'rt.`,
      ],
    },
    {
      type: 'example',
      kicker: '2-MISOL',
      title: "Parametr: cheksiz ko'p yechim",
      label: 'SPR SAVOLI',
      question: r`The system $2x-3y=6$ and $ax-9y=b$ has infinitely many solutions, where $a$ and $b$ are constants. What is $a+b$?`,
      steps: [
        {m: r`6x-9y=18`, note: r`birinchisini $3$ ga ko'paytiramiz`},
        {m: r`a=6,\ \ b=18`, note: r`ikkinchisi aynan shu tenglama`},
        {m: r`a+b=24`},
      ],
      answer: r`$24$`,
      say: [
        r`Ikkinchi misol. The system two x minus three y equals six and a x minus nine y equals b has infinitely many solutions. What is a plus b?`,
        r`Y koeffitsiyentlariga qaraymiz: minus uch va minus to'qqiz. Birinchi tenglamani uchga ko'paytirsak, olti x minus to'qqiz y teng o'n sakkiz chiqadi.`,
        r`Cheksiz ko'p yechim uchun ikkinchi tenglama aynan shu bo'lishi kerak: a teng olti, b teng o'n sakkiz.`,
        r`A plyus b — yigirma to'rt.`,
        r`Javob: yigirma to'rt.`,
      ],
    },
    {
      type: 'trap',
      title: "Parallelmi yoki bitta chiziqmi?",
      question: r`How many solutions does the system $4x-2y=6$ and $2x-y=3$ have?`,
      wrong: r`Zero`,
      why: r`Qiyaliklar teng ekanini ko'rib, "parallel" deb xulosa qilingan — ozod hadlar tekshirilmagan.`,
      right: r`Ikkinchi tenglamani $2$ ga ko'paytirsak — aynan birinchisi: **infinitely many**.`,
      say: [
        r`Tuzoq. How many solutions does the system four x minus two y equals six and two x minus y equals three have?`,
        r`O'quvchi qiyaliklar bir xil ekanini ko'radi va darhol "parallel, yechim yo'q" deydi. Lekin ozod hadlarni tekshirmagan.`,
        r`Ikkinchi tenglamani ikkiga ko'paytirsak, to'rt x minus ikki y teng olti — aynan birinchi tenglama. Bu bitta chiziq, demak cheksiz ko'p yechim. Qiyaliklar teng bo'lsa, doim ozod hadlarni ham solishtiring.`,
      ],
    },
    {
      type: 'cards',
      kicker: 'TENGSIZLIKLAR SISTEMASI',
      title: 'Tengsizliklar sistemasi grafigi',
      cards: [
        {title: 'Yarim tekislik', text: r`Har bir tengsizlik — chiziqning bir tomonidagi soha`},
        {title: 'Chegara chizig\'i', text: r`$\le,\ \ge$ — tutash chiziq; $<,\ >$ — **uzuq** chiziq`},
        {title: 'Qaysi tomon?', text: r`$y>\ldots$ — chiziqdan yuqori, $y<\ldots$ — pastda`},
        {title: 'Yechim', text: r`Barcha sohalar **kesishgan** joy`},
      ],
      say: [
        r`Endi tengsizliklar sistemasi.`,
        r`Har bir chiziqli tengsizlik tekislikning yarmini — chiziqning bir tomonidagi sohani — tasvirlaydi.`,
        r`Chegara chizig'i: "yoki teng" belgilarida tutash, qat'iy belgilarda uzuq chiziladi — chunki chiziqning o'zi yechimga kirmaydi.`,
        r`Y katta bo'lsa — chiziqdan yuqoridagi soha, y kichik bo'lsa — pastdagi soha bo'yaladi.`,
        r`Sistemaning yechimi — barcha sohalar ustma-ust tushgan, ya'ni kesishgan qism.`,
      ],
    },
    {
      type: 'graph',
      kicker: 'GRAFIKDA',
      title: r`$y\ge x-1$ va $y<-2x+5$`,
      x: [-3, 5],
      y: [-4, 7],
      items: [
        {kind: 'region', f: (x) => x - 1, above: true, color: '#22C55E', label: r`$y\ge x-1$`, note: r`Tutash chiziq, yuqori soha`},
        {kind: 'region', f: (x) => -2 * x + 5, above: false, dashed: true, color: '#EC4899', label: r`$y<-2x+5$`, note: r`Uzuq chiziq, pastki soha`},
        {kind: 'point', x: 0, y: 2, label: r`$(0,\,2)$`, color: '#FFFFFF', note: r`$(0,2)$: $2\ge-1$ ✓, $2<5$ ✓ — yechim`},
        {kind: 'point', x: 3, y: 1, label: r`$(3,\,1)$`, color: '#EF4444', note: r`$(3,1)$: $1\ge2$ ✗ — yechim emas`},
      ],
      say: [
        r`Grafikda ko'ramiz: y katta yoki teng x minus bir va y kichik minus ikki x plyus besh.`,
        r`Birinchi tengsizlik: tutash chiziq, yuqoridagi soha yashil bilan bo'yaladi.`,
        r`Ikkinchisi: qat'iy belgi, shuning uchun uzuq chiziq, va pastdagi soha bo'yaladi. Ikkala rang ustma-ust tushgan joy — yechim.`,
        r`Nuqtani tekshirish uchun uni ikkala tengsizlikka qo'yamiz. Nol, ikki: ikki katta yoki teng minus bir — rost, ikki kichik besh — rost. Demak, bu nuqta yechim.`,
        r`Uch, bir: bir katta yoki teng ikki — yolg'on. Bitta tengsizlik bajarilmasa ham, nuqta yechim emas.`,
      ],
    },
    {
      type: 'example',
      kicker: 'SAT MISOLI',
      title: 'Qaysi nuqta yechim?',
      question: r`Which point $(x,\,y)$ is a solution to the system $y>2x-3$ and $y\le -x+6$?`,
      choices: [r`$(4,\,6)$`, r`$(0,\,0)$`, r`$(5,\,2)$`, r`$(2,\,1)$`],
      steps: [
        {m: r`A:\ 6\le2\ \text{✗}`},
        {m: r`B:\ 0>-3\ \checkmark,\ \ 0\le6\ \checkmark`},
        {m: r`D:\ 1>1\ \text{✗}`, note: r`qat'iy belgi — chegaradagi nuqta kirmaydi`},
      ],
      answer: r`B`,
      tip: r`Variantlarni birma-bir qo'ying; bitta tengsizlik buzilsa — keyingisiga o'ting.`,
      say: [
        r`SAT misoli. Which point is a solution to the system y greater than two x minus three and y less than or equal to minus x plus six?`,
        r`A: to'rt, olti. Ikkinchi tengsizlik: olti kichik yoki teng ikki — yolg'on.`,
        r`B: nol, nol. Nol katta minus uch — rost, nol kichik yoki teng olti — rost. Mos keladi.`,
        r`D ni ham ko'raylik: ikki, bir. Bir katta bir — yolg'on, chunki belgi qat'iy. Bu nuqta chegara chizig'ida yotadi va kirmaydi.`,
        r`Javob: B.`,
        r`Bunday savollarda variantlarni bittadan qo'yib tekshiring. Birinchi tengsizlik buzilsa, ikkinchisini tekshirmasdan keyingi variantga o'ting.`,
      ],
    },
    {
      type: 'example',
      kicker: 'MATNLI MASALA',
      title: 'Matndan tengsizliklar sistemasi',
      question: r`A bakery makes at most 200 cookies and muffins per day. Each cookie earns 1 dollar of profit and each muffin earns 2 dollars. The bakery needs a profit of at least 300 dollars. Which system represents this?`,
      choices: [r`$c+m\le200,\ c+2m\ge300$`, r`$c+m\ge200,\ c+2m\le300$`, r`$c+m\le200,\ 2c+m\ge300$`, r`$c+2m\le200,\ c+m\ge300$`],
      steps: [
        {m: r`c+m\le200`, note: r`"at most 200" — soni`},
        {m: r`1\cdot c+2\cdot m\ge300`, note: r`"at least 300" — foyda`},
      ],
      answer: r`A`,
      say: [
        r`Matnli masala. Novvoyxona kuniga ko'pi bilan ikki yuzta pechenye va keks pishiradi. Har bir pechenye bir dollar, har bir keks ikki dollar foyda beradi. Foyda kamida uch yuz dollar bo'lishi kerak. Which system represents this?`,
        r`Birinchi tengsizlik — mahsulotlar soni: c plyus m ko'pi bilan ikki yuz, ya'ni kichik yoki teng.`,
        r`Ikkinchisi — foyda: bir karra c plyus ikki karra m kamida uch yuz, ya'ni katta yoki teng.`,
        r`Javob: A.`,
        r`C variant — koeffitsiyentlarni almashtirib qo'ygan tuzoq: pechenye bir dollar, keks ikki dollar. Kim nimaga mosligini doim tekshiring.`,
      ],
    },
    {
      type: 'example',
      kicker: 'MUSTAQIL MASHQ',
      title: "O'zingiz yeching",
      label: 'MASHQ',
      question: r`The system $x+2y=5$ and $3x+ky=15$ has infinitely many solutions. What is the value of $k$?`,
      steps: [
        {m: r`3x+6y=15`, note: r`birinchisini $3$ ga ko'paytiramiz`},
        {m: r`k=6`},
      ],
      answer: r`$6$`,
      say: [
        r`Mustaqil mashq. Videoni to'xtating: x plyus ikki y teng besh va uch x plyus k y teng o'n besh sistemasi cheksiz ko'p yechimga ega. K nimaga teng?`,
        r`Birinchi tenglamani uchga ko'paytiramiz: uch x plyus olti y teng o'n besh. O'ng tomon ham mos keldi.`,
        r`Demak, k teng olti.`,
        r`Javob: olti.`,
      ],
    },
    {
      type: 'example',
      kicker: 'SAT MISOLI',
      title: "Cheksiz ko'p yechim: o'ng tomon",
      question: r`For what value of $c$ does the system $5x-2y=c$ and $10x-4y=8$ have infinitely many solutions?`,
      choices: [r`$2$`, r`$4$`, r`$8$`, r`$16$`],
      steps: [
        {m: r`10x-4y=2(5x-2y)`, note: r`chap tomon — ikki baravar`},
        {m: r`8=2c`, note: r`o'ng tomon ham ikki baravar bo'lishi kerak`},
        {m: r`c=4`},
      ],
      answer: r`B`,
      tip: r`Agar $c\neq4$ bo'lsa — chiziqlar parallel, yechim yo'q.`,
      say: [
        r`Yana bir SAT misoli. For what value of c does the system five x minus two y equals c and ten x minus four y equals eight have infinitely many solutions?`,
        r`Ikkinchi tenglamaning chap tomoni birinchisining aynan ikki baravari.`,
        r`Cheksiz ko'p yechim uchun o'ng tomon ham ikki baravar bo'lishi kerak: sakkiz teng ikki c.`,
        r`C teng to'rt.`,
        r`Javob: B.`,
        r`Agar c to'rtdan boshqa son bo'lsa, chiziqlar parallel bo'lardi va yechim yo'q bo'lardi. C varianti — sakkiz — ko'paytirishni unutganlar uchun tuzoq.`,
      ],
    },
  ],
  recap: [
    r`Qiyalik har xil — 1 yechim; teng — parallel yoki bitta chiziq`,
    r`Karrali tenglama — cheksiz ko'p; faqat chap tomoni karrali — yechim yo'q`,
    r`Tengsizliklar sistemasi: sohalar kesishmasi; qat'iy — uzuq chiziq`,
  ],
  homework: r`platformada Algebra moduli bo'yicha 20 ta aralash savol`,
  recapSay: [
    r`Xulosa.`,
    r`Sistemada qiyaliklar har xil bo'lsa — bitta yechim. Teng bo'lsa — yoki parallel, yoki bitta chiziq.`,
    r`Bir tenglama ikkinchisining to'liq karralisi bo'lsa — cheksiz ko'p yechim, faqat chap tomoni karrali bo'lsa — yechim yo'q.`,
    r`Tengsizliklar sistemasining yechimi — bo'yalgan sohalar kesishmasi, qat'iy belgida chegara uzuq chiziladi.`,
    r`Hozir platformada Algebra moduli bo'yicha yigirmata aralash savolni yeching. Keyingi darsdan Advanced Math moduli boshlanadi: ko'phadlar va ekvivalent ifodalar.`,
    r`Ko'rishguncha!`,
  ],
};

export default lesson;
