import {meta} from '../catalog';
import type {Lesson} from '../types';

const r = String.raw;

const lesson: Lesson = {
  ...meta(11),
  topics: ['Atamalar', "Qo'shish va ayirish", "Ko'paytirish", 'Qisqa formulalar', 'Koeffitsiyentlarni tenglash'],
  cover: [
    r`Assalomu alaykum! O'n birinchi darsga xush kelibsiz. Bugundan Advanced Math moduli boshlanadi. Birinchi mavzu — ko'phadlar va ekvivalent ifodalar.`,
    r`Ko'phadlarni qo'shish, ayirish va ko'paytirishni, qisqa ko'paytirish formulalarini va SAT'ning sevimli savoli — "for all x" bo'lganda koeffitsiyentlarni tenglashni o'rganamiz.`,
  ],
  goals: [
    r`Ko'phadlarni qo'shish, ayirish va ko'paytirish`,
    r`Qisqa ko'paytirish formulalarini qo'llash`,
    r`Ekvivalent ifodani tez tanlash`,
    r`"For all $x$" savollarida koeffitsiyentlarni tenglash`,
  ],
  goalsSay: [
    r`Darsning maqsadlari.`,
    r`Birinchi: ko'phadlar ustida asosiy amallar — qo'shish, ayirish, ko'paytirish.`,
    r`Ikkinchi: uchta qisqa ko'paytirish formulasini yod olish va qo'llash.`,
    r`Uchinchi: "which expression is equivalent" savollarida to'g'ri variantni tez tanlash.`,
    r`To'rtinchi: "for all values of x" degan savollarda ikki tomondagi koeffitsiyentlarni tenglash.`,
    r`Advanced Math — Algebra bilan bir qatorda balingizning taxminan o'ttiz besh foizi. Uning poydevori — ifodalar bilan ishlash.`,
  ],
  goalsResult: r`ekvivalent ifoda savollari — xatosiz`,
  slides: [
    {
      type: 'cards',
      kicker: 'ATAMALAR',
      title: "Ko'phad: asosiy atamalar",
      cards: [
        {title: 'Had (term)', text: r`$3x^2$, $-5x$, $7$ — qo'shish/ayirish bilan ajralgan qismlar`},
        {title: 'Koeffitsiyent', text: r`Harf oldidagi son: $3x^2$ da — $3$`},
        {title: 'Daraja (degree)', text: r`Eng katta daraja: $3x^2-5x+7$ — ikkinchi darajali`},
        {title: "O'xshash hadlar", text: r`Harf va daraja bir xil: $4x^2$ va $-x^2$ — qo'shiladi`},
      ],
      say: [
        r`Avval atamalar. Ko'phad — bir nechta haddan iborat ifoda.`,
        r`Had — qo'shish yoki ayirish belgilari bilan ajralgan qism: uch x kvadrat, minus besh x, yetti.`,
        r`Koeffitsiyent — harf oldidagi son. Uch x kvadratda koeffitsiyent uch.`,
        r`Ko'phadning darajasi — undagi eng katta daraja. Uch x kvadrat minus besh x plyus yetti — ikkinchi darajali ko'phad.`,
        r`O'xshash hadlar — harfi ham, darajasi ham bir xil hadlar. Faqat o'xshash hadlarni qo'shish mumkin: to'rt x kvadrat va minus x kvadrat — uch x kvadrat.`,
      ],
    },
    {
      type: 'example',
      kicker: '1-MISOL',
      title: "Ko'phadlarni ayirish",
      label: 'MISOL',
      question: r`Simplify $(3x^2-5x+2)-(x^2+2x-7)$.`,
      steps: [
        {m: r`3x^2-5x+2-x^2-2x+7`, note: r`minus — qavsdagi **har bir** ishorani o'zgartiradi`},
        {m: r`(3x^2-x^2)+(-5x-2x)+(2+7)`, note: r`o'xshash hadlarni guruhlaymiz`},
        {m: r`2x^2-7x+9`},
      ],
      answer: r`$2x^2-7x+9$`,
      tip: r`Eng ko'p xato: ikkinchi qavsdagi faqat birinchi hadning ishorasini o'zgartirish.`,
      say: [
        r`Birinchi misol: uch x kvadrat minus besh x plyus ikki, minus, x kvadrat plyus ikki x minus yetti.`,
        r`Qavs oldidagi minus qavs ichidagi har bir hadning ishorasini o'zgartiradi: minus x kvadrat, minus ikki x, plyus yetti.`,
        r`O'xshash hadlarni guruhlaymiz.`,
        r`Natija: ikki x kvadrat minus yetti x plyus to'qqiz.`,
        r`Javob: ikki x kvadrat minus yetti x plyus to'qqiz.`,
        r`Eng ko'p uchraydigan xato — faqat birinchi hadning ishorasini o'zgartirib, qolganlarini unutish. Minus yettining plyus yettiga aylanishini kuzating.`,
      ],
    },
    {
      type: 'example',
      kicker: '2-MISOL',
      title: "Ko'phadlarni ko'paytirish",
      label: 'MISOL',
      question: r`Expand $(2x-3)(x+4)$.`,
      steps: [
        {m: r`2x\cdot x+2x\cdot4-3\cdot x-3\cdot4`, note: r`har bir hadni har biriga`},
        {m: r`2x^2+8x-3x-12`},
        {m: r`2x^2+5x-12`},
      ],
      answer: r`$2x^2+5x-12$`,
      tip: r`Tekshiruv: $x=1$ qo'ying: $(2-3)(5)=-5$ va $2+5-12=-5$ ✓`,
      say: [
        r`Ikkinchi misol: ikki x minus uch, ko'paytirilgan x plyus to'rtga.`,
        r`Birinchi qavsdagi har bir hadni ikkinchi qavsdagi har bir hadga ko'paytiramiz: ikki x karra x, ikki x karra to'rt, minus uch karra x, minus uch karra to'rt.`,
        r`Ikki x kvadrat plyus sakkiz x minus uch x minus o'n ikki.`,
        r`O'xshash hadlarni qo'shamiz: ikki x kvadrat plyus besh x minus o'n ikki.`,
        r`Javob: ikki x kvadrat plyus besh x minus o'n ikki.`,
        r`Tez tekshirish: x o'rniga bir qo'ying. Dastlabki ifoda minus besh, natija ham minus besh. Bitta sonni qo'yish — ekvivalentlikni tekshirishning eng tez usuli.`,
      ],
    },
    {
      type: 'formula',
      kicker: 'QISQA FORMULALAR',
      title: "Qisqa ko'paytirish formulalari",
      formulas: [
        {label: "Yig'indi kvadrati", tex: r`(a+b)^2=a^2+2ab+b^2`},
        {label: 'Ayirma kvadrati', tex: r`(a-b)^2=a^2-2ab+b^2`},
        {label: 'Kvadratlar ayirmasi', tex: r`(a+b)(a-b)=a^2-b^2`},
      ],
      banner: r`Bu uch formula SAT'da ikki tomonga ishlatiladi: ochish uchun ham, ko'paytuvchilarga ajratish uchun ham`,
      say: [
        r`Uchta formulani albatta yod oling.`,
        r`Yig'indi kvadrati: a plyus b, kvadrat, teng a kvadrat plyus ikki a b plyus b kvadrat.`,
        r`Ayirma kvadrati: a minus b, kvadrat, teng a kvadrat minus ikki a b plyus b kvadrat.`,
        r`Kvadratlar ayirmasi: a plyus b karra a minus b teng a kvadrat minus b kvadrat.`,
        r`SAT bu formulalarni ikki yo'nalishda ishlatadi: qavslarni ochish uchun ham, teskarisi — ko'paytuvchilarga ajratish uchun ham. Keyingi darsda ikkinchisini batafsil ko'ramiz.`,
      ],
    },
    {
      type: 'example',
      kicker: 'SAT MISOLI',
      title: 'Ekvivalent ifoda',
      question: r`Which of the following is equivalent to $(x-5)^2$?`,
      choices: [r`$x^2-25$`, r`$x^2+25$`, r`$x^2-10x+25$`, r`$x^2-5x+25$`],
      steps: [
        {m: r`(a-b)^2=a^2-2ab+b^2`},
        {m: r`x^2-2\cdot x\cdot5+25`},
        {m: r`x^2-10x+25`},
      ],
      answer: r`C`,
      say: [
        r`SAT misoli. Which of the following is equivalent to x minus five, squared?`,
        r`Ayirma kvadrati formulasini qo'llaymiz.`,
        r`X kvadrat minus ikki karra x karra besh plyus yigirma besh.`,
        r`X kvadrat minus o'n x plyus yigirma besh.`,
        r`Javob: C. A variant — x kvadrat minus yigirma besh — eng ko'p tanlanadigan xato javob: o'rtadagi ikki a b hadi unutilgan.`,
      ],
    },
    {
      type: 'trap',
      title: 'Kvadratni hadma-had olish',
      question: r`Expand $(x+3)^2$.`,
      wrong: r`$x^2+9$`,
      why: r`Kvadrat yig'indiga "taqsimlanmaydi": $(a+b)^2\neq a^2+b^2$. O'rta had $2ab$ yo'qolgan.`,
      right: r`$(x+3)^2=(x+3)(x+3)=$ **$x^2+6x+9$**. Tekshiruv: $x=1$: $16$ va $1+6+9=16$ ✓`,
      say: [
        r`Tuzoq. Expand x plus three, squared.`,
        r`Ko'p o'quvchi har bir hadni alohida kvadratga oshiradi va x kvadrat plyus to'qqiz deb yozadi. Bu xato: yig'indining kvadrati kvadratlar yig'indisiga teng emas.`,
        r`To'g'risi: x plyus uchni o'ziga ko'paytiramiz — x kvadrat plyus olti x plyus to'qqiz. Shubha bo'lsa, x teng bir qo'ying: chap tomon o'n olti, o'ng tomon ham o'n olti.`,
      ],
    },
    {
      type: 'example',
      kicker: 'FOR ALL X',
      title: 'Koeffitsiyentlarni tenglash',
      label: 'SPR SAVOLI',
      question: r`If $(ax+3)(2x-b)=6x^2-6x-12$ for all values of $x$, where $a$ and $b$ are positive constants, what is $a+b$?`,
      steps: [
        {m: r`2a\,x^2+(6-ab)\,x-3b`, note: r`chap tomonni ochamiz`},
        {m: r`2a=6\Rightarrow a=3`, note: r`$x^2$ koeffitsiyentlari`},
        {m: r`-3b=-12\Rightarrow b=4`, note: r`ozod hadlar`},
        {m: r`6-ab=6-12=-6\ \checkmark`, note: r`$x$ koeffitsiyenti mos`},
      ],
      answer: r`$a+b=7$`,
      tip: r`"For all values of $x$" — ikki tomondagi bir xil darajali hadlarning koeffitsiyentlari teng degani.`,
      say: [
        r`SAT'ning sevimli savoli. If a x plus three times two x minus b equals six x squared minus six x minus twelve for all values of x, what is a plus b?`,
        r`"For all values of x" — bu ikki ifoda aynan bir xil degani. Chap tomonni ochamiz: ikki a x kvadrat, plyus olti minus a b x, minus uch b.`,
        r`X kvadrat oldidagi sonlarni tenglaymiz: ikki a teng olti, a teng uch.`,
        r`Ozod hadlarni tenglaymiz: minus uch b teng minus o'n ikki, b teng to'rt.`,
        r`Tekshiramiz: x oldidagi son olti minus o'n ikki — minus olti. To'g'ri keldi.`,
        r`A plyus b — yetti.`,
        r`Qoida: "for all x" ko'rsangiz — ikki tomonda bir xil darajadagi hadlarning koeffitsiyentlarini tenglang.`,
      ],
    },
    {
      type: 'example',
      kicker: 'SAT MISOLI',
      title: "Ko'phadni birhadga bo'lish",
      question: r`Which expression is equivalent to $\dfrac{6x^3-9x^2}{3x}$, for $x\neq0$?`,
      choices: [r`$2x^2-9x^2$`, r`$2x^2-3x$`, r`$2x^3-3x^2$`, r`$6x^2-3x$`],
      steps: [
        {m: r`\frac{6x^3}{3x}-\frac{9x^2}{3x}`, note: r`har bir hadni alohida bo'lamiz`},
        {m: r`2x^2-3x`},
      ],
      answer: r`B`,
      say: [
        r`Yana bir SAT misoli. Which expression is equivalent to six x cubed minus nine x squared, over three x?`,
        r`Suratdagi har bir hadni maxrajga alohida bo'lamiz: olti x kub bo'lingan uch x, minus to'qqiz x kvadrat bo'lingan uch x.`,
        r`Ikki x kvadrat minus uch x.`,
        r`Javob: B. A variant — faqat birinchi hadni bo'lib, ikkinchisini unutganlar uchun.`,
      ],
    },
    {
      type: 'example',
      kicker: 'KOEFFITSIYENT',
      title: r`$x$ oldidagi koeffitsiyent`,
      label: 'SPR SAVOLI',
      question: r`What is the coefficient of $x$ when $(x+2)(x^2-3x+1)$ is expanded?`,
      steps: [
        {m: r`x\cdot1=x`, note: r`faqat $x$ beradigan ko'paytmalar`},
        {m: r`2\cdot(-3x)=-6x`},
        {m: r`x-6x=-5x`},
      ],
      answer: r`$-5$`,
      tip: r`To'liq ochish shart emas — faqat kerakli darajani beradigan juftlarni ko'paytiring.`,
      say: [
        r`Koeffitsiyent savoli. What is the coefficient of x when x plus two times x squared minus three x plus one is expanded?`,
        r`Butun ifodani ochish shart emas. Faqat natijada x ning birinchi darajasini beradigan juftlarni topamiz. Birinchisi: x karra bir — x.`,
        r`Ikkinchisi: ikki karra minus uch x — minus olti x.`,
        r`Ularni qo'shamiz: minus besh x.`,
        r`Javob: minus besh.`,
        r`Bu usul ko'p vaqt tejaydi: faqat so'ralgan darajaga hissa qo'shadigan ko'paytmalarni hisoblang.`,
      ],
    },
    {
      type: 'example',
      kicker: 'MUSTAQIL MASHQ',
      title: "O'zingiz yeching",
      label: 'MASHQ',
      question: r`If $(2x+1)^2-(2x-1)^2=kx$ for all $x$, what is the value of $k$?`,
      steps: [
        {m: r`(4x^2+4x+1)-(4x^2-4x+1)`},
        {m: r`=8x`},
        {m: r`k=8`},
      ],
      answer: r`$8$`,
      say: [
        r`Mustaqil mashq. Videoni to'xtating: ikki x plyus bir, kvadrat, minus ikki x minus bir, kvadrat, teng k x — barcha x lar uchun. K nimaga teng?`,
        r`Ikkala kvadratni ochamiz: to'rt x kvadrat plyus to'rt x plyus bir, minus to'rt x kvadrat minus to'rt x plyus bir.`,
        r`Ayirsak, faqat sakkiz x qoladi.`,
        r`Demak, k teng sakkiz.`,
        r`Javob: sakkiz. Kvadratlar ayirmasi formulasi bilan ham tezroq: ikki ifoda yig'indisi to'rt x, ayirmasi ikki, ko'paytmasi sakkiz x.`,
      ],
    },
  ],
  recap: [
    r`Qavs oldidagi minus — har bir ishorani o'zgartiradi`,
    r`$(a\pm b)^2=a^2\pm2ab+b^2$; $(a+b)(a-b)=a^2-b^2$`,
    r`"For all $x$" — bir xil darajali koeffitsiyentlarni tenglang`,
  ],
  homework: r`platformada ekvivalent ifodalar bo'yicha 15 ta savol`,
  recapSay: [
    r`Xulosa.`,
    r`Qavs oldidagi minus qavs ichidagi har bir hadning ishorasini o'zgartiradi.`,
    r`Uchta qisqa ko'paytirish formulasi: yig'indi va ayirma kvadrati, kvadratlar ayirmasi. O'rtadagi ikki a b hadini unutmang.`,
    r`"For all x" savollarida ikki tomonda bir xil darajali hadlarning koeffitsiyentlarini tenglang.`,
    r`Hozir platformada ekvivalent ifodalar bo'yicha o'n beshta savolni yeching. Keyingi darsda ko'paytuvchilarga ajratishni o'rganamiz.`,
    r`Ko'rishguncha!`,
  ],
};

export default lesson;
