import {meta} from '../catalog';
import type {Lesson} from '../types';

const r = String.raw;

const lesson: Lesson = {
  ...meta(12),
  topics: ['Umumiy ko\'paytuvchi', 'Kvadratlar ayirmasi', 'Trinom', 'AC usuli', 'Ildiz bilan bog\'liqlik'],
  cover: [
    r`Assalomu alaykum! O'n ikkinchi darsga xush kelibsiz. Bugungi mavzu — ko'paytuvchilarga ajratish, inglizcha factoring.`,
    r`To'rtta asosiy usulni — umumiy ko'paytuvchi, kvadratlar ayirmasi, trinomni ajratish va AC usulini — hamda ko'paytuvchi va ildiz orasidagi bog'liqlikni o'rganamiz.`,
  ],
  goals: [
    r`Umumiy ko'paytuvchini qavsdan chiqarish`,
    r`Kvadratlar ayirmasi va to'liq kvadratni tanish`,
    r`$x^2+bx+c$ va $ax^2+bx+c$ ni ajratish`,
    r`Ko'paytuvchidan ildizni va aksincha topish`,
  ],
  goalsSay: [
    r`Darsning maqsadlari.`,
    r`Birinchi: umumiy ko'paytuvchini qavsdan chiqarish — har doim birinchi qadam.`,
    r`Ikkinchi: kvadratlar ayirmasi va to'liq kvadrat shablonlarini bir qarashda tanish.`,
    r`Uchinchi: kvadrat uchhadlarni — oddiy va bosh koeffitsiyenti birdan farqli bo'lganlarini — ajratish.`,
    r`To'rtinchi: ko'paytuvchi x minus a bo'lsa, a — ildiz ekanini va buning SAT savollarida qanday ishlatilishini tushunish.`,
    r`Ko'paytuvchilarga ajratish — kvadrat tenglamalar va ratsional ifodalarning kaliti.`,
  ],
  goalsResult: r`kvadrat ifodalarni 20 soniyada ajratish`,
  slides: [
    {
      type: 'cards',
      kicker: 'USULLAR',
      title: "Ko'paytuvchilarga ajratishning 4 usuli",
      cards: [
        {title: "Umumiy ko'paytuvchi", text: r`$6x^3-15x^2=3x^2(2x-5)$`},
        {title: 'Kvadratlar ayirmasi', text: r`$a^2-b^2=(a-b)(a+b)$`},
        {title: r`Trinom $x^2+bx+c$`, text: r`ko'paytmasi $c$, yig'indisi $b$ bo'lgan ikki son`},
        {title: r`$ax^2+bx+c$ — AC usuli`, text: r`ko'paytmasi $ac$, yig'indisi $b$; guruhlash`},
      ],
      say: [
        r`Ko'paytuvchilarga ajratishning to'rtta asosiy usuli bor.`,
        r`Birinchi: umumiy ko'paytuvchini qavsdan chiqarish. Har doim shu bilan boshlang.`,
        r`Ikkinchi: kvadratlar ayirmasi — a kvadrat minus b kvadrat teng a minus b karra a plyus b.`,
        r`Uchinchi: x kvadrat plyus b x plyus c ko'rinishidagi trinom. Ko'paytmasi c ga, yig'indisi b ga teng ikki son qidiramiz.`,
        r`To'rtinchi: bosh koeffitsiyent birdan farqli bo'lsa — AC usuli: ko'paytmasi a karra c, yig'indisi b bo'lgan sonlar va guruhlash.`,
      ],
    },
    {
      type: 'example',
      kicker: '1-USUL',
      title: "Umumiy ko'paytuvchi",
      label: 'MISOL',
      question: r`Factor $6x^3-15x^2$ completely.`,
      steps: [
        {m: r`\gcd(6,15)=3,\quad x^2`, note: r`sonlarning EKUBi va eng kichik daraja`},
        {m: r`3x^2(2x-5)`, note: r`har bir hadni $3x^2$ ga bo'lamiz`},
      ],
      answer: r`$3x^2(2x-5)$`,
      say: [
        r`Birinchi usul. Olti x kub minus o'n besh x kvadratni ko'paytuvchilarga ajrating.`,
        r`Sonlarning eng katta umumiy bo'luvchisi — uch. Harfning eng kichik darajasi — x kvadrat. Umumiy ko'paytuvchi: uch x kvadrat.`,
        r`Har bir hadni unga bo'lamiz: ikki x va minus besh. Natija: uch x kvadrat karra ikki x minus besh.`,
        r`Javob: uch x kvadrat karra ikki x minus besh. Qavsni ochib tekshirish mumkin.`,
      ],
    },
    {
      type: 'example',
      kicker: '2-USUL',
      title: 'Kvadratlar ayirmasi',
      label: 'MISOL',
      question: r`Factor $x^2-49$ and $4x^2-9y^2$.`,
      steps: [
        {m: r`x^2-7^2=(x-7)(x+7)`},
        {m: r`(2x)^2-(3y)^2=(2x-3y)(2x+3y)`},
      ],
      answer: r`$(x-7)(x+7)$, $(2x-3y)(2x+3y)$`,
      tip: r`Belgi: ikki **kvadrat** va ular orasida **minus**. Plyus bo'lsa — bu formula ishlamaydi.`,
      say: [
        r`Ikkinchi usul — kvadratlar ayirmasi.`,
        r`X kvadrat minus qirq to'qqiz — bu x kvadrat minus yetti kvadrat. Demak, x minus yetti karra x plyus yetti.`,
        r`To'rt x kvadrat minus to'qqiz y kvadrat — bu ikki x ning kvadrati minus uch y ning kvadrati. Natija: ikki x minus uch y karra ikki x plyus uch y.`,
        r`Javob ekranda.`,
        r`Bu formulani tanish belgisi: ikki to'liq kvadrat va ular orasida minus. Agar orada plyus bo'lsa, formula ishlamaydi.`,
      ],
    },
    {
      type: 'example',
      kicker: '3-USUL',
      title: r`Trinom $x^2+bx+c$`,
      label: 'MISOL',
      question: r`Factor $x^2+5x-14$.`,
      steps: [
        {m: r`p\cdot q=-14,\quad p+q=5`, note: r`ikki son qidiramiz`},
        {m: r`7\cdot(-2)=-14,\quad 7+(-2)=5`},
        {m: r`(x+7)(x-2)`},
      ],
      answer: r`$(x+7)(x-2)$`,
      tip: r`$c$ manfiy bo'lsa — sonlar har xil ishorali; $c$ musbat bo'lsa — bir xil ishorali ($b$ ning ishorasida).`,
      say: [
        r`Uchinchi usul: x kvadrat plyus besh x minus o'n to'rt.`,
        r`Ko'paytmasi minus o'n to'rt, yig'indisi besh bo'lgan ikki son qidiramiz.`,
        r`Yetti va minus ikki: ko'paytmasi minus o'n to'rt, yig'indisi besh.`,
        r`Demak, x plyus yetti karra x minus ikki.`,
        r`Javob: x plyus yetti karra x minus ikki.`,
        r`Ishora qoidasi: c manfiy bo'lsa, sonlar har xil ishorali. C musbat bo'lsa, ikkalasi bir xil ishorali — b ning ishorasida.`,
      ],
    },
    {
      type: 'example',
      kicker: '4-USUL',
      title: r`AC usuli: $2x^2+7x+3$`,
      label: 'MISOL',
      question: r`Factor $2x^2+7x+3$.`,
      steps: [
        {m: r`ac=6,\quad b=7\ \Rightarrow\ 6\ \text{va}\ 1`},
        {m: r`2x^2+6x+x+3`, note: r`o'rta hadni bo'lamiz`},
        {m: r`2x(x+3)+1(x+3)`, note: r`guruhlaymiz`},
        {m: r`(2x+1)(x+3)`},
      ],
      answer: r`$(2x+1)(x+3)$`,
      say: [
        r`To'rtinchi usul: ikki x kvadrat plyus yetti x plyus uch. Bosh koeffitsiyent ikki.`,
        r`A karra c — olti. Ko'paytmasi olti, yig'indisi yetti bo'lgan sonlar: olti va bir.`,
        r`O'rta hadni shu sonlar bo'yicha bo'lamiz: ikki x kvadrat plyus olti x plyus x plyus uch.`,
        r`Juft-juft guruhlaymiz: ikki x karra x plyus uch, plyus bir karra x plyus uch.`,
        r`Umumiy qavsni chiqaramiz: ikki x plyus bir karra x plyus uch.`,
        r`Javob: ikki x plyus bir karra x plyus uch. Agar bu usul sekin tuyulsa, Desmos'da ildizlarni topib, ulardan ko'paytuvchilarni tiklash mumkin.`,
      ],
    },
    {
      type: 'formula',
      kicker: "BOG'LIQLIK",
      title: "Ko'paytuvchi $\\leftrightarrow$ ildiz",
      formulas: [
        {label: "Ko'paytuvchi", tex: r`(x-a)\ \text{— ko'paytuvchi}`},
        {label: 'Ildiz (zero)', tex: r`\Leftrightarrow\ x=a\ \text{— ildiz}`},
        {label: 'Qiymat', tex: r`\Leftrightarrow\ p(a)=0`},
      ],
      banner: r`$(2x+1)$ ko'paytuvchi bo'lsa, ildiz $x=-\frac12$ — ishorasi teskari va bo'linadi`,
      say: [
        r`Ko'paytuvchi va ildiz orasidagi bog'liqlik — SAT'ning eng ko'p so'raydigan g'oyalaridan biri.`,
        r`Agar x minus a — ko'phadning ko'paytuvchisi bo'lsa…`,
        r`…unda x teng a — ko'phadning ildizi, ya'ni grafik x o'qini shu nuqtada kesadi…`,
        r`…va ko'phadning a dagi qiymati nolga teng. Bu uchta gap bir xil ma'noni bildiradi.`,
        r`E'tibor bering: ko'paytuvchi ikki x plyus bir bo'lsa, ildiz minus yarim — ishorasi teskari va koeffitsiyentga bo'linadi.`,
      ],
    },
    {
      type: 'example',
      kicker: 'SAT MISOLI',
      title: "Qaysi biri ko'paytuvchi?",
      question: r`Which of the following is a factor of $x^2-3x-10$?`,
      choices: [r`$x-2$`, r`$x+5$`, r`$x-5$`, r`$x+10$`],
      steps: [
        {m: r`p\cdot q=-10,\ \ p+q=-3\ \Rightarrow\ -5,\ 2`},
        {m: r`(x-5)(x+2)`},
      ],
      answer: r`C`,
      tip: r`Muqobil: variantdagi ildizni qo'ying — $x=5$: $25-15-10=0$ ✓`,
      say: [
        r`SAT misoli. Which of the following is a factor of x squared minus three x minus ten?`,
        r`Ko'paytmasi minus o'n, yig'indisi minus uch: minus besh va ikki.`,
        r`Demak, x minus besh karra x plyus ikki.`,
        r`Javob: C.`,
        r`Muqobil usul: har bir variantdan ildizni olib, ko'phadga qo'ying. X teng besh: yigirma besh minus o'n besh minus o'n — nol. Demak, x minus besh — ko'paytuvchi.`,
      ],
    },
    {
      type: 'example',
      kicker: 'SAT HIYLASI',
      title: 'Kvadratlar ayirmasi bilan sistema',
      label: 'SPR SAVOLI',
      question: r`If $x^2-y^2=48$ and $x+y=8$, what is the value of $x-y$?`,
      steps: [
        {m: r`(x-y)(x+y)=48`},
        {m: r`(x-y)\cdot8=48`},
        {m: r`x-y=6`},
      ],
      answer: r`$6$`,
      say: [
        r`SAT hiylasi. If x squared minus y squared equals forty eight and x plus y equals eight, what is x minus y?`,
        r`X kvadrat minus y kvadratni ajratamiz: x minus y karra x plyus y teng qirq sakkiz.`,
        r`X plyus y sakkizga teng: x minus y karra sakkiz teng qirq sakkiz.`,
        r`X minus y teng olti.`,
        r`Javob: olti. X va y ni alohida topish shart emas edi.`,
      ],
    },
    {
      type: 'trap',
      title: "Kvadratlar yig'indisi",
      question: r`Factor $x^2+9$.`,
      wrong: r`$(x+3)(x-3)$`,
      why: r`Bu $x^2-9$ ning yoyilmasi. Kvadratlar **yig'indisi** haqiqiy sonlarda ko'paytuvchilarga ajralmaydi.`,
      right: r`$x^2+9$ — ajralmaydi. Tekshiruv: $(x+3)(x-3)=x^2-9\neq x^2+9$.`,
      say: [
        r`Tuzoq. Factor x squared plus nine.`,
        r`Ko'p o'quvchi avtomatik ravishda x plyus uch karra x minus uch deb yozadi. Lekin bu x kvadrat minus to'qqiz.`,
        r`Kvadratlar yig'indisi haqiqiy sonlarda ko'paytuvchilarga ajralmaydi. Shubha bo'lsa, javobingizni ochib tekshiring.`,
      ],
    },
    {
      type: 'example',
      kicker: 'SAT MISOLI',
      title: "To'liq kvadratni tanish",
      question: r`Which of the following is equivalent to $9x^2-12x+4$?`,
      choices: [r`$(3x-2)^2$`, r`$(3x+2)^2$`, r`$(9x-2)^2$`, r`$(3x-4)(3x+1)$`],
      steps: [
        {m: r`9x^2=(3x)^2,\quad 4=2^2`, note: r`chetlar — kvadratlar`},
        {m: r`2\cdot3x\cdot2=12x`, note: r`o'rta had mos keladi`},
        {m: r`(3x-2)^2`, note: r`o'rtada minus`},
      ],
      answer: r`A`,
      say: [
        r`SAT misoli. Which is equivalent to nine x squared minus twelve x plus four?`,
        r`Chetki hadlar to'liq kvadrat: to'qqiz x kvadrat — uch x ning kvadrati, to'rt — ikkining kvadrati.`,
        r`O'rta hadni tekshiramiz: ikki karra uch x karra ikki — o'n ikki x. Mos keldi.`,
        r`O'rtada minus bo'lgani uchun: uch x minus ikki, kvadrat.`,
        r`Javob: A.`,
      ],
    },
    {
      type: 'example',
      kicker: 'MUSTAQIL MASHQ',
      title: "O'zingiz yeching",
      label: 'MASHQ',
      question: r`For $x\neq-3$, the expression $\dfrac{x^2-9}{x+3}$ is evaluated at $x=10$. What is the result?`,
      steps: [
        {m: r`\frac{(x-3)(x+3)}{x+3}=x-3`},
        {m: r`10-3=7`},
      ],
      answer: r`$7$`,
      say: [
        r`Mustaqil mashq. Videoni to'xtating. X kvadrat minus to'qqiz, bo'lingan x plyus uch ifodaning x teng o'n dagi qiymati qancha?`,
        r`Suratni kvadratlar ayirmasi bo'yicha ajratamiz va x plyus uchni qisqartiramiz: x minus uch qoladi.`,
        r`O'n minus uch — yetti.`,
        r`Javob: yetti. To'g'ridan-to'g'ri hisoblasak ham: to'qson bir bo'lingan o'n uch — yetti. Lekin ajratish usuli murakkab ifodalarda ancha tez.`,
      ],
    },
  ],
  recap: [
    r`Avval umumiy ko'paytuvchi, keyin shablonlar`,
    r`$x^2+bx+c$: ko'paytma $c$, yig'indi $b$; $ax^2+bx+c$: AC usuli`,
    r`$(x-a)$ ko'paytuvchi $\Leftrightarrow$ $x=a$ ildiz $\Leftrightarrow$ $p(a)=0$`,
  ],
  homework: r`platformada factoring bo'yicha 15 ta savol`,
  recapSay: [
    r`Xulosa.`,
    r`Har doim avval umumiy ko'paytuvchini chiqaring, keyin shablonlarni qidiring.`,
    r`Trinomda ko'paytmasi c, yig'indisi b bo'lgan sonlar; bosh koeffitsiyent birdan farqli bo'lsa — AC usuli.`,
    r`X minus a ko'paytuvchi bo'lsa, a — ildiz va ko'phadning a dagi qiymati nol.`,
    r`Hozir platformada ko'paytuvchilarga ajratish bo'yicha o'n beshta savolni yeching. Keyingi darsda kvadrat tenglamalarni yechish usullarini o'rganamiz.`,
    r`Ko'rishguncha!`,
  ],
};

export default lesson;
