import {meta} from '../catalog';
import type {Lesson} from '../types';

const r = String.raw;

const lesson: Lesson = {
  ...meta(13),
  topics: ['Ajratish usuli', 'Ildiz chiqarish', 'Kvadrat formula', "To'liq kvadrat", 'Desmos'],
  cover: [
    r`Assalomu alaykum! O'n uchinchi darsga xush kelibsiz. Bugungi mavzu — kvadrat tenglamalarni yechish.`,
    r`Kvadrat tenglamani yechishning to'rt usulini — ko'paytuvchilarga ajratish, kvadrat ildiz chiqarish, kvadrat formula va to'liq kvadratga keltirishni — hamda qaysi usulni qachon tanlashni o'rganamiz.`,
  ],
  goals: [
    r`Ko'paytuvchilarga ajratib yechish`,
    r`$(x-h)^2=k$ ko'rinishida ildiz chiqarish`,
    r`Kvadrat formulani xatosiz qo'llash`,
    r`To'liq kvadratga keltirish`,
  ],
  goalsSay: [
    r`Darsning maqsadlari.`,
    r`Birinchi: tenglamani ko'paytuvchilarga ajratib yechish — butun sonli ildizlar uchun eng tez yo'l.`,
    r`Ikkinchi: qavs kvadrati songa teng bo'lganda kvadrat ildiz chiqarish — plyus-minusni unutmasdan.`,
    r`Uchinchi: kvadrat formula — har qanday kvadrat tenglama uchun universal kalit.`,
    r`To'rtinchi: to'liq kvadratga keltirish — bu usul keyingi darslarda parabola uchi va aylana tenglamasida kerak bo'ladi.`,
    r`Kvadrat tenglamalar Advanced Math domenining yuragi.`,
  ],
  goalsResult: r`har qanday kvadrat tenglamani ishonch bilan yechish`,
  slides: [
    {
      type: 'cards',
      kicker: 'USULLAR',
      title: 'Kvadrat tenglamani yechishning 4 usuli',
      cards: [
        {title: "Ko'paytuvchilarga ajratish", text: r`$(x-4)(x+3)=0\Rightarrow x=4$ yoki $x=-3$`},
        {title: 'Ildiz chiqarish', text: r`$(x-3)^2=16\Rightarrow x-3=\pm4$`},
        {title: 'Kvadrat formula', text: r`$x=\frac{-b\pm\sqrt{b^2-4ac}}{2a}$ — har doim ishlaydi`},
        {title: 'Desmos', text: r`$y=ax^2+bx+c$ ni chizing — $x$-kesishmalar`},
      ],
      say: [
        r`Kvadrat tenglama — a x kvadrat plyus b x plyus c teng nol ko'rinishidagi tenglama. Uni yechishning to'rtta usuli bor.`,
        r`Ko'paytuvchilarga ajratish: agar ko'paytma nolga teng bo'lsa, ko'paytuvchilardan biri nolga teng. Demak, har bir qavsni nolga tenglaymiz.`,
        r`Ildiz chiqarish: qavs kvadrati songa teng bo'lsa, ikkala tomondan ildiz olamiz — plyus va minus bilan.`,
        r`Kvadrat formula: hech narsa ishlamasa ham, u doim ishlaydi.`,
        r`Va Desmos: parabolani chizing va x o'qi bilan kesishishlarini toping.`,
      ],
    },
    {
      type: 'example',
      kicker: '1-USUL',
      title: "Ko'paytuvchilarga ajratib yechish",
      label: 'MISOL',
      question: r`Solve $x^2-x-12=0$.`,
      steps: [
        {m: r`(x-4)(x+3)=0`, note: r`ko'paytma $-12$, yig'indi $-1$`},
        {m: r`x-4=0\ \ \text{yoki}\ \ x+3=0`, note: r`nol ko'paytma qoidasi`},
        {m: r`x=4,\quad x=-3`},
      ],
      answer: r`$4$ va $-3$`,
      tip: r`Ajratishdan oldin tenglamani **nolga** keltiring: $x^2-x=12$ ni avval $x^2-x-12=0$ qiling.`,
      say: [
        r`Birinchi usul: x kvadrat minus x minus o'n ikki teng nol.`,
        r`Ko'paytmasi minus o'n ikki, yig'indisi minus bir bo'lgan sonlar: minus to'rt va uch. X minus to'rt karra x plyus uch teng nol.`,
        r`Ko'paytma nol bo'lsa, ko'paytuvchilardan biri nol: x minus to'rt teng nol yoki x plyus uch teng nol.`,
        r`X teng to'rt yoki x teng minus uch.`,
        r`Javob: to'rt va minus uch.`,
        r`Muhim: ajratishdan oldin tenglamani albatta nolga keltiring. X kvadrat minus x teng o'n ikki bo'lsa, avval o'n ikkini chapga o'tkazing.`,
      ],
    },
    {
      type: 'graph',
      kicker: 'GRAFIKDA',
      title: r`$y=x^2-x-12$`,
      x: [-5, 6],
      y: [-14, 10],
      items: [
        {kind: 'fn', f: (x) => x * x - x - 12, label: r`$y=x^2-x-12$`, note: r`Parabola — kvadrat funksiya grafigi`},
        {kind: 'point', x: -3, y: 0, label: r`$(-3,\,0)$`, color: '#22C55E', note: r`Ildiz $x=-3$ — $x$ o'qi bilan kesishish`},
        {kind: 'point', x: 4, y: 0, label: r`$(4,\,0)$`, color: '#22C55E', note: r`Ildiz $x=4$ — ikkinchi kesishish`},
      ],
      say: [
        r`Bu tenglamani grafikda ko'ramiz.`,
        r`Kvadrat funksiya grafigi — parabola.`,
        r`Parabola x o'qini minus uchda kesadi…`,
        r`…va to'rtda. Tenglamaning yechimlari — aynan shu kesishish nuqtalari. Ularni inglizcha zeros, roots yoki x-intercepts deyishadi — uchalasi bir narsa.`,
      ],
    },
    {
      type: 'example',
      kicker: '2-USUL',
      title: 'Kvadrat ildiz chiqarish',
      label: 'MISOL',
      question: r`Solve $(x-3)^2=16$.`,
      steps: [
        {m: r`x-3=\pm4`, note: r`ikkala tomondan ildiz — **plyus-minus**`},
        {m: r`x=3+4=7`},
        {m: r`x=3-4=-1`},
      ],
      answer: r`$7$ va $-1$`,
      tip: r`$x^2=16$ ning yechimi faqat $4$ emas — $-4$ ham. Minus yechimni yo'qotish — klassik xato.`,
      say: [
        r`Ikkinchi usul: x minus uch, kvadrat, teng o'n olti.`,
        r`Ikkala tomondan kvadrat ildiz olamiz. O'n oltining ildizi plyus to'rt ham, minus to'rt ham bo'lishi mumkin: x minus uch teng plyus-minus to'rt.`,
        r`Birinchi holat: x teng uch plyus to'rt — yetti.`,
        r`Ikkinchi holat: x teng uch minus to'rt — minus bir.`,
        r`Javob: yetti va minus bir.`,
        r`Plyus-minusni unutib, faqat bitta yechim topish — juda keng tarqalgan xato.`,
      ],
    },
    {
      type: 'formula',
      kicker: '3-USUL',
      title: 'Kvadrat formula',
      formulas: [
        {label: 'Tenglama', tex: r`ax^2+bx+c=0`, note: r`avval shu ko'rinishga keltiring`},
        {label: 'Yechimlar', tex: r`x=\dfrac{-b\pm\sqrt{b^2-4ac}}{2a}`, note: r`$a$, $b$, $c$ — ishoralari bilan`},
      ],
      banner: r`Eng ko'p xato: $b$ manfiy bo'lganda $-b$ ni noto'g'ri yozish va $b^2$ ning ishorasi`,
      say: [
        r`Uchinchi usul — kvadrat formula.`,
        r`Avval tenglamani a x kvadrat plyus b x plyus c teng nol ko'rinishiga keltiring va a, b, c ni ishoralari bilan yozib oling.`,
        r`Yechimlar: x teng minus b plyus-minus ildiz ostida b kvadrat minus to'rt a c, bo'lingan ikki a.`,
        r`Eng ko'p xatolar: b manfiy bo'lganda minus b ni noto'g'ri yozish va b kvadratni manfiy deb hisoblash. B kvadrat har doim musbat.`,
      ],
    },
    {
      type: 'example',
      kicker: 'SAT MISOLI',
      title: 'Kvadrat formula bilan',
      question: r`What are the solutions to $2x^2-4x-3=0$?`,
      choices: [r`$1\pm\frac{\sqrt{10}}{2}$`, r`$2\pm\sqrt{10}$`, r`$-1\pm\frac{\sqrt{10}}{2}$`, r`$1\pm\sqrt{10}$`],
      steps: [
        {m: r`a=2,\ b=-4,\ c=-3`},
        {m: r`x=\frac{4\pm\sqrt{16+24}}{4}=\frac{4\pm\sqrt{40}}{4}`},
        {m: r`\sqrt{40}=2\sqrt{10}\ \Rightarrow\ x=1\pm\frac{\sqrt{10}}{2}`},
      ],
      answer: r`A`,
      tip: r`Desmos bilan tekshiring: $y=2x^2-4x-3$ ildizlari $\approx2.58$ va $\approx-0.58$; $1+\frac{\sqrt{10}}{2}\approx2.58$ ✓`,
      say: [
        r`SAT misoli. What are the solutions to two x squared minus four x minus three equals zero?`,
        r`A teng ikki, b teng minus to'rt, c teng minus uch.`,
        r`Formulaga qo'yamiz: minus b — to'rt. Diskriminant: o'n olti minus to'rt karra ikki karra minus uch — o'n olti plyus yigirma to'rt — qirq. Maxraj: to'rt.`,
        r`Qirqning ildizi — ikki ildiz o'n. Har bir hadni to'rtga bo'lsak: bir plyus-minus ildiz o'n bo'lingan ikki.`,
        r`Javob: A.`,
        r`Variantlar murakkab ko'rinsa, Desmos'da ildizlarni toping va variantlarni kalkulyatorda hisoblab solishtiring.`,
      ],
    },
    {
      type: 'example',
      kicker: '4-USUL',
      title: "To'liq kvadratga keltirish",
      label: 'MISOL',
      question: r`Solve $x^2+6x-7=0$ by completing the square.`,
      steps: [
        {m: r`x^2+6x=7`},
        {m: r`x^2+6x+9=7+9`, note: r`$\left(\frac{6}{2}\right)^2=9$ ni qo'shamiz`},
        {m: r`(x+3)^2=16`},
        {m: r`x+3=\pm4\Rightarrow x=1,\ -7`},
      ],
      answer: r`$1$ va $-7$`,
      say: [
        r`To'rtinchi usul — to'liq kvadratga keltirish. X kvadrat plyus olti x minus yetti teng nol.`,
        r`Ozod hadni o'ngga o'tkazamiz: x kvadrat plyus olti x teng yetti.`,
        r`X oldidagi sonning yarmini kvadratga oshiramiz: olti bo'lingan ikki — uch, kvadrati — to'qqiz. Ikkala tomonga to'qqiz qo'shamiz.`,
        r`Chap tomon to'liq kvadrat bo'ldi: x plyus uch, kvadrat, teng o'n olti.`,
        r`Ildiz chiqaramiz: x plyus uch teng plyus-minus to'rt, demak x teng bir yoki minus yetti.`,
        r`Javob: bir va minus yetti. Bu usul ayniqsa parabolaning uchini va aylananing markazini topishda kerak bo'ladi.`,
      ],
    },
    {
      type: 'trap',
      title: "$x$ ga bo'lish",
      question: r`What are all solutions to $x^2=5x$?`,
      wrong: r`$x=5$`,
      why: r`Ikkala tomon $x$ ga bo'lindi — bu $x=0$ yechimini yo'qotadi.`,
      right: r`Nolga keltiramiz: $x^2-5x=0$, $x(x-5)=0$ $\Rightarrow$ **$x=0$ yoki $x=5$**.`,
      say: [
        r`Tuzoq. What are all solutions to x squared equals five x?`,
        r`O'quvchi ikkala tomonni x ga bo'ladi va x teng besh deb javob beradi. Lekin x ga bo'lganimizda x nol bo'lishi mumkinligini unutdik va bitta yechimni yo'qotdik.`,
        r`To'g'ri yo'l: nolga keltiramiz, x ni qavsdan chiqaramiz: x karra x minus besh teng nol. Yechimlar: nol va besh. Qoida: tenglamani hech qachon noma'lumga bo'lmang — qavsdan chiqaring.`,
      ],
    },
    {
      type: 'compare',
      kicker: 'STRATEGIYA',
      title: 'Qaysi usulni tanlash kerak?',
      cards: [
        {title: 'Ajratish', rule: r`Kichik butun sonlar, oson topiladigan juftlik`, example: r`$x^2+5x+6=0$`},
        {title: 'Ildiz / formula', rule: r`$(\ldots)^2=k$ shakli yoki ajralmaydigan tenglama`, example: r`$2x^2-4x-3=0$`},
        {title: 'Desmos', rule: r`Har doim tekshiruv; o'nli ildizlar`, example: r`$0.5x^2-1.3x-2=0$`},
      ],
      say: [
        r`Qaysi usulni qachon tanlash kerak?`,
        r`Koeffitsiyentlar kichik butun sonlar bo'lsa va juftlik tez topilsa — ajratish usuli eng tez.`,
        r`Tenglama qavs kvadrati shaklida bo'lsa — ildiz chiqarish. Hech qanday juftlik topilmasa — kvadrat formula.`,
        r`Desmos — o'nli kasrli tenglamalar uchun va har qanday javobni tekshirish uchun.`,
      ],
    },
    {
      type: 'example',
      kicker: 'MUSTAQIL MASHQ',
      title: "O'zingiz yeching",
      label: 'MASHQ',
      question: r`The solutions to $x^2-6x+4=0$ can be written as $a\pm\sqrt{b}$, where $a$ and $b$ are integers. What is $b$?`,
      steps: [
        {m: r`x^2-6x+9=-4+9`, note: r`to'liq kvadrat`},
        {m: r`(x-3)^2=5`},
        {m: r`x=3\pm\sqrt5`},
      ],
      answer: r`$b=5$`,
      say: [
        r`Mustaqil mashq. Videoni to'xtating. X kvadrat minus olti x plyus to'rt teng nol tenglamaning yechimlari a plyus-minus ildiz b ko'rinishida. B nimaga teng?`,
        r`To'liq kvadratga keltiramiz: olti bo'lingan ikki — uch, kvadrati to'qqiz. To'rtni o'ngga o'tkazib, ikkala tomonga to'qqiz qo'shamiz.`,
        r`X minus uch, kvadrat, teng besh.`,
        r`X teng uch plyus-minus ildiz besh.`,
        r`Demak, b teng besh. Kvadrat formula bilan ham xuddi shu javob chiqadi.`,
      ],
    },
    {
      type: 'example',
      kicker: 'SAT MISOLI',
      title: 'Avval nolga keltiring',
      label: 'SPR SAVOLI',
      question: r`What is the positive solution to $x(x+2)=15$?`,
      steps: [
        {m: r`x^2+2x-15=0`, note: r`qavsni ochib, nolga keltiramiz`},
        {m: r`(x+5)(x-3)=0`},
        {m: r`x=-5\ \text{yoki}\ x=3`},
      ],
      answer: r`$3$`,
      tip: r`$x=15$ yoki $x+2=15$ — **xato**: nol ko'paytma qoidasi faqat o'ng tomon $0$ bo'lganda ishlaydi.`,
      say: [
        r`SAT misoli. What is the positive solution to x times x plus two equals fifteen?`,
        r`Ba'zi o'quvchilar x teng o'n besh yoki x plyus ikki teng o'n besh deb yozadi. Bu xato — nol ko'paytma qoidasi faqat o'ng tomon nol bo'lganda ishlaydi. Qavsni ochib, nolga keltiramiz: x kvadrat plyus ikki x minus o'n besh teng nol.`,
        r`Ajratamiz: x plyus besh karra x minus uch.`,
        r`Ildizlar: minus besh va uch.`,
        r`Musbat yechim — uch.`,
        r`Esda tuting: ko'paytma o'n beshga teng bo'lsa, ko'paytuvchilar haqida hech narsa deya olmaymiz. Faqat nolga teng bo'lganda har bir ko'paytuvchini nolga tenglash mumkin.`,
      ],
    },
    {
      type: 'example',
      kicker: 'DESMOS',
      title: "O'nli koeffitsiyentli tenglama",
      label: 'SPR SAVOLI',
      question: r`What is the greater solution to $0.5x^2-1.3x-2=0$? (Round to the nearest thousandth.)`,
      steps: [
        {m: r`y=0.5x^2-1.3x-2`, note: r`Desmos'da chizamiz`},
        {m: r`x\approx-1.085,\quad x\approx3.685`, note: r`$x$-kesishmalarni bosamiz`},
      ],
      answer: r`$3.685$`,
      tip: r`Kiritish: **3.685** — musbat javobga 5 belgi sig'adi (nuqta bilan).`,
      say: [
        r`Desmos misoli. What is the greater solution to zero point five x squared minus one point three x minus two equals zero?`,
        r`Bunday o'nli koeffitsiyentlar bilan formula noqulay. Desmos'ga y teng nol butun besh x kvadrat minus bir butun uch x minus ikki deb yozamiz.`,
        r`X kesishmalarni bosamiz: taxminan minus bir butun nol sakson besh va uch butun olti yuz sakson besh.`,
        r`Kattasi — uch butun olti yuz sakson besh.`,
        r`Kiritishda nuqta bilan birga besh belgi: uch nuqta olti sakkiz besh. O'nli koeffitsiyentlarni ko'rsangiz — darhol Desmos.`,
      ],
    },
  ],
  recap: [
    r`Avval nolga keltiring; ko'paytma $=0$ — har bir qavs $=0$`,
    r`Ildiz chiqarishda $\pm$; noma'lumga bo'lmang`,
    r`$x=\frac{-b\pm\sqrt{b^2-4ac}}{2a}$ — universal yo'l`,
  ],
  homework: r`platformada kvadrat tenglamalar bo'yicha 15 ta savol`,
  recapSay: [
    r`Xulosa.`,
    r`Kvadrat tenglamani avval nolga keltiring. Ko'paytma nolga teng bo'lsa, har bir ko'paytuvchini nolga tenglang.`,
    r`Ildiz chiqarishda plyus-minusni unutmang va tenglamani hech qachon noma'lumga bo'lmang.`,
    r`Kvadrat formula — har doim ishlaydigan universal yo'l.`,
    r`Hozir platformada kvadrat tenglamalar bo'yicha o'n beshta savolni yeching. Keyingi darsda diskriminant va Viyet teoremasini o'rganamiz.`,
    r`Ko'rishguncha!`,
  ],
};

export default lesson;
