import {meta} from '../catalog';
import type {Lesson} from '../types';

const r = String.raw;

const lesson: Lesson = {
  ...meta(14),
  topics: ['Diskriminant', 'Ildizlar soni', 'Parametr', "Ildizlar yig'indisi", "Ildizlar ko'paytmasi"],
  cover: [
    r`Assalomu alaykum! O'n to'rtinchi darsga xush kelibsiz. Bugungi mavzu — diskriminant va Viyet teoremasi.`,
    r`Kvadrat tenglamani yechmasdan ildizlar sonini aniqlashni, parametrli savollarni hamda ildizlar yig'indisi va ko'paytmasini bir qadamda topishni o'rganamiz.`,
  ],
  goals: [
    r`Diskriminant orqali ildizlar sonini aniqlash`,
    r`"Exactly one / no real solution" savollarida parametr topish`,
    r`Ildizlar yig'indisi va ko'paytmasini yechmasdan topish`,
    r`Ildizlar orqali ifodalarni hisoblash`,
  ],
  goalsSay: [
    r`Darsning maqsadlari.`,
    r`Birinchi: diskriminant yordamida tenglamaning nechta haqiqiy ildizi borligini aniqlash.`,
    r`Ikkinchi: tenglama aniq bitta yoki birorta ham haqiqiy yechimga ega bo'lmasa, noma'lum o'zgarmasni topish.`,
    r`Uchinchi: Viyet teoremasi — ildizlar yig'indisi va ko'paytmasini tenglamani yechmasdan topish.`,
    r`To'rtinchi: ildizlar qatnashgan murakkabroq ifodalarni hisoblash.`,
    r`Bu savollar ko'pincha ikkinchi, qiyin modulda uchraydi — va 750 plyus uchun aynan ular hal qiluvchi.`,
  ],
  goalsResult: r`qiyin moduldagi kvadrat savollar — sizniki`,
  slides: [
    {
      type: 'formula',
      kicker: 'DISKRIMINANT',
      title: r`$D=b^2-4ac$`,
      formulas: [
        {label: r`$D>0$`, tex: r`\text{ikki haqiqiy ildiz}`, note: r`parabola $x$ o'qini 2 marta kesadi`},
        {label: r`$D=0$`, tex: r`\text{bitta ildiz}`, note: r`parabola $x$ o'qiga urinadi`},
        {label: r`$D<0$`, tex: r`\text{haqiqiy ildiz yo'q}`, note: r`parabola $x$ o'qini kesmaydi`},
      ],
      say: [
        r`Kvadrat formulada ildiz ostidagi ifoda — b kvadrat minus to'rt a c — diskriminant deyiladi. U ildizlar sonini aytib beradi.`,
        r`Diskriminant musbat bo'lsa — ikkita har xil haqiqiy ildiz. Parabola x o'qini ikki nuqtada kesadi.`,
        r`Diskriminant nol bo'lsa — bitta ildiz. Parabola x o'qiga faqat tegib o'tadi.`,
        r`Diskriminant manfiy bo'lsa — haqiqiy ildiz yo'q, chunki manfiy sondan kvadrat ildiz olib bo'lmaydi. Parabola x o'qini umuman kesmaydi.`,
      ],
    },
    {
      type: 'graph',
      kicker: 'GRAFIKDA',
      title: 'Uch holat grafikda',
      x: [-4, 4],
      y: [-5, 7],
      items: [
        {kind: 'fn', f: (x) => x * x - 4, label: r`$D>0$`, note: r`$y=x^2-4$: $D=16>0$ — 2 kesishish`},
        {kind: 'fn', f: (x) => (x - 1) * (x - 1), label: r`$D=0$`, note: r`$y=x^2-2x+1$: $D=0$ — urinish`},
        {kind: 'fn', f: (x) => x * x + 2, label: r`$D<0$`, note: r`$y=x^2+2$: $D=-8<0$ — kesishish yo'q`},
      ],
      say: [
        r`Uchala holatni grafikda ko'ramiz.`,
        r`X kvadrat minus to'rt: diskriminant o'n olti, parabola x o'qini ikki marta kesadi.`,
        r`X kvadrat minus ikki x plyus bir: diskriminant nol, parabola x o'qiga bir nuqtada tegadi.`,
        r`X kvadrat plyus ikki: diskriminant manfiy, parabola butunlay x o'qidan yuqorida.`,
      ],
    },
    {
      type: 'example',
      kicker: '1-MISOL',
      title: 'Nechta haqiqiy yechim?',
      question: r`How many real solutions does $3x^2-2x+5=0$ have?`,
      choices: [r`Zero`, r`Exactly one`, r`Exactly two`, r`Infinitely many`],
      steps: [
        {m: r`a=3,\ b=-2,\ c=5`},
        {m: r`D=(-2)^2-4\cdot3\cdot5=4-60`},
        {m: r`D=-56<0`},
      ],
      answer: r`A`,
      say: [
        r`Birinchi misol. How many real solutions does three x squared minus two x plus five equals zero have?`,
        r`A teng uch, b teng minus ikki, c teng besh.`,
        r`Diskriminant: minus ikkining kvadrati — to'rt, minus to'rt karra uch karra besh — oltmish.`,
        r`To'rt minus oltmish — minus ellik olti, manfiy.`,
        r`Haqiqiy yechim yo'q. Javob: A.`,
      ],
    },
    {
      type: 'example',
      kicker: '2-MISOL',
      title: 'Parametr: aniq bitta yechim',
      label: 'SPR SAVOLI',
      question: r`The equation $x^2+kx+9=0$, where $k$ is a positive constant, has exactly one real solution. What is the value of $k$?`,
      steps: [
        {m: r`D=k^2-4\cdot1\cdot9=0`, note: r`bitta yechim — $D=0$`},
        {m: r`k^2=36`},
        {m: r`k=6`, note: r`$k>0$ shart bo'yicha`},
      ],
      answer: r`$6$`,
      say: [
        r`Ikkinchi misol. The equation x squared plus k x plus nine equals zero, where k is positive, has exactly one real solution. What is k?`,
        r`Aniq bitta yechim — diskriminant nolga teng: k kvadrat minus o'ttiz olti teng nol.`,
        r`K kvadrat teng o'ttiz olti.`,
        r`K teng plyus yoki minus olti, lekin shartda k musbat. Demak, k teng olti.`,
        r`Javob: olti. Tekshiruv: x kvadrat plyus olti x plyus to'qqiz — bu x plyus uch, kvadrat. Haqiqatan bitta ildiz: minus uch.`,
      ],
    },
    {
      type: 'example',
      kicker: 'SAT MISOLI',
      title: "Haqiqiy yechim yo'q",
      question: r`For which value of $c$ does $x^2-6x+c=0$ have no real solutions?`,
      choices: [r`$5$`, r`$8$`, r`$9$`, r`$10$`],
      steps: [
        {m: r`D=36-4c<0`},
        {m: r`c>9`},
        {m: r`10>9`},
      ],
      answer: r`D`,
      tip: r`$c=9$ da $D=0$ — bitta yechim. Chegaraviy son tuzoq sifatida beriladi.`,
      say: [
        r`SAT misoli. For which value of c does x squared minus six x plus c equals zero have no real solutions?`,
        r`Yechim yo'q — diskriminant manfiy: o'ttiz olti minus to'rt c kichik nol.`,
        r`To'rt c katta o'ttiz olti, c katta to'qqiz.`,
        r`Variantlardan faqat o'n to'qqizdan katta.`,
        r`Javob: D.`,
        r`C variant — to'qqiz — chegaraviy son: unda diskriminant nol va bitta yechim bor. Bu tuzoq.`,
      ],
    },
    {
      type: 'trap',
      title: "Manfiy $a$ bilan ishoralar",
      question: r`How many real solutions does $-x^2+4x-5=0$ have?`,
      wrong: r`2 ta`,
      why: r`$4ac$ ishorasi xato hisoblangan: $16+20=36$ deb olingan.`,
      right: r`$a=-1,\ c=-5$: $4ac=4\cdot(-1)\cdot(-5)=20$. $D=16-20=-4<0$ — **yechim yo'q**.`,
      say: [
        r`Tuzoq. How many real solutions does minus x squared plus four x minus five equals zero have?`,
        r`Ko'p o'quvchi to'rt a c ning ishorasida adashadi: o'n olti plyus yigirma — o'ttiz olti deb, ikki yechim chiqaradi.`,
        r`To'g'risi: a minus bir, c minus besh, to'rt a c — plyus yigirma. Diskriminant o'n olti minus yigirma — minus to'rt. Yechim yo'q. Ishorali sonlarni doim qavsga olib qo'ying.`,
      ],
    },
    {
      type: 'formula',
      kicker: 'VIYET TEOREMASI',
      title: "Ildizlar yig'indisi va ko'paytmasi",
      formulas: [
        {label: "Yig'indi", tex: r`x_1+x_2=-\dfrac{b}{a}`},
        {label: "Ko'paytma", tex: r`x_1\cdot x_2=\dfrac{c}{a}`},
      ],
      banner: r`Tenglamani yechmasdan: "sum of the solutions" — $-\frac ba$, "product" — $\frac ca$`,
      say: [
        r`Endi Viyet teoremasi. Kvadrat tenglama a x kvadrat plyus b x plyus c teng nolning ildizlari uchun ikkita ajoyib formula bor.`,
        r`Ildizlar yig'indisi minus b bo'lingan a ga teng.`,
        r`Ildizlar ko'paytmasi c bo'lingan a ga teng.`,
        r`Savolda "sum of the solutions" yoki "product of the roots" ko'rsangiz, tenglamani yechmasdan shu formulalarni qo'llang.`,
      ],
    },
    {
      type: 'example',
      kicker: '3-MISOL',
      title: "Ildizlar yig'indisi",
      label: 'SPR SAVOLI',
      question: r`What is the sum of the solutions to $2x^2-10x+7=0$?`,
      steps: [
        {m: r`a=2,\ b=-10`},
        {m: r`x_1+x_2=-\frac{-10}{2}=5`},
      ],
      answer: r`$5$`,
      tip: r`Ildizlar irratsional ($\frac{5\pm\sqrt{11}}{2}$) bo'lsa ham, yig'indi butun son chiqadi.`,
      say: [
        r`Uchinchi misol. What is the sum of the solutions to two x squared minus ten x plus seven equals zero?`,
        r`A teng ikki, b teng minus o'n.`,
        r`Yig'indi: minus b bo'lingan a — minus minus o'n bo'lingan ikki — besh.`,
        r`Javob: besh.`,
        r`Ildizlarning o'zi noqulay irratsional sonlar, lekin ularning yig'indisi oddiy besh. Viyet teoremasi aynan shunday holatlarda vaqtni tejaydi.`,
      ],
    },
    {
      type: 'example',
      kicker: '4-MISOL',
      title: "Ildizlar ko'paytmasi",
      label: 'SPR SAVOLI',
      question: r`What is the product of the solutions to $3x^2+4x-12=0$?`,
      steps: [
        {m: r`a=3,\ c=-12`},
        {m: r`x_1x_2=\frac{-12}{3}=-4`},
      ],
      answer: r`$-4$`,
      say: [
        r`To'rtinchi misol. What is the product of the solutions to three x squared plus four x minus twelve equals zero?`,
        r`A teng uch, c teng minus o'n ikki.`,
        r`Ko'paytma: c bo'lingan a — minus to'rt.`,
        r`Javob: minus to'rt. Ko'paytma manfiy bo'lsa, ildizlar har xil ishorali ekanini ham bilib olamiz.`,
      ],
    },
    {
      type: 'example',
      kicker: 'MUSTAQIL MASHQ',
      title: "O'zingiz yeching",
      label: 'MASHQ',
      question: r`The solutions to $x^2-8x+12=0$ are $r$ and $s$. What is the value of $r^2+s^2$?`,
      steps: [
        {m: r`r+s=8,\quad rs=12`, note: r`Viyet`},
        {m: r`r^2+s^2=(r+s)^2-2rs`},
        {m: r`=64-24=40`},
      ],
      answer: r`$40$`,
      say: [
        r`Mustaqil mashq. Videoni to'xtating. X kvadrat minus sakkiz x plyus o'n ikki teng nol tenglamaning ildizlari r va s. R kvadrat plyus s kvadrat nimaga teng?`,
        r`Viyet: r plyus s teng sakkiz, r karra s teng o'n ikki.`,
        r`R kvadrat plyus s kvadrat — bu yig'indi kvadratidan ikki karra ko'paytmani ayirganiga teng.`,
        r`Oltmish to'rt minus yigirma to'rt — qirq.`,
        r`Javob: qirq. Tekshiruv: ildizlar ikki va olti, to'rt plyus o'ttiz olti — qirq.`,
      ],
    },
    {
      type: 'example',
      kicker: 'SAT MISOLI',
      title: "Gorizontal chiziq bitta nuqtada",
      label: 'SPR SAVOLI',
      question: r`The line $y=k$ intersects the parabola $y=x^2-4x+7$ at exactly one point. What is the value of $k$?`,
      steps: [
        {m: r`x^2-4x+7=k\ \Rightarrow\ x^2-4x+(7-k)=0`},
        {m: r`D=16-4(7-k)=0`, note: r`bitta nuqta — $D=0$`},
        {m: r`k=3`},
      ],
      answer: r`$3$`,
      tip: r`Tezroq: gorizontal chiziq parabolaga faqat **uchida** urinadi: $x=2$, $y=4-8+7=3$.`,
      say: [
        r`SAT misoli. The line y equals k intersects the parabola y equals x squared minus four x plus seven at exactly one point. What is k?`,
        r`Ikki tenglamani tenglaymiz va nolga keltiramiz: x kvadrat minus to'rt x plyus yetti minus k teng nol.`,
        r`Bitta umumiy nuqta — bitta ildiz, ya'ni diskriminant nol: o'n olti minus to'rt karra yetti minus k teng nol.`,
        r`O'n olti minus yigirma sakkiz plyus to'rt k teng nol, k teng uch.`,
        r`Javob: uch.`,
        r`Tezroq yo'l: gorizontal chiziq parabolaga faqat uchida urinadi. Uch: x teng ikki, y teng uch. Demak, k teng uch.`,
      ],
    },
    {
      type: 'example',
      kicker: 'VIYET',
      title: "Bitta ildizdan ikkinchisini topish",
      label: 'SPR SAVOLI',
      question: r`One solution to $x^2+bx-15=0$ is $x=3$. What is the value of $b$?`,
      steps: [
        {m: r`3\cdot x_2=-15\Rightarrow x_2=-5`, note: r`ko'paytma $\frac ca=-15$`},
        {m: r`3+(-5)=-2=-b`, note: r`yig'indi $-\frac ba$`},
        {m: r`b=2`},
      ],
      answer: r`$2$`,
      tip: r`Yoki to'g'ridan-to'g'ri: $9+3b-15=0\Rightarrow b=2$.`,
      say: [
        r`Viyet misoli. One solution to x squared plus b x minus fifteen equals zero is three. What is b?`,
        r`Ildizlar ko'paytmasi c bo'lingan a — minus o'n besh. Bitta ildiz uch bo'lsa, ikkinchisi minus besh.`,
        r`Ildizlar yig'indisi: uch plyus minus besh — minus ikki. Bu minus b ga teng.`,
        r`Demak, b teng ikki.`,
        r`Javob: ikki.`,
        r`Boshqa yo'l: uchni tenglamaga qo'yamiz — to'qqiz plyus uch b minus o'n besh teng nol, b teng ikki. Ildiz berilsa, uni qo'yish ham juda tez.`,
      ],
    },
  ],
  recap: [
    r`$D=b^2-4ac$: $>0$ — 2 ta, $=0$ — 1 ta, $<0$ — yo'q`,
    r`Ishorali sonlarni qavsga oling: $4ac$ da xato qilmang`,
    r`Viyet: $x_1+x_2=-\frac ba$, $x_1x_2=\frac ca$`,
  ],
  homework: r`platformada diskriminant va Viyet bo'yicha 12 ta savol`,
  recapSay: [
    r`Xulosa.`,
    r`Diskriminant b kvadrat minus to'rt a c: musbat — ikki ildiz, nol — bitta, manfiy — haqiqiy ildiz yo'q.`,
    r`Ishorali sonlarni doim qavsga oling — to'rt a c dagi ishora eng ko'p xato beradigan joy.`,
    r`Viyet teoremasi: ildizlar yig'indisi minus b bo'lingan a, ko'paytmasi c bo'lingan a.`,
    r`Hozir platformada diskriminant va Viyet teoremasi bo'yicha o'n ikkita savolni yeching. Keyingi darsda kvadrat funksiya va parabolani o'rganamiz.`,
    r`Ko'rishguncha!`,
  ],
};

export default lesson;
