import {meta} from '../catalog';
import type {Lesson} from '../types';

const r = String.raw;

const lesson: Lesson = {
  ...meta(15),
  topics: ['3 ko\'rinish', 'Uch (vertex)', 'Simmetriya o\'qi', 'Maksimum/minimum', 'Harakat masalasi'],
  cover: [
    r`Assalomu alaykum! O'n beshinchi darsga xush kelibsiz. Bugungi mavzu — kvadrat funksiya va parabola.`,
    r`Kvadrat funksiyaning uch ko'rinishini, parabola uchini, simmetriya o'qini, eng katta va eng kichik qiymatni hamda harakat masalalarini o'rganamiz.`,
  ],
  goals: [
    r`Kvadrat funksiyaning 3 ko'rinishini o'qish`,
    r`Parabola uchini tez topish`,
    r`Simmetriyadan foydalanish`,
    r`Maksimum/minimum masalalarini yechish`,
  ],
  goalsSay: [
    r`Darsning maqsadlari.`,
    r`Birinchi: kvadrat funksiyaning standart, uch va ko'paytuvchi ko'rinishlarida qaysi ma'lumot ko'rinib turishini bilish.`,
    r`Ikkinchi: parabolaning uchini — vertexni — tez topish.`,
    r`Uchinchi: parabolaning simmetriyasidan foydalanib, hisob-kitobni qisqartirish.`,
    r`To'rtinchi: eng katta yoki eng kichik qiymatni topish va harakat masalalarini yechish.`,
    r`Parabolalar SAT'ning Advanced Math qismida eng ko'p uchraydigan grafiklar.`,
  ],
  goalsResult: r`parabolaga bir qarashda barcha ma'lumotni o'qish`,
  slides: [
    {
      type: 'formula',
      kicker: '3 KO\'RINISH',
      title: "Kvadrat funksiyaning uch ko'rinishi",
      formulas: [
        {label: 'Standart', tex: r`y=ax^2+bx+c`, note: r`$c$ — $y$-kesishma`},
        {label: 'Uch (vertex) ko\'rinishi', tex: r`y=a(x-h)^2+k`, note: r`uch: $(h,\,k)$`},
        {label: "Ko'paytuvchi ko'rinishi", tex: r`y=a(x-r)(x-s)`, note: r`ildizlar: $r$ va $s$`},
      ],
      banner: r`SAT savoli: "Which form displays… as a constant?" — kerakli ma'lumot ko'rinadigan shaklni tanlang`,
      say: [
        r`Kvadrat funksiya uch xil ko'rinishda yozilishi mumkin, va har biri boshqa ma'lumotni ko'rsatadi.`,
        r`Standart ko'rinish: y teng a x kvadrat plyus b x plyus c. Unda c darhol ko'rinadi — bu y kesishma.`,
        r`Uch ko'rinishi: y teng a karra x minus h, kvadrat, plyus k. Unda parabola uchi — h, k — ko'rinadi.`,
        r`Ko'paytuvchi ko'rinishi: y teng a karra x minus r karra x minus s. Unda ildizlar r va s ko'rinadi.`,
        r`SAT ko'pincha so'raydi: qaysi ko'rinish maksimum qiymatni yoki x kesishmalarni konstanta sifatida ko'rsatadi? Javob — o'sha ma'lumot ko'rinadigan shakl.`,
      ],
    },
    {
      type: 'cards',
      kicker: 'XOSSALAR',
      title: r`$a$ nimani aytadi?`,
      cards: [
        {title: r`$a>0$`, text: r`Parabola **yuqoriga** ochiladi — uchda **minimum**`},
        {title: r`$a<0$`, text: r`Parabola **pastga** ochiladi — uchda **maksimum**`},
        {title: r`$|a|$ katta`, text: r`Parabola **torroq**; $|a|$ kichik — kengroq`},
        {title: "Simmetriya o'qi", text: r`$x=-\frac{b}{2a}$ — uchdan o'tuvchi vertikal chiziq`},
      ],
      say: [
        r`A koeffitsiyenti parabolaning shaklini aytadi.`,
        r`A musbat bo'lsa, parabola yuqoriga ochiladi va uchida eng kichik qiymat — minimum.`,
        r`A manfiy bo'lsa, parabola pastga ochiladi va uchida eng katta qiymat — maksimum.`,
        r`A ning moduli katta bo'lsa, parabola torroq, kichik bo'lsa — kengroq.`,
        r`Simmetriya o'qi — uchdan o'tuvchi vertikal chiziq: x teng minus b bo'lingan ikki a. Bu formula standart ko'rinishdan uchni topishning kaliti.`,
      ],
    },
    {
      type: 'graph',
      kicker: 'GRAFIKDA',
      title: r`$y=(x-2)^2-3$`,
      x: [-3, 7],
      y: [-5, 8],
      items: [
        {kind: 'fn', f: (x) => (x - 2) * (x - 2) - 3, label: r`$y=(x-2)^2-3$`, note: r`$a=1>0$ — yuqoriga ochiladi`},
        {kind: 'point', x: 2, y: -3, label: r`$(2,\,-3)$`, color: '#22C55E', note: r`Uch: $(h,k)=(2,\,-3)$ — minimum $-3$`},
        {kind: 'segment', from: [2, -5], to: [2, 8], dashed: true, color: '#C7CCF5', label: r`$x=2$`, note: r`Simmetriya o'qi: $x=2$`},
        {kind: 'point', x: 0, y: 1, label: r`$(0,\,1)$`, color: '#F59E0B', note: r`$y$-kesishma: $x=0$ da $y=4-3=1$`},
      ],
      say: [
        r`Grafikda ko'ramiz: y teng x minus ikki, kvadrat, minus uch.`,
        r`A teng bir, musbat — parabola yuqoriga ochiladi.`,
        r`Uchi: ikki, minus uch. E'tibor bering: qavs ichida minus ikki, lekin h — plyus ikki. Funksiyaning eng kichik qiymati — minus uch.`,
        r`Simmetriya o'qi — x teng ikki. Parabolaning chap va o'ng qismlari bu chiziqqa nisbatan ko'zgudagi aksdek.`,
        r`Y kesishmani topish uchun x o'rniga nol qo'yamiz: to'rt minus uch — bir.`,
      ],
    },
    {
      type: 'example',
      kicker: '1-MISOL',
      title: 'Standart ko\'rinishdan uchni topish',
      label: 'MISOL',
      question: r`Find the vertex of $y=x^2-8x+5$.`,
      steps: [
        {m: r`x=-\frac{b}{2a}=-\frac{-8}{2}=4`},
        {m: r`y=16-32+5=-11`, note: r`$x=4$ ni qo'yamiz`},
      ],
      answer: r`$(4,\,-11)$`,
      tip: r`Desmos'da: parabolani chizing va uchdagi kulrang nuqtani bosing.`,
      say: [
        r`Birinchi misol: y teng x kvadrat minus sakkiz x plyus besh funksiyaning uchini toping.`,
        r`Uchning x koordinatasi: minus b bo'lingan ikki a — sakkiz bo'lingan ikki — to'rt.`,
        r`Y koordinatasi uchun to'rtni funksiyaga qo'yamiz: o'n olti minus o'ttiz ikki plyus besh — minus o'n bir.`,
        r`Javob: to'rt, minus o'n bir.`,
        r`Desmos bilan: parabolani chizing, uchida kulrang nuqta paydo bo'ladi — uni bossangiz, koordinatalar chiqadi.`,
      ],
    },
    {
      type: 'example',
      kicker: 'SAT MISOLI',
      title: 'Maksimum qiymat',
      question: r`The function $f$ is defined by $f(x)=-2(x+1)^2+7$. What is the maximum value of $f$?`,
      choices: [r`$-1$`, r`$1$`, r`$2$`, r`$7$`],
      steps: [
        {m: r`a=-2<0`, note: r`pastga ochiladi — maksimum bor`},
        {m: r`(h,k)=(-1,\,7)`},
        {m: r`\max f=k=7`},
      ],
      answer: r`D`,
      tip: r`"Maximum value" — bu $y$ qiymat ($k$). "Where" yoki "for what $x$" — bu $h$.`,
      say: [
        r`SAT misoli. f of x equals minus two times x plus one squared plus seven. What is the maximum value of f?`,
        r`A minus ikki, manfiy — parabola pastga ochiladi va uchida maksimum.`,
        r`Uchi: minus bir, yetti.`,
        r`Maksimum qiymat — uchning y koordinatasi: yetti.`,
        r`Javob: D.`,
        r`Farqiga e'tibor bering: maksimum qiymat — bu y, ya'ni k. Agar savol "maksimumga qaysi x da erishadi" desa — bu h, ya'ni minus bir. A variant aynan shu tuzoq.`,
      ],
    },
    {
      type: 'example',
      kicker: 'SAT MISOLI',
      title: "Qaysi ko'rinish minimumni ko'rsatadi?",
      question: r`Which of the following equivalent forms of $f(x)=x^2-6x+13$ displays the minimum value of $f$ as a constant or coefficient?`,
      choices: [r`$f(x)=(x-3)^2+4$`, r`$f(x)=x(x-6)+13$`, r`$f(x)=(x-1)(x-5)+8$`, r`$f(x)=x^2-6(x-2)+1$`],
      steps: [
        {m: r`a(x-h)^2+k`, note: r`minimum ko'rinadigan shakl — uch ko'rinishi`},
        {m: r`(x-3)^2+4\Rightarrow\min f=4`},
      ],
      answer: r`A`,
      say: [
        r`Yana bir SAT misoli. Which equivalent form of f of x equals x squared minus six x plus thirteen displays the minimum value as a constant?`,
        r`Minimum qiymat uch ko'rinishida ko'rinadi: a karra x minus h, kvadrat, plyus k.`,
        r`A variant aynan shu ko'rinishda: x minus uch, kvadrat, plyus to'rt. Minimum — to'rt.`,
        r`Javob: A.`,
      ],
    },
    {
      type: 'example',
      kicker: 'SIMMETRIYA',
      title: 'Ikki nuqtadan uchning $x$ koordinatasi',
      label: 'SPR SAVOLI',
      question: r`A parabola passes through the points $(-1,\,6)$ and $(5,\,6)$. What is the $x$-coordinate of its vertex?`,
      steps: [
        {m: r`y_1=y_2=6`, note: r`bir xil balandlikdagi nuqtalar — simmetrik`},
        {m: r`x=\frac{-1+5}{2}=2`, note: r`o'rtasi`},
      ],
      answer: r`$2$`,
      tip: r`Xuddi shunday: ildizlar $r$ va $s$ bo'lsa, uch $x=\frac{r+s}{2}$ da.`,
      say: [
        r`Simmetriya. A parabola passes through minus one, six and five, six. What is the x-coordinate of its vertex?`,
        r`Ikki nuqtaning y koordinatasi bir xil — olti. Parabola simmetrik bo'lgani uchun ular simmetriya o'qidan teng uzoqlikda.`,
        r`Uchning x koordinatasi — ularning o'rtasi: minus bir plyus besh, bo'lingan ikki — ikki.`,
        r`Javob: ikki.`,
        r`Xuddi shu g'oya ildizlarga ham tegishli: ildizlar r va s bo'lsa, uch aynan ularning o'rtasida.`,
      ],
    },
    {
      type: 'example',
      kicker: 'HARAKAT MASALASI',
      title: "To'pning eng yuqori nuqtasi",
      label: 'SPR SAVOLI',
      question: r`A ball's height, in feet, $t$ seconds after it is thrown is $h(t)=-16t^2+64t+5$. What is the maximum height of the ball, in feet?`,
      steps: [
        {m: r`t=-\frac{64}{2\cdot(-16)}=2`, note: r`uchning vaqti`},
        {m: r`h(2)=-64+128+5`},
        {m: r`h(2)=69`},
      ],
      answer: r`$69$`,
      tip: r`$5$ — boshlang'ich balandlik ($t=0$), $h(t)=0$ — to'p yerga tushgan vaqt.`,
      say: [
        r`Harakat masalasi. To'p otilgandan t soniya keyin uning balandligi minus o'n olti t kvadrat plyus oltmish to'rt t plyus besh. Eng katta balandlik qancha?`,
        r`Uchning vaqti: minus oltmish to'rt bo'lingan ikki karra minus o'n olti — ikki soniya.`,
        r`T teng ikki ni qo'yamiz: minus oltmish to'rt plyus bir yuz yigirma sakkiz plyus besh.`,
        r`Oltmish to'qqiz.`,
        r`Javob: oltmish to'qqiz fut.`,
        r`Bunday masalalarda boshqa savollar ham bo'ladi: besh — boshlang'ich balandlik, t nol bo'lgandagi qiymat. H teng nol bo'lgan musbat t — to'p yerga tushgan vaqt.`,
      ],
    },
    {
      type: 'trap',
      title: 'Uch ko\'rinishida ishora',
      question: r`What is the vertex of $y=3(x+4)^2-2$?`,
      wrong: r`$(4,\,-2)$`,
      why: r`Formula $a(x-h)^2+k$: qavs ichida **minus** $h$. $x+4=x-(-4)$.`,
      right: r`$h=-4,\ k=-2$: uch **$(-4,\,-2)$**. Qavsdagi son ishorasi teskari olinadi, $k$ esa shundayligicha.`,
      say: [
        r`Tuzoq. What is the vertex of y equals three times x plus four squared minus two?`,
        r`Ko'p o'quvchi qavs ichidagi to'rtni olib, uch to'rt, minus ikki deydi. Lekin formula x minus h: x plyus to'rt — bu x minus minus to'rt.`,
        r`To'g'risi: minus to'rt, minus ikki. Qavs ichidagi sonning ishorasi teskari olinadi, k esa shundayligicha qoladi.`,
      ],
    },
    {
      type: 'example',
      kicker: 'MUSTAQIL MASHQ',
      title: "O'zingiz yeching",
      label: 'MASHQ',
      question: r`The function $f(x)=(x-3)(x+7)$. What is the $x$-coordinate of the vertex of the graph of $f$?`,
      steps: [
        {m: r`r=3,\ s=-7`, note: r`ildizlar`},
        {m: r`x=\frac{3+(-7)}{2}=-2`},
      ],
      answer: r`$-2$`,
      say: [
        r`Mustaqil mashq. Videoni to'xtating. F of x teng x minus uch karra x plyus yetti. Uchning x koordinatasi qancha?`,
        r`Ko'paytuvchi ko'rinishidan ildizlar: uch va minus yetti.`,
        r`Uch — ildizlar o'rtasida: uch plyus minus yetti, bo'lingan ikki — minus ikki.`,
        r`Javob: minus ikki. Qavslarni ochish shart emas edi.`,
      ],
    },
    {
      type: 'graph',
      kicker: "a NING TA'SIRI",
      title: r`$y=x^2$, $y=3x^2$, $y=-\frac12x^2$`,
      x: [-4, 4],
      y: [-6, 9],
      items: [
        {kind: 'fn', f: (x) => x * x, label: r`$y=x^2$`, note: r`Asosiy parabola`},
        {kind: 'fn', f: (x) => 3 * x * x, label: r`$y=3x^2$`, note: r`$|a|=3$ — torroq`},
        {kind: 'fn', f: (x) => -0.5 * x * x, label: r`$y=-\frac12x^2$`, note: r`$a<0$ — pastga, $|a|<1$ — kengroq`},
      ],
      say: [
        r`A ning ta'sirini grafikda ko'ramiz.`,
        r`Asosiy parabola: y teng x kvadrat.`,
        r`Y teng uch x kvadrat — tezroq o'sadi, shuning uchun torroq.`,
        r`Y teng minus yarim x kvadrat — manfiy a sababli pastga ochiladi, moduli birdan kichik bo'lgani uchun kengroq. SAT grafikdan a ning ishorasini so'rashi mumkin: yuqoriga ochilsa — musbat, pastga — manfiy.`,
      ],
    },
    {
      type: 'example',
      kicker: 'SAT MISOLI',
      title: r`Nuqtadan $a$ ni topish`,
      label: 'SPR SAVOLI',
      question: r`The graph of $f(x)=a(x-2)^2+5$ passes through the point $(0,\,-3)$. What is the value of $a$?`,
      steps: [
        {m: r`-3=a(0-2)^2+5`, note: r`nuqtani qo'yamiz`},
        {m: r`-3=4a+5`},
        {m: r`a=-2`},
      ],
      answer: r`$-2$`,
      say: [
        r`SAT misoli. The graph of f of x equals a times x minus two squared plus five passes through zero, minus three. What is a?`,
        r`Nuqtani qo'yamiz: minus uch teng a karra nol minus ikki, kvadrat, plyus besh.`,
        r`Minus uch teng to'rt a plyus besh.`,
        r`To'rt a teng minus sakkiz, a teng minus ikki.`,
        r`Javob: minus ikki. Mantiqan ham to'g'ri: uch y teng besh balandlikda, nuqta esa pastroqda — parabola pastga ochiladi, a manfiy.`,
      ],
    },
  ],
  recap: [
    r`Standart — $c$, uch ko'rinishi — $(h,k)$, ko'paytuvchi — ildizlar`,
    r`Uch: $x=-\frac{b}{2a}$ yoki ildizlar o'rtasi`,
    r`Maksimum/minimum qiymat — $k$; qaysi $x$ da — $h$`,
  ],
  homework: r`platformada parabolalar bo'yicha 15 ta savol`,
  recapSay: [
    r`Xulosa.`,
    r`Standart ko'rinish y kesishmani, uch ko'rinishi parabola uchini, ko'paytuvchi ko'rinishi ildizlarni ko'rsatadi.`,
    r`Uchning x koordinatasi — minus b bo'lingan ikki a, yoki ildizlarning o'rtasi.`,
    r`Maksimum yoki minimum qiymat — bu k, unga erishiladigan x — bu h.`,
    r`Hozir platformada parabolalar bo'yicha o'n beshta savolni yeching. Keyingi darsda darajalar va ildizlarni o'rganamiz.`,
    r`Ko'rishguncha!`,
  ],
};

export default lesson;
