import {meta} from '../catalog';
import type {Lesson} from '../types';

const r = String.raw;

const lesson: Lesson = {
  ...meta(16),
  topics: ['Daraja qoidalari', 'Manfiy daraja', 'Kasr daraja', 'Ildizlarni soddalashtirish', 'Eksponensial tenglama'],
  cover: [
    r`Assalomu alaykum! O'n oltinchi darsga xush kelibsiz. Bugungi mavzu — darajalar va ildizlar.`,
    r`Daraja qoidalarini, nol, manfiy va kasr darajalarni, ildizlarni soddalashtirishni va asoslarni tenglashtirib eksponensial tenglamalarni yechishni o'rganamiz.`,
  ],
  goals: [
    r`Daraja qoidalarini xatosiz qo'llash`,
    r`Manfiy va kasr darajalarni ildizga o'tkazish`,
    r`Ildizlarni soddalashtirish va qo'shish`,
    r`Bir xil asosga keltirib tenglama yechish`,
  ],
  goalsSay: [
    r`Darsning maqsadlari.`,
    r`Birinchi: ko'paytirish, bo'lish va darajani darajaga oshirish qoidalarini xatosiz qo'llash.`,
    r`Ikkinchi: manfiy va kasr darajalarning ma'nosini tushunish va ularni ildiz ko'rinishiga o'tkazish.`,
    r`Uchinchi: ildizlarni soddalashtirish va o'xshash ildizlarni qo'shish.`,
    r`To'rtinchi: ikki tomonni bir xil asosga keltirib, eksponensial tenglamalarni yechish.`,
    r`Bu ko'nikmalar keyingi darsdagi eksponensial funksiyalar uchun ham poydevor bo'ladi.`,
  ],
  goalsResult: r`daraja va ildiz savollari — tez va aniq`,
  slides: [
    {
      type: 'formula',
      kicker: 'ASOSIY QOIDALAR',
      title: 'Daraja qoidalari',
      formulas: [
        {label: "Ko'paytirish", tex: r`a^m\cdot a^n=a^{m+n}`, note: r`asos bir xil — darajalar qo'shiladi`},
        {label: "Bo'lish", tex: r`\dfrac{a^m}{a^n}=a^{m-n}`, note: r`darajalar ayiriladi`},
        {label: 'Darajani darajaga', tex: r`(a^m)^n=a^{mn},\quad (ab)^n=a^nb^n`, note: r`darajalar ko'paytiriladi`},
      ],
      say: [
        r`Uchta asosiy qoida.`,
        r`Asoslari bir xil darajalarni ko'paytirganda darajalar qo'shiladi: a ning m darajasi karra a ning n darajasi — a ning m plyus n darajasi.`,
        r`Bo'lganda darajalar ayiriladi.`,
        r`Darajani darajaga oshirganda darajalar ko'paytiriladi. Ko'paytmaning darajasi esa har bir ko'paytuvchining darajasiga teng: a b ning n darajasi — a ning n darajasi karra b ning n darajasi.`,
      ],
    },
    {
      type: 'formula',
      kicker: 'MAXSUS DARAJALAR',
      title: 'Nol, manfiy va kasr daraja',
      formulas: [
        {label: 'Nol daraja', tex: r`a^0=1\quad(a\neq0)`},
        {label: 'Manfiy daraja', tex: r`a^{-n}=\dfrac{1}{a^n}`, note: r`manfiy — "teskari", manfiy son emas!`},
        {label: 'Kasr daraja', tex: r`a^{\frac{m}{n}}=\sqrt[n]{a^m}`, note: r`maxraj — ildiz ko'rsatkichi`},
      ],
      say: [
        r`Endi maxsus darajalar.`,
        r`Noldan farqli istalgan sonning nol darajasi bir.`,
        r`Manfiy daraja — teskari son: a ning minus n darajasi — bir bo'lingan a ning n darajasi. E'tibor bering: natija manfiy son bo'lmaydi, faqat kasrga aylanadi.`,
        r`Kasr daraja — ildiz: a ning m n-dan darajasi — n-darajali ildiz ostida a ning m darajasi. Eslab qolish oson: maxraj — ildiz ko'rsatkichi, surat — daraja.`,
      ],
    },
    {
      type: 'example',
      kicker: '1-MISOL',
      title: 'Ifodani soddalashtirish',
      label: 'MISOL',
      question: r`Simplify $\dfrac{(2x^3)^2\cdot x^{-1}}{4x^2}$ for $x\neq0$.`,
      steps: [
        {m: r`(2x^3)^2=4x^6`, note: r`har bir ko'paytuvchini kvadratga`},
        {m: r`\frac{4x^6\cdot x^{-1}}{4x^2}=\frac{4x^5}{4x^2}`},
        {m: r`x^{5-2}=x^3`},
      ],
      answer: r`$x^3$`,
      say: [
        r`Birinchi misol. Ikki x kubning kvadrati karra x ning minus birinchi darajasi, bo'lingan to'rt x kvadrat.`,
        r`Avval qavs: ikkining kvadrati to'rt, x kubning kvadrati x ning oltinchi darajasi. To'rt x oltinchi daraja.`,
        r`X ning minus birinchi darajasiga ko'paytirsak, darajalar qo'shiladi: to'rt x beshinchi daraja, bo'lingan to'rt x kvadrat.`,
        r`To'rtlar qisqaradi, darajalar ayiriladi: x kub.`,
        r`Javob: x kub.`,
      ],
    },
    {
      type: 'example',
      kicker: 'SAT MISOLI',
      title: 'Kasr daraja va ildiz',
      question: r`Which of the following is equivalent to $x^{\frac34}$, for $x>0$?`,
      choices: [r`$\sqrt[3]{x^4}$`, r`$\sqrt[4]{x^3}$`, r`$\frac{x^3}{x^4}$`, r`$\frac{1}{x^{4/3}}$`],
      steps: [
        {m: r`a^{\frac mn}=\sqrt[n]{a^m}`},
        {m: r`x^{\frac34}=\sqrt[4]{x^3}`, note: r`maxraj $4$ — ildiz ko'rsatkichi`},
      ],
      answer: r`B`,
      say: [
        r`SAT misoli. Which of the following is equivalent to x to the three fourths?`,
        r`Qoida: kasr darajada maxraj — ildiz ko'rsatkichi, surat — daraja.`,
        r`Maxraj to'rt — to'rtinchi darajali ildiz; surat uch — x kub. To'rtinchi darajali ildiz ostida x kub.`,
        r`Javob: B. A variant — surat va maxrajni almashtirib qo'ygan tuzoq.`,
      ],
    },
    {
      type: 'example',
      kicker: '2-MISOL',
      title: 'Ildizlarni soddalashtirish',
      label: 'MISOL',
      question: r`Simplify $\sqrt{50}+\sqrt{18}$.`,
      steps: [
        {m: r`\sqrt{50}=\sqrt{25\cdot2}=5\sqrt2`, note: r`eng katta to'liq kvadratni ajratamiz`},
        {m: r`\sqrt{18}=\sqrt{9\cdot2}=3\sqrt2`},
        {m: r`5\sqrt2+3\sqrt2=8\sqrt2`, note: r`o'xshash ildizlar qo'shiladi`},
      ],
      answer: r`$8\sqrt2$`,
      tip: r`$\sqrt{50}+\sqrt{18}\neq\sqrt{68}$ — ildizlarni bunday qo'shib bo'lmaydi.`,
      say: [
        r`Ikkinchi misol: ildiz ellik plyus ildiz o'n sakkiz.`,
        r`Ellikdan eng katta to'liq kvadratni ajratamiz: yigirma besh karra ikki. Ildiz ellik teng besh ildiz ikki.`,
        r`O'n sakkiz — to'qqiz karra ikki: uch ildiz ikki.`,
        r`Endi ular o'xshash ildizlar — xuddi o'xshash hadlar kabi qo'shiladi: sakkiz ildiz ikki.`,
        r`Javob: sakkiz ildiz ikki.`,
        r`Diqqat: ildiz ellik plyus ildiz o'n sakkiz ildiz oltmish sakkizga teng emas. Ildizlarni faqat soddalashtirgandan keyin, o'xshash bo'lsa, qo'shish mumkin.`,
      ],
    },
    {
      type: 'example',
      kicker: '3-MISOL',
      title: 'Maxrajni ildizdan qutqarish',
      label: 'MISOL',
      question: r`Simplify $\dfrac{6}{\sqrt3}$.`,
      steps: [
        {m: r`\frac{6}{\sqrt3}\cdot\frac{\sqrt3}{\sqrt3}`, note: r`surat va maxrajni $\sqrt3$ ga ko'paytiramiz`},
        {m: r`=\frac{6\sqrt3}{3}`},
        {m: r`=2\sqrt3`},
      ],
      answer: r`$2\sqrt3$`,
      say: [
        r`Uchinchi misol: olti bo'lingan ildiz uch. Variantlarda odatda maxrajida ildiz yo'q shakl beriladi.`,
        r`Surat va maxrajni ildiz uchga ko'paytiramiz.`,
        r`Maxrajda ildiz uch karra ildiz uch — uch. Olti ildiz uch bo'lingan uch.`,
        r`Ikki ildiz uch.`,
        r`Javob: ikki ildiz uch. Kalkulyatorda tekshirish oson: ikkalasi ham taxminan uch butun to'rt yuz oltmish to'rt.`,
      ],
    },
    {
      type: 'example',
      kicker: 'EKSPONENSIAL TENGLAMA',
      title: 'Bir xil asosga keltirish',
      label: 'MISOL',
      question: r`Solve $9^{x}=27^{2}$.`,
      steps: [
        {m: r`(3^2)^x=(3^3)^2`, note: r`ikkala asosni $3$ ning darajasiga`},
        {m: r`3^{2x}=3^{6}`},
        {m: r`2x=6\Rightarrow x=3`, note: r`asoslar teng — darajalar teng`},
      ],
      answer: r`$x=3$`,
      say: [
        r`Eksponensial tenglama: to'qqizning x darajasi teng yigirma yettining kvadrati.`,
        r`To'qqiz ham, yigirma yetti ham uchning darajasi: to'qqiz — uch kvadrat, yigirma yetti — uch kub.`,
        r`Darajani darajaga oshiramiz: uchning ikki x darajasi teng uchning oltinchi darajasi.`,
        r`Asoslar teng bo'lsa, darajalar ham teng: ikki x teng olti, x teng uch.`,
        r`Javob: uch. Qoida: ikki tomonni bir xil asosga keltiring, keyin darajalarni tenglang.`,
      ],
    },
    {
      type: 'trap',
      title: "Asoslarni ko'paytirish",
      question: r`Simplify $3^2\cdot3^4$.`,
      wrong: r`$9^6$`,
      why: r`Asoslar ko'paytirilgan va darajalar qo'shilgan. Asos o'zgarmaydi!`,
      right: r`Asos bir xil qoladi, darajalar qo'shiladi: **$3^6=729$**. Tekshiruv: $9\cdot81=729$ ✓`,
      say: [
        r`Tuzoq. Simplify three squared times three to the fourth.`,
        r`Ko'p o'quvchi asoslarni ham ko'paytirib, to'qqizning oltinchi darajasi deb yozadi. Bu juda katta xato: asos o'zgarmaydi.`,
        r`To'g'risi: uchning oltinchi darajasi, ya'ni yetti yuz yigirma to'qqiz. Tekshirish oson: to'qqiz karra sakson bir — yetti yuz yigirma to'qqiz.`,
      ],
    },
    {
      type: 'example',
      kicker: 'SAT MISOLI',
      title: 'Ildizlarni daraja bilan ifodalash',
      label: 'SPR SAVOLI',
      question: r`If $\sqrt{x}\cdot\sqrt[3]{x}=x^{k}$ for all $x>0$, what is the value of $k$?`,
      steps: [
        {m: r`x^{\frac12}\cdot x^{\frac13}`, note: r`ildizlarni kasr darajaga`},
        {m: r`x^{\frac12+\frac13}=x^{\frac56}`},
        {m: r`k=\frac56`},
      ],
      answer: r`$5/6$`,
      say: [
        r`SAT misoli. If square root of x times cube root of x equals x to the k, what is k?`,
        r`Ildizlarni kasr darajaga o'tkazamiz: x ning yarim darajasi va x ning uchdan bir darajasi.`,
        r`Ko'paytirganda darajalar qo'shiladi: yarim plyus uchdan bir — besh oltidan.`,
        r`K teng besh oltidan.`,
        r`Javob: besh slesh olti. Ildizlar bilan ishlashda ularni kasr darajaga o'tkazish ko'pincha eng qulay yo'l.`,
      ],
    },
    {
      type: 'example',
      kicker: 'MANFIY DARAJA',
      title: 'Kasrning manfiy darajasi',
      label: 'SPR SAVOLI',
      question: r`What is the value of $\left(\dfrac{2}{3}\right)^{-2}$?`,
      steps: [
        {m: r`\left(\frac23\right)^{-2}=\left(\frac32\right)^{2}`, note: r`manfiy — kasrni ag'daramiz`},
        {m: r`=\frac94`},
      ],
      answer: r`$9/4$ yoki $2.25$`,
      say: [
        r`Yana bir misol: ikki uchdanning minus ikkinchi darajasi.`,
        r`Manfiy daraja kasrni ag'daradi: uch ikkidanning kvadrati.`,
        r`To'qqiz to'rtdan.`,
        r`Javob: to'qqiz slesh to'rt yoki ikki nuqta yigirma besh.`,
      ],
    },
    {
      type: 'example',
      kicker: 'MUSTAQIL MASHQ',
      title: "O'zingiz yeching",
      label: 'MASHQ',
      question: r`If $4^{a}=8$, what is the value of $a$?`,
      steps: [
        {m: r`(2^2)^a=2^3`},
        {m: r`2a=3`},
        {m: r`a=\frac32`},
      ],
      answer: r`$3/2$ yoki $1.5$`,
      say: [
        r`Mustaqil mashq. Videoni to'xtating: to'rtning a darajasi sakkizga teng. A nimaga teng?`,
        r`To'rt — ikki kvadrat, sakkiz — ikki kub: ikkining ikki a darajasi teng ikkining uchinchi darajasi.`,
        r`Ikki a teng uch.`,
        r`A teng uch ikkidan, ya'ni bir butun o'ndan besh.`,
        r`Javob: uch slesh ikki yoki bir nuqta besh. Tekshiruv: to'rtning yarim darajasi ikki, ikki karra to'rt — sakkiz.`,
      ],
    },
    {
      type: 'example',
      kicker: 'SAT MISOLI',
      title: 'Ikki harfli ifoda',
      question: r`Which of the following is equivalent to $\dfrac{x^{5}y^{-2}}{x^{2}y^{3}}$, for $x,y>0$?`,
      choices: [r`$x^3y$`, r`$\frac{x^3}{y^5}$`, r`$\frac{x^3}{y}$`, r`$x^7y^5$`],
      steps: [
        {m: r`x^{5-2}=x^3`, note: r`$x$ lar alohida`},
        {m: r`y^{-2-3}=y^{-5}`, note: r`$y$ lar alohida`},
        {m: r`x^3y^{-5}=\frac{x^3}{y^5}`},
      ],
      answer: r`B`,
      say: [
        r`SAT misoli. Which is equivalent to x to the fifth times y to the minus two, over x squared times y cubed?`,
        r`Har bir harfni alohida ko'ramiz. X lar: beshdan ikkini ayiramiz — x kub.`,
        r`Y lar: minus ikkidan uchni ayiramiz — minus besh.`,
        r`Manfiy darajani maxrajga tushiramiz: x kub bo'lingan y ning beshinchi darajasi.`,
        r`Javob: B. C variant — minus ikkidan uchni ayirish o'rniga qo'shib yuborgan xato.`,
      ],
    },
    {
      type: 'example',
      kicker: 'SAT HIYLASI',
      title: r`$2^x$ ma'lum bo'lsa`,
      label: 'SPR SAVOLI',
      question: r`If $2^{x}=5$, what is the value of $2^{x+2}$?`,
      steps: [
        {m: r`2^{x+2}=2^x\cdot2^2`, note: r`daraja yig'indisi — ko'paytma`},
        {m: r`=5\cdot4=20`},
      ],
      answer: r`$20$`,
      tip: r`$x$ ni topish shart emas (u butun son ham emas). Qoidani teskari yo'nalishda ishlating.`,
      say: [
        r`SAT hiylasi. If two to the x equals five, what is two to the x plus two?`,
        r`X ni topishga urinmang — u butun son emas. Qoidani teskari ishlatamiz: ikkining x plyus ikki darajasi — ikkining x darajasi karra ikkining kvadrati.`,
        r`Besh karra to'rt — yigirma.`,
        r`Javob: yigirma.`,
        r`Daraja qoidalari ikki yo'nalishda ham ishlaydi: yig'indi darajani ko'paytmaga ajratish ko'pincha eng tez yo'l.`,
      ],
    },
  ],
  recap: [
    r`Ko'paytirish — qo'shish, bo'lish — ayirish, darajaga — ko'paytirish`,
    r`$a^{-n}=\frac1{a^n}$, $a^{m/n}=\sqrt[n]{a^m}$`,
    r`Eksponensial tenglama: bir xil asos $\Rightarrow$ darajalar teng`,
  ],
  homework: r`platformada darajalar va ildizlar bo'yicha 15 ta savol`,
  recapSay: [
    r`Xulosa.`,
    r`Bir xil asosli darajalarni ko'paytirganda darajalar qo'shiladi, bo'lganda ayiriladi, darajaga oshirganda ko'paytiriladi. Asos o'zgarmaydi.`,
    r`Manfiy daraja — teskari son, kasr daraja — ildiz: maxraj ildiz ko'rsatkichi.`,
    r`Eksponensial tenglamada ikki tomonni bir xil asosga keltiring va darajalarni tenglang.`,
    r`Hozir platformada darajalar va ildizlar bo'yicha o'n beshta savolni yeching. Keyingi darsda eksponensial funksiyalar — o'sish va kamayishni o'rganamiz.`,
    r`Ko'rishguncha!`,
  ],
};

export default lesson;
