import {meta} from '../catalog';
import type {Lesson} from '../types';

const r = String.raw;

const lesson: Lesson = {
  ...meta(17),
  topics: ['$y=a\\cdot b^x$', 'Foizli o\'sish', 'Kamayish', 'Chiziqli vs eksponensial', 'Talqin'],
  cover: [
    r`Assalomu alaykum! O'n yettinchi darsga xush kelibsiz. Bugungi mavzu — eksponensial funksiyalar: o'sish va kamayish.`,
    r`Eksponensial modelni tuzishni, foizli o'sish va kamayishni, chiziqli va eksponensial modellarni farqlashni va modeldagi sonlarni talqin qilishni o'rganamiz.`,
  ],
  goals: [
    r`$y=a\cdot b^x$ modelini o'qish va tuzish`,
    r`Foizli o'sish va kamayishni modellashtirish`,
    r`Chiziqli va eksponensial modelni farqlash`,
    r`"Har $k$ yilda" kabi davrlarni to'g'ri yozish`,
  ],
  goalsSay: [
    r`Darsning maqsadlari.`,
    r`Birinchi: a karra b ning x darajasi modelini o'qish va tuzish.`,
    r`Ikkinchi: foiz bilan beriladigan o'sish va kamayishni formulaga aylantirish.`,
    r`Uchinchi: jadval yoki matndan model chiziqli yoki eksponensial ekanini aniqlash.`,
    r`To'rtinchi: "har uch soatda ikki baravar" kabi davrlarni darajada to'g'ri ko'rsatish.`,
    r`Eksponensial modellar SAT'da matnli masala ko'rinishida tez-tez uchraydi.`,
  ],
  goalsResult: r`o'sish va kamayish masalalari — ishonchli`,
  slides: [
    {
      type: 'formula',
      kicker: 'MODEL',
      title: 'Eksponensial funksiya',
      formulas: [
        {label: 'Umumiy ko\'rinish', tex: r`y=a\cdot b^{x}`, note: r`$a$ — boshlang'ich qiymat, $b$ — ko'paytuvchi`},
        {label: "Foizli o'sish", tex: r`y=a(1+r)^{t}`, note: r`$r$ — o'sish foizi (o'nli kasrda)`},
        {label: 'Foizli kamayish', tex: r`y=a(1-r)^{t}`, note: r`$b<1$ — kamayadi`},
      ],
      banner: r`$b>1$ — o'sish, $0<b<1$ — kamayish. $a$ — doim $x=0$ dagi qiymat`,
      say: [
        r`Eksponensial funksiya: y teng a karra b ning x darajasi.`,
        r`A — boshlang'ich qiymat, x nol bo'lgandagi y. B — har qadamda ko'paytiriladigan son.`,
        r`Foiz bilan o'sish: a karra bir plyus r ning t darajasi. Masalan, yiliga besh foiz — bir butun nol besh.`,
        r`Foiz bilan kamayish: a karra bir minus r ning t darajasi. Yiliga o'n besh foiz kamaysa — nol butun sakson besh.`,
        r`Qoida: b birdan katta bo'lsa — o'sish, nol bilan bir orasida bo'lsa — kamayish. A esa doim boshlang'ich qiymat.`,
      ],
    },
    {
      type: 'table',
      kicker: 'FARQ',
      title: 'Chiziqli va eksponensial o\'sish',
      head: ['$t$', 'Chiziqli: $+20$', 'Eksponensial: $\\times1.2$'],
      rows: [
        [r`$0$`, r`$100$`, r`$100$`],
        [r`$1$`, r`$120$`, r`$120$`],
        [r`$2$`, r`$140$`, r`$144$`],
        [r`$3$`, r`$160$`, r`$172.8$`],
      ],
      banner: r`Chiziqli — teng **ayirma**, eksponensial — teng **nisbat** (har safar bir xil songa ko'paytiriladi)`,
      say: [
        r`Chiziqli va eksponensial o'sish farqini jadvalda ko'ramiz. Chap ustunda chiziqli model — har qadamda yigirma qo'shiladi, o'ng ustunda eksponensial — har qadamda bir butun ikkiga ko'paytiriladi.`,
        r`Nol qadamda ikkalasi ham yuzdan boshlanadi.`,
        r`Birinchi qadamda ikkalasi ham bir yuz yigirma.`,
        r`Ikkinchi qadamda chiziqli model yana yigirma qo'shadi — bir yuz qirq. Eksponensial esa bir butun ikkiga ko'paytiradi — bir yuz qirq to'rt.`,
        r`Uchinchi qadamda farq kattalashadi: bir yuz oltmish va bir yuz yetmish ikki butun sakkiz.`,
        r`Chiziqli model har qadamda bir xil son qo'shadi, eksponensial esa bir xil songa ko'paytiradi. Jadvalda ayirmalar teng bo'lsa — chiziqli, nisbatlar teng bo'lsa — eksponensial.`,
      ],
    },
    {
      type: 'graph',
      kicker: 'GRAFIKDA',
      title: r`$y=2^x$ va $y=\left(\frac12\right)^x$`,
      x: [-4, 4],
      y: [-1, 10],
      items: [
        {kind: 'fn', f: (x) => Math.pow(2, x), label: r`$y=2^x$`, note: r`$b=2>1$ — o'sish, tobora tezlashadi`},
        {kind: 'fn', f: (x) => Math.pow(0.5, x), label: r`$y=\left(\frac12\right)^x$`, note: r`$b=\frac12<1$ — kamayish`},
        {kind: 'point', x: 0, y: 1, label: r`$(0,\,1)$`, color: '#FFFFFF', note: r`Ikkalasi ham $(0,\,a)=(0,\,1)$ dan o'tadi; grafik $x$ o'qini kesmaydi`},
      ],
      say: [
        r`Grafiklarni ko'ramiz.`,
        r`Ikkining x darajasi — o'sish. Grafik avval sekin, keyin tobora tez ko'tariladi.`,
        r`Yarimning x darajasi — kamayish. Grafik nolga yaqinlashadi, lekin hech qachon nolga yetmaydi.`,
        r`Ikkala grafik ham nol, bir nuqtasidan o'tadi — bu a. Eksponensial funksiyaning grafigi x o'qini kesmaydi.`,
      ],
    },
    {
      type: 'example',
      kicker: '1-MISOL',
      title: '"Har 3 soatda ikki baravar"',
      question: r`A population of 500 bacteria doubles every 3 hours. Which function gives the population $P$ after $t$ hours?`,
      choices: [r`$P=500\cdot2^{3t}$`, r`$P=500\cdot2^{t/3}$`, r`$P=500\cdot3^{t/2}$`, r`$P=500+2^{t/3}$`],
      steps: [
        {m: r`a=500,\ b=2`, note: r`ikki baravar — $\times2$`},
        {m: r`\frac{t}{3}`, note: r`$t$ soatda $\frac t3$ marta ikkilanadi`},
        {m: r`P=500\cdot2^{t/3}`},
      ],
      answer: r`B`,
      tip: r`Tekshiruv: $t=3$ da $P=500\cdot2=1000$ ✓ — 3 soatda haqiqatan ikki baravar.`,
      say: [
        r`Birinchi misol. Besh yuzta bakteriya har uch soatda ikki baravar ko'payadi. Which function gives the population after t hours?`,
        r`Boshlang'ich qiymat besh yuz, ko'paytuvchi ikki.`,
        r`T soat ichida necha marta ikkilanadi? Har uch soatda bir marta, demak t bo'lingan uch marta. Daraja — t bo'lingan uch.`,
        r`P teng besh yuz karra ikkining t uchdan darajasi.`,
        r`Javob: B.`,
        r`Tekshiruv: t teng uch bo'lsa, ikkining birinchi darajasi — ikki, besh yuz karra ikki — ming. Uch soatda haqiqatan ikki baravar.`,
      ],
    },
    {
      type: 'example',
      kicker: '2-MISOL',
      title: 'Foizli kamayish',
      question: r`A car is worth 20,000 dollars and loses 15% of its value each year. What is its value after 3 years?`,
      choices: [r`$11{,}000$`, r`$12{,}282.50$`, r`$17{,}000$`, r`$8{,}500$`],
      steps: [
        {m: r`V=20000(1-0.15)^t=20000(0.85)^t`},
        {m: r`V(3)=20000\cdot0.85^3`},
        {m: r`=20000\cdot0.614125=12282.5`},
      ],
      answer: r`B`,
      tip: r`A — chiziqli xato: $20000-3\cdot0.15\cdot20000$. Foiz har yil **qolgan** qiymatdan olinadi.`,
      say: [
        r`Ikkinchi misol. Avtomobil yigirma ming dollar turadi va har yili qiymatining o'n besh foizini yo'qotadi. Uch yildan keyin qiymati qancha?`,
        r`O'n besh foiz kamayish — har yili qiymat nol butun sakson beshga ko'paytiriladi.`,
        r`T teng uch: yigirma ming karra nol butun sakson beshning kubi.`,
        r`Kalkulyatorda: o'n ikki ming ikki yuz sakson ikki butun besh.`,
        r`Javob: B.`,
        r`A variant — chiziqli hisob: har yili boshlang'ich qiymatning o'n besh foizini ayirish. Lekin eksponensial kamayishda foiz har yili qolgan, kamaygan qiymatdan olinadi.`,
      ],
    },
    {
      type: 'example',
      kicker: 'SAT MISOLI',
      title: "Sonning ma'nosi",
      question: r`The value of an investment is modeled by $P(t)=1200(1.04)^t$, where $t$ is years. What does $1.04$ represent?`,
      choices: [r`The value increases by 4% each year`, r`The value increases by 1.04% each year`, r`The initial value is 1.04 dollars`, r`The value increases by 104% each year`],
      steps: [
        {m: r`1.04=1+0.04`},
        {m: r`r=0.04=4\%`, note: r`yillik o'sish foizi`},
      ],
      answer: r`A`,
      say: [
        r`SAT misoli. The value of an investment is modeled by twelve hundred times one point zero four to the t. What does one point zero four represent?`,
        r`Bir butun yuzdan to'rt — bu bir plyus nol butun nol to'rt.`,
        r`Nol butun nol to'rt — to'rt foiz. Demak, qiymat har yili to'rt foizga oshadi.`,
        r`Javob: A. Bir ming ikki yuz esa — boshlang'ich qiymat.`,
      ],
    },
    {
      type: 'example',
      kicker: 'SAT MISOLI',
      title: 'Har 2 yilda 20% kamayish',
      question: r`A quantity decreases by 20% every 2 years. Which function models the quantity after $t$ years, if it starts at $Q_0$?`,
      choices: [r`$Q_0(0.2)^{t/2}$`, r`$Q_0(0.8)^{2t}$`, r`$Q_0(0.8)^{t/2}$`, r`$Q_0(1.2)^{t/2}$`],
      steps: [
        {m: r`b=1-0.2=0.8`, note: r`kamayish`},
        {m: r`\frac t2`, note: r`har 2 yilda bir marta`},
        {m: r`Q_0(0.8)^{t/2}`},
      ],
      answer: r`C`,
      say: [
        r`Yana bir misol. A quantity decreases by twenty percent every two years. Which function models it?`,
        r`Yigirma foiz kamayish — ko'paytuvchi nol butun sakkiz.`,
        r`Har ikki yilda bir marta — daraja t bo'lingan ikki.`,
        r`Q nol karra nol butun sakkizning t ikkidan darajasi.`,
        r`Javob: C. Ikkita tuzoq bor: A — kamayish foizini ko'paytuvchi deb olgan, B — darajani ikki t qilgan.`,
      ],
    },
    {
      type: 'trap',
      title: 'Kamayish foizi',
      question: r`A town's population of 8,000 decreases by 30% per year. Which expression gives the population after $t$ years?`,
      wrong: r`$8000(0.3)^t$`,
      why: r`$0.3$ — bu **yo'qotilgan** qism. Har yili **qoladigan** qism kerak.`,
      right: r`Qoladigan qism: $1-0.3=0.7$. Javob: **$8000(0.7)^t$**.`,
      say: [
        r`Tuzoq. Sakkiz minglik shahar aholisi yiliga o'ttiz foizga kamayadi. Which expression gives the population after t years?`,
        r`Ko'p o'quvchi nol butun uchni ko'paytuvchi qilib oladi. Lekin o'ttiz foiz — har yili yo'qotiladigan qism. Agar nol butun uchga ko'paytirsak, aholi bir yilda yetmish foizga kamaygan bo'lardi.`,
        r`Bizga har yili qoladigan qism kerak: bir minus nol butun uch — nol butun yetti. To'g'ri javob: sakkiz ming karra nol butun yettining t darajasi.`,
      ],
    },
    {
      type: 'example',
      kicker: 'JADVALDAN',
      title: 'Qaysi model?',
      label: 'SPR SAVOLI',
      question: r`For a function $f$: $f(0)=5$, $f(1)=15$, $f(2)=45$, $f(3)=135$. If the pattern continues, what is $f(4)$?`,
      steps: [
        {m: r`\frac{15}{5}=\frac{45}{15}=\frac{135}{45}=3`, note: r`nisbat o'zgarmas — eksponensial`},
        {m: r`f(x)=5\cdot3^x`},
        {m: r`f(4)=5\cdot81=405`},
      ],
      answer: r`$405$`,
      say: [
        r`Jadvaldan model. F of zero five, f of one fifteen, f of two forty five, f of three one hundred thirty five. What is f of four?`,
        r`Ayirmalar har xil — o'n, o'ttiz, to'qson — demak chiziqli emas. Nisbatlar esa bir xil — uch. Bu eksponensial.`,
        r`Model: f teng besh karra uchning x darajasi.`,
        r`F to'rt: besh karra sakson bir — to'rt yuz besh.`,
        r`Javob: to'rt yuz besh. Yoki oddiygina oxirgi qiymatni uchga ko'paytiring.`,
      ],
    },
    {
      type: 'example',
      kicker: 'MUSTAQIL MASHQ',
      title: "O'zingiz yeching",
      label: 'MASHQ',
      question: r`1,000 dollars is invested at 5% interest compounded annually. To the nearest dollar, what is the value after 2 years?`,
      steps: [
        {m: r`1000(1.05)^2`},
        {m: r`=1000\cdot1.1025=1102.5`},
        {m: r`\approx1103`},
      ],
      answer: r`$1103$`,
      say: [
        r`Mustaqil mashq. Videoni to'xtating. Ming dollar yillik besh foiz bilan qo'yildi. Ikki yildan keyin qiymati qancha bo'ladi — butun dollargacha yaxlitlang.`,
        r`Model: ming karra bir butun nol beshning kvadrati.`,
        r`Bir butun nol beshning kvadrati — bir butun bir nol ikki besh. Ming dollar uchun — bir ming bir yuz ikki butun besh.`,
        r`Butun dollargacha — bir ming bir yuz uch.`,
        r`Javob: bir ming bir yuz uch. E'tibor bering: chiziqli hisob bir ming bir yuz berardi — eksponensial o'sish "foizdan foiz" beradi.`,
      ],
    },
  ],
  recap: [
    r`$y=a\cdot b^x$: $a$ — boshlang'ich, $b>1$ o'sish, $b<1$ kamayish`,
    r`$r\%$ o'sish — $(1+r)$, kamayish — $(1-r)$; "har $k$ yilda" — $t/k$`,
    r`Teng ayirma — chiziqli, teng nisbat — eksponensial`,
  ],
  homework: r`platformada eksponensial modellar bo'yicha 15 ta savol`,
  recapSay: [
    r`Xulosa.`,
    r`Eksponensial model: y teng a karra b ning x darajasi. A — boshlang'ich qiymat, b birdan katta — o'sish, birdan kichik — kamayish.`,
    r`R foiz o'sish — bir plyus r, kamayish — bir minus r. "Har k yilda" bo'lsa, daraja t bo'lingan k.`,
    r`Jadvalda teng ayirma — chiziqli, teng nisbat — eksponensial model.`,
    r`Hozir platformada eksponensial modellar bo'yicha o'n beshta savolni yeching. Keyingi darsda ratsional ifodalar va tenglamalarni o'rganamiz.`,
    r`Ko'rishguncha!`,
  ],
};

export default lesson;
