import {meta} from '../catalog';
import type {Lesson} from '../types';

const r = String.raw;

const lesson: Lesson = {
  ...meta(18),
  topics: ['Qisqartirish', 'Kasrlarni qo\'shish', 'Ratsional tenglama', 'Begona ildiz', 'Ish masalasi'],
  cover: [
    r`Assalomu alaykum! O'n sakkizinchi darsga xush kelibsiz. Bugungi mavzu — ratsional ifodalar va tenglamalar, ya'ni maxrajida o'zgaruvchi bo'lgan kasrlar.`,
    r`Ratsional ifodalarni qisqartirishni, qo'shishni, ratsional tenglamalarni yechishni, begona ildizlarni aniqlashni va birgalikdagi ish masalalarini o'rganamiz.`,
  ],
  goals: [
    r`Ratsional ifodani to'g'ri qisqartirish`,
    r`Kasrlarni umumiy maxrajga keltirib qo'shish`,
    r`Ratsional tenglamani yechish va begona ildizni tashlash`,
    r`Birgalikdagi ish masalalarini yechish`,
  ],
  goalsSay: [
    r`Darsning maqsadlari.`,
    r`Birinchi: ratsional ifodani to'g'ri qisqartirish — faqat ko'paytuvchilarni.`,
    r`Ikkinchi: harfli kasrlarni umumiy maxrajga keltirib qo'shish va ayirish.`,
    r`Uchinchi: ratsional tenglamani yechish va maxrajni nolga aylantiradigan begona ildizlarni tashlab yuborish.`,
    r`To'rtinchi: "ikki quvur birgalikda qancha vaqtda to'ldiradi" kabi ish masalalarini yechish.`,
    r`Bu savollar ko'pincha qiyin modulda uchraydi va tuzoqlarga boy.`,
  ],
  goalsResult: r`kasrli ifodalar va tenglamalarda tuzoqlarga tushmaslik`,
  slides: [
    {
      type: 'cards',
      kicker: 'ASOSLAR',
      title: 'Ratsional ifoda: 4 qoida',
      cards: [
        {title: 'Maxraj $\\neq0$', text: r`$\frac{x+1}{x-3}$ da $x\neq3$ — taqiqlangan qiymat`},
        {title: "Faqat ko'paytuvchi qisqaradi", text: r`$\frac{x(x+2)}{x}=x+2$, lekin $\frac{x+2}{x}\neq2$`},
        {title: 'Avval ajrating', text: r`Surat va maxrajni ko'paytuvchilarga ajratib, keyin qisqartiring`},
        {title: 'Tenglamada — tekshiring', text: r`Topilgan ildiz maxrajni $0$ qilmasin`},
      ],
      say: [
        r`Ratsional ifoda — surati va maxraji ko'phad bo'lgan kasr. To'rtta asosiy qoida.`,
        r`Birinchi: maxraj nolga teng bo'lishi mumkin emas. X minus uch maxrajda bo'lsa, x uchga teng bo'la olmaydi.`,
        r`Ikkinchi: faqat ko'paytuvchilar qisqaradi, qo'shiluvchilar emas. X karra x plyus ikki bo'lingan x — x plyus ikki. Lekin x plyus ikki bo'lingan x ikkiga teng emas.`,
        r`Uchinchi: qisqartirishdan oldin surat va maxrajni ko'paytuvchilarga ajrating.`,
        r`To'rtinchi: tenglama yechganda topilgan ildizni tekshiring — u maxrajni nolga aylantirmasligi kerak.`,
      ],
    },
    {
      type: 'example',
      kicker: '1-MISOL',
      title: 'Qisqartirish',
      label: 'MISOL',
      question: r`Simplify $\dfrac{x^2-4}{x^2+x-6}$.`,
      steps: [
        {m: r`\frac{(x-2)(x+2)}{(x+3)(x-2)}`, note: r`ikkalasini ajratamiz`},
        {m: r`=\frac{x+2}{x+3}`, note: r`$(x-2)$ qisqaradi`},
        {m: r`x\neq2,\ x\neq-3`, note: r`dastlabki maxraj bo'yicha`},
      ],
      answer: r`$\frac{x+2}{x+3}$`,
      say: [
        r`Birinchi misol: x kvadrat minus to'rt, bo'lingan x kvadrat plyus x minus olti.`,
        r`Surat — kvadratlar ayirmasi: x minus ikki karra x plyus ikki. Maxraj — trinom: x plyus uch karra x minus ikki.`,
        r`Umumiy ko'paytuvchi x minus ikki qisqaradi: x plyus ikki bo'lingan x plyus uch.`,
        r`Taqiqlangan qiymatlar dastlabki maxrajdan olinadi: x ikki ham, minus uch ham bo'la olmaydi.`,
        r`Javob: x plyus ikki bo'lingan x plyus uch.`,
      ],
    },
    {
      type: 'trap',
      title: "Qo'shiluvchini qisqartirish",
      question: r`Simplify $\dfrac{x+6}{x+3}$.`,
      wrong: r`$2$`,
      why: r`$x$ lar "qisqartirilgan" va $\frac63=2$ olingan. Lekin $x$ — qo'shiluvchi, ko'paytuvchi emas.`,
      right: r`Bu ifoda **soddalashmaydi**. Tekshiruv: $x=1$: $\frac{7}{4}\neq2$.`,
      say: [
        r`Tuzoq. Simplify x plus six over x plus three.`,
        r`O'quvchi x larni qisqartiradi, oltini uchga bo'ladi va ikki deydi. Bu mumkin emas: x bu yerda qo'shiluvchi, ko'paytuvchi emas.`,
        r`Bu ifoda soddalashmaydi. Bitta son qo'yib tekshirsangiz: x teng bir — yetti to'rtdan, ikki emas. Shubha bo'lsa, doim son qo'yib tekshiring.`,
      ],
    },
    {
      type: 'example',
      kicker: '2-MISOL',
      title: 'Kasrlarni qo\'shish',
      label: 'MISOL',
      question: r`Write $\dfrac{2}{x}+\dfrac{3}{x+1}$ as a single fraction.`,
      steps: [
        {m: r`\frac{2(x+1)}{x(x+1)}+\frac{3x}{x(x+1)}`, note: r`umumiy maxraj $x(x+1)$`},
        {m: r`=\frac{2x+2+3x}{x(x+1)}`},
        {m: r`=\frac{5x+2}{x^2+x}`},
      ],
      answer: r`$\frac{5x+2}{x^2+x}$`,
      say: [
        r`Ikkinchi misol: ikki bo'lingan x plyus uch bo'lingan x plyus bir — bitta kasr qilib yozing.`,
        r`Umumiy maxraj — x karra x plyus bir. Birinchi kasrni x plyus birga, ikkinchisini x ga kengaytiramiz.`,
        r`Suratlarni qo'shamiz: ikki x plyus ikki plyus uch x.`,
        r`Besh x plyus ikki, bo'lingan x kvadrat plyus x.`,
        r`Javob: besh x plyus ikki, bo'lingan x kvadrat plyus x. Oddiy kasrlardagi kabi: avval umumiy maxraj, keyin suratlar.`,
      ],
    },
    {
      type: 'example',
      kicker: '3-MISOL',
      title: 'Ratsional tenglama',
      label: 'SPR SAVOLI',
      question: r`Solve $\dfrac{3}{x}+\dfrac12=\dfrac{5}{x}$.`,
      steps: [
        {m: r`6+x=10`, note: r`ikkala tomonni $2x$ ga ko'paytiramiz`},
        {m: r`x=4`},
        {m: r`x=4\neq0\ \checkmark`, note: r`maxrajni nolga aylantirmaydi`},
      ],
      answer: r`$4$`,
      say: [
        r`Uchinchi misol: uch bo'lingan x plyus yarim teng besh bo'lingan x.`,
        r`Barcha maxrajlarning umumiy karralisi — ikki x. Ikkala tomonni ikki x ga ko'paytiramiz: olti plyus x teng o'n.`,
        r`X teng to'rt.`,
        r`Tekshiramiz: to'rt maxrajni nolga aylantirmaydi. To'g'ri.`,
        r`Javob: to'rt.`,
      ],
    },
    {
      type: 'example',
      kicker: 'BEGONA ILDIZ',
      title: "Yechim yo'q bo'lib chiqadigan tenglama",
      question: r`What are all solutions to $\dfrac{x}{x-2}=\dfrac{2}{x-2}+3$?`,
      choices: [r`$2$`, r`$3$`, r`No solution`, r`$-2$`],
      steps: [
        {m: r`x=2+3(x-2)`, note: r`$(x-2)$ ga ko'paytiramiz`},
        {m: r`x=3x-4\Rightarrow x=2`},
        {m: r`x=2\Rightarrow x-2=0\ \text{✗}`, note: r`maxraj nolga aylanadi — begona ildiz`},
      ],
      answer: r`C`,
      tip: r`A variant — begona ildiz. Ratsional tenglamada javobni **doim** dastlabki tenglamaga qo'ying.`,
      say: [
        r`Begona ildiz misoli. What are all solutions to x over x minus two equals two over x minus two plus three?`,
        r`Ikkala tomonni x minus ikkiga ko'paytiramiz: x teng ikki plyus uch karra x minus ikki.`,
        r`X teng uch x minus to'rt, demak x teng ikki.`,
        r`Lekin x teng ikki dastlabki tenglamada maxrajni nolga aylantiradi — bu begona ildiz. Uni tashlaymiz.`,
        r`Boshqa yechim yo'q. Javob: C — no solution.`,
        r`A variant — aynan begona ildiz. Ratsional tenglamada javobni doim dastlabki tenglamaga qo'yib tekshiring.`,
      ],
    },
    {
      type: 'example',
      kicker: 'PROPORSIYA',
      title: "Krest ko'paytirish",
      label: 'SPR SAVOLI',
      question: r`What is the positive solution to $\dfrac{x+1}{4}=\dfrac{6}{x-1}$?`,
      steps: [
        {m: r`(x+1)(x-1)=24`, note: r`krest ko'paytirish`},
        {m: r`x^2-1=24\Rightarrow x^2=25`},
        {m: r`x=\pm5\Rightarrow x=5`},
      ],
      answer: r`$5$`,
      say: [
        r`Proporsiya. What is the positive solution to x plus one over four equals six over x minus one?`,
        r`Ikki kasr tengligida krest ko'paytiramiz: x plyus bir karra x minus bir teng yigirma to'rt.`,
        r`Chap tomon — kvadratlar ayirmasi: x kvadrat minus bir teng yigirma to'rt, x kvadrat teng yigirma besh.`,
        r`X teng plyus yoki minus besh. Musbati — besh. Ikkalasi ham maxrajni nolga aylantirmaydi.`,
        r`Javob: besh.`,
      ],
    },
    {
      type: 'example',
      kicker: 'SAT MISOLI',
      title: 'Murakkab kasr',
      question: r`Which of the following is equivalent to $\dfrac{1}{\frac1x+\frac1y}$, for $x,y>0$?`,
      choices: [r`$x+y$`, r`$\frac{x+y}{xy}$`, r`$\frac{xy}{x+y}$`, r`$\frac{1}{x+y}$`],
      steps: [
        {m: r`\frac1x+\frac1y=\frac{y+x}{xy}`, note: r`maxrajni bitta kasr qilamiz`},
        {m: r`\frac{1}{\frac{x+y}{xy}}=\frac{xy}{x+y}`, note: r`kasrni ag'daramiz`},
      ],
      answer: r`C`,
      tip: r`Tekshiruv: $x=y=2$: $\frac{1}{1}=1$ va $\frac{4}{4}=1$ ✓`,
      say: [
        r`SAT misoli. Which is equivalent to one over one over x plus one over y?`,
        r`Avval maxrajdagi kasrlarni qo'shamiz: y plyus x bo'lingan x y.`,
        r`Bir bo'lingan kasr — kasrning ag'darilgani: x y bo'lingan x plyus y.`,
        r`Javob: C.`,
        r`Son qo'yib tekshirish: x va y ikkiga teng bo'lsa, dastlabki ifoda bir, C variant ham bir. B variant — ag'darishni unutgan tuzoq.`,
      ],
    },
    {
      type: 'example',
      kicker: 'ISH MASALASI',
      title: 'Birgalikda ishlash',
      label: 'SPR SAVOLI',
      question: r`Pipe A can fill a tank in 6 hours and pipe B can fill it in 3 hours. Working together, how many hours will it take to fill the tank?`,
      steps: [
        {m: r`\frac16+\frac13=\frac{1}{t}`, note: r`soatlik ish unumlari qo'shiladi`},
        {m: r`\frac16+\frac26=\frac36=\frac12`},
        {m: r`t=2`},
      ],
      answer: r`$2$ soat`,
      tip: r`Vaqtlarni qo'shmang ($6+3$ yoki o'rtachasi $4.5$ — xato). **Unumlar** qo'shiladi.`,
      say: [
        r`Ish masalasi. A quvur bakni olti soatda, B quvur uch soatda to'ldiradi. Birgalikda necha soatda to'ldiradi?`,
        r`Vaqtlarni emas, unumlarni qo'shamiz. A bir soatda bakning oltidan birini, B — uchdan birini to'ldiradi. Birgalikda — t dan bir.`,
        r`Oltidan bir plyus oltidan ikki — oltidan uch — yarim.`,
        r`Bir soatda yarim bak, demak to'liq bak — ikki soatda.`,
        r`Javob: ikki soat.`,
        r`Ko'p uchraydigan xato — vaqtlarni qo'shish yoki o'rtachasini olish. Birgalikda ishlash har doim eng tez ishchidan ham tezroq bo'ladi — ikki soat mantiqan to'g'ri.`,
      ],
    },
    {
      type: 'example',
      kicker: "BO'LISH",
      title: "Ko'phadni ko'phadga bo'lish",
      label: 'SPR SAVOLI',
      question: r`The expression $\dfrac{x^2+5x+7}{x+2}$ is equivalent to $x+3+\dfrac{a}{x+2}$. What is $a$?`,
      steps: [
        {m: r`(x+2)(x+3)=x^2+5x+6`},
        {m: r`x^2+5x+7=(x+2)(x+3)+1`},
        {m: r`a=1`, note: r`qoldiq`},
      ],
      answer: r`$1$`,
      say: [
        r`Ko'phadni ko'phadga bo'lish. The expression x squared plus five x plus seven over x plus two equals x plus three plus a over x plus two. What is a?`,
        r`X plyus ikkini x plyus uchga ko'paytiramiz: x kvadrat plyus besh x plyus olti.`,
        r`Suratdan bu bir kam: x kvadrat plyus besh x plyus yetti — bu x plyus ikki karra x plyus uch, plyus bir.`,
        r`Demak, qoldiq — a — bir.`,
        r`Javob: bir. Bunday savolda uzun bo'lish o'rniga, bo'linuvchini "bo'luvchi karra bo'linma plyus qoldiq" ko'rinishida yozish tezroq.`,
      ],
    },
    {
      type: 'example',
      kicker: 'MUSTAQIL MASHQ',
      title: "O'zingiz yeching",
      label: 'MASHQ',
      question: r`What is the solution to $\dfrac{2}{x-1}=\dfrac{3}{x+1}$?`,
      steps: [
        {m: r`2(x+1)=3(x-1)`},
        {m: r`2x+2=3x-3`},
        {m: r`x=5`},
      ],
      answer: r`$5$`,
      say: [
        r`Mustaqil mashq. Videoni to'xtating: ikki bo'lingan x minus bir teng uch bo'lingan x plyus bir.`,
        r`Krest ko'paytiramiz: ikki karra x plyus bir teng uch karra x minus bir.`,
        r`Ikki x plyus ikki teng uch x minus uch.`,
        r`X teng besh. Maxrajlar to'rt va olti — nolga teng emas.`,
        r`Javob: besh.`,
      ],
    },
  ],
  recap: [
    r`Faqat ko'paytuvchilar qisqaradi — avval ajrating`,
    r`Tenglamada maxrajlarga ko'paytiring va begona ildizni tashlang`,
    r`Ish masalasi: unumlar qo'shiladi, $\frac1a+\frac1b=\frac1t$`,
  ],
  homework: r`platformada ratsional ifodalar bo'yicha 12 ta savol`,
  recapSay: [
    r`Xulosa.`,
    r`Ratsional ifodada faqat ko'paytuvchilar qisqaradi — avval surat va maxrajni ajrating.`,
    r`Ratsional tenglamada barcha maxrajlarga ko'paytiring va topilgan ildizlarni tekshiring: maxrajni nolga aylantiradigani — begona.`,
    r`Birgalikdagi ish masalalarida vaqtlar emas, unumlar qo'shiladi.`,
    r`Hozir platformada ratsional ifodalar bo'yicha o'n ikkita savolni yeching. Keyingi darsda radikal va modulli tenglamalarni o'rganamiz.`,
    r`Ko'rishguncha!`,
  ],
};

export default lesson;
