import {meta} from '../catalog';
import type {Lesson} from '../types';

const r = String.raw;

const lesson: Lesson = {
  ...meta(20),
  topics: ['$f(x)$ belgisi', 'Qiymat hisoblash', 'Kompozitsiya', 'Siljitish', 'Aks ettirish'],
  cover: [
    r`Assalomu alaykum! Yigirmanchi darsga xush kelibsiz. Bugungi mavzu — funksiyalar: belgilash, kompozitsiya va siljitish.`,
    r`F of x belgisini o'qishni, funksiya qiymatini hisoblashni, ikki funksiya kompozitsiyasini, jadvaldan qiymat topishni va grafikni siljitish hamda aks ettirishni o'rganamiz.`,
  ],
  goals: [
    r`$f(3)$, $f(a+2)$ va $f(x)=7$ ni farqlash`,
    r`$f(g(x))$ kompozitsiyani hisoblash`,
    r`Jadval va grafikdan funksiya qiymatini o'qish`,
    r`Grafikni siljitish va aks ettirish qoidalari`,
  ],
  goalsSay: [
    r`Darsning maqsadlari.`,
    r`Birinchi: f of three, f of a plus two va f of x teng yetti — bu uch xil savolni farqlash.`,
    r`Ikkinchi: f of g of x — ikki funksiya kompozitsiyasini hisoblash.`,
    r`Uchinchi: jadval va grafikdan funksiya qiymatini to'g'ri o'qish.`,
    r`To'rtinchi: grafikni yuqoriga, pastga, chapga, o'ngga siljitish va aks ettirish qoidalarini bilish.`,
    r`Funksiya belgisi SAT'ning deyarli har bir Advanced Math savolida bor, shuning uchun uni erkin o'qish shart.`,
  ],
  goalsResult: r`funksiya belgisi bilan erkin ishlash`,
  slides: [
    {
      type: 'cards',
      kicker: 'BELGILASH',
      title: r`$f(x)$ belgisini o'qish`,
      cards: [
        {title: r`$f(3)$`, text: r`$x$ o'rniga $3$ qo'ying — natija **$y$ qiymat**`},
        {title: r`$f(x)=7$`, text: r`Qaysi $x$ da qiymat $7$? — **tenglama yeching**`},
        {title: r`$f(a+2)$`, text: r`$x$ o'rniga **butun ifoda** $(a+2)$ qavs bilan`},
        {title: 'Grafikdan $f(2)$', text: r`$x=2$ dagi nuqtaning **balandligi** ($y$)`},
      ],
      say: [
        r`F of x belgisi bilan to'rt xil savol bo'ladi.`,
        r`F of three — x o'rniga uchni qo'yamiz va y qiymatni hisoblaymiz.`,
        r`F of x teng yetti — bu teskari savol: qaysi x da funksiya qiymati yetti? Buning uchun tenglama yechamiz.`,
        r`F of a plus two — x o'rniga butun ifodani qavs bilan qo'yamiz.`,
        r`Grafikdan f of two — x teng ikki bo'lgan joydagi grafik nuqtasining balandligi, ya'ni y koordinatasi.`,
      ],
    },
    {
      type: 'example',
      kicker: '1-MISOL',
      title: 'Qiymat hisoblash',
      label: 'SPR SAVOLI',
      question: r`If $f(x)=2x^2-3x+1$, what is the value of $f(-2)$?`,
      steps: [
        {m: r`f(-2)=2(-2)^2-3(-2)+1`, note: r`manfiy sonni **qavs** bilan qo'yamiz`},
        {m: r`=2\cdot4+6+1`},
        {m: r`=15`},
      ],
      answer: r`$15$`,
      tip: r`$-2^2=-4$, lekin $(-2)^2=4$. Qavssiz qo'yish — eng ko'p xato manbai.`,
      say: [
        r`Birinchi misol. If f of x equals two x squared minus three x plus one, what is f of minus two?`,
        r`X o'rniga minus ikkini qavs bilan qo'yamiz: ikki karra minus ikkining kvadrati, minus uch karra minus ikki, plyus bir.`,
        r`Minus ikkining kvadrati to'rt, ikki karra to'rt — sakkiz. Minus uch karra minus ikki — plyus olti.`,
        r`Sakkiz plyus olti plyus bir — o'n besh.`,
        r`Javob: o'n besh.`,
        r`Manfiy sonni albatta qavsga oling: qavssiz minus ikkining kvadrati minus to'rt bo'lib qoladi.`,
      ],
    },
    {
      type: 'example',
      kicker: '2-MISOL',
      title: 'Ifodani qo\'yish',
      question: r`If $f(x)=3x-5$, which of the following is equal to $f(a+2)$?`,
      choices: [r`$3a-3$`, r`$3a+1$`, r`$3a+2$`, r`$a-3$`],
      steps: [
        {m: r`f(a+2)=3(a+2)-5`},
        {m: r`=3a+6-5`},
        {m: r`=3a+1`},
      ],
      answer: r`B`,
      say: [
        r`Ikkinchi misol. If f of x equals three x minus five, which is equal to f of a plus two?`,
        r`X o'rniga a plyus ikkini qavs bilan qo'yamiz: uch karra a plyus ikki, minus besh.`,
        r`Uch a plyus olti minus besh.`,
        r`Uch a plyus bir.`,
        r`Javob: B. A variant — qavsni unutib, faqat a ni uchga ko'paytirgan xato: uch a plyus ikki minus besh.`,
      ],
    },
    {
      type: 'example',
      kicker: 'KOMPOZITSIYA',
      title: r`$f(g(x))$`,
      label: 'SPR SAVOLI',
      question: r`If $f(x)=x^2+1$ and $g(x)=2x-3$, what is the value of $f(g(2))$?`,
      steps: [
        {m: r`g(2)=2\cdot2-3=1`, note: r`avval ichkisi`},
        {m: r`f(1)=1^2+1=2`, note: r`natijani tashqi funksiyaga`},
      ],
      answer: r`$2$`,
      tip: r`Tartib muhim: $g(f(2))=g(5)=7\neq2$. Har doim **ichkaridan tashqariga**.`,
      say: [
        r`Kompozitsiya. If f of x equals x squared plus one and g of x equals two x minus three, what is f of g of two?`,
        r`Ichkaridan boshlaymiz: g of two — ikki karra ikki minus uch — bir.`,
        r`Endi bu natijani f ga qo'yamiz: f of one — bir plyus bir — ikki.`,
        r`Javob: ikki.`,
        r`Tartib muhim: g of f of two boshqa javob beradi — f of two besh, g of five yetti. Har doim ichkaridagi funksiyadan boshlang.`,
      ],
    },
    {
      type: 'table',
      kicker: 'JADVALDAN',
      title: r`Jadvaldan $g(f(0))$`,
      head: ['$x$', '$-1$', '$0$', '$1$', '$2$'],
      rows: [
        [r`$f(x)$`, r`$3$`, r`$1$`, r`$-1$`, r`$-3$`],
        [r`$g(x)$`, r`$0$`, r`$2$`, r`$4$`, r`$6$`],
      ],
      banner: r`$f(0)=1$ — jadvaldan; keyin $g(1)=4$. Javob: $g(f(0))=4$`,
      say: [
        r`Ko'pincha funksiyalar jadvalda beriladi. Savol: g of f of zero nimaga teng?`,
        r`F qatoridan: x nol bo'lganda f qiymati bir.`,
        r`Endi g qatoridan x teng bir bo'lgan ustunni qidiramiz: g of one — to'rt.`,
        r`Javob: to'rt. Jadvalda ham qoida bir xil: ichkaridan tashqariga, har safar yangi qiymatni x qatoridan qidirasiz.`,
      ],
    },
    {
      type: 'formula',
      kicker: 'SILJITISH',
      title: 'Grafikni siljitish va aks ettirish',
      formulas: [
        {label: 'Yuqoriga / pastga', tex: r`f(x)+k\quad/\quad f(x)-k`},
        {label: "O'ngga / chapga", tex: r`f(x-h)\quad/\quad f(x+h)`, note: r`qavs ichida — **teskari**!`},
        {label: 'Aks ettirish', tex: r`-f(x):\ x\text{-o'qiga},\quad f(-x):\ y\text{-o'qiga}`},
      ],
      say: [
        r`Grafikni siljitish qoidalari.`,
        r`Funksiyaga k qo'shsak — grafik k birlik yuqoriga, ayirsak — pastga siljiydi. Bu tashqi o'zgarish, kutilganidek ishlaydi.`,
        r`Qavs ichida x o'rniga x minus h yozsak — grafik o'ngga, x plyus h — chapga siljiydi. Ichki o'zgarish teskari ishlaydi, bunga ehtiyot bo'ling.`,
        r`Minus f of x — grafik x o'qiga nisbatan ag'dariladi. F of minus x — y o'qiga nisbatan ag'dariladi.`,
      ],
    },
    {
      type: 'graph',
      kicker: 'GRAFIKDA',
      title: r`$y=x^2\ \to\ y=(x-3)^2+1$`,
      x: [-3, 7],
      y: [-1, 9],
      items: [
        {kind: 'fn', f: (x) => x * x, label: r`$y=x^2$`, note: r`Asosiy grafik, uchi $(0,\,0)$`},
        {kind: 'fn', f: (x) => (x - 3) * (x - 3) + 1, label: r`$y=(x-3)^2+1$`, note: r`$x-3$: o'ngga $3$; $+1$: yuqoriga $1$`},
        {kind: 'point', x: 3, y: 1, label: r`$(3,\,1)$`, color: '#22C55E', note: r`Yangi uch: $(0+3,\ 0+1)=(3,\,1)$`},
      ],
      say: [
        r`Grafikda ko'ramiz.`,
        r`Asosiy grafik: y teng x kvadrat, uchi koordinata boshida.`,
        r`Y teng x minus uch, kvadrat, plyus bir: qavs ichidagi minus uch — o'ngga uch, tashqaridagi plyus bir — yuqoriga bir.`,
        r`Har bir nuqta, jumladan uch ham, xuddi shunday siljiydi: nol, nol nuqtasi uch, bir ga o'tadi.`,
      ],
    },
    {
      type: 'example',
      kicker: 'SAT MISOLI',
      title: 'Nuqta qayerga siljiydi?',
      question: r`The graph of $y=f(x)$ passes through the point $(2,\,5)$. Which point must lie on the graph of $y=f(x-3)+1$?`,
      choices: [r`$(-1,\,6)$`, r`$(5,\,6)$`, r`$(5,\,4)$`, r`$(-1,\,4)$`],
      steps: [
        {m: r`x-3\Rightarrow\ \text{o'ngga }3:\ 2+3=5`},
        {m: r`+1\Rightarrow\ \text{yuqoriga }1:\ 5+1=6`},
        {m: r`(5,\,6)`},
      ],
      answer: r`B`,
      tip: r`Tekshiruv: $y=f(5-3)+1=f(2)+1=5+1=6$ ✓`,
      say: [
        r`SAT misoli. The graph of y equals f of x passes through two, five. Which point must lie on the graph of y equals f of x minus three plus one?`,
        r`Qavs ichida minus uch — o'ngga uch birlik: x koordinata ikki plyus uch — besh.`,
        r`Tashqarida plyus bir — yuqoriga bir: y koordinata besh plyus bir — olti.`,
        r`Yangi nuqta: besh, olti.`,
        r`Javob: B.`,
        r`Tekshiruv: x teng beshni qo'ysak, f of two plyus bir — besh plyus bir — olti. A variant — ichki siljish yo'nalishini teskari olgan tuzoq.`,
      ],
    },
    {
      type: 'trap',
      title: r`$f(x+2)$ qaysi tomonga?`,
      question: r`How is the graph of $y=f(x+2)$ related to the graph of $y=f(x)$?`,
      wrong: r`2 birlik o'ngga`,
      why: r`"$+2$" ko'rib o'ngga deyilgan. Qavs ichidagi o'zgarish **teskari** ishlaydi.`,
      right: r`**2 birlik chapga**. Tekshiruv: eski $x=0$ dagi qiymat endi $x=-2$ da: $f(-2+2)=f(0)$.`,
      say: [
        r`Tuzoq. How is the graph of y equals f of x plus two related to the graph of f of x?`,
        r`Ko'pchilik plyus ikkini ko'rib, o'ngga deydi. Lekin qavs ichidagi o'zgarish teskari ishlaydi.`,
        r`To'g'risi: ikki birlik chapga. Tekshiruv: eski grafikning x nol dagi qiymati endi x minus ikkida olinadi, chunki minus ikki plyus ikki — nol.`,
      ],
    },
    {
      type: 'example',
      kicker: 'SAT MISOLI',
      title: "Noma'lum koeffitsiyent",
      label: 'SPR SAVOLI',
      question: r`The function $f$ is defined by $f(x)=kx+4$, where $k$ is a constant. If $f(3)=19$, what is the value of $f(-1)$?`,
      steps: [
        {m: r`3k+4=19\Rightarrow k=5`, note: r`berilgan qiymatdan $k$`},
        {m: r`f(x)=5x+4`},
        {m: r`f(-1)=-5+4=-1`},
      ],
      answer: r`$-1$`,
      say: [
        r`Yana bir SAT misoli. F of x equals k x plus four. If f of three equals nineteen, what is f of minus one?`,
        r`Avval k ni topamiz: uch k plyus to'rt teng o'n to'qqiz, k teng besh.`,
        r`Funksiya: besh x plyus to'rt.`,
        r`F of minus one: minus besh plyus to'rt — minus bir.`,
        r`Javob: minus bir. Bunday savollar ikki bosqichli: avval noma'lum konstantani topasiz, keyin so'ralgan qiymatni hisoblaysiz.`,
      ],
    },
    {
      type: 'example',
      kicker: 'MUSTAQIL MASHQ',
      title: "O'zingiz yeching",
      label: 'MASHQ',
      question: r`If $f(x)=x^2-4x$, what is the value of $f(3)-f(1)$?`,
      steps: [
        {m: r`f(3)=9-12=-3`},
        {m: r`f(1)=1-4=-3`},
        {m: r`-3-(-3)=0`},
      ],
      answer: r`$0$`,
      say: [
        r`Mustaqil mashq. Videoni to'xtating. F of x teng x kvadrat minus to'rt x. F of three minus f of one nimaga teng?`,
        r`F of three: to'qqiz minus o'n ikki — minus uch.`,
        r`F of one: bir minus to'rt — minus uch.`,
        r`Minus uch minus minus uch — nol.`,
        r`Javob: nol. Bu bejiz emas: parabolaning uchi x teng ikkida, bir va uch esa undan teng uzoqlikda — simmetriya.`,
      ],
    },
  ],
  recap: [
    r`$f(3)$ — qiymat; $f(x)=7$ — tenglama; manfiyni qavsga oling`,
    r`$f(g(x))$ — ichkaridan tashqariga`,
    r`$f(x-h)+k$: o'ngga $h$, yuqoriga $k$; qavs ichi — teskari`,
  ],
  homework: r`platformada funksiyalar bo'yicha 15 ta savol`,
  recapSay: [
    r`Xulosa.`,
    r`F of three — qiymat hisoblash, f of x teng yetti — tenglama yechish. Manfiy sonlarni qavs bilan qo'ying.`,
    r`Kompozitsiyada har doim ichkaridagi funksiyadan boshlang.`,
    r`F of x minus h plyus k — o'ngga h, yuqoriga k. Qavs ichidagi o'zgarish teskari yo'nalishda ishlaydi.`,
    r`Hozir platformada funksiyalar bo'yicha o'n beshta savolni yeching. Keyingi darsda chiziqli va kvadrat sistemalarni o'rganamiz.`,
    r`Ko'rishguncha!`,
  ],
};

export default lesson;
