import {meta} from '../catalog';
import type {Lesson} from '../types';

const r = String.raw;

const lesson: Lesson = {
  ...meta(21),
  topics: ["O'rniga qo'yish", 'Kesishishlar soni', 'Diskriminant', 'Urinish', 'Desmos'],
  cover: [
    r`Assalomu alaykum! Yigirma birinchi darsga xush kelibsiz. Bugungi mavzu — chiziqli va kvadrat sistemalar, ya'ni to'g'ri chiziq va parabola birgalikda.`,
    r`Bunday sistemalarni o'rniga qo'yish usulida yechishni, kesishish nuqtalari sonini diskriminant bilan aniqlashni va urinish holatidagi parametr savollarini o'rganamiz.`,
  ],
  goals: [
    r`Chiziq va parabola sistemasini yechish`,
    r`Kesishishlar sonini diskriminant bilan topish`,
    r`"Exactly one point" — urinish shartidan parametr topish`,
    r`$xy$ va $x+y$ berilgan sistemalarni yechish`,
  ],
  goalsSay: [
    r`Darsning maqsadlari.`,
    r`Birinchi: to'g'ri chiziq va parabola sistemasini o'rniga qo'yish usulida yechish.`,
    r`Ikkinchi: ular necha nuqtada kesishishini diskriminant yordamida aniqlash.`,
    r`Uchinchi: chiziq parabolaga urinadigan, ya'ni bitta umumiy nuqtaga ega bo'ladigan parametrni topish.`,
    r`To'rtinchi: x karra y va x plyus y berilgan nostandart sistemalarni yechish.`,
    r`Bu dars oldingi darslardagi sistemalar va kvadrat tenglamalarni birlashtiradi.`,
  ],
  goalsResult: r`nochiziqli sistemalar — qiyin moduldagi ishonchli ball`,
  slides: [
    {
      type: 'cards',
      kicker: "G'OYA",
      title: 'Chiziq va parabola sistemasi',
      cards: [
        {title: 'Yechim — kesishish', text: r`Sistemaning yechimlari — chiziq va parabolaning umumiy nuqtalari`},
        {title: "O'rniga qo'yish", text: r`$y$ larni tenglaymiz $\Rightarrow$ kvadrat tenglama`},
        {title: '0, 1 yoki 2 nuqta', text: r`Kvadrat tenglamaning $D$ si kesishishlar sonini aytadi`},
        {title: 'Desmos', text: r`Ikkalasini chizing — kesishishlarni bosing`},
      ],
      say: [
        r`Bugungi sistema: bir tenglama — to'g'ri chiziq, ikkinchisi — parabola.`,
        r`Sistemaning yechimlari — ular kesishgan nuqtalar.`,
        r`Algebraik usul: ikkala tenglama y ga teng bo'lsa, o'ng tomonlarni tenglaymiz va kvadrat tenglama hosil bo'ladi.`,
        r`Kvadrat tenglamaning nechta ildizi bo'lsa, shuncha kesishish nuqtasi bor: nol, bir yoki ikki. Diskriminant buni aytib beradi.`,
        r`Va albatta Desmos: ikkala grafikni chizib, kesishish nuqtalarini bosamiz.`,
      ],
    },
    {
      type: 'graph',
      kicker: 'GRAFIKDA',
      title: r`$y=x^2-2x-3$ va $y=x+1$`,
      x: [-3, 6],
      y: [-5, 8],
      items: [
        {kind: 'fn', f: (x) => x * x - 2 * x - 3, label: r`$y=x^2-2x-3$`, note: r`Parabola`},
        {kind: 'fn', f: (x) => x + 1, label: r`$y=x+1$`, note: r`To'g'ri chiziq`},
        {kind: 'point', x: -1, y: 0, label: r`$(-1,\,0)$`, color: '#FFFFFF', note: r`Birinchi kesishish: $(-1,\,0)$`},
        {kind: 'point', x: 4, y: 5, label: r`$(4,\,5)$`, color: '#FFFFFF', note: r`Ikkinchi kesishish: $(4,\,5)$`},
      ],
      say: [
        r`Misolni grafikda ko'ramiz: y teng x kvadrat minus ikki x minus uch va y teng x plyus bir.`,
        r`Parabola.`,
        r`To'g'ri chiziq.`,
        r`Ular minus bir, nol nuqtasida…`,
        r`…va to'rt, besh nuqtasida kesishadi. Ikkita yechim. Endi xuddi shu javobni algebraik yo'l bilan topamiz.`,
      ],
    },
    {
      type: 'example',
      kicker: '1-MISOL',
      title: 'Algebraik yechish',
      label: 'MISOL',
      question: r`Solve the system $y=x^2-2x-3$ and $y=x+1$.`,
      steps: [
        {m: r`x^2-2x-3=x+1`, note: r`$y$ larni tenglaymiz`},
        {m: r`x^2-3x-4=0\Rightarrow(x-4)(x+1)=0`},
        {m: r`x=4\Rightarrow y=5;\quad x=-1\Rightarrow y=0`, note: r`$y$ ni **chiziq** tenglamasidan`},
      ],
      answer: r`$(4,\,5)$ va $(-1,\,0)$`,
      tip: r`$y$ ni topish uchun oddiyroq — chiziqli — tenglamani ishlating.`,
      say: [
        r`Algebraik yechim.`,
        r`Ikkala y ni tenglaymiz: x kvadrat minus ikki x minus uch teng x plyus bir.`,
        r`Nolga keltirib ajratamiz: x kvadrat minus uch x minus to'rt — x minus to'rt karra x plyus bir.`,
        r`X teng to'rt bo'lsa, chiziqdan y teng besh. X teng minus bir bo'lsa, y teng nol.`,
        r`Javob: to'rt, besh va minus bir, nol — grafikdagi bilan bir xil.`,
        r`Maslahat: y ni topish uchun har doim oddiyroq, chiziqli tenglamadan foydalaning — kamroq hisob, kamroq xato.`,
      ],
    },
    {
      type: 'example',
      kicker: 'SAT MISOLI',
      title: 'Bitta yechimning koordinatasi',
      label: 'SPR SAVOLI',
      question: r`The system $y=x^2$ and $y=2x+3$ has a solution $(a,\,b)$ with $a>0$. What is the value of $b$?`,
      steps: [
        {m: r`x^2=2x+3\Rightarrow x^2-2x-3=0`},
        {m: r`(x-3)(x+1)=0\Rightarrow a=3`, note: r`$a>0$`},
        {m: r`b=2\cdot3+3=9`},
      ],
      answer: r`$9$`,
      say: [
        r`SAT misoli. The system y equals x squared and y equals two x plus three has a solution a, b with a greater than zero. What is b?`,
        r`Tenglaymiz: x kvadrat teng ikki x plyus uch, nolga keltiramiz.`,
        r`Ajratamiz: x minus uch karra x plyus bir. Musbat ildiz — uch, demak a teng uch.`,
        r`B — y koordinata: ikki karra uch plyus uch — to'qqiz.`,
        r`Javob: to'qqiz. Savol b ni so'rayapti, uchni belgilab qo'ymang.`,
      ],
    },
    {
      type: 'example',
      kicker: 'KESISHISHLAR SONI',
      title: 'Nechta yechim?',
      question: r`How many solutions does the system $y=x^2+4$ and $y=2x$ have?`,
      choices: [r`Zero`, r`Exactly one`, r`Exactly two`, r`Infinitely many`],
      steps: [
        {m: r`x^2+4=2x\Rightarrow x^2-2x+4=0`},
        {m: r`D=4-16=-12<0`},
      ],
      answer: r`A`,
      say: [
        r`Kesishishlar soni. How many solutions does the system y equals x squared plus four and y equals two x have?`,
        r`Tenglaymiz va nolga keltiramiz: x kvadrat minus ikki x plyus to'rt teng nol.`,
        r`Diskriminant: to'rt minus o'n olti — minus o'n ikki, manfiy.`,
        r`Haqiqiy ildiz yo'q — chiziq va parabola kesishmaydi. Javob: A.`,
      ],
    },
    {
      type: 'example',
      kicker: 'PARAMETR',
      title: 'Aniq bitta umumiy nuqta',
      label: 'SPR SAVOLI',
      question: r`The graphs of $y=x^2+c$ and $y=4x$ intersect at exactly one point. What is the value of the constant $c$?`,
      steps: [
        {m: r`x^2+c=4x\Rightarrow x^2-4x+c=0`},
        {m: r`D=16-4c=0`, note: r`bitta nuqta — $D=0$`},
        {m: r`c=4`},
      ],
      answer: r`$4$`,
      say: [
        r`Parametr. The graphs of y equals x squared plus c and y equals four x intersect at exactly one point. What is c?`,
        r`Tenglaymiz va nolga keltiramiz: x kvadrat minus to'rt x plyus c teng nol.`,
        r`Aniq bitta nuqta — kvadrat tenglamaning bitta ildizi, ya'ni diskriminant nol: o'n olti minus to'rt c teng nol.`,
        r`C teng to'rt.`,
        r`Javob: to'rt. Bu holatda chiziq parabolaga urinadi — keyingi grafikda ko'ramiz.`,
      ],
    },
    {
      type: 'graph',
      kicker: 'URINISH',
      title: r`$y=x^2+4$ va $y=4x$`,
      x: [-2, 5],
      y: [-1, 14],
      items: [
        {kind: 'fn', f: (x) => x * x + 4, label: r`$y=x^2+4$`, note: r`$c=4$ dagi parabola`},
        {kind: 'fn', f: (x) => 4 * x, label: r`$y=4x$`, note: r`Chiziq parabolaga **urinadi**`},
        {kind: 'point', x: 2, y: 8, label: r`$(2,\,8)$`, color: '#FFFFFF', note: r`Yagona umumiy nuqta: $(2,\,8)$. $c>4$ — kesishmaydi, $c<4$ — 2 nuqta`},
      ],
      say: [
        r`Grafikda.`,
        r`C teng to'rt bo'lgandagi parabola.`,
        r`Chiziq y teng to'rt x parabolaga faqat bitta nuqtada tegadi — bu urinish.`,
        r`Umumiy nuqta: ikki, sakkiz. Agar c to'rtdan katta bo'lsa, parabola yuqoriga ko'tariladi va kesishish yo'qoladi. Kichik bo'lsa — ikki nuqtada kesishadi.`,
      ],
    },
    {
      type: 'example',
      kicker: 'NOSTANDART SISTEMA',
      title: r`$xy$ va $x+y$ berilgan`,
      label: 'SPR SAVOLI',
      question: r`If $x+y=7$ and $xy=12$, what is the value of $x^2+y^2$?`,
      steps: [
        {m: r`x^2+y^2=(x+y)^2-2xy`, note: r`ayniyat`},
        {m: r`=49-24`},
        {m: r`=25`},
      ],
      answer: r`$25$`,
      tip: r`Tekshiruv: $x=3,\ y=4$: $9+16=25$ ✓. Lekin ayniyat bilan $x,y$ ni topish shart emas.`,
      say: [
        r`Nostandart sistema. If x plus y equals seven and x times y equals twelve, what is x squared plus y squared?`,
        r`O'n birinchi darsdagi ayniyatni eslaymiz: x kvadrat plyus y kvadrat — yig'indi kvadratidan ikki karra ko'paytmani ayirganiga teng.`,
        r`Qirq to'qqiz minus yigirma to'rt.`,
        r`Yigirma besh.`,
        r`Javob: yigirma besh.`,
        r`Tekshiruv: sonlar uch va to'rt — to'qqiz plyus o'n olti, yigirma besh. Lekin ayniyat bilan x va y ni topish shart emas edi.`,
      ],
    },
    {
      type: 'trap',
      title: "$x$ ni emas, $y$ ni so'rashadi",
      question: r`The system $y=x^2$ and $y=x+2$ has a solution $(x,\,y)$ with $x<0$. What is the value of $y$?`,
      wrong: r`$-1$`,
      why: r`$x^2-x-2=0$ dan $x=-1$ topildi va shu belgilandi — bu $x$.`,
      right: r`$x=-1\Rightarrow y=-1+2=$ **1**. Sistemada savol qaysi koordinatani so'rayotganini tekshiring.`,
      say: [
        r`Tuzoq. The system y equals x squared and y equals x plus two has a solution with x less than zero. What is y?`,
        r`O'quvchi x kvadrat minus x minus ikki teng nol tenglamani yechadi, x teng minus bir chiqadi va minus birni belgilaydi. Lekin bu x.`,
        r`Y teng minus bir plyus ikki — bir. Sistemalarda har doim qaysi koordinata so'ralganiga e'tibor bering.`,
      ],
    },
    {
      type: 'example',
      kicker: 'MUSTAQIL MASHQ',
      title: "O'zingiz yeching",
      label: 'MASHQ',
      question: r`At how many points do the graphs of $y=2x^2-5x+1$ and $y=x-3$ intersect?`,
      steps: [
        {m: r`2x^2-5x+1=x-3\Rightarrow2x^2-6x+4=0`},
        {m: r`x^2-3x+2=0`},
        {m: r`D=9-8=1>0`},
      ],
      answer: r`$2$`,
      say: [
        r`Mustaqil mashq. Videoni to'xtating. Y teng ikki x kvadrat minus besh x plyus bir va y teng x minus uch grafiklari necha nuqtada kesishadi?`,
        r`Tenglaymiz: ikki x kvadrat minus olti x plyus to'rt teng nol.`,
        r`Ikkiga bo'lamiz: x kvadrat minus uch x plyus ikki teng nol.`,
        r`Diskriminant: to'qqiz minus sakkiz — bir, musbat.`,
        r`Javob: ikki nuqta. Ildizlar bir va ikki ekanini ham ko'rish mumkin.`,
      ],
    },
    {
      type: 'example',
      kicker: 'SAT MISOLI',
      title: 'Gorizontal chiziq: 2 ta kesishish',
      question: r`The system $y=-x^2+6x-5$ and $y=k$ has exactly two solutions. Which of the following could be the value of $k$?`,
      choices: [r`$2$`, r`$4$`, r`$5$`, r`$6$`],
      steps: [
        {m: r`x=-\frac{6}{2(-1)}=3,\ \ y=-9+18-5=4`, note: r`parabola uchi — maksimum $4$`},
        {m: r`k<4\ \Rightarrow\ 2\ \text{ta kesishish}`},
        {m: r`k=2`},
      ],
      answer: r`A`,
      tip: r`$k=4$ — urinish (1 ta), $k>4$ — kesishmaydi.`,
      say: [
        r`SAT misoli. The system y equals minus x squared plus six x minus five and y equals k has exactly two solutions. Which could be k?`,
        r`Parabola pastga ochiladi. Uning uchi: x teng uch, y teng minus to'qqiz plyus o'n sakkiz minus besh — to'rt. Bu eng yuqori nuqta.`,
        r`Gorizontal chiziq to'rtdan pastda bo'lsa, parabolani ikki nuqtada kesadi.`,
        r`Variantlardan faqat ikki to'rtdan kichik.`,
        r`Javob: A.`,
        r`K to'rtga teng bo'lsa — urinish, bitta yechim. To'rtdan katta bo'lsa — kesishmaydi.`,
      ],
    },
    {
      type: 'example',
      kicker: 'VIYET',
      title: "Kesishishlar $x$ koordinatalari yig'indisi",
      label: 'SPR SAVOLI',
      question: r`The graphs of $y=x^2-4$ and $y=3x$ intersect at two points. What is the sum of the $x$-coordinates of these points?`,
      steps: [
        {m: r`x^2-4=3x\Rightarrow x^2-3x-4=0`},
        {m: r`x_1+x_2=-\frac{-3}{1}=3`, note: r`Viyet`},
      ],
      answer: r`$3$`,
      tip: r`Tekshiruv: $(x-4)(x+1)=0$, $4+(-1)=3$ ✓`,
      say: [
        r`Viyet bilan. The graphs of y equals x squared minus four and y equals three x intersect at two points. What is the sum of the x-coordinates?`,
        r`Tenglaymiz va nolga keltiramiz: x kvadrat minus uch x minus to'rt teng nol.`,
        r`Ildizlar yig'indisi — minus b bo'lingan a — uch.`,
        r`Javob: uch.`,
        r`Tekshiruv: ildizlar to'rt va minus bir, yig'indisi uch. Viyet o'n to'rtinchi darsdan — bu yerda ham ish beradi.`,
      ],
    },
  ],
  recap: [
    r`$y$ larni tenglang $\Rightarrow$ kvadrat tenglama`,
    r`$D>0$ — 2 nuqta, $D=0$ — urinish, $D<0$ — kesishmaydi`,
    r`$x^2+y^2=(x+y)^2-2xy$`,
  ],
  homework: r`platformada nochiziqli sistemalar bo'yicha 12 ta savol`,
  recapSay: [
    r`Xulosa.`,
    r`Chiziq va parabola sistemasida y larni tenglang — kvadrat tenglama hosil bo'ladi.`,
    r`Uning diskriminanti kesishishlar sonini aytadi: musbat — ikki nuqta, nol — urinish, manfiy — kesishmaydi.`,
    r`X kvadrat plyus y kvadrat — yig'indi kvadrati minus ikki karra ko'paytma. Bu ayniyat ko'p vaqt tejaydi.`,
    r`Hozir platformada nochiziqli sistemalar bo'yicha o'n ikkita savolni yeching. Keyingi darsda ko'phad funksiyalar — nollar va grafiklarni o'rganamiz.`,
    r`Ko'rishguncha!`,
  ],
};

export default lesson;
