import {meta} from '../catalog';
import type {Lesson} from '../types';

const r = String.raw;

const lesson: Lesson = {
  ...meta(22),
  topics: ['Nollar', 'Karralik', 'Grafik shakli', 'Qoldiq teoremasi', 'Jadvaldan ko\'paytuvchi'],
  cover: [
    r`Assalomu alaykum! Yigirma ikkinchi darsga xush kelibsiz. Bu Advanced Math modulining yakuniy darsi. Mavzu — ko'phad funksiyalar: nollar va grafik.`,
    r`Ko'phadning nollarini topishni, karralik va grafikning x o'qiga tegishi yoki kesib o'tishini, qoldiq teoremasini va jadvaldan ko'paytuvchi topishni o'rganamiz.`,
  ],
  goals: [
    r`Ko'paytuvchilardan nollarni topish va aksincha`,
    r`Karralikka qarab grafikni tasavvur qilish`,
    r`Qoldiq teoremasini qo'llash`,
    r`Jadval va grafikdan ko'paytuvchini aniqlash`,
  ],
  goalsSay: [
    r`Darsning maqsadlari.`,
    r`Birinchi: ko'paytuvchilardan nollarni topish va nollardan ko'phadni tiklash.`,
    r`Ikkinchi: nolning karraligiga qarab, grafik x o'qini kesib o'tadimi yoki unga tegib qaytadimi — buni aniqlash.`,
    r`Uchinchi: qoldiq teoremasi — p of a qiymati bo'lishdagi qoldiqqa teng.`,
    r`To'rtinchi: jadval yoki grafikdan ko'phadning ko'paytuvchilarini aniqlash.`,
    r`Bu dars bilan Advanced Math moduli yakunlanadi.`,
  ],
  goalsResult: r`Advanced Math moduli yakunlandi`,
  slides: [
    {
      type: 'cards',
      kicker: 'ASOSLAR',
      title: "Ko'phad funksiya: 4 g'oya",
      cards: [
        {title: "Nol = ildiz = $x$-kesishma", text: r`$p(a)=0\iff(x-a)$ ko'paytuvchi`},
        {title: 'Darajasi $n$', text: r`Ko'pi bilan $n$ ta nol; grafik ko'pi bilan $n-1$ marta buriladi`},
        {title: 'Toq karralik', text: r`$(x-a)^1,\ (x-a)^3$ — grafik $x$ o'qini **kesib o'tadi**`},
        {title: 'Juft karralik', text: r`$(x-a)^2$ — grafik $x$ o'qiga **tegib qaytadi**`},
      ],
      say: [
        r`Ko'phad funksiyalar haqida to'rtta asosiy g'oya.`,
        r`Birinchi: nol, ildiz va x kesishma — bir xil narsa. P of a nolga teng bo'lsa, x minus a — ko'paytuvchi, va aksincha.`,
        r`Ikkinchi: n-darajali ko'phadning ko'pi bilan n ta noli bor.`,
        r`Uchinchi: ko'paytuvchi toq darajada — birinchi yoki uchinchi — bo'lsa, grafik shu nuqtada x o'qini kesib o'tadi.`,
        r`To'rtinchi: ko'paytuvchi juft darajada, masalan kvadratda bo'lsa, grafik x o'qiga tegib, qaytib ketadi — kesib o'tmaydi.`,
      ],
    },
    {
      type: 'graph',
      kicker: 'GRAFIKDA',
      title: r`$y=(x+2)(x-1)(x-3)$`,
      x: [-3, 4.5],
      y: [-8, 12],
      items: [
        {kind: 'fn', f: (x) => (x + 2) * (x - 1) * (x - 3), label: r`$y=(x+2)(x-1)(x-3)$`, note: r`Uchinchi darajali ko'phad`},
        {kind: 'point', x: -2, y: 0, label: r`$-2$`, color: '#22C55E', note: r`$(x+2)\Rightarrow$ nol $x=-2$`},
        {kind: 'point', x: 1, y: 0, label: r`$1$`, color: '#22C55E', note: r`$(x-1)\Rightarrow$ nol $x=1$`},
        {kind: 'point', x: 3, y: 0, label: r`$3$`, color: '#22C55E', note: r`$(x-3)\Rightarrow$ nol $x=3$; $y$-kesishma: $p(0)=2\cdot(-1)\cdot(-3)=6$`},
      ],
      say: [
        r`Grafikda ko'ramiz: x plyus ikki karra x minus bir karra x minus uch.`,
        r`Bu uchinchi darajali ko'phad — uchta nolga ega bo'lishi mumkin.`,
        r`X plyus ikki ko'paytuvchisidan — nol minus ikki. Ishora teskari!`,
        r`X minus birdan — nol bir.`,
        r`X minus uchdan — nol uch. Y kesishma — p of zero: ikki karra minus bir karra minus uch — olti. Uchala nol toq karrali, shuning uchun grafik har birida x o'qini kesib o'tadi.`,
      ],
    },
    {
      type: 'example',
      kicker: '1-MISOL',
      title: "Ko'paytuvchilardan nollar",
      label: 'MISOL',
      question: r`What are the zeros of $f(x)=x(x-4)(2x+1)$?`,
      steps: [
        {m: r`x=0`},
        {m: r`x-4=0\Rightarrow x=4`},
        {m: r`2x+1=0\Rightarrow x=-\frac12`, note: r`koeffitsiyentga bo'lishni unutmang`},
      ],
      answer: r`$0,\ 4,\ -\frac12$`,
      say: [
        r`Birinchi misol: f of x teng x karra x minus to'rt karra ikki x plyus bir. Nollarini toping.`,
        r`Har bir ko'paytuvchini nolga tenglaymiz. Birinchisi: x teng nol.`,
        r`Ikkinchisi: x teng to'rt.`,
        r`Uchinchisi: ikki x plyus bir teng nol, x teng minus yarim.`,
        r`Javob: nol, to'rt va minus yarim. Yolg'iz x ko'paytuvchisini unutmang — u ham nol beradi.`,
      ],
    },
    {
      type: 'graph',
      kicker: 'KARRALIK',
      title: r`$y=\frac14(x-3)^2(x+1)$`,
      x: [-2.5, 5],
      y: [-3, 5],
      items: [
        {kind: 'fn', f: (x) => 0.25 * (x - 3) * (x - 3) * (x + 1), label: r`$y=\frac14(x-3)^2(x+1)$`, note: r`$(x+1)$ — toq, $(x-3)^2$ — juft karrali`},
        {kind: 'point', x: -1, y: 0, label: r`$-1$`, color: '#22C55E', note: r`$x=-1$: grafik o'qni **kesib o'tadi**`},
        {kind: 'point', x: 3, y: 0, label: r`$3$`, color: '#EC4899', note: r`$x=3$: grafik o'qqa **tegib qaytadi**`},
      ],
      say: [
        r`Karralikni grafikda ko'ramiz.`,
        r`Bu ko'phadda x plyus bir birinchi darajada, x minus uch esa kvadratda.`,
        r`Minus birda grafik x o'qini kesib o'tadi — pastdan yuqoriga.`,
        r`Uchda esa grafik x o'qiga tegadi va yana yuqoriga qaytadi — chunki x minus uchning kvadrati hech qachon manfiy bo'lmaydi.`,
      ],
    },
    {
      type: 'example',
      kicker: 'SAT MISOLI',
      title: 'Grafik qayerda tegib qaytadi?',
      question: r`The function $p$ is defined by $p(x)=(x-3)^2(x+1)$. At which $x$-value does the graph of $p$ touch the $x$-axis but not cross it?`,
      choices: [r`$-3$`, r`$-1$`, r`$1$`, r`$3$`],
      steps: [
        {m: r`(x-3)^2\ \text{— juft karrali}`},
        {m: r`x=3`},
      ],
      answer: r`D`,
      say: [
        r`SAT misoli. P of x equals x minus three squared times x plus one. At which x-value does the graph touch the x-axis but not cross it?`,
        r`Juft karrali ko'paytuvchi — x minus uch, kvadrat.`,
        r`Uning noli — uch.`,
        r`Javob: D. Minus bir — oddiy nol, u yerda grafik kesib o'tadi. A variant — ishorani teskari olgan tuzoq.`,
      ],
    },
    {
      type: 'formula',
      kicker: 'QOLDIQ TEOREMASI',
      title: "Qoldiq teoremasi",
      formulas: [
        {label: "Qoldiq", tex: r`p(x)\div(x-a)\ \Rightarrow\ \text{qoldiq}=p(a)`},
        {label: "Ko'paytuvchi", tex: r`p(a)=0\iff(x-a)\ \text{— ko'paytuvchi}`},
      ],
      banner: r`"Remainder when $p(x)$ is divided by $x-3$" — shunchaki $p(3)$ ni hisoblang`,
      say: [
        r`Qoldiq teoremasi.`,
        r`Ko'phadni x minus a ga bo'lganda qoladigan qoldiq — p of a ga teng. Bo'lishni bajarish shart emas.`,
        r`Xususan, p of a nolga teng bo'lsa, qoldiq nol, ya'ni x minus a — ko'paytuvchi.`,
        r`Savolda "remainder when p of x is divided by x minus three" ko'rsangiz — shunchaki p of three ni hisoblang.`,
      ],
    },
    {
      type: 'example',
      kicker: '2-MISOL',
      title: "Ko'paytuvchidan parametr",
      label: 'SPR SAVOLI',
      question: r`In the polynomial $p(x)=2x^3-3x^2+kx-6$, $k$ is a constant. If $x-2$ is a factor of $p(x)$, what is the value of $k$?`,
      steps: [
        {m: r`p(2)=0`, note: r`$(x-2)$ ko'paytuvchi`},
        {m: r`16-12+2k-6=0`},
        {m: r`2k=2\Rightarrow k=1`},
      ],
      answer: r`$1$`,
      say: [
        r`Ikkinchi misol. In p of x equals two x cubed minus three x squared plus k x minus six, x minus two is a factor. What is k?`,
        r`X minus ikki ko'paytuvchi bo'lsa, p of two nolga teng.`,
        r`Ikkini qo'yamiz: o'n olti minus o'n ikki plyus ikki k minus olti teng nol.`,
        r`Ikki k teng ikki, k teng bir.`,
        r`Javob: bir.`,
      ],
    },
    {
      type: 'example',
      kicker: 'SAT MISOLI',
      title: 'Qoldiq haqida xulosa',
      question: r`For a polynomial $p$, $p(3)=5$. Which of the following must be true?`,
      choices: [r`$x-5$ is a factor of $p(x)$`, r`$x-3$ is a factor of $p(x)$`, r`The remainder when $p(x)$ is divided by $x-3$ is $5$`, r`The remainder when $p(x)$ is divided by $x-5$ is $3$`],
      steps: [
        {m: r`p(3)=\text{qoldiq}\ (x-3\ \text{ga bo'lganda})`},
        {m: r`=5`},
      ],
      answer: r`C`,
      say: [
        r`SAT misoli. For a polynomial p, p of three equals five. Which must be true?`,
        r`Qoldiq teoremasi: p of three — x minus uchga bo'lgandagi qoldiq.`,
        r`Demak, qoldiq besh.`,
        r`Javob: C. B noto'g'ri — x minus uch ko'paytuvchi bo'lishi uchun p of three nol bo'lishi kerak edi.`,
      ],
    },
    {
      type: 'example',
      kicker: 'NOLLARDAN',
      title: "Nollardan ko'phad tuzish",
      label: 'SPR SAVOLI',
      question: r`A polynomial $p$ of degree 3 has zeros $-1$, $2$, and $5$, and leading coefficient $1$. What is the constant term of $p(x)$?`,
      steps: [
        {m: r`p(x)=(x+1)(x-2)(x-5)`, note: r`ishoralar teskari`},
        {m: r`\text{ozod had}=1\cdot(-2)\cdot(-5)`, note: r`faqat sonlarni ko'paytiramiz`},
        {m: r`=10`},
      ],
      answer: r`$10$`,
      say: [
        r`Nollardan ko'phad. Uchinchi darajali ko'phadning nollari minus bir, ikki va besh, bosh koeffitsiyenti bir. Ozod hadi nimaga teng?`,
        r`Ko'phad: x plyus bir karra x minus ikki karra x minus besh. Nol minus bir bo'lsa, ko'paytuvchi x plyus bir — ishora teskari.`,
        r`Ozod had — x qatnashmagan had: qavslardagi sonlarning ko'paytmasi — bir karra minus ikki karra minus besh.`,
        r`O'n.`,
        r`Javob: o'n. Qavslarni to'liq ochish shart emas.`,
      ],
    },
    {
      type: 'table',
      kicker: 'JADVALDAN',
      title: "Jadvaldan ko'paytuvchi",
      head: ['$x$', '$-2$', '$0$', '$1$', '$3$'],
      rows: [[r`$p(x)$`, r`$0$`, r`$6$`, r`$0$`, r`$10$`]],
      banner: r`$p(-2)=0\Rightarrow(x+2)$ va $p(1)=0\Rightarrow(x-1)$ — ko'paytuvchilar; $p(0)=6$ — $y$-kesishma`,
      say: [
        r`Jadvaldan ko'paytuvchi topish. Jadvalda ko'phadning bir nechta qiymati berilgan. Which of the following must be a factor of p?`,
        r`Nollarni qidiramiz: x minus ikki va x bir da p nolga teng.`,
        r`Demak, x plyus ikki va x minus bir — ko'paytuvchilar. P of zero — olti — bu y kesishma, ko'paytuvchi emas. Eng ko'p xato: x minus ikkini ko'paytuvchi deb tanlash.`,
      ],
    },
    {
      type: 'trap',
      title: 'Nol va ko\'paytuvchi ishorasi',
      question: r`The graph of a polynomial $p$ crosses the $x$-axis at $x=-4$. Which must be a factor of $p(x)$?`,
      wrong: r`$x-4$`,
      why: r`Nol $-4$ bo'lsa, ko'paytuvchi $x-(-4)$ — ishora teskari.`,
      right: r`**$x+4$**. Tekshiruv: $x=-4$ da $x+4=0$ ✓`,
      say: [
        r`Tuzoq. The graph of p crosses the x-axis at minus four. Which must be a factor?`,
        r`Ko'p o'quvchi x minus to'rtni tanlaydi. Lekin nol minus to'rt bo'lsa, ko'paytuvchi x minus minus to'rt, ya'ni x plyus to'rt.`,
        r`Tekshirish oson: x minus to'rt bo'lsa, x plyus to'rt nolga aylanadi. Nol va ko'paytuvchida ishora doim teskari.`,
      ],
    },
    {
      type: 'example',
      kicker: 'MUSTAQIL MASHQ',
      title: "O'zingiz yeching",
      label: 'MASHQ',
      question: r`How many distinct real zeros does $p(x)=x^3-4x$ have?`,
      steps: [
        {m: r`x(x^2-4)`, note: r`$x$ ni chiqaramiz`},
        {m: r`x(x-2)(x+2)`},
        {m: r`0,\ 2,\ -2`},
      ],
      answer: r`$3$`,
      say: [
        r`Mustaqil mashq. Videoni to'xtating. P of x teng x kub minus to'rt x ko'phadning nechta har xil haqiqiy noli bor?`,
        r`X ni qavsdan chiqaramiz: x karra x kvadrat minus to'rt.`,
        r`Kvadratlar ayirmasi: x karra x minus ikki karra x plyus ikki.`,
        r`Nollar: nol, ikki va minus ikki.`,
        r`Javob: uchta. Faqat x kvadrat minus to'rtni yechib, nolni unutish — keng tarqalgan xato.`,
      ],
    },
  ],
  recap: [
    r`Nol $a$ $\iff$ ko'paytuvchi $(x-a)$ — ishora teskari`,
    r`Toq karrali — kesib o'tadi, juft — tegib qaytadi`,
    r`Qoldiq teoremasi: $x-a$ ga bo'lgandagi qoldiq $=p(a)$`,
  ],
  homework: r`platformada Advanced Math bo'yicha 20 ta aralash savol`,
  recapSay: [
    r`Xulosa.`,
    r`Nol a bo'lsa, ko'paytuvchi x minus a. Ishora doim teskari.`,
    r`Toq karrali nolda grafik x o'qini kesib o'tadi, juft karralida — tegib qaytadi.`,
    r`Qoldiq teoremasi: x minus a ga bo'lgandagi qoldiq — p of a.`,
    r`Hozir platformada Advanced Math moduli bo'yicha yigirmata aralash savolni yeching. Keyingi darsdan PSDA moduli boshlanadi: nisbat, proporsiya va birliklar.`,
    r`Ko'rishguncha!`,
  ],
};

export default lesson;
