import {meta} from '../catalog';
import type {Lesson} from '../types';

const r = String.raw;

const lesson: Lesson = {
  ...meta(23),
  topics: ['Nisbat', 'Proporsiya', 'Tezlik (rate)', 'Birlik almashtirish', 'Masshtab'],
  cover: [
    r`Assalomu alaykum! Yigirma uchinchi darsga xush kelibsiz. Bugundan Problem-Solving and Data Analysis — PSDA moduli boshlanadi. Birinchi mavzu — nisbat, proporsiya va birliklar.`,
    r`Nisbat bilan bo'lishni, proporsiya tuzishni, birlik tezlikni, birliklarni almashtirishni va masshtab masalalarini o'rganamiz.`,
  ],
  goals: [
    r`Nisbat bo'yicha miqdorlarni topish`,
    r`Proporsiya tuzib, krest ko'paytirish`,
    r`Birlik tezlik (rate) bilan ishlash`,
    r`Birliklarni zanjir usulida almashtirish`,
  ],
  goalsSay: [
    r`Darsning maqsadlari.`,
    r`Birinchi: nisbat berilganda har bir qismni topish.`,
    r`Ikkinchi: proporsiya tuzish va krest ko'paytirish bilan yechish.`,
    r`Uchinchi: "per" bilan beriladigan birlik tezlik — rate — bilan ishlash.`,
    r`To'rtinchi: birliklarni zanjir usulida xatosiz almashtirish — ayniqsa yuza va hajm birliklarida.`,
    r`PSDA domeni taxminan o'n besh foiz, va uning savollari ko'pincha eng oson ball manbai.`,
  ],
  goalsResult: r`PSDA'ning "oson ballari" — kafolatlangan`,
  slides: [
    {
      type: 'cards',
      kicker: 'ASOSLAR',
      title: 'Nisbat, tezlik, proporsiya',
      cards: [
        {title: 'Nisbat (ratio)', text: r`$3:5$ — har $3$ qismga $5$ qism; jami $8$ qism`},
        {title: 'Tezlik (rate)', text: r`"per": $60$ km/soat, $3$ dollar/kg — birlik bo'yicha miqdor`},
        {title: 'Proporsiya', text: r`$\frac ab=\frac cd\ \Rightarrow\ ad=bc$ (krest ko'paytirish)`},
        {title: 'Birlik almashtirish', text: r`$1$ ga teng kasrlarga ko'paytiring: $\frac{100\text{ sm}}{1\text{ m}}$`},
      ],
      say: [
        r`To'rtta asosiy tushuncha.`,
        r`Nisbat: uch ga besh — har uch qismga besh qism to'g'ri keladi. Jami sakkiz qism.`,
        r`Tezlik yoki rate — "per" bilan beriladigan miqdor: soatiga oltmish kilometr, kilogramiga uch dollar.`,
        r`Proporsiya — ikki nisbatning tengligi. Uni krest ko'paytirish bilan yechamiz.`,
        r`Birlik almashtirish — birga teng kasrlarga ko'paytirish: yuz santimetr bo'lingan bir metr — bu bir.`,
      ],
    },
    {
      type: 'example',
      kicker: '1-MISOL',
      title: "Nisbat bo'yicha bo'lish",
      label: 'SPR SAVOLI',
      question: r`The ratio of boys to girls in a class is $3:5$. If there are 40 students, how many girls are there?`,
      steps: [
        {m: r`3+5=8\ \text{qism}`},
        {m: r`40\div8=5\ \text{o'quvchi bir qismda}`},
        {m: r`5\cdot5=25`},
      ],
      answer: r`$25$`,
      say: [
        r`Birinchi misol. O'g'il va qiz bolalar nisbati uch ga besh. Sinfda qirq o'quvchi bo'lsa, qizlar nechta?`,
        r`Jami qismlar: uch plyus besh — sakkiz.`,
        r`Bir qism: qirq bo'lingan sakkiz — besh o'quvchi.`,
        r`Qizlar — besh qism: besh karra besh — yigirma besh.`,
        r`Javob: yigirma besh. Eng ko'p xato — qirqni beshga bo'lish. Avval jami qismni toping.`,
      ],
    },
    {
      type: 'example',
      kicker: '2-MISOL',
      title: 'Proporsiya',
      label: 'SPR SAVOLI',
      question: r`5 notebooks cost 12 dollars. At the same rate, how much do 8 notebooks cost, in dollars?`,
      steps: [
        {m: r`\frac{5}{12}=\frac{8}{x}`, note: r`bir xil tartib: daftar/narx`},
        {m: r`5x=96`},
        {m: r`x=19.2`},
      ],
      answer: r`$19.2$`,
      tip: r`Yoki birlik narx: $12\div5=2.4$ dollar, $8\cdot2.4=19.2$.`,
      say: [
        r`Ikkinchi misol. Beshta daftar o'n ikki dollar turadi. Sakkiztasi qancha turadi?`,
        r`Proporsiya: besh bo'lingan o'n ikki teng sakkiz bo'lingan x. Ikkala kasrda tartib bir xil — daftar bo'lingan narx.`,
        r`Krest ko'paytiramiz: besh x teng to'qson olti.`,
        r`X teng o'n to'qqiz butun ikki.`,
        r`Javob: o'n to'qqiz butun ikki dollar.`,
        r`Muqobil usul — birlik narx: bitta daftar o'n ikki bo'lingan besh — ikki butun to'rt dollar, sakkiztasi — o'n to'qqiz butun ikki. Ikkala usul ham bir xil javob beradi.`,
      ],
    },
    {
      type: 'example',
      kicker: '3-MISOL',
      title: 'Birlik tezlik',
      label: 'SPR SAVOLI',
      question: r`A car travels 150 miles on 6 gallons of gas. At this rate, how many gallons are needed to travel 225 miles?`,
      steps: [
        {m: r`150\div6=25\ \text{mil/gallon}`, note: r`birlik tezlik`},
        {m: r`225\div25=9`},
      ],
      answer: r`$9$ gallon`,
      say: [
        r`Uchinchi misol. Avtomobil olti gallon benzinga bir yuz ellik mil yuradi. Ikki yuz yigirma besh mil uchun necha gallon kerak?`,
        r`Birlik tezlik: bir yuz ellik bo'lingan olti — gallonga yigirma besh mil.`,
        r`Ikki yuz yigirma besh bo'lingan yigirma besh — to'qqiz gallon.`,
        r`Javob: to'qqiz gallon.`,
      ],
    },
    {
      type: 'formula',
      kicker: 'ZANJIR USULI',
      title: 'Birliklarni almashtirish',
      formulas: [
        {label: 'km/soat → m/s', tex: r`72\,\tfrac{\text{km}}{\text{h}}\cdot\tfrac{1000\text{ m}}{1\text{ km}}\cdot\tfrac{1\text{ h}}{3600\text{ s}}=20\,\tfrac{\text{m}}{\text{s}}`},
        {label: 'Yuza', tex: r`1\text{ m}^2=100\cdot100=10\,000\text{ sm}^2`, note: r`kvadrat — ikki marta!`},
        {label: 'Hajm', tex: r`1\text{ m}^3=100^3=1\,000\,000\text{ sm}^3`, note: r`kub — uch marta`},
      ],
      banner: r`Keraksiz birlik qisqarishi uchun kasrni "teskari" yozing: km pastda bo'lsa, km tepada`,
      say: [
        r`Birliklarni almashtirishning zanjir usuli.`,
        r`Soatiga yetmish ikki kilometrni sekundiga metrga o'tkazamiz. Ming metr bo'lingan bir kilometrga ko'paytiramiz — kilometr qisqaradi. Bir soat bo'lingan uch ming olti yuz sekundga ko'paytiramiz — soat qisqaradi. Natija: sekundiga yigirma metr.`,
        r`Yuza birliklarida ehtiyot bo'ling: bir kvadrat metr — yuz karra yuz, o'n ming kvadrat santimetr. Kvadrat — ikki marta ko'paytiramiz.`,
        r`Hajmda — uch marta: bir kub metr — million kub santimetr.`,
        r`Qoida: keraksiz birlik qisqarishi uchun kasrni shunday yozingki, u surat va maxrajda qarama-qarshi tursin.`,
      ],
    },
    {
      type: 'trap',
      title: 'Yuza birligini almashtirish',
      question: r`A rectangle measures 2 m by 3 m. What is its area in square centimeters?`,
      wrong: r`$600$`,
      why: r`$6\text{ m}^2$ ni $100$ ga ko'paytirilgan — lekin $1\text{ m}^2=10\,000\text{ sm}^2$.`,
      right: r`Avval tomonlarni o'tkazing: $200\cdot300=$ **60 000 sm²**. Yoki $6\cdot10\,000$.`,
      say: [
        r`Tuzoq. A rectangle measures two meters by three meters. What is its area in square centimeters?`,
        r`O'quvchi yuzani olti kvadrat metr deb topadi va yuzga ko'paytiradi — olti yuz. Lekin bir kvadrat metr — o'n ming kvadrat santimetr.`,
        r`Eng ishonchli yo'l: avval tomonlarni santimetrga o'tkazing — ikki yuz va uch yuz, ko'paytmasi oltmish ming. Yuza va hajmda doim shunday qiling.`,
      ],
    },
    {
      type: 'example',
      kicker: 'ZICHLIK',
      title: 'Zichlik — ham tezlik',
      label: 'SPR SAVOLI',
      question: r`A metal has a density of 2.5 grams per cubic centimeter. What is the mass, in grams, of a 40 cm³ piece of this metal?`,
      steps: [
        {m: r`\text{massa}=\text{zichlik}\cdot\text{hajm}`},
        {m: r`2.5\cdot40=100`},
      ],
      answer: r`$100$ g`,
      tip: r`Birliklarga qarang: $\frac{\text{g}}{\text{sm}^3}\cdot\text{sm}^3=\text{g}$ — birliklar formulani o'zi aytadi.`,
      say: [
        r`Zichlik ham bir turdagi tezlik. Metallning zichligi kub santimetrga ikki butun besh gramm. Qirq kub santimetrlik bo'lagining massasi qancha?`,
        r`Massa teng zichlik karra hajm.`,
        r`Ikki butun besh karra qirq — yuz gramm.`,
        r`Javob: yuz gramm.`,
        r`Formulani unutgan bo'lsangiz, birliklarga qarang: gramm bo'lingan kub santimetr karra kub santimetr — gramm. Birliklar formulani o'zi aytib beradi.`,
      ],
    },
    {
      type: 'example',
      kicker: 'SAT MISOLI',
      title: 'Retsept proporsiyasi',
      question: r`A recipe uses 3 cups of flour to make 24 cookies. How many cups of flour are needed to make 40 cookies?`,
      choices: [r`$4$`, r`$4.5$`, r`$5$`, r`$6$`],
      steps: [
        {m: r`\frac{3}{24}=\frac{x}{40}`},
        {m: r`24x=120`},
        {m: r`x=5`},
      ],
      answer: r`C`,
      say: [
        r`SAT misoli. Retseptda yigirma to'rtta pechenye uchun uch stakan un ishlatiladi. Qirqta pechenye uchun necha stakan kerak?`,
        r`Proporsiya: uch bo'lingan yigirma to'rt teng x bo'lingan qirq.`,
        r`Yigirma to'rt x teng bir yuz yigirma.`,
        r`X teng besh.`,
        r`Javob: C.`,
      ],
    },
    {
      type: 'example',
      kicker: 'MASSHTAB',
      title: 'Xarita masshtabi',
      label: 'SPR SAVOLI',
      question: r`On a map, 1 inch represents 25 miles. Two cities are 3.4 inches apart on the map. What is the actual distance, in miles?`,
      steps: [
        {m: r`3.4\cdot25`},
        {m: r`=85`},
      ],
      answer: r`$85$ mil`,
      say: [
        r`Masshtab. Xaritada bir dyuym yigirma besh milga teng. Ikki shahar xaritada uch butun to'rt dyuym uzoqlikda. Haqiqiy masofa qancha?`,
        r`Uch butun to'rt karra yigirma besh.`,
        r`Sakson besh mil.`,
        r`Javob: sakson besh mil.`,
      ],
    },
    {
      type: 'example',
      kicker: 'TEZLIK',
      title: 'm/s dan km/soatga',
      label: 'SPR SAVOLI',
      question: r`A runner covers 400 meters in 50 seconds. What is the runner's average speed in kilometers per hour?`,
      steps: [
        {m: r`400\div50=8\ \tfrac{\text{m}}{\text{s}}`},
        {m: r`8\cdot\tfrac{3600}{1000}=8\cdot3.6`, note: r`m/s $\to$ km/soat: $\times3.6$`},
        {m: r`=28.8`},
      ],
      answer: r`$28.8$`,
      say: [
        r`Tezlik masalasi. Yuguruvchi to'rt yuz metrni ellik sekundda bosib o'tdi. Uning o'rtacha tezligi soatiga necha kilometr?`,
        r`Avval sekundiga metr: to'rt yuz bo'lingan ellik — sakkiz.`,
        r`Soatiga kilometrga o'tkazish: uch ming olti yuzga ko'paytirib, mingga bo'lamiz — ya'ni uch butun oltiga ko'paytiramiz.`,
        r`Yigirma sakkiz butun sakkiz.`,
        r`Javob: yigirma sakkiz butun sakkiz. Foydali yorliq: sekundiga metrdan soatiga kilometrga — uch butun oltiga ko'paytiring, teskarisiga — bo'ling.`,
      ],
    },
    {
      type: 'example',
      kicker: 'MUSTAQIL MASHQ',
      title: "O'zingiz yeching",
      label: 'MASHQ',
      question: r`If $a:b=2:3$ and $b:c=4:5$, what is the value of $\dfrac{a}{c}$?`,
      steps: [
        {m: r`a:b=8:12,\quad b:c=12:15`, note: r`$b$ ni umumiy qilamiz`},
        {m: r`a:c=8:15`},
      ],
      answer: r`$8/15$`,
      tip: r`Yoki: $\frac ac=\frac ab\cdot\frac bc=\frac23\cdot\frac45=\frac{8}{15}$.`,
      say: [
        r`Mustaqil mashq. Videoni to'xtating. A ga b — ikki ga uch, b ga c — to'rt ga besh. A bo'lingan c nimaga teng?`,
        r`B ni umumiy qilamiz: birinchi nisbatni to'rtga, ikkinchisini uchga ko'paytiramiz. A ga b — sakkiz ga o'n ikki, b ga c — o'n ikki ga o'n besh.`,
        r`Demak, a ga c — sakkiz ga o'n besh.`,
        r`Javob: sakkiz o'n beshdan.`,
        r`Qisqa yo'l: a bo'lingan b ni b bo'lingan c ga ko'paytiring — ikki uchdan karra to'rt beshdan — sakkiz o'n beshdan.`,
      ],
    },
    {
      type: 'example',
      kicker: 'SAT MISOLI',
      title: 'Tezlik va vaqt birliklari',
      label: 'SPR SAVOLI',
      question: r`A printer prints 45 pages per minute. How many pages does it print in 2.5 hours?`,
      steps: [
        {m: r`2.5\ \text{h}=2.5\cdot60=150\ \text{min}`, note: r`avval birlikni moslaymiz`},
        {m: r`45\cdot150=6750`},
      ],
      answer: r`$6750$`,
      say: [
        r`SAT misoli. Printer daqiqasiga qirq besh sahifa chop etadi. Ikki yarim soatda necha sahifa chop etadi?`,
        r`Tezlik daqiqada, vaqt soatda berilgan — avval birliklarni moslaymiz: ikki yarim soat — bir yuz ellik daqiqa.`,
        r`Qirq besh karra bir yuz ellik — olti ming yetti yuz ellik.`,
        r`Javob: olti ming yetti yuz ellik. Birliklarni moslashtirmasdan qirq beshni ikki butun beshga ko'paytirish — eng keng tarqalgan xato.`,
      ],
    },
    {
      type: 'example',
      kicker: 'TESKARI PROPORSIYA',
      title: "Ishchilar va kunlar",
      label: 'SPR SAVOLI',
      question: r`6 workers can finish a job in 10 days. Working at the same rate, how many days would 15 workers need to finish the same job?`,
      steps: [
        {m: r`6\cdot10=60\ \text{ishchi-kun}`, note: r`umumiy ish hajmi`},
        {m: r`60\div15=4`},
      ],
      answer: r`$4$ kun`,
      tip: r`Ishchilar ko'paysa — kunlar **kamayadi**: bu teskari proporsiya, krest ko'paytirish noto'g'ri natija beradi.`,
      say: [
        r`Teskari proporsiya. Olti ishchi ishni o'n kunda tugatadi. O'n besh ishchi necha kunda tugatadi?`,
        r`Umumiy ish hajmini hisoblaymiz: olti karra o'n — oltmish ishchi-kun.`,
        r`O'n besh ishchiga bo'lamiz: to'rt kun.`,
        r`Javob: to'rt kun.`,
        r`Bu teskari proporsiya: ishchilar ko'paysa, kunlar kamayadi. Oddiy krest ko'paytirish yigirma besh kun beradi — mantiqqa zid javob.`,
      ],
    },
  ],
  recap: [
    r`Nisbat: avval jami qismlar soni`,
    r`Proporsiyada tartib bir xil; rate — "per"`,
    r`Yuza — $\times100^2$, hajm — $\times100^3$`,
  ],
  homework: r`platformada nisbat va birliklar bo'yicha 15 ta savol`,
  recapSay: [
    r`Xulosa.`,
    r`Nisbat masalasida avval jami qismlar sonini toping.`,
    r`Proporsiyada ikkala kasrda tartib bir xil bo'lsin. Rate — bir birlikka to'g'ri keladigan miqdor.`,
    r`Yuza birliklarida kvadrat, hajmda kub: bir kvadrat metr — o'n ming kvadrat santimetr.`,
    r`Hozir platformada nisbat va birliklar bo'yicha o'n beshta savolni yeching. Keyingi darsda foizlarni o'rganamiz.`,
    r`Ko'rishguncha!`,
  ],
};

export default lesson;
