import {meta} from '../catalog';
import type {Lesson} from '../types';

const r = String.raw;

const lesson: Lesson = {
  ...meta(24),
  topics: ['Qism va butun', 'Foiz o\'zgarishi', "Ko'paytuvchi usuli", 'Teskari foiz', 'Ketma-ket foizlar'],
  cover: [
    r`Assalomu alaykum! Yigirma to'rtinchi darsga xush kelibsiz. Bugungi mavzu — foizlar.`,
    r`Foizning uch asosiy savolini, foiz o'zgarishini, ko'paytuvchi usulini, chegirma va soliqni, teskari foizni va ketma-ket foizlardagi tuzoqni o'rganamiz.`,
  ],
  goals: [
    r`"Qism = foiz × butun" formulasini erkin qo'llash`,
    r`Foiz o'zgarishini hisoblash`,
    r`Ko'paytuvchi usuli: $\times1.08$, $\times0.75$`,
    r`Teskari va ketma-ket foiz savollari`,
  ],
  goalsSay: [
    r`Darsning maqsadlari.`,
    r`Birinchi: qism teng foiz karra butun formulasini uch xil savolda qo'llash.`,
    r`Ikkinchi: foiz o'zgarishini — necha foizga oshdi yoki kamaydi — hisoblash.`,
    r`Uchinchi: ko'paytuvchi usuli — sakkiz foiz qo'shish bir butun nol sakkizga ko'paytirish ekanini tushunish.`,
    r`To'rtinchi: chegirmadan oldingi narxni topish va ketma-ket foizlardagi tuzoqlardan qochish.`,
    r`Foizlar har bir SAT testida bir necha marta uchraydi.`,
  ],
  goalsResult: r`foiz savollarida tez va aniq hisob`,
  slides: [
    {
      type: 'formula',
      kicker: 'FORMULALAR',
      title: 'Foizning asosiy formulalari',
      formulas: [
        {label: 'Qism', tex: r`\text{qism}=\frac{p}{100}\cdot\text{butun}`},
        {label: "Foiz o'zgarishi", tex: r`\frac{\text{yangi}-\text{eski}}{\text{eski}}\cdot100\%`, note: r`maxrajda doim **eski** qiymat`},
        {label: "Ko'paytuvchi", tex: r`+p\%:\ \times\left(1+\tfrac{p}{100}\right),\quad -p\%:\ \times\left(1-\tfrac{p}{100}\right)`},
      ],
      say: [
        r`Uchta asosiy formula.`,
        r`Qism teng foiz bo'lingan yuz karra butun. Masalan, sakson ning o'ttiz besh foizi — nol butun o'ttiz besh karra sakson.`,
        r`Foiz o'zgarishi: yangi minus eski, bo'lingan eski, karra yuz foiz. Maxrajda doim eski, boshlang'ich qiymat turadi.`,
        r`Ko'paytuvchi usuli: p foiz oshirish — bir plyus p yuzdan ga ko'paytirish, p foiz kamaytirish — bir minus p yuzdan ga ko'paytirish. Bu usul eng tez va xatosiz.`,
      ],
    },
    {
      type: 'example',
      kicker: '1-MISOL',
      title: 'Ikki asosiy savol',
      label: 'MISOL',
      question: r`(a) What is 35% of 80? (b) 18 is what percent of 72?`,
      steps: [
        {m: r`(a)\ 0.35\cdot80=28`},
        {m: r`(b)\ \frac{18}{72}=0.25`, note: r`qism / butun`},
        {m: r`0.25=25\%`},
      ],
      answer: r`$28$; $25\%$`,
      say: [
        r`Birinchi misol, ikki qismli. Birinchi: sakson ning o'ttiz besh foizi qancha? Ikkinchi: o'n sakkiz yetmish ikkining necha foizi?`,
        r`Birinchisi: nol butun o'ttiz besh karra sakson — yigirma sakkiz.`,
        r`Ikkinchisi: qism bo'lingan butun — o'n sakkiz bo'lingan yetmish ikki — nol butun yigirma besh.`,
        r`Yuzga ko'paytirsak — yigirma besh foiz.`,
        r`Javoblar: yigirma sakkiz va yigirma besh foiz. Ingliz tilida "of" — ko'paytirish, "is" — tenglik belgisi. Bu savolni tenglamaga aylantirishni osonlashtiradi.`,
      ],
    },
    {
      type: 'example',
      kicker: '2-MISOL',
      title: "Foiz o'zgarishi",
      label: 'SPR SAVOLI',
      question: r`The price of a book increased from 40 dollars to 52 dollars. By what percent did the price increase?`,
      steps: [
        {m: r`\frac{52-40}{40}=\frac{12}{40}`, note: r`maxrajda — eski narx`},
        {m: r`=0.3=30\%`},
      ],
      answer: r`$30$`,
      tip: r`$\frac{12}{52}$ — xato (yangi narxga bo'lingan). SPR'da faqat **30** kiriting, % siz.`,
      say: [
        r`Ikkinchi misol. Kitob narxi qirq dollardan ellik ikki dollarga oshdi. Necha foizga oshgan?`,
        r`O'zgarish o'n ikki dollar. Uni eski narxga — qirqqa bo'lamiz.`,
        r`Nol butun uch — o'ttiz foiz.`,
        r`Javob: o'ttiz.`,
        r`SPR'da foiz belgisisiz, faqat o'ttiz deb kiriting. O'n ikkini yangi narxga — ellik ikkiga — bo'lish keng tarqalgan xato.`,
      ],
    },
    {
      type: 'example',
      kicker: '3-MISOL',
      title: 'Chegirma va soliq',
      label: 'SPR SAVOLI',
      question: r`A jacket costs 80 dollars. It is on sale for 25% off, and then an 8% sales tax is applied to the sale price. What is the final cost, in dollars?`,
      steps: [
        {m: r`80\cdot0.75=60`, note: r`$25\%$ chegirma — $\times0.75$`},
        {m: r`60\cdot1.08=64.8`, note: r`$8\%$ soliq — $\times1.08$`},
      ],
      answer: r`$64.8$`,
      tip: r`Bir qatorda: $80\cdot0.75\cdot1.08=64.8$. Ko'paytuvchilar tartibi natijaga ta'sir qilmaydi.`,
      say: [
        r`Uchinchi misol. Kurtka sakson dollar. Unga yigirma besh foiz chegirma, keyin chegirmali narxga sakkiz foiz soliq qo'shiladi. Yakuniy narx qancha?`,
        r`Yigirma besh foiz chegirma — nol butun yetmish beshga ko'paytirish: oltmish dollar.`,
        r`Sakkiz foiz soliq — bir butun nol sakkizga ko'paytirish: oltmish to'rt butun sakkiz.`,
        r`Javob: oltmish to'rt butun sakkiz dollar.`,
        r`Bir qatorda yozish mumkin: sakson karra nol butun yetmish besh karra bir butun nol sakkiz. Ko'paytuvchilar tartibi muhim emas.`,
      ],
    },
    {
      type: 'trap',
      title: 'Ketma-ket foizlar',
      question: r`A price is increased by 20% and then the new price is decreased by 20%. How does the final price compare to the original?`,
      wrong: r`O'zgarmaydi`,
      why: r`$+20\%$ va $-20\%$ har xil **asosdan** olinadi — ular bir-birini yo'q qilmaydi.`,
      right: r`$1.2\cdot0.8=0.96$ — narx **4% ga kamaydi**. Masalan: $100\to120\to96$.`,
      say: [
        r`Tuzoq. Narx avval yigirma foizga oshirildi, keyin yangi narx yigirma foizga kamaytirildi. Yakuniy narx dastlabkisiga nisbatan qanday?`,
        r`Ko'pchilik "o'zgarmaydi" deydi. Lekin yigirma foizlar har xil asosdan olinadi: ikkinchisi kattaroq narxdan.`,
        r`Ko'paytuvchilar: bir butun ikki karra nol butun sakkiz — nol butun to'qson olti. Narx to'rt foizga kamaygan. Masalan: yuz — bir yuz yigirma — to'qson olti.`,
      ],
    },
    {
      type: 'example',
      kicker: 'TESKARI FOIZ',
      title: 'Asl narxni topish',
      label: 'SPR SAVOLI',
      question: r`After a 15% discount, a pair of shoes costs 68 dollars. What was the original price, in dollars?`,
      steps: [
        {m: r`0.85\cdot x=68`, note: r`chegirmali narx = $85\%$`},
        {m: r`x=\frac{68}{0.85}=80`},
      ],
      answer: r`$80$`,
      tip: r`Xato yo'l: $68\cdot1.15=78.2$ — foiz yangi narxdan emas, **asl** narxdan olingan edi.`,
      say: [
        r`Teskari foiz. O'n besh foiz chegirmadan keyin poyabzal oltmish sakkiz dollar turadi. Asl narx qancha edi?`,
        r`Chegirmali narx — asl narxning sakson besh foizi: nol butun sakson besh karra x teng oltmish sakkiz.`,
        r`X teng oltmish sakkiz bo'lingan nol butun sakson besh — sakson.`,
        r`Javob: sakson dollar.`,
        r`Xato yo'l — oltmish sakkizga o'n besh foiz qo'shish: yetmish sakkiz butun ikki chiqadi. Lekin chegirma asl narxdan olingan, shuning uchun bo'lish kerak.`,
      ],
    },
    {
      type: 'example',
      kicker: 'SAT MISOLI',
      title: "Foizdan foizga",
      question: r`If 30% of $a$ is 45, what is 60% of $a$?`,
      choices: [r`$15$`, r`$75$`, r`$90$`, r`$150$`],
      steps: [
        {m: r`60\%=2\cdot30\%`},
        {m: r`2\cdot45=90`},
      ],
      answer: r`C`,
      tip: r`$a=150$ ni topish shart emas — D variant aynan shu "oraliq javob".`,
      say: [
        r`SAT misoli. If thirty percent of a is forty five, what is sixty percent of a?`,
        r`Oltmish foiz — o'ttiz foizning ikki baravari.`,
        r`Demak, ikki karra qirq besh — to'qson.`,
        r`Javob: C.`,
        r`A ni topish shart emas edi. D variant — bir yuz ellik — aynan a ning o'zi, to'xtab qolganlar uchun tuzoq.`,
      ],
    },
    {
      type: 'compare',
      kicker: 'FARQ',
      title: 'Foiz va foiz punkti',
      cards: [
        {title: 'Foiz punkti', rule: r`Foizlar **ayirmasi**`, example: r`$20\%\to25\%$: $+5$ punkt`},
        {title: 'Nisbiy foiz', rule: r`O'zgarish / eski qiymat`, example: r`$\frac{25-20}{20}=25\%$ ga oshdi`},
      ],
      banner: r`Savolda "percentage points" bo'lsa — ayiring; "percent increase" bo'lsa — eskiga bo'ling`,
      say: [
        r`Muhim farq: foiz va foiz punkti.`,
        r`Ishsizlik darajasi yigirma foizdan yigirma besh foizga oshdi deylik. Foiz punktlarda — besh punktga oshdi, oddiy ayirma.`,
        r`Nisbiy o'sish esa — besh bo'lingan yigirma — yigirma besh foiz.`,
        r`Savolda "percentage points" bo'lsa — ayiring, "percent increase" bo'lsa — eski qiymatga bo'ling.`,
      ],
    },
    {
      type: 'example',
      kicker: 'SAT MISOLI',
      title: "Foizli o'sish ifodasi",
      question: r`The price of an item is $p$ dollars. Which expression represents the price after a 12% increase?`,
      choices: [r`$0.12p$`, r`$1.12p$`, r`$p+12$`, r`$0.88p$`],
      steps: [
        {m: r`p+0.12p`},
        {m: r`=1.12p`},
      ],
      answer: r`B`,
      say: [
        r`SAT misoli. Which expression represents the price after a twelve percent increase of p?`,
        r`Yangi narx — eski narx plyus uning o'n ikki foizi: p plyus nol butun o'n ikki p.`,
        r`Bir butun o'n ikki p.`,
        r`Javob: B. A — faqat o'sish miqdori, C — o'n ikki dollar qo'shish, D — kamayish.`,
      ],
    },
    {
      type: 'example',
      kicker: 'MUSTAQIL MASHQ',
      title: "O'zingiz yeching",
      label: 'MASHQ',
      question: r`When a number is increased by 25%, the result is 60. What is the number?`,
      steps: [
        {m: r`1.25x=60`},
        {m: r`x=48`},
      ],
      answer: r`$48$`,
      say: [
        r`Mustaqil mashq. Videoni to'xtating. Son yigirma besh foizga oshirilganda oltmish chiqadi. Son nechaga teng?`,
        r`Bir butun yigirma besh karra x teng oltmish.`,
        r`X teng qirq sakkiz.`,
        r`Javob: qirq sakkiz. Tekshiruv: qirq sakkizning chorak qismi — o'n ikki, qirq sakkiz plyus o'n ikki — oltmish.`,
      ],
    },
    {
      type: 'example',
      kicker: 'FOIZDAN FOIZ',
      title: "Guruh ichidagi foiz",
      label: 'SPR SAVOLI',
      question: r`In a school, 40% of the students are boys, and 25% of the boys play chess. What percent of all students are boys who play chess?`,
      steps: [
        {m: r`0.40\cdot0.25=0.10`, note: r`foizdan foiz — ko'paytiramiz`},
        {m: r`=10\%`},
      ],
      answer: r`$10$`,
      tip: r`Qo'shish ($40+25$) yoki ayirish emas — "of" ko'paytirishni bildiradi.`,
      say: [
        r`Foizdan foiz. Maktabda o'quvchilarning qirq foizi o'g'il bolalar, ularning yigirma besh foizi shaxmat o'ynaydi. Barcha o'quvchilarning necha foizi shaxmat o'ynaydigan o'g'il bolalar?`,
        r`Foizdan foiz olinganda ko'paytiramiz: nol butun qirq karra nol butun yigirma besh — nol butun bir.`,
        r`Ya'ni o'n foiz.`,
        r`Javob: o'n.`,
        r`Tekshirish uchun yuz o'quvchi deb oling: qirqta o'g'il bola, ularning chorak qismi — o'nta. Yuzdan o'n — o'n foiz.`,
      ],
    },
    {
      type: 'example',
      kicker: 'NARX',
      title: 'Ustama va chegirma',
      label: 'SPR SAVOLI',
      question: r`A store buys a lamp for 50 dollars, marks the price up by 40%, and later sells it at a 10% discount off the marked price. What is the selling price, in dollars?`,
      steps: [
        {m: r`50\cdot1.4=70`, note: r`ustama $40\%$`},
        {m: r`70\cdot0.9=63`, note: r`chegirma $10\%$`},
      ],
      answer: r`$63$`,
      say: [
        r`Narx masalasi. Do'kon chiroqni ellik dollarga sotib olib, narxni qirq foizga oshiradi, keyin yangi narxdan o'n foiz chegirma bilan sotadi. Sotish narxi qancha?`,
        r`Qirq foiz ustama — bir butun to'rtga ko'paytirish: yetmish dollar.`,
        r`O'n foiz chegirma — nol butun to'qqizga ko'paytirish: oltmish uch dollar.`,
        r`Javob: oltmish uch. Ketma-ket foizlarda ko'paytuvchilarni ketma-ket ko'paytiring — foizlarni qo'shib-ayirmang.`,
      ],
    },
    {
      type: 'example',
      kicker: 'SAT MISOLI',
      title: 'Teskari nisbat foizda',
      question: r`If $a$ is 150% of $b$, then $b$ is what percent of $a$?`,
      choices: [r`$50\%$`, r`$66\tfrac23\%$`, r`$75\%$`, r`$150\%$`],
      steps: [
        {m: r`a=1.5b\Rightarrow\frac ba=\frac{1}{1.5}`},
        {m: r`=\frac23\approx66.7\%`},
      ],
      answer: r`B`,
      tip: r`Son bilan tekshiring: $b=100$, $a=150$; $\frac{100}{150}=66\frac23\%$.`,
      say: [
        r`SAT misoli. If a is one hundred fifty percent of b, then b is what percent of a?`,
        r`A teng bir butun besh b, demak b bo'lingan a — bir bo'lingan bir butun besh.`,
        r`Ikki uchdan — taxminan oltmish olti butun yetti foiz.`,
        r`Javob: B.`,
        r`Son bilan tekshirish eng oson: b yuz bo'lsa, a bir yuz ellik, yuz bo'lingan bir yuz ellik — oltmish olti va uchdan ikki foiz. A variant — ellik foiz — "ellik foiz ko'p bo'lsa, ellik foiz kam" degan xato fikr.`,
      ],
    },
  ],
  recap: [
    r`Qism $=\frac{p}{100}\cdot$ butun; o'zgarish — **eski** qiymatga bo'ling`,
    r`$+p\%$: $\times(1+p)$, $-p\%$: $\times(1-p)$; teskari — bo'ling`,
    r`$+20\%$, $-20\%$ $\neq$ o'zgarishsiz: $\times0.96$`,
  ],
  homework: r`platformada foizlar bo'yicha 15 ta savol`,
  recapSay: [
    r`Xulosa.`,
    r`Qism teng foiz karra butun. Foiz o'zgarishida doim eski qiymatga bo'ling.`,
    r`Ko'paytuvchi usuli: oshirish — bir plyus p, kamaytirish — bir minus p. Asl qiymatni topish uchun — bo'ling.`,
    r`Ketma-ket foizlar bir-birini yo'q qilmaydi: yigirma foiz oshirib, yigirma foiz kamaytirish — to'rt foiz kamayish.`,
    r`Hozir platformada foizlar bo'yicha o'n beshta savolni yeching. Keyingi darsda statistika: o'rtacha, median va tarqoqlikni o'rganamiz.`,
    r`Ko'rishguncha!`,
  ],
};

export default lesson;
