import {meta} from '../catalog';
import type {Lesson} from '../types';

const r = String.raw;

const lesson: Lesson = {
  ...meta(25),
  topics: ["O'rtacha", 'Median', 'Moda va oraliq', 'Chetki qiymat', 'Standart chetlanish'],
  cover: [
    r`Assalomu alaykum! Yigirma beshinchi darsga xush kelibsiz. Bugungi mavzu — statistika: o'rtacha, median va tarqoqlik.`,
    r`O'rtacha qiymat, median, moda va oraliqni hisoblashni, chetki qiymatning ta'sirini, chastota jadvallarini va standart chetlanishni tushunishni o'rganamiz.`,
  ],
  goals: [
    r`O'rtacha, median, moda va oraliqni hisoblash`,
    r`Chetki qiymatning o'rtacha va medianaga ta'sirini bilish`,
    r`Chastota jadvalidan median va o'rtachani topish`,
    r`Standart chetlanishni hisob-kitobsiz solishtirish`,
  ],
  goalsSay: [
    r`Darsning maqsadlari.`,
    r`Birinchi: to'rtta asosiy statistik ko'rsatkichni hisoblash.`,
    r`Ikkinchi: chetki, juda katta yoki juda kichik qiymat o'rtacha va medianaga qanday ta'sir qilishini bilish.`,
    r`Uchinchi: chastota jadvalidan median va o'rtachani to'g'ri topish.`,
    r`To'rtinchi: standart chetlanishni hisoblamasdan, ma'lumotlar tarqoqligiga qarab solishtirish.`,
    r`SAT statistikada murakkab formulalarni emas, tushunchani tekshiradi.`,
  ],
  goalsResult: r`statistika savollarini hisob-kitobsiz tushunish`,
  slides: [
    {
      type: 'formula',
      kicker: "KO'RSATKICHLAR",
      title: "Markaz va tarqoqlik o'lchovlari",
      formulas: [
        {label: "O'rtacha (mean)", tex: r`\bar x=\dfrac{\text{yig'indi}}{n}`},
        {label: 'Median', tex: r`\text{tartiblangan qatorning o'rtasi}`, note: r`juft $n$ da — ikki o'rtadagining o'rtachasi`},
        {label: 'Moda / oraliq', tex: r`\text{eng ko'p uchragan}\ \ /\ \ \max-\min`},
      ],
      say: [
        r`Asosiy ko'rsatkichlar.`,
        r`O'rtacha qiymat, inglizcha mean — barcha qiymatlar yig'indisi bo'lingan ularning soniga.`,
        r`Median — qiymatlar o'sish tartibida joylashtirilganda o'rtada turgan son. Qiymatlar soni juft bo'lsa — ikki o'rtadagi sonning o'rtachasi.`,
        r`Moda — eng ko'p uchragan qiymat. Oraliq, inglizcha range — eng katta minus eng kichik qiymat.`,
      ],
    },
    {
      type: 'example',
      kicker: '1-MISOL',
      title: "To'rt ko'rsatkichni hisoblash",
      label: 'MISOL',
      question: r`For the data set $3,\ 7,\ 7,\ 9,\ 14$, find the mean, median, mode, and range.`,
      steps: [
        {m: r`\bar x=\frac{40}{5}=8`},
        {m: r`\text{median}=7`, note: r`5 ta son — 3-o'rindagisi`},
        {m: r`\text{moda}=7,\quad\text{range}=14-3=11`},
      ],
      answer: r`$8,\ 7,\ 7,\ 11$`,
      say: [
        r`Birinchi misol: uch, yetti, yetti, to'qqiz, o'n to'rt.`,
        r`Yig'indi qirq, beshta son: o'rtacha sakkiz.`,
        r`Sonlar allaqachon tartiblangan. Beshta son — o'rtadagisi uchinchi: yetti.`,
        r`Moda — eng ko'p uchragan: yetti. Oraliq: o'n to'rt minus uch — o'n bir.`,
        r`Javob: o'rtacha sakkiz, median yetti, moda yetti, oraliq o'n bir.`,
      ],
    },
    {
      type: 'example',
      kicker: '2-MISOL',
      title: 'Juft sonli qator mediani',
      label: 'SPR SAVOLI',
      question: r`What is the median of the data set $15,\ 4,\ 10,\ 8$?`,
      steps: [
        {m: r`4,\ 8,\ 10,\ 15`, note: r`avval **tartiblaymiz**!`},
        {m: r`\frac{8+10}{2}=9`, note: r`ikki o'rtadagining o'rtachasi`},
      ],
      answer: r`$9$`,
      tip: r`Tartiblamasdan "o'rtadagi" $4$ va $10$ ni olish — eng ko'p xato.`,
      say: [
        r`Ikkinchi misol. What is the median of fifteen, four, ten, eight?`,
        r`Avval albatta tartiblaymiz: to'rt, sakkiz, o'n, o'n besh.`,
        r`To'rtta son — o'rtada ikkitasi: sakkiz va o'n. Ularning o'rtachasi — to'qqiz.`,
        r`Javob: to'qqiz.`,
        r`Eng ko'p xato — sonlarni tartiblamasdan, berilgan qatorning o'rtasidan olish.`,
      ],
    },
    {
      type: 'cards',
      kicker: 'CHETKI QIYMAT',
      title: 'Chetki qiymat (outlier) ta\'siri',
      cards: [
        {title: "O'rtacha — sezgir", text: r`Chetki qiymat o'rtachani o'ziga qarab **tortadi**`},
        {title: 'Median — barqaror', text: r`Median deyarli o'zgarmaydi`},
        {title: 'Katta outlier', text: r`$\bar x>\text{median}$ (o'ngga og'gan taqsimot)`},
        {title: 'Kichik outlier', text: r`$\bar x<\text{median}$ (chapga og'gan)`},
      ],
      say: [
        r`Chetki qiymat — boshqalardan juda uzoqda turgan son. Uning ta'siri SAT'da tez-tez so'raladi.`,
        r`O'rtacha qiymat chetki qiymatga juda sezgir: uni o'ziga qarab tortadi.`,
        r`Median esa barqaror — u faqat tartibga bog'liq, shuning uchun deyarli o'zgarmaydi.`,
        r`Juda katta chetki qiymat bo'lsa, o'rtacha mediandan katta bo'ladi.`,
        r`Juda kichik chetki qiymat bo'lsa — o'rtacha mediandan kichik.`,
      ],
    },
    {
      type: 'example',
      kicker: 'SAT MISOLI',
      title: "O'rtacha va median solishtirish",
      question: r`The data set $10,\ 12,\ 14,\ 16,\ 100$ is given. Which statement is true?`,
      choices: [r`Mean < median`, r`Mean = median`, r`Mean > median`, r`Cannot be determined`],
      steps: [
        {m: r`\text{median}=14`},
        {m: r`\bar x=\frac{152}{5}=30.4`},
        {m: r`30.4>14`, note: r`$100$ — chetki qiymat`},
      ],
      answer: r`C`,
      say: [
        r`SAT misoli. Ma'lumotlar: o'n, o'n ikki, o'n to'rt, o'n olti, yuz. Which statement is true?`,
        r`Median — o'rtadagi son: o'n to'rt.`,
        r`O'rtacha: yig'indi bir yuz ellik ikki, beshga bo'lsak — o'ttiz butun to'rt.`,
        r`O'rtacha mediandan ancha katta, chunki yuz — chetki qiymat.`,
        r`Javob: C. Hisoblamasdan ham bilish mumkin edi: katta outlier o'rtachani yuqoriga tortadi.`,
      ],
    },
    {
      type: 'example',
      kicker: '3-MISOL',
      title: "Birlashgan guruh o'rtachasi",
      label: 'SPR SAVOLI',
      question: r`Class A has 20 students with a mean score of 80. Class B has 30 students with a mean score of 70. What is the mean score of all 50 students?`,
      steps: [
        {m: r`20\cdot80=1600,\quad30\cdot70=2100`, note: r`yig'indilarga o'tamiz`},
        {m: r`\frac{1600+2100}{50}=\frac{3700}{50}`},
        {m: r`=74`},
      ],
      answer: r`$74$`,
      tip: r`$\frac{80+70}{2}=75$ — xato: guruhlar hajmi har xil, kattaroq guruh og'irroq.`,
      say: [
        r`Uchinchi misol. A sinfda yigirma o'quvchi, o'rtacha ball sakson. B sinfda o'ttiz o'quvchi, o'rtacha yetmish. Ellik o'quvchining umumiy o'rtachasi qancha?`,
        r`O'rtachalarni to'g'ridan-to'g'ri qo'shib bo'lmaydi — yig'indilarga o'tamiz: bir ming olti yuz va ikki ming bir yuz.`,
        r`Umumiy yig'indi uch ming yetti yuz, ellikka bo'lamiz.`,
        r`Yetmish to'rt.`,
        r`Javob: yetmish to'rt.`,
        r`Yetmish besh — oddiy o'rtacha — xato, chunki B sinf kattaroq va natijani o'ziga qarab tortadi.`,
      ],
    },
    {
      type: 'example',
      kicker: '4-MISOL',
      title: "Yetishmayotgan qiymat",
      label: 'SPR SAVOLI',
      question: r`The mean of five numbers is 12. Four of the numbers are 10, 15, 8, and 14. What is the fifth number?`,
      steps: [
        {m: r`5\cdot12=60`, note: r`umumiy yig'indi`},
        {m: r`10+15+8+14=47`},
        {m: r`60-47=13`},
      ],
      answer: r`$13$`,
      say: [
        r`To'rtinchi misol. Beshta sonning o'rtachasi o'n ikki. To'rttasi: o'n, o'n besh, sakkiz, o'n to'rt. Beshinchisi qancha?`,
        r`O'rtacha karra soni — yig'indi: besh karra o'n ikki — oltmish.`,
        r`Ma'lum to'rttasining yig'indisi — qirq yetti.`,
        r`Beshinchisi: oltmish minus qirq yetti — o'n uch.`,
        r`Javob: o'n uch. O'rtacha qiymat masalalarida har doim yig'indiga o'ting.`,
      ],
    },
    {
      type: 'table',
      kicker: 'CHASTOTA JADVALI',
      title: 'Chastota jadvalidan median',
      head: ['Ball', '$1$', '$2$', '$3$', '$4$'],
      rows: [[r`Chastota`, r`$3$`, r`$5$`, r`$8$`, r`$4$`]],
      banner: r`$n=20$: median — 10- va 11-qiymatlar o'rtachasi. $3+5=8$ tasi $\le2$, 9–16-o'rinlar — $3$. Median $=3$`,
      say: [
        r`Chastota jadvali. Ballar bir dan to'rtgacha, pastda — har bir ball necha marta uchragani.`,
        r`Bir — uch marta, ikki — besh marta, uch — sakkiz marta, to'rt — to'rt marta. Jami yigirma qiymat.`,
        r`Yigirmata qiymat — median o'ninchi va o'n birinchi qiymatlarning o'rtachasi. Birinchi sakkizta qiymat bir va ikkilardan iborat, to'qqizinchidan o'n oltinchigacha — uchlar. Demak, o'ninchi ham, o'n birinchi ham uch. Median — uch.`,
      ],
    },
    {
      type: 'trap',
      title: 'Chastota jadvalida median',
      question: r`Using the same frequency table (scores 1, 2, 3, 4 with frequencies 3, 5, 8, 4), what is the median score?`,
      wrong: r`$2.5$`,
      why: r`Faqat "Ball" qatoridagi to'rtta son ($1,2,3,4$) mediani olingan — chastotalar hisobga olinmagan.`,
      right: r`20 ta qiymat bor: 10- va 11-qiymat — ikkalasi $3$. Median **3**.`,
      say: [
        r`Tuzoq. Xuddi shu jadval bo'yicha median qancha?`,
        r`Ba'zi o'quvchilar faqat ballar qatoriga qaraydi — bir, ikki, uch, to'rt — va ikki butun besh deydi. Lekin har bir ball bir necha marta uchraydi.`,
        r`To'g'ri yechim: yigirmata qiymat, o'ninchi va o'n birinchisi — uch. Median — uch.`,
      ],
    },
    {
      type: 'compare',
      kicker: 'STANDART CHETLANISH',
      title: 'Standart chetlanish (SD) — tarqoqlik',
      cards: [
        {title: 'Kichik SD', rule: r`Qiymatlar o'rtachaga **yaqin** to'plangan`, example: r`$49,\,50,\,50,\,51$`},
        {title: 'Katta SD', rule: r`Qiymatlar **keng** tarqalgan`, example: r`$10,\,40,\,60,\,90$`},
        {title: "O'zgarishlar", rule: r`Hammaga $+k$: SD o'zgarmaydi; $\times k$: SD $\times k$`, example: r`$\{1,2,3\}\to\{11,12,13\}$: SD bir xil`},
      ],
      say: [
        r`Standart chetlanish — qiymatlar o'rtachadan qanchalik uzoqqa tarqalganini o'lchaydi. SAT uni hisoblatmaydi, faqat solishtirishni so'raydi.`,
        r`Qiymatlar o'rtachaga yaqin to'plangan bo'lsa — standart chetlanish kichik.`,
        r`Keng tarqalgan bo'lsa — katta.`,
        r`Muhim xossalar: barcha qiymatlarga bir xil son qo'shsak, o'rtacha o'zgaradi, lekin standart chetlanish o'zgarmaydi. Barcha qiymatlarni k ga ko'paytirsak, standart chetlanish ham k marta oshadi.`,
      ],
    },
    {
      type: 'example',
      kicker: 'MUSTAQIL MASHQ',
      title: "O'zingiz yeching",
      label: 'MASHQ',
      question: r`The mean of $2,\ 4,\ x,\ 10$ is 6. What is the value of $x$?`,
      steps: [
        {m: r`4\cdot6=24`},
        {m: r`2+4+10=16`},
        {m: r`x=24-16=8`},
      ],
      answer: r`$8$`,
      say: [
        r`Mustaqil mashq. Videoni to'xtating. Ikki, to'rt, x va o'nning o'rtachasi olti. X nimaga teng?`,
        r`Yig'indi: to'rt karra olti — yigirma to'rt.`,
        r`Ma'lum sonlar yig'indisi — o'n olti.`,
        r`X teng sakkiz.`,
        r`Javob: sakkiz.`,
      ],
    },
    {
      type: 'example',
      kicker: 'SAT MISOLI',
      title: 'Medianni nima oshiradi?',
      question: r`The data set $2,\ 5,\ 8,\ 11,\ 14$ has median 8. Which change would increase the median?`,
      choices: [r`Add the value 1`, r`Add the value 8`, r`Add the value 20`, r`Remove the value 14`],
      steps: [
        {m: r`A:\ 1,2,5,8,11,14\Rightarrow\frac{5+8}{2}=6.5`},
        {m: r`B:\ \ldots,8,8,\ldots\Rightarrow8`},
        {m: r`C:\ 2,5,8,11,14,20\Rightarrow\frac{8+11}{2}=9.5`},
      ],
      answer: r`C`,
      tip: r`D: $2,5,8,11\Rightarrow6.5$ — kamayadi. Medianni oshirish uchun mediandan **katta** qiymat qo'shing.`,
      say: [
        r`SAT misoli. Ikki, besh, sakkiz, o'n bir, o'n to'rt — median sakkiz. Which change would increase the median?`,
        r`A: bir qo'shsak, oltita son, o'rtadagilari besh va sakkiz — median olti butun besh. Kamaydi.`,
        r`B: sakkiz qo'shsak, o'rtadagilar sakkiz va sakkiz — median o'zgarmaydi.`,
        r`C: yigirma qo'shsak, o'rtadagilar sakkiz va o'n bir — median to'qqiz butun besh. Oshdi.`,
        r`Javob: C.`,
        r`Qoida: mediandan katta qiymat qo'shilsa, median oshadi yoki o'zgarmaydi; kichik qo'shilsa — kamayadi yoki o'zgarmaydi. Qo'shilgan son qanchalik katta ekani ahamiyatsiz — yigirma yoki ming, natija bir xil.`,
      ],
    },
    {
      type: 'cards',
      kicker: 'BOX PLOT',
      title: "Quti diagrammasi (box plot)",
      cards: [
        {title: 'Besh son', text: r`min, $Q_1$, median, $Q_3$, max`},
        {title: 'Quti', text: r`$Q_1$ dan $Q_3$ gacha — ma'lumotlarning **o'rta 50%** i`},
        {title: 'IQR', text: r`$Q_3-Q_1$ — o'rta qismning kengligi`},
        {title: 'Mo\'ylovlar', text: r`min va max gacha; range $=\max-\min$`},
      ],
      say: [
        r`Ba'zan ma'lumotlar quti diagrammasi — box plot — ko'rinishida beriladi.`,
        r`U beshta sonni ko'rsatadi: minimum, birinchi kvartil, median, uchinchi kvartil va maksimum.`,
        r`Quti birinchi kvartildan uchinchi kvartilgacha cho'ziladi — bu ma'lumotlarning o'rtadagi ellik foizi. Qutining ichidagi chiziq — median.`,
        r`Kvartillararo oraliq — IQR — uchinchi kvartil minus birinchi kvartil.`,
        r`Qutidan chiqqan "mo'ylovlar" minimum va maksimumgacha boradi, ular orasidagi masofa — oraliq. Box plotdan o'rtacha qiymatni o'qib bo'lmaydi — faqat median.`,
      ],
    },
    {
      type: 'example',
      kicker: '5-MISOL',
      title: "Qiymatni olib tashlash",
      label: 'SPR SAVOLI',
      question: r`The mean of six numbers is 20. When one number, 35, is removed, what is the mean of the remaining five numbers?`,
      steps: [
        {m: r`6\cdot20=120`},
        {m: r`120-35=85`},
        {m: r`85\div5=17`},
      ],
      answer: r`$17$`,
      say: [
        r`Beshinchi misol. Oltita sonning o'rtachasi yigirma. Ulardan o'ttiz besh olib tashlansa, qolgan beshtasining o'rtachasi qancha?`,
        r`Yig'indi: olti karra yigirma — bir yuz yigirma.`,
        r`O'ttiz beshni ayiramiz: sakson besh.`,
        r`Beshga bo'lamiz: o'n yetti.`,
        r`Javob: o'n yetti. O'rtachadan katta son olib tashlansa — o'rtacha kamayadi. Bu mantiqiy tekshiruv.`,
      ],
    },
    {
      type: 'example',
      kicker: 'SAT MISOLI',
      title: 'Eng katta standart chetlanish',
      question: r`Which data set has the greatest standard deviation?`,
      choices: [r`$5,5,5,5$`, r`$4,5,6,5$`, r`$1,5,9,5$`, r`$10,10,11,11$`],
      steps: [
        {m: r`A:\ \text{SD}=0`, note: r`hammasi bir xil`},
        {m: r`C:\ 1\ \text{va}\ 9\ \text{— o'rtachadan 4 uzoqda}`, note: r`eng tarqoq`},
      ],
      answer: r`C`,
      tip: r`D ning qiymatlari katta, lekin **tarqoqligi** kichik — SD qiymatlar kattaligiga emas, tarqalishiga bog'liq.`,
      say: [
        r`SAT misoli. Which data set has the greatest standard deviation?`,
        r`A: barcha qiymatlar bir xil — standart chetlanish nol.`,
        r`C: bir va to'qqiz o'rtachadan to'rt birlik uzoqda — eng keng tarqalgan to'plam.`,
        r`Javob: C.`,
        r`D ning sonlari katta, lekin ular bir-biriga juda yaqin — tarqoqlik kichik. Standart chetlanish qiymatlar kattaligini emas, ularning tarqalishini o'lchaydi.`,
      ],
    },
  ],
  recap: [
    r`O'rtacha — yig'indi$/n$; median — tartiblab, o'rtadagisi`,
    r`Katta outlier: $\bar x>$ median; median barqaror`,
    r`$+k$ — SD o'zgarmaydi; tarqoq ma'lumot — katta SD`,
  ],
  homework: r`platformada statistika bo'yicha 15 ta savol`,
  recapSay: [
    r`Xulosa.`,
    r`O'rtacha — yig'indi bo'lingan soni, median — tartiblangan qatorning o'rtasi. O'rtacha masalalarida yig'indiga o'ting.`,
    r`Chetki qiymat o'rtachani o'ziga tortadi, median esa barqaror.`,
    r`Standart chetlanish — tarqoqlik: hammaga bir xil son qo'shilsa, u o'zgarmaydi.`,
    r`Hozir platformada statistika bo'yicha o'n beshta savolni yeching. Keyingi darsda grafiklar va ma'lumotlarni talqin qilishni o'rganamiz.`,
    r`Ko'rishguncha!`,
  ],
};

export default lesson;
