import {meta} from '../catalog';
import type {Lesson} from '../types';

const r = String.raw;

const lesson: Lesson = {
  ...meta(27),
  topics: ['Ehtimollik formulasi', 'Ikki tomonlama jadval', 'Shartli ehtimollik', 'Mustaqil hodisalar', 'Kutilgan son'],
  cover: [
    r`Assalomu alaykum! Yigirma yettinchi darsga xush kelibsiz. Bugungi mavzu — ehtimollik va ikki tomonlama jadvallar.`,
    r`Ehtimollikning asosiy formulasini, ikki tomonlama jadvaldan ehtimollik va shartli ehtimollik topishni, mustaqil hodisalarni va kutilgan sonni o'rganamiz.`,
  ],
  goals: [
    r`Ehtimollikni qulay/jami formulasi bilan topish`,
    r`Ikki tomonlama jadvaldan to'g'ri maxrajni tanlash`,
    r`Shartli ehtimollik: "given that…"`,
    r`Mustaqil hodisalar va kutilgan son`,
  ],
  goalsSay: [
    r`Darsning maqsadlari.`,
    r`Birinchi: ehtimollikni qulay holatlar bo'lingan jami holatlar formulasi bilan topish.`,
    r`Ikkinchi: ikki tomonlama jadvaldan ehtimollik topishda to'g'ri maxrajni tanlash — eng muhim ko'nikma.`,
    r`Uchinchi: shartli ehtimollik — inglizcha "given that" yoki "of those who" savollari.`,
    r`To'rtinchi: mustaqil hodisalar ehtimolini ko'paytirish va kutilgan sonni hisoblash.`,
    r`Ikki tomonlama jadval savollari SAT'da deyarli har doim bor va ularning asosiy tuzog'i — maxraj.`,
  ],
  goalsResult: r`ehtimollik savollarida to'g'ri maxraj`,
  slides: [
    {
      type: 'formula',
      kicker: 'FORMULALAR',
      title: 'Ehtimollik formulalari',
      formulas: [
        {label: 'Ehtimollik', tex: r`P(A)=\dfrac{\text{qulay holatlar}}{\text{jami holatlar}}`, note: r`$0\le P\le1$`},
        {label: "To'ldiruvchi", tex: r`P(\text{not }A)=1-P(A)`},
        {label: 'Shartli', tex: r`P(A\mid B)=\dfrac{n(A\ \text{va}\ B)}{n(B)}`, note: r`maxraj — **shart** guruhi`},
      ],
      say: [
        r`Uchta formula.`,
        r`Ehtimollik — qulay holatlar soni bo'lingan barcha holatlar soni. U doim nol va bir orasida.`,
        r`Hodisa ro'y bermasligi ehtimoli — bir minus uning ehtimoli.`,
        r`Shartli ehtimollik: B ro'y bergani ma'lum bo'lsa, A ning ehtimoli — A va B birga bo'lgan holatlar bo'lingan B holatlari soni. Maxrajda — shart qo'yilgan guruh.`,
      ],
    },
    {
      type: 'table',
      kicker: 'IKKI TOMONLAMA JADVAL',
      title: "Matematikani yoqtirasizmi? (100 o'quvchi)",
      head: ['', 'Ha', "Yo'q", 'Jami'],
      rows: [
        [r`10-sinf`, r`$30$`, r`$20$`, r`$50$`],
        [r`11-sinf`, r`$25$`, r`$25$`, r`$50$`],
        [r`Jami`, r`$55$`, r`$45$`, r`$100$`],
      ],
      say: [
        r`Ikki tomonlama jadval. Yuz o'quvchidan matematikani yoqtirasizmi deb so'raldi. Qatorlarda — sinflar, ustunlarda — javoblar.`,
        r`O'ninchi sinf: o'ttiz "ha", yigirma "yo'q", jami ellik.`,
        r`O'n birinchi sinf: yigirma besh va yigirma besh, jami ellik.`,
        r`Oxirgi qator — jami: ellik besh "ha", qirq besh "yo'q", hammasi yuz. Endi bu jadval bo'yicha uch xil savol beramiz.`,
      ],
    },
    {
      type: 'example',
      kicker: '1-SAVOL',
      title: 'Oddiy ehtimollik',
      label: 'SPR SAVOLI',
      question: r`If one of the 100 students is selected at random, what is the probability that the student likes math?`,
      steps: [
        {m: r`P=\frac{55}{100}`, note: r`maxraj — **hamma** o'quvchilar`},
        {m: r`=0.55`},
      ],
      answer: r`$0.55$ yoki $11/20$`,
      say: [
        r`Birinchi savol. Yuz o'quvchidan tasodifan biri tanlanadi. U matematikani yoqtirishi ehtimoli qancha?`,
        r`Shart yo'q — maxraj barcha o'quvchilar, yuz. Qulay holatlar — ellik besh.`,
        r`Ellik besh yuzdan — nol butun ellik besh.`,
        r`Javob: nol butun ellik besh, yoki o'n bir yigirmadan.`,
      ],
    },
    {
      type: 'example',
      kicker: '2-SAVOL',
      title: 'Shartli ehtimollik',
      label: 'SPR SAVOLI',
      question: r`If a 10th-grade student is selected at random, what is the probability that the student likes math?`,
      steps: [
        {m: r`\text{shart: 10-sinf}\Rightarrow\text{maxraj }50`, note: r`faqat shu qator`},
        {m: r`P=\frac{30}{50}=0.6`},
      ],
      answer: r`$0.6$`,
      say: [
        r`Ikkinchi savol. Tasodifan o'ninchi sinf o'quvchisi tanlanadi. U matematikani yoqtirishi ehtimoli qancha?`,
        r`Endi shart bor: o'quvchi o'ninchi sinfdan. Demak, faqat o'ninchi sinf qatoriga qaraymiz — maxraj ellik.`,
        r`Ulardan o'ttiz nafari "ha": o'ttiz bo'lingan ellik — nol butun olti.`,
        r`Javob: nol butun olti.`,
      ],
    },
    {
      type: 'example',
      kicker: '3-SAVOL',
      title: 'Teskari shart',
      label: 'SPR SAVOLI',
      question: r`If a student who likes math is selected at random, what is the probability that the student is in 10th grade?`,
      steps: [
        {m: r`\text{shart: "Ha"}\Rightarrow\text{maxraj }55`, note: r`endi — ustun`},
        {m: r`P=\frac{30}{55}=\frac{6}{11}`},
      ],
      answer: r`$6/11$`,
      tip: r`Surat ikkala savolda ham $30$, lekin maxraj har xil: $50$ va $55$. Hammasi **shartga** bog'liq.`,
      say: [
        r`Uchinchi savol — teskari shart. Matematikani yoqtiradigan o'quvchi tanlansa, uning o'ninchi sinfdan bo'lishi ehtimoli qancha?`,
        r`Endi shart — "ha" javobi. Maxraj — "ha" ustunining jami: ellik besh.`,
        r`Ulardan o'ttiztasi o'ninchi sinfdan: o'ttiz bo'lingan ellik besh — olti o'n birdan.`,
        r`Javob: olti o'n birdan.`,
        r`E'tibor bering: ikkinchi va uchinchi savollarda surat bir xil — o'ttiz. Lekin maxraj shartga qarab ellik yoki ellik besh. Bu SAT'ning asosiy tuzog'i.`,
      ],
    },
    {
      type: 'trap',
      title: "Noto'g'ri maxraj",
      question: r`Of the students who do NOT like math, what fraction are in 11th grade? (Use the table.)`,
      wrong: r`$\frac{25}{100}$ yoki $\frac{25}{50}$`,
      why: r`"Of the students who do not like math" — bu **shart**: maxraj "Yo'q" ustuni jami bo'lishi kerak.`,
      right: r`$\frac{25}{45}=$ **$\frac59$**. "Of those…", "given that…" — maxraj shu guruh.`,
      say: [
        r`Tuzoq. Of the students who do not like math, what fraction are in eleventh grade?`,
        r`Ko'pchilik yigirma beshni yuzga yoki o'n birinchi sinf jami — ellikka bo'ladi. Ikkalasi ham xato.`,
        r`"Of the students who do not like math" — bu shart. Maxraj — "yo'q" ustuni jami — qirq besh. Yigirma besh bo'lingan qirq besh — besh to'qqizdan. "Of those", "given that", "among" so'zlaridan keyingi guruh — maxraj.`,
      ],
    },
    {
      type: 'example',
      kicker: 'TAJRIBA',
      title: 'Ikki zar',
      label: 'SPR SAVOLI',
      question: r`Two fair six-sided dice are rolled. What is the probability that the sum is 7?`,
      steps: [
        {m: r`6\cdot6=36\ \text{holat}`},
        {m: r`(1,6),(2,5),(3,4),(4,3),(5,2),(6,1)`, note: r`6 ta qulay`},
        {m: r`P=\frac{6}{36}=\frac16`},
      ],
      answer: r`$1/6$`,
      say: [
        r`Klassik tajriba. Ikkita zar tashlanadi. Yig'indi yetti bo'lishi ehtimoli qancha?`,
        r`Jami holatlar: olti karra olti — o'ttiz olti.`,
        r`Yig'indisi yetti bo'lgan juftlar: bir-olti, ikki-besh, uch-to'rt, to'rt-uch, besh-ikki, olti-bir — oltita.`,
        r`Olti bo'lingan o'ttiz olti — oltidan bir.`,
        r`Javob: oltidan bir. Uch-to'rt va to'rt-uch — har xil holatlar, chunki zarlar ikki xil.`,
      ],
    },
    {
      type: 'formula',
      kicker: 'MUSTAQIL HODISALAR',
      title: "Ko'paytirish qoidasi",
      formulas: [
        {label: 'Mustaqil', tex: r`P(A\ \text{va}\ B)=P(A)\cdot P(B)`, note: r`biri ikkinchisiga ta'sir qilmaydi`},
        {label: 'Qaytarmasdan', tex: r`P=\frac{4}{10}\cdot\frac{3}{9}`, note: r`ikkinchi tanlovda jami va qulay kamayadi`},
      ],
      say: [
        r`Ikki hodisa birga ro'y berishi.`,
        r`Agar hodisalar mustaqil bo'lsa — biri ikkinchisiga ta'sir qilmasa — ehtimollar ko'paytiriladi. Masalan, tanga "gerb" va zar "olti": yarim karra oltidan bir — o'n ikkidan bir.`,
        r`Agar narsalar qaytarilmasdan tanlansa, ikkinchi tanlovda jami ham, qulay holatlar ham bittaga kamayadi. Keyingi misolda ko'ramiz.`,
      ],
    },
    {
      type: 'example',
      kicker: 'SAT MISOLI',
      title: 'Qaytarmasdan tanlash',
      question: r`A bag contains 4 red and 6 blue marbles. Two marbles are drawn at random without replacement. What is the probability that both are red?`,
      choices: [r`$\frac{4}{25}$`, r`$\frac{2}{15}$`, r`$\frac{2}{5}$`, r`$\frac{1}{6}$`],
      steps: [
        {m: r`\frac{4}{10}`, note: r`birinchisi qizil`},
        {m: r`\frac{3}{9}`, note: r`ikkinchisi qizil — 3 ta qizil, 9 ta jami qoldi`},
        {m: r`\frac{4}{10}\cdot\frac39=\frac{12}{90}=\frac{2}{15}`},
      ],
      answer: r`B`,
      tip: r`A — qaytarib tanlash ($\frac4{10}\cdot\frac4{10}$) uchun javob; "without replacement" ga e'tibor bering.`,
      say: [
        r`SAT misoli. Xaltada to'rtta qizil va oltita ko'k shar bor. Qaytarmasdan ikkita shar olinadi. Ikkalasi ham qizil bo'lishi ehtimoli qancha?`,
        r`Birinchi shar qizil: to'rt o'ndan.`,
        r`Endi xaltada uchta qizil va jami to'qqizta shar qoldi: ikkinchisi qizil — uch to'qqizdan.`,
        r`Ko'paytiramiz: o'n ikki to'qsondan — ikki o'n beshdan.`,
        r`Javob: B.`,
        r`A variant — to'rt yigirma beshdan — shar qaytarilgan holat uchun. "Without replacement" so'ziga doim e'tibor bering.`,
      ],
    },
    {
      type: 'example',
      kicker: 'KUTILGAN SON',
      title: 'Ehtimollikdan son',
      label: 'SPR SAVOLI',
      question: r`The probability that a randomly chosen light bulb is defective is 0.15. In a shipment of 400 bulbs, how many are expected to be defective?`,
      steps: [
        {m: r`400\cdot0.15`},
        {m: r`=60`},
      ],
      answer: r`$60$`,
      say: [
        r`Kutilgan son. Tasodifiy lampochka nosoz bo'lish ehtimoli nol butun o'n besh. To'rt yuzta lampochkadan nechtasi nosoz bo'lishi kutiladi?`,
        r`Kutilgan son — jami karra ehtimollik: to'rt yuz karra nol butun o'n besh.`,
        r`Oltmish.`,
        r`Javob: oltmish.`,
      ],
    },
    {
      type: 'example',
      kicker: 'MUSTAQIL MASHQ',
      title: "O'zingiz yeching",
      label: 'MASHQ',
      question: r`Using the table (100 students), what is the probability that a randomly selected student is in 11th grade AND does not like math?`,
      steps: [
        {m: r`\text{shart yo'q}\Rightarrow\text{maxraj }100`},
        {m: r`\frac{25}{100}=\frac14`},
      ],
      answer: r`$1/4$ yoki $0.25$`,
      say: [
        r`Mustaqil mashq. Videoni to'xtating. Jadval bo'yicha: tasodifiy tanlangan o'quvchi o'n birinchi sinfdan bo'lishi va matematikani yoqtirmasligi ehtimoli qancha?`,
        r`"Va" — ikkala shart birga, lekin bu shartli savol emas: tanlov hamma o'quvchilardan, maxraj yuz.`,
        r`O'n birinchi sinf va "yo'q" katagida yigirma besh: yigirma besh yuzdan — chorak.`,
        r`Javob: chorak yoki nol butun yigirma besh.`,
      ],
    },
    {
      type: 'example',
      kicker: "TO'LDIRUVCHI",
      title: '"Kamida bitta" — teskaridan',
      label: 'SPR SAVOLI',
      question: r`A fair coin is tossed 3 times. What is the probability of getting at least one head?`,
      steps: [
        {m: r`P(\text{hech bir gerb yo'q})=\left(\tfrac12\right)^3=\tfrac18`, note: r`teskari hodisa: hammasi "raqam"`},
        {m: r`P(\text{kamida bitta})=1-\tfrac18=\tfrac78`},
      ],
      answer: r`$7/8$`,
      tip: r`"At least one" ko'rsangiz — teskari hodisani ("birorta ham yo'q") hisoblab, birdan ayiring.`,
      say: [
        r`To'ldiruvchi hodisa. Tanga uch marta tashlanadi. Kamida bitta gerb tushishi ehtimoli qancha?`,
        r`To'g'ridan-to'g'ri sanash uzoq. Teskari hodisani olamiz: birorta ham gerb yo'q, ya'ni uch marta raqam. Ehtimoli — yarimning kubi — sakkizdan bir.`,
        r`Kamida bitta gerb: bir minus sakkizdan bir — yetti sakkizdan.`,
        r`Javob: yetti sakkizdan.`,
        r`Qoida: "at least one" — kamida bitta — ko'rsangiz, teskari hodisani hisoblab, birdan ayiring.`,
      ],
    },
    {
      type: 'table',
      kicker: 'YANA BIR JADVAL',
      title: 'Uy hayvoni bormi? (200 kishi)',
      head: ['', 'Ha', "Yo'q", 'Jami'],
      rows: [
        [r`30 yoshdan kichik`, r`$48$`, r`$72$`, r`$120$`],
        [r`30 va undan katta`, r`$52$`, r`$28$`, r`$80$`],
        [r`Jami`, r`$100$`, r`$100$`, r`$200$`],
      ],
      say: [
        r`Yana bir jadval: ikki yuz kishidan uy hayvoni bormi deb so'raldi, yosh guruhlari bo'yicha.`,
        r`O'ttiz yoshdan kichiklar: qirq sakkiz "ha", yetmish ikki "yo'q", jami bir yuz yigirma.`,
        r`O'ttiz va undan kattalar: ellik ikki "ha", yigirma sakkiz "yo'q", jami sakson.`,
        r`Jami: yuz va yuz. Endi bu jadval bo'yicha SAT uslubidagi savol.`,
      ],
    },
    {
      type: 'example',
      kicker: 'SAT MISOLI',
      title: 'Ikki shartli ehtimollikni solishtirish',
      question: r`Based on the table, which statement is true?`,
      choices: [r`People under 30 are more likely to own a pet`, r`People 30 or older are more likely to own a pet`, r`Both groups are equally likely to own a pet`, r`Cannot be determined`],
      steps: [
        {m: r`P(\text{Ha}\mid<30)=\frac{48}{120}=0.4`},
        {m: r`P(\text{Ha}\mid\ge30)=\frac{52}{80}=0.65`},
        {m: r`0.65>0.4`},
      ],
      answer: r`B`,
      tip: r`Sonlarni ($48$ va $52$) emas, **ulushlarni** solishtiring — guruhlar hajmi har xil.`,
      say: [
        r`Based on the table, which statement is true?`,
        r`O'ttizdan kichiklar orasida: qirq sakkiz bo'lingan bir yuz yigirma — nol butun to'rt.`,
        r`O'ttiz va kattalar orasida: ellik ikki bo'lingan sakson — nol butun oltmish besh.`,
        r`Nol butun oltmish besh kattaroq.`,
        r`Javob: B.`,
        r`Faqat sonlarni — qirq sakkiz va ellik ikkini — solishtirish yetarli emas: guruhlar hajmi har xil. Doim ulushlarni solishtiring.`,
      ],
    },
  ],
  recap: [
    r`$P=\frac{\text{qulay}}{\text{jami}}$; $P(\text{not }A)=1-P(A)$`,
    r`"Given / of those / among" — maxraj shu guruh`,
    r`Mustaqil — ko'paytiring; qaytarmasdan — maxraj kamayadi`,
  ],
  homework: r`platformada ehtimollik va jadvallar bo'yicha 15 ta savol`,
  recapSay: [
    r`Xulosa.`,
    r`Ehtimollik — qulay holatlar bo'lingan jami holatlar. Hodisa ro'y bermasligi — bir minus ehtimol.`,
    r`Ikki tomonlama jadvalda "given that", "of those", "among" so'zlaridan keyingi guruh — maxraj.`,
    r`Mustaqil hodisalarda ehtimollar ko'paytiriladi; qaytarmasdan tanlashda ikkinchi qadamda maxraj kamayadi.`,
    r`Hozir platformada ehtimollik va jadvallar bo'yicha o'n beshta savolni yeching. Keyingi darsda tanlanma, xulosa va xatolik chegarasini o'rganamiz.`,
    r`Ko'rishguncha!`,
  ],
};

export default lesson;
