import {meta} from '../catalog';
import type {Lesson} from '../types';

const r = String.raw;

const lesson: Lesson = {
  ...meta(32),
  topics: ['Uzunlik va yuza', 'Yoy uzunligi', 'Sektor yuzasi', 'Radian', 'Burchak teoremalari'],
  cover: [
    r`Assalomu alaykum! O'ttiz ikkinchi darsga xush kelibsiz. Bugungi mavzu — aylana: yoy, sektor va radian.`,
    r`Aylana uzunligi va doira yuzasini, yoy uzunligi va sektor yuzasini, gradus va radian orasidagi o'tishni hamda aylanadagi burchak teoremalarini o'rganamiz.`,
  ],
  goals: [
    r`Yoy uzunligi va sektor yuzasini proporsiya bilan topish`,
    r`Gradus $\leftrightarrow$ radian o'tkazish`,
    r`Markaziy va ichki chizilgan burchaklar`,
    r`Urinma va radius xossasini qo'llash`,
  ],
  goalsSay: [
    r`Darsning maqsadlari.`,
    r`Birinchi: yoy uzunligi va sektor yuzasini butun aylanaga nisbatan proporsiya bilan topish.`,
    r`Ikkinchi: gradusni radianga va radianni gradusga o'tkazish.`,
    r`Uchinchi: markaziy va ichki chizilgan burchaklar orasidagi bog'lanish.`,
    r`To'rtinchi: urinma radiusga perpendikulyar ekanini ishlatish.`,
    r`Aylana savollari geometriyaning eng ko'p uchraydigan qismi.`,
  ],
  goalsResult: r`aylana savollari — bitta proporsiya bilan`,
  slides: [
    {
      type: 'formula',
      kicker: 'FORMULALAR',
      title: 'Aylana va uning qismlari',
      formulas: [
        {label: 'Uzunlik / yuza', tex: r`C=2\pi r,\qquad A=\pi r^2`},
        {label: 'Yoy uzunligi', tex: r`s=\dfrac{\theta}{360^\circ}\cdot2\pi r`},
        {label: 'Sektor yuzasi', tex: r`A_{\text{sektor}}=\dfrac{\theta}{360^\circ}\cdot\pi r^2`},
      ],
      banner: r`Bitta g'oya: qism $=\frac{\theta}{360}\times$ butun. Burchak, yoy va sektor — bir xil ulush`,
      say: [
        r`Aylana formulalari.`,
        r`Aylana uzunligi — ikki pi r, doira yuzasi — pi r kvadrat.`,
        r`Yoy uzunligi — markaziy burchak bo'lingan uch yuz oltmish, karra aylana uzunligi.`,
        r`Sektor yuzasi — xuddi shu ulush, karra doira yuzasi.`,
        r`Aslida bitta g'oya: burchak aylananing qanday ulushi bo'lsa, yoy ham, sektor ham butunning shunday ulushi.`,
      ],
    },
    {
      type: 'example',
      kicker: '1-MISOL',
      title: 'Yoy uzunligi',
      label: 'SPR SAVOLI',
      question: r`A circle has radius 9. What is the length of an arc with central angle $80^\circ$? (Answer in the form $k\pi$; give $k$.)`,
      steps: [
        {m: r`\frac{80}{360}=\frac29`, note: r`ulush`},
        {m: r`\frac29\cdot2\pi\cdot9=4\pi`},
      ],
      answer: r`$k=4$`,
      say: [
        r`Birinchi misol. Radiusi to'qqiz bo'lgan aylanada markaziy burchagi sakson gradus bo'lgan yoyning uzunligi k pi. K ni toping.`,
        r`Ulush: sakson bo'lingan uch yuz oltmish — ikki to'qqizdan.`,
        r`Aylana uzunligi o'n sakkiz pi, uning ikki to'qqizdan qismi — to'rt pi.`,
        r`Javob: to'rt.`,
      ],
    },
    {
      type: 'example',
      kicker: '2-MISOL',
      title: 'Sektor yuzasi',
      label: 'SPR SAVOLI',
      question: r`A sector of a circle with radius 6 has a central angle of $120^\circ$. Its area is $k\pi$. What is $k$?`,
      steps: [
        {m: r`\frac{120}{360}=\frac13`},
        {m: r`\frac13\cdot\pi\cdot36=12\pi`},
      ],
      answer: r`$12$`,
      say: [
        r`Ikkinchi misol. Radiusi olti bo'lgan doirada markaziy burchagi bir yuz yigirma gradusli sektorning yuzasi k pi. K ni toping.`,
        r`Ulush: bir yuz yigirma bo'lingan uch yuz oltmish — uchdan bir.`,
        r`Doira yuzasi o'ttiz olti pi, uchdan biri — o'n ikki pi.`,
        r`Javob: o'n ikki.`,
      ],
    },
    {
      type: 'formula',
      kicker: 'RADIAN',
      title: 'Gradus va radian',
      formulas: [
        {label: 'Asosiy tenglik', tex: r`180^\circ=\pi\ \text{rad}`},
        {label: "O'tkazish", tex: r`\text{rad}=\text{grad}\cdot\frac{\pi}{180},\qquad\text{grad}=\text{rad}\cdot\frac{180}{\pi}`},
        {label: 'Radianda', tex: r`s=r\theta,\qquad A=\tfrac12r^2\theta`, note: r`faqat $\theta$ **radianda** bo'lsa`},
      ],
      say: [
        r`Radian — burchakning boshqa o'lchov birligi.`,
        r`Asosiy tenglik: bir yuz sakson gradus teng pi radian.`,
        r`Gradusdan radianga — pi bo'lingan bir yuz saksonga ko'paytiramiz. Radiandan gradusga — teskarisi.`,
        r`Radianda yoy uzunligi juda oddiy: r karra theta. Sektor yuzasi: yarim r kvadrat theta. Lekin bu faqat theta radianda bo'lganda ishlaydi.`,
      ],
    },
    {
      type: 'example',
      kicker: '3-MISOL',
      title: "O'tkazish",
      label: 'MISOL',
      question: r`(a) Convert $150^\circ$ to radians. (b) Convert $\dfrac{3\pi}{4}$ radians to degrees.`,
      steps: [
        {m: r`150\cdot\frac{\pi}{180}=\frac{5\pi}{6}`},
        {m: r`\frac{3\pi}{4}\cdot\frac{180}{\pi}=135^\circ`},
      ],
      answer: r`$\frac{5\pi}{6}$; $135^\circ$`,
      tip: r`Tez usul: $\pi$ o'rniga $180^\circ$ qo'ying: $\frac{3\cdot180}{4}=135$.`,
      say: [
        r`Uchinchi misol. Bir yuz ellik gradusni radianga va uch pi to'rtdan radianni gradusga o'tkazing.`,
        r`Bir yuz ellik karra pi bo'lingan bir yuz sakson — besh pi oltidan.`,
        r`Uch pi to'rtdan karra bir yuz sakson bo'lingan pi — bir yuz o'ttiz besh gradus.`,
        r`Javob ekranda.`,
        r`Tez usul: radianda pi o'rniga bir yuz sakson gradusni qo'ying — uch karra bir yuz sakson bo'lingan to'rt — bir yuz o'ttiz besh.`,
      ],
    },
    {
      type: 'example',
      kicker: 'SAT MISOLI',
      title: 'Yoydan markaziy burchak',
      question: r`In a circle of radius 10, an arc has length $5\pi$. What is the measure of its central angle, in radians?`,
      choices: [r`$\frac{\pi}{4}$`, r`$\frac{\pi}{2}$`, r`$\pi$`, r`$90$`],
      steps: [
        {m: r`s=r\theta\Rightarrow5\pi=10\theta`},
        {m: r`\theta=\frac{\pi}{2}`},
      ],
      answer: r`B`,
      tip: r`D ($90$) — gradusdagi qiymat; savol **radian** so'rayapti.`,
      say: [
        r`SAT misoli. Radiusi o'n bo'lgan aylanada yoy uzunligi besh pi. Markaziy burchak radianda qancha?`,
        r`Radianda yoy formulasi: s teng r theta. Besh pi teng o'n theta.`,
        r`Theta teng pi ikkidan.`,
        r`Javob: B.`,
        r`D variant — to'qson — gradusdagi qiymat: pi ikkidan radian aynan to'qson gradus. Savol qaysi birlikni so'rayotganiga doim qarang.`,
      ],
    },
    {
      type: 'cards',
      kicker: 'BURCHAK TEOREMALARI',
      title: 'Aylanadagi burchaklar',
      cards: [
        {title: 'Markaziy burchak', text: r`Tirayotgan yoyiga **teng**`},
        {title: 'Ichki chizilgan burchak', text: r`Tirayotgan yoyning **yarmiga** teng`},
        {title: 'Yarim aylana', text: r`Diametrga tiralgan ichki burchak — $90^\circ$`},
        {title: 'Urinma', text: r`Urinma urinish nuqtasidagi radiusga **perpendikulyar**`},
      ],
      say: [
        r`Aylanadagi burchak teoremalari.`,
        r`Markaziy burchak — uchi markazda — o'zi tirayotgan yoyning gradus o'lchoviga teng.`,
        r`Ichki chizilgan burchak — uchi aylanada — tirayotgan yoyning yarmiga teng. Demak, bir xil yoyga tiralgan ichki burchak markaziy burchakning yarmi.`,
        r`Diametrga tiralgan ichki burchak doim to'qson gradus.`,
        r`Urinma aylanaga tegib o'tgan nuqtadagi radiusga perpendikulyar. Bu to'g'ri burchakli uchburchak hosil qiladi va Pifagor ishga tushadi.`,
      ],
    },
    {
      type: 'example',
      kicker: '4-MISOL',
      title: 'Urinma va Pifagor',
      label: 'SPR SAVOLI',
      question: r`Segment $PA$ is tangent to a circle with center $O$ at point $A$. If $OA=5$ and $OP=13$, what is the length of $PA$?`,
      steps: [
        {m: r`OA\perp PA`, note: r`urinma $\perp$ radius`},
        {m: r`PA^2=13^2-5^2=144`},
        {m: r`PA=12`},
      ],
      answer: r`$12$`,
      say: [
        r`To'rtinchi misol. PA kesma O markazli aylanaga A nuqtada urinadi. OA besh, OP o'n uch. PA qancha?`,
        r`Urinma radiusga perpendikulyar — OAP to'g'ri burchakli uchburchak, to'g'ri burchak A da.`,
        r`OP — gipotenuza: PA kvadrat teng o'n uch kvadrat minus besh kvadrat — bir yuz qirq to'rt.`,
        r`PA teng o'n ikki.`,
        r`Javob: o'n ikki. Yana besh-o'n ikki-o'n uch uchligi.`,
      ],
    },
    {
      type: 'example',
      kicker: 'SAT MISOLI',
      title: 'Sektordan burchak',
      label: 'SPR SAVOLI',
      question: r`A sector of a circle with radius 6 has area $15\pi$. What is the measure, in degrees, of the sector's central angle?`,
      steps: [
        {m: r`\frac{\theta}{360}\cdot36\pi=15\pi`},
        {m: r`\theta=\frac{15\cdot360}{36}`},
        {m: r`\theta=150`},
      ],
      answer: r`$150$`,
      say: [
        r`SAT misoli. Radiusi olti bo'lgan doiraning sektori yuzasi o'n besh pi. Markaziy burchak necha gradus?`,
        r`Theta bo'lingan uch yuz oltmish karra o'ttiz olti pi teng o'n besh pi.`,
        r`Theta teng o'n besh karra uch yuz oltmish bo'lingan o'ttiz olti.`,
        r`Bir yuz ellik gradus.`,
        r`Javob: bir yuz ellik.`,
      ],
    },
    {
      type: 'trap',
      title: 'Gradusni radian formulasiga qo\'yish',
      question: r`An arc in a circle of radius 4 has central angle $45^\circ$. What is its length?`,
      wrong: r`$4\cdot45=180$`,
      why: r`$s=r\theta$ faqat **radian** uchun. $45$ gradusda berilgan.`,
      right: r`$45^\circ=\frac{\pi}{4}$: $s=4\cdot\frac{\pi}{4}=$ **$\pi$**. Yoki $\frac{45}{360}\cdot8\pi=\pi$.`,
      say: [
        r`Tuzoq. Radiusi to'rt bo'lgan aylanada markaziy burchak qirq besh gradus. Yoy uzunligi qancha?`,
        r`O'quvchi s teng r theta formulasiga qirq beshni qo'yib, bir yuz sakson deydi. Lekin bu formula faqat radian uchun.`,
        r`To'g'risi: qirq besh gradus — pi to'rtdan radian, s teng to'rt karra pi to'rtdan — pi. Yoki gradus formulasi bilan: sakkizdan bir karra sakkiz pi — pi.`,
      ],
    },
    {
      type: 'example',
      kicker: 'MUSTAQIL MASHQ',
      title: "O'zingiz yeching",
      label: 'MASHQ',
      question: r`A circle has circumference $20\pi$. Its area is $k\pi$. What is $k$?`,
      steps: [
        {m: r`2\pi r=20\pi\Rightarrow r=10`},
        {m: r`A=\pi\cdot10^2=100\pi`},
      ],
      answer: r`$100$`,
      say: [
        r`Mustaqil mashq. Videoni to'xtating. Aylana uzunligi yigirma pi. Doira yuzasi k pi. K nimaga teng?`,
        r`Ikki pi r teng yigirma pi, demak r teng o'n.`,
        r`Yuza: pi karra o'n kvadrat — yuz pi.`,
        r`Javob: yuz. Diqqat: yuzani yigirma pi kvadrat deb olish — keng tarqalgan xato.`,
      ],
    },
    {
      type: 'example',
      kicker: 'ICHKI BURCHAK',
      title: 'Ichki chizilgan va markaziy burchak',
      label: 'SPR SAVOLI',
      question: r`An inscribed angle in a circle measures $35^\circ$. What is the measure, in degrees, of the central angle that intercepts the same arc?`,
      steps: [
        {m: r`\text{ichki}=\frac12\,\text{yoy}`},
        {m: r`\text{yoy}=70^\circ=\text{markaziy}`},
      ],
      answer: r`$70$`,
      say: [
        r`Ichki burchak misoli. Ichki chizilgan burchak o'ttiz besh gradus. Xuddi shu yoyga tiralgan markaziy burchak necha gradus?`,
        r`Ichki chizilgan burchak yoyning yarmi.`,
        r`Demak, yoy yetmish gradus, markaziy burchak ham yetmish.`,
        r`Javob: yetmish.`,
      ],
    },
    {
      type: 'example',
      kicker: 'SAT MISOLI',
      title: "Bo'yalgan soha yuzasi",
      question: r`A circle is inscribed in a square with side length 10. What is the area of the region inside the square but outside the circle?`,
      choices: [r`$100-10\pi$`, r`$100-25\pi$`, r`$100-100\pi$`, r`$25\pi$`],
      steps: [
        {m: r`r=\frac{10}{2}=5`, note: r`ichki aylana diametri = kvadrat tomoni`},
        {m: r`10^2-\pi\cdot5^2`},
        {m: r`=100-25\pi`},
      ],
      answer: r`B`,
      say: [
        r`SAT misoli. Tomoni o'n bo'lgan kvadratga aylana ichki chizilgan. Kvadrat ichida, lekin doira tashqarisidagi soha yuzasi qancha?`,
        r`Ichki chizilgan aylananing diametri kvadrat tomoniga teng, radius — besh.`,
        r`Kvadrat yuzasidan doira yuzasini ayiramiz: yuz minus pi karra yigirma besh.`,
        r`Yuz minus yigirma besh pi.`,
        r`Javob: B. C variant — radius o'rniga diametrni olgan xato.`,
      ],
    },
  ],
  recap: [
    r`Yoy va sektor: $\frac{\theta}{360}\times$ butun`,
    r`$180^\circ=\pi$; $s=r\theta$ faqat radianda`,
    r`Ichki burchak = yoy/2; urinma $\perp$ radius`,
  ],
  homework: r`platformada aylana bo'yicha 12 ta savol`,
  recapSay: [
    r`Xulosa.`,
    r`Yoy uzunligi va sektor yuzasi — butunning theta bo'lingan uch yuz oltmish ulushi.`,
    r`Bir yuz sakson gradus — pi radian. S teng r theta formulasi faqat radianda ishlaydi.`,
    r`Ichki chizilgan burchak tirayotgan yoyning yarmi, urinma esa radiusga perpendikulyar.`,
    r`Hozir platformada aylana bo'yicha o'n ikkita savolni yeching. Keyingi darsda aylana tenglamasini o'rganamiz.`,
    r`Ko'rishguncha!`,
  ],
};

export default lesson;
