import {meta} from '../catalog';
import type {Lesson} from '../types';

const r = String.raw;

const lesson: Lesson = {
  ...meta(33),
  topics: ['Standart tenglama', 'Markaz va radius', "To'liq kvadrat", 'Nuqta holati', 'Diametr va urinma'],
  cover: [
    r`Assalomu alaykum! O'ttiz uchinchi darsga xush kelibsiz. Bugungi mavzu — aylana tenglamasi.`,
    r`Aylana tenglamasidan markaz va radiusni o'qishni, tenglama tuzishni, to'liq kvadratga keltirishni, nuqta aylanaga nisbatan qayerdaligini va diametr hamda urinma masalalarini o'rganamiz.`,
  ],
  goals: [
    r`Tenglamadan markaz va radiusni o'qish`,
    r`Berilgan ma'lumotdan aylana tenglamasini tuzish`,
    r`Yoyilgan tenglamani to'liq kvadrat bilan standartga keltirish`,
    r`Nuqtaning aylanaga nisbatan holatini aniqlash`,
  ],
  goalsSay: [
    r`Darsning maqsadlari.`,
    r`Birinchi: standart tenglamadan markaz va radiusni ishoralarda adashmasdan o'qish.`,
    r`Ikkinchi: markaz va nuqta yoki diametr uchlari berilganda tenglamani tuzish.`,
    r`Uchinchi: qavslari ochilgan tenglamani to'liq kvadratga keltirib, markaz va radiusni topish — SAT'ning eng qiyin aylana savoli.`,
    r`To'rtinchi: nuqta aylana ichida, ustida yoki tashqarisida ekanini aniqlash.`,
    r`Bu mavzu o'n uchinchi darsdagi to'liq kvadratga keltirish va o'ttizinchi darsdagi Pifagor teoremasini birlashtiradi.`,
  ],
  goalsResult: r`aylana tenglamasi savollari — 1 daqiqada`,
  slides: [
    {
      type: 'formula',
      kicker: 'TENGLAMA',
      title: 'Aylananing standart tenglamasi',
      formulas: [
        {label: 'Standart', tex: r`(x-h)^2+(y-k)^2=r^2`},
        {label: 'Markaz', tex: r`(h,\,k)`, note: r`qavslardagi sonlarning **teskari** ishorasi`},
        {label: 'Radius', tex: r`r=\sqrt{\text{o'ng tomon}}`, note: r`o'ng tomon — $r^2$, radius emas!`},
      ],
      banner: r`Bu tenglama — Pifagor: markazdan $(x,y)$ gacha masofa $r$ ga teng`,
      say: [
        r`Aylana tenglamasi.`,
        r`Standart ko'rinish: x minus h, kvadrat, plyus y minus k, kvadrat, teng r kvadrat.`,
        r`Markaz — h, k. Qavslardagi sonlarning ishorasi teskari olinadi: x minus ikki bo'lsa, h teng ikki; y plyus bir bo'lsa, k teng minus bir.`,
        r`Radius — o'ng tomonning kvadrat ildizi. O'ng tomon r kvadrat, radiusning o'zi emas.`,
        r`Bu tenglama aslida Pifagor teoremasi: aylanadagi har bir nuqta markazdan aynan r masofada.`,
      ],
    },
    {
      type: 'graph',
      kicker: 'GRAFIKDA',
      title: r`$(x-2)^2+(y+1)^2=9$`,
      x: [-3, 7],
      y: [-6, 4],
      items: [
        {kind: 'circle', h: 2, k: -1, r: 3, label: r`$r=3$`, note: r`Aylana: radius $\sqrt9=3$`},
        {kind: 'point', x: 2, y: -1, label: r`$(2,\,-1)$`, color: '#FFFFFF', note: r`Markaz: $x-2\Rightarrow h=2$, $y+1\Rightarrow k=-1$`},
        {kind: 'segment', from: [2, -1], to: [5, -1], dashed: true, color: '#F59E0B', note: r`Radius — markazdan aylanagacha: $3$ birlik`},
      ],
      say: [
        r`Grafikda ko'ramiz: x minus ikki, kvadrat, plyus y plyus bir, kvadrat, teng to'qqiz.`,
        r`O'ng tomon to'qqiz — radius uch.`,
        r`Markaz: x minus ikkidan — ikki, y plyus birdan — minus bir. Ishoralar teskari.`,
        r`Markazdan har qanday yo'nalishda uch birlik — aylana nuqtalari.`,
      ],
    },
    {
      type: 'example',
      kicker: '1-MISOL',
      title: "Markaz va radiusni o'qish",
      question: r`What are the center and radius of the circle $(x+3)^2+(y-4)^2=25$?`,
      choices: [r`$(3,-4)$, $25$`, r`$(-3,4)$, $5$`, r`$(-3,4)$, $25$`, r`$(3,-4)$, $5$`],
      steps: [
        {m: r`x+3=x-(-3)\Rightarrow h=-3`},
        {m: r`y-4\Rightarrow k=4`},
        {m: r`r=\sqrt{25}=5`},
      ],
      answer: r`B`,
      say: [
        r`Birinchi misol. What are the center and radius of x plus three squared plus y minus four squared equals twenty five?`,
        r`X plyus uch — bu x minus minus uch, demak h teng minus uch.`,
        r`Y minus to'rt — k teng to'rt.`,
        r`Radius — yigirma beshning ildizi — besh.`,
        r`Javob: B. Qolgan variantlar ikki xil xatoning kombinatsiyasi: ishorani teskari olmaslik va r kvadratni radius deb olish.`,
      ],
    },
    {
      type: 'example',
      kicker: '2-MISOL',
      title: 'Tenglama tuzish',
      label: 'MISOL',
      question: r`Write an equation of the circle with center $(1,\,-2)$ that passes through the point $(4,\,2)$.`,
      steps: [
        {m: r`r^2=(4-1)^2+(2+2)^2`, note: r`radius — markazdan nuqtagacha masofa`},
        {m: r`=9+16=25`},
        {m: r`(x-1)^2+(y+2)^2=25`},
      ],
      answer: r`$(x-1)^2+(y+2)^2=25$`,
      say: [
        r`Ikkinchi misol. Markazi bir, minus ikki bo'lgan va to'rt, ikki nuqtadan o'tuvchi aylana tenglamasini yozing.`,
        r`Radius — markazdan berilgan nuqtagacha masofa: r kvadrat teng uch kvadrat plyus to'rt kvadrat.`,
        r`To'qqiz plyus o'n olti — yigirma besh. Ildizni olish shart emas, tenglamaga r kvadrat kerak.`,
        r`Tenglama: x minus bir, kvadrat, plyus y plyus ikki, kvadrat, teng yigirma besh.`,
        r`Javob ekranda.`,
      ],
    },
    {
      type: 'example',
      kicker: "TO'LIQ KVADRAT",
      title: 'Yoyilgan tenglamadan markaz va radius',
      label: 'SPR SAVOLI',
      question: r`The equation $x^2+y^2-6x+4y-12=0$ defines a circle. What is its radius?`,
      steps: [
        {m: r`(x^2-6x)+(y^2+4y)=12`, note: r`$x$ va $y$ larni guruhlaymiz`},
        {m: r`(x^2-6x+9)+(y^2+4y+4)=12+9+4`, note: r`$\left(\frac{-6}{2}\right)^2=9$, $\left(\frac{4}{2}\right)^2=4$`},
        {m: r`(x-3)^2+(y+2)^2=25`},
        {m: r`r=5,\quad\text{markaz }(3,\,-2)`},
      ],
      answer: r`$5$`,
      tip: r`Ikkala tomonga qo'shishni unutmang: $12+9+4$. Eng ko'p xato — faqat chap tomonga qo'shish.`,
      say: [
        r`Eng qiyin tur. The equation x squared plus y squared minus six x plus four y minus twelve equals zero defines a circle. What is its radius?`,
        r`X li va y li hadlarni guruhlaymiz, ozod hadni o'ngga o'tkazamiz.`,
        r`Har bir guruhni to'liq kvadratga to'ldiramiz: minus oltining yarmi minus uch, kvadrati to'qqiz; to'rtning yarmi ikki, kvadrati to'rt. Ikkala tomonga ham to'qqiz va to'rt qo'shamiz.`,
        r`Natija: x minus uch, kvadrat, plyus y plyus ikki, kvadrat, teng yigirma besh.`,
        r`Radius besh, markaz — uch, minus ikki.`,
        r`Javob: besh.`,
        r`Eng ko'p xato — to'qqiz va to'rtni faqat chap tomonga qo'shib, o'ng tomonni o'zgartirmaslik.`,
      ],
    },
    {
      type: 'trap',
      title: 'Markaz ishorasi va radius',
      question: r`What are the center and radius of $(x+2)^2+(y-5)^2=16$?`,
      wrong: r`$(2,\,-5)$, $r=16$`,
      why: r`Ikki xato: ishoralar teskari olinmagan va $r^2$ radius deb olingan.`,
      right: r`Markaz **$(-2,\,5)$**, radius **$\sqrt{16}=4$**.`,
      say: [
        r`Tuzoq. Center and radius of x plus two squared plus y minus five squared equals sixteen?`,
        r`Ikki keng tarqalgan xato birga: markazni ikki, minus besh deb olish — ishoralar teskari olinmagan — va radiusni o'n olti deyish.`,
        r`To'g'risi: markaz minus ikki, besh; radius o'n oltining ildizi — to'rt.`,
      ],
    },
    {
      type: 'example',
      kicker: 'SAT MISOLI',
      title: "To'liq kvadrat: yana bir misol",
      question: r`The graph of $x^2+y^2+8x-10y=8$ is a circle. What is the length of its radius?`,
      choices: [r`$\sqrt8$`, r`$7$`, r`$49$`, r`$\sqrt{41}$`],
      steps: [
        {m: r`(x+4)^2-16+(y-5)^2-25=8`},
        {m: r`(x+4)^2+(y-5)^2=49`},
        {m: r`r=7`},
      ],
      answer: r`B`,
      say: [
        r`SAT misoli. X kvadrat plyus y kvadrat plyus sakkiz x minus o'n y teng sakkiz — aylana. Radiusi qancha?`,
        r`To'liq kvadratlar: sakkizning yarmi to'rt — o'n olti; minus o'nning yarmi minus besh — yigirma besh.`,
        r`O'ng tomon: sakkiz plyus o'n olti plyus yigirma besh — qirq to'qqiz.`,
        r`Radius yetti.`,
        r`Javob: B. C — r kvadratni radius deb olgan, A — to'liq kvadratni umuman qilmagan xato.`,
      ],
    },
    {
      type: 'example',
      kicker: 'DIAMETR',
      title: 'Diametr uchlaridan aylana',
      label: 'MISOL',
      question: r`The endpoints of a diameter of a circle are $(-1,\,2)$ and $(5,\,10)$. Find the center and radius.`,
      steps: [
        {m: r`\text{markaz}=\left(\frac{-1+5}{2},\ \frac{2+10}{2}\right)=(2,\,6)`, note: r`o'rta nuqta`},
        {m: r`d=\sqrt{6^2+8^2}=10`, note: r`diametr uzunligi`},
        {m: r`r=5`},
      ],
      answer: r`$(2,6)$, $r=5$`,
      say: [
        r`Diametr masalasi. Diametrning uchlari minus bir, ikki va besh, o'n. Markaz va radiusni toping.`,
        r`Markaz — diametrning o'rtasi: x lar yig'indisining yarmi — ikki, y lar yig'indisining yarmi — olti.`,
        r`Diametr uzunligi: farqlar olti va sakkiz, Pifagor bilan — o'n.`,
        r`Radius — yarmi — besh.`,
        r`Javob: markaz ikki, olti; radius besh. Tenglama: x minus ikki, kvadrat, plyus y minus olti, kvadrat, teng yigirma besh.`,
      ],
    },
    {
      type: 'example',
      kicker: 'NUQTA HOLATI',
      title: 'Ichida, ustida yoki tashqarida?',
      question: r`Is the point $(1,\,1)$ inside, on, or outside the circle $(x-2)^2+(y-3)^2=9$?`,
      choices: [r`Inside`, r`On`, r`Outside`, r`Cannot be determined`],
      steps: [
        {m: r`(1-2)^2+(1-3)^2=1+4=5`},
        {m: r`5<9`, note: r`$<r^2$ — ichida, $=r^2$ — ustida, $>r^2$ — tashqarida`},
      ],
      answer: r`A`,
      say: [
        r`Nuqta holati. Bir, bir nuqta x minus ikki, kvadrat, plyus y minus uch, kvadrat, teng to'qqiz aylanaga nisbatan qayerda?`,
        r`Nuqtani chap tomonga qo'yamiz: bir plyus to'rt — besh.`,
        r`Besh to'qqizdan kichik — nuqta markazga radiusdan yaqinroq, ya'ni ichida. Teng bo'lsa — aylana ustida, katta bo'lsa — tashqarida.`,
        r`Javob: A.`,
      ],
    },
    {
      type: 'example',
      kicker: 'URINMA',
      title: "O'qqa urinuvchi aylana",
      label: 'SPR SAVOLI',
      question: r`A circle with center $(3,\,-4)$ is tangent to the $x$-axis. What is the radius of the circle?`,
      steps: [
        {m: r`\text{markazdan }x\text{-o'qigacha masofa}=|-4|`},
        {m: r`r=4`},
      ],
      answer: r`$4$`,
      tip: r`$y$-o'qiga urinsa — radius $|h|=3$ bo'lardi.`,
      say: [
        r`Urinma. Markazi uch, minus to'rt bo'lgan aylana x o'qiga urinadi. Radiusi qancha?`,
        r`Aylana x o'qiga tegsa, radius markazdan x o'qigacha bo'lgan masofaga teng — y koordinataning moduli.`,
        r`Radius to'rt.`,
        r`Javob: to'rt.`,
        r`Agar aylana y o'qiga urinsa, radius x koordinataning moduli — uch bo'lardi. Qaysi o'qqa urinishiga qarab kerakli koordinatani oling.`,
      ],
    },
    {
      type: 'example',
      kicker: 'MUSTAQIL MASHQ',
      title: "O'zingiz yeching",
      label: 'MASHQ',
      question: r`What is the radius of the circle $x^2+y^2-10x=0$?`,
      steps: [
        {m: r`(x^2-10x+25)+y^2=25`},
        {m: r`(x-5)^2+y^2=25`},
        {m: r`r=5`},
      ],
      answer: r`$5$`,
      say: [
        r`Mustaqil mashq. Videoni to'xtating. X kvadrat plyus y kvadrat minus o'n x teng nol aylananing radiusi qancha?`,
        r`X li hadlarni to'liq kvadratga to'ldiramiz: minus o'nning yarmi minus besh, kvadrati yigirma besh — ikkala tomonga qo'shamiz.`,
        r`X minus besh, kvadrat, plyus y kvadrat teng yigirma besh.`,
        r`Radius besh, markaz — besh, nol.`,
        r`Javob: besh.`,
      ],
    },
  ],
  recap: [
    r`$(x-h)^2+(y-k)^2=r^2$: markaz — teskari ishora, $r=\sqrt{\ }$`,
    r`Yoyilgan tenglama — to'liq kvadrat, **ikkala** tomonga qo'shing`,
    r`Nuqtani qo'ying: $<r^2$ ichida, $=r^2$ ustida, $>r^2$ tashqarida`,
  ],
  homework: r`platformada aylana tenglamasi bo'yicha 12 ta savol`,
  recapSay: [
    r`Xulosa.`,
    r`Aylana tenglamasida markaz — qavslardagi sonlarning teskari ishorasi, radius — o'ng tomonning ildizi.`,
    r`Yoyilgan tenglamani to'liq kvadratga keltiring va qo'shilgan sonlarni ikkala tomonga ham qo'shing.`,
    r`Nuqtaning holati: chap tomonga qo'ying va r kvadrat bilan solishtiring.`,
    r`Hozir platformada aylana tenglamasi bo'yicha o'n ikkita savolni yeching. Keyingi darsda yuza va hajmni o'rganamiz.`,
    r`Ko'rishguncha!`,
  ],
};

export default lesson;
