import {meta} from '../catalog';
import type {Lesson} from '../types';

const r = String.raw;

const lesson: Lesson = {
  ...meta(34),
  topics: ['Yuza formulalari', 'Hajm formulalari', 'Masshtab', 'Murakkab shakllar', 'Sirt yuzasi'],
  cover: [
    r`Assalomu alaykum! O'ttiz to'rtinchi darsga xush kelibsiz. Bu Geometriya modulining yakuniy darsi. Mavzu — yuza va hajm.`,
    r`Asosiy yuza va hajm formulalarini, formulalar varag'idan foydalanishni, o'lcham o'zgarganda hajm qanday o'zgarishini, murakkab shakllarni va sirt yuzasini o'rganamiz.`,
  ],
  goals: [
    r`Yuza formulalarini to'g'ri qo'llash`,
    r`Silindr, konus, shar, prizma hajmini topish`,
    r`O'lcham o'zgarganda hajm o'zgarishini hisoblash`,
    r`Murakkab masalalarda formulalarni birlashtirish`,
  ],
  goalsSay: [
    r`Darsning maqsadlari.`,
    r`Birinchi: asosiy tekis shakllar yuzalarini to'g'ri hisoblash.`,
    r`Ikkinchi: silindr, konus, shar va prizma hajmini topish.`,
    r`Uchinchi: radius yoki balandlik o'zgarganda hajm necha marta o'zgarishini topish.`,
    r`To'rtinchi: suyuqlikni bir idishdan boshqasiga quyish kabi murakkab masalalarni yechish.`,
    r`Bu formulalarning deyarli barchasi SAT'ning formulalar varag'ida berilgan — asosiysi ularni to'g'ri qo'llash.`,
  ],
  goalsResult: r`Geometriya moduli yakunlandi`,
  slides: [
    {
      type: 'formula',
      kicker: 'YUZALAR',
      title: 'Tekis shakllar yuzasi',
      formulas: [
        {label: "To'rtburchak / uchburchak", tex: r`A=lw,\qquad A=\tfrac12bh`, note: r`$h$ — asosga **perpendikulyar** balandlik`},
        {label: 'Trapetsiya', tex: r`A=\tfrac12(a+b)h`},
        {label: 'Doira', tex: r`A=\pi r^2`},
      ],
      say: [
        r`Tekis shakllarning yuzalari.`,
        r`To'g'ri to'rtburchak — bo'yi karra eni. Uchburchak — yarim asos karra balandlik. Balandlik asosga perpendikulyar bo'lishi shart — qiya tomon emas.`,
        r`Trapetsiya — ikki asos yig'indisining yarmi karra balandlik.`,
        r`Doira — pi r kvadrat.`,
      ],
    },
    {
      type: 'formula',
      kicker: 'HAJMLAR',
      title: 'Jismlar hajmi',
      formulas: [
        {label: 'Prizma / silindr', tex: r`V=Bh,\qquad V=\pi r^2h`, note: r`$B$ — asos yuzasi`},
        {label: 'Piramida / konus', tex: r`V=\tfrac13Bh,\qquad V=\tfrac13\pi r^2h`, note: r`xuddi shu asos va balandlikdagi prizmaning uchdan biri`},
        {label: 'Shar', tex: r`V=\tfrac43\pi r^3`},
      ],
      banner: r`Barcha formulalar SAT formulalar varag'ida bor — vazifa: qaysi biri kerakligini tanlash`,
      say: [
        r`Jismlarning hajmi.`,
        r`Prizma va silindr — asos yuzasi karra balandlik. Silindr uchun: pi r kvadrat h.`,
        r`Piramida va konus — xuddi shu asos va balandlikdagi prizma yoki silindrning uchdan biri.`,
        r`Shar — to'rt uchdan pi r kub.`,
        r`Bu formulalarning hammasi SAT'ning formulalar varag'ida beriladi. Sizning vazifangiz — kerakli formulani tanlash va to'g'ri sonlarni qo'yish.`,
      ],
    },
    {
      type: 'example',
      kicker: '1-MISOL',
      title: 'Trapetsiya yuzasi',
      label: 'SPR SAVOLI',
      question: r`A trapezoid has bases of length 6 and 10 and a height of 4. What is its area?`,
      steps: [
        {m: r`A=\tfrac12(6+10)\cdot4`},
        {m: r`=8\cdot4=32`},
      ],
      answer: r`$32$`,
      say: [
        r`Birinchi misol. Trapetsiyaning asoslari olti va o'n, balandligi to'rt. Yuzasi qancha?`,
        r`Asoslar yig'indisining yarmi — sakkiz, karra balandlik to'rt.`,
        r`O'ttiz ikki.`,
        r`Javob: o'ttiz ikki.`,
      ],
    },
    {
      type: 'example',
      kicker: '2-MISOL',
      title: 'Silindr va konus',
      label: 'MISOL',
      question: r`(a) A cylinder has radius 3 and height 10. (b) A cone has radius 6 and height 5. Find each volume in terms of $\pi$.`,
      steps: [
        {m: r`V_{\text{sil}}=\pi\cdot3^2\cdot10=90\pi`},
        {m: r`V_{\text{kon}}=\tfrac13\pi\cdot6^2\cdot5=60\pi`},
      ],
      answer: r`$90\pi$; $60\pi$`,
      tip: r`Diametr berilsa — avval yarmini oling. Formulalarga **radius** kerak.`,
      say: [
        r`Ikkinchi misol: radiusi uch, balandligi o'n bo'lgan silindr va radiusi olti, balandligi besh bo'lgan konus hajmlari.`,
        r`Silindr: pi karra to'qqiz karra o'n — to'qson pi.`,
        r`Konus: uchdan bir karra pi karra o'ttiz olti karra besh — oltmish pi.`,
        r`Javob: to'qson pi va oltmish pi.`,
        r`Eslatma: agar diametr berilsa, avval uni ikkiga bo'lib radiusni toping — bu eng ko'p uchraydigan xato.`,
      ],
    },
    {
      type: 'example',
      kicker: 'SAT MISOLI',
      title: 'Hajmdan radius',
      label: 'SPR SAVOLI',
      question: r`A sphere has a volume of $36\pi$ cubic units. What is its radius?`,
      steps: [
        {m: r`\tfrac43\pi r^3=36\pi`},
        {m: r`r^3=27`},
        {m: r`r=3`},
      ],
      answer: r`$3$`,
      say: [
        r`SAT misoli. Sharning hajmi o'ttiz olti pi. Radiusi qancha?`,
        r`To'rt uchdan pi r kub teng o'ttiz olti pi.`,
        r`Pi qisqaradi, ikkala tomonni to'rt uchdanga bo'lamiz: r kub teng yigirma yetti.`,
        r`R teng uch.`,
        r`Javob: uch.`,
      ],
    },
    {
      type: 'example',
      kicker: 'MASSHTAB',
      title: 'Radius ikki baravar oshsa',
      question: r`The radius of a cylinder is doubled and its height stays the same. By what factor does the volume increase?`,
      choices: [r`$2$`, r`$4$`, r`$6$`, r`$8$`],
      steps: [
        {m: r`V=\pi r^2h\ \to\ \pi(2r)^2h`},
        {m: r`=4\pi r^2h`, note: r`radius kvadratda`},
      ],
      answer: r`B`,
      tip: r`Uchala o'lcham ham ikki baravar bo'lsa — $2^3=8$. Faqat qaysi o'lcham o'zgarganiga qarang.`,
      say: [
        r`Masshtab. Silindr radiusi ikki baravar oshirildi, balandligi o'zgarmadi. Hajm necha marta oshadi?`,
        r`Formula: pi r kvadrat h. R o'rniga ikki r qo'yamiz.`,
        r`Ikki r ning kvadrati — to'rt r kvadrat. Hajm to'rt marta oshadi.`,
        r`Javob: B.`,
        r`Agar uchala o'lcham ham ikki baravar oshsa — sakkiz marta bo'lardi. Faqat haqiqatan o'zgargan o'lchamlarni hisobga oling.`,
      ],
    },
    {
      type: 'example',
      kicker: 'MURAKKAB MASALA',
      title: 'Suvni quyish',
      label: 'SPR SAVOLI',
      question: r`Water fills a rectangular box measuring 4 by 5 by 6 inches. All the water is poured into an empty cylinder with radius 2 inches. To the nearest thousandth of an inch, how high is the water in the cylinder?`,
      steps: [
        {m: r`V=4\cdot5\cdot6=120`},
        {m: r`\pi\cdot2^2\cdot h=120\Rightarrow h=\frac{120}{4\pi}=\frac{30}{\pi}`},
        {m: r`h\approx9.549`},
      ],
      answer: r`$9.549$`,
      say: [
        r`Murakkab masala. To'rt, besh, olti dyuymli to'g'ri burchakli qutidagi suv radiusi ikki dyuym bo'lgan bo'sh silindrga quyiladi. Silindrda suv balandligi qancha bo'ladi — mingdan birgacha?`,
        r`Suv hajmi o'zgarmaydi: to'rt karra besh karra olti — bir yuz yigirma.`,
        r`Silindrda: pi karra to'rt karra h teng bir yuz yigirma, h teng o'ttiz bo'lingan pi.`,
        r`Taxminan to'qqiz butun besh yuz qirq to'qqiz.`,
        r`Javob: to'qqiz nuqta besh to'rt to'qqiz — besh belgi, maydonga sig'adi. Asosiy g'oya: quyishda hajm saqlanadi.`,
      ],
    },
    {
      type: 'example',
      kicker: 'SIRT YUZASI',
      title: "To'g'ri burchakli parallelepiped",
      label: 'SPR SAVOLI',
      question: r`What is the surface area of a rectangular prism with dimensions 3, 4, and 5?`,
      steps: [
        {m: r`SA=2(lw+lh+wh)`, note: r`6 ta yuz, juft-juft teng`},
        {m: r`=2(12+15+20)`},
        {m: r`=94`},
      ],
      answer: r`$94$`,
      say: [
        r`Sirt yuzasi. O'lchamlari uch, to'rt, besh bo'lgan to'g'ri burchakli parallelepipedning sirt yuzasi qancha?`,
        r`Oltita yuz bor, ular juft-juft teng: ikki karra, uch karra to'rt plyus uch karra besh plyus to'rt karra besh.`,
        r`Ikki karra, o'n ikki plyus o'n besh plyus yigirma.`,
        r`To'qson to'rt.`,
        r`Javob: to'qson to'rt. Hajm — oltmish, uni sirt yuzasi bilan adashtirmang.`,
      ],
    },
    {
      type: 'trap',
      title: 'Balandlik o\'rniga yon tomon',
      question: r`An isosceles triangle has sides 13, 13, and 10. What is its area?`,
      wrong: r`$\tfrac12\cdot10\cdot13=65$`,
      why: r`$13$ — yon tomon, balandlik emas. Balandlik asosga perpendikulyar bo'lishi kerak.`,
      right: r`Balandlik asosni teng bo'ladi: $h=\sqrt{13^2-5^2}=12$. Yuza $=\tfrac12\cdot10\cdot12=$ **60**.`,
      say: [
        r`Tuzoq. Teng yonli uchburchakning tomonlari o'n uch, o'n uch va o'n. Yuzasi qancha?`,
        r`O'quvchi yarim karra o'n karra o'n uch deb, oltmish besh chiqaradi. Lekin o'n uch — yon tomon, balandlik emas.`,
        r`Balandlik asosni teng ikkiga bo'ladi: besh. Pifagor bilan: o'n uch kvadrat minus besh kvadrat — bir yuz qirq to'rt, balandlik o'n ikki. Yuza: yarim karra o'n karra o'n ikki — oltmish.`,
      ],
    },
    {
      type: 'example',
      kicker: 'MUSTAQIL MASHQ',
      title: "O'zingiz yeching",
      label: 'MASHQ',
      question: r`A cube has a volume of 64 cubic centimeters. What is its surface area, in square centimeters?`,
      steps: [
        {m: r`s^3=64\Rightarrow s=4`},
        {m: r`SA=6s^2=6\cdot16`},
        {m: r`=96`},
      ],
      answer: r`$96$`,
      say: [
        r`Mustaqil mashq. Videoni to'xtating. Kubning hajmi oltmish to'rt kub santimetr. Sirt yuzasi qancha?`,
        r`Tomon: oltmish to'rtning kub ildizi — to'rt.`,
        r`Oltita yuz, har biri o'n olti: olti karra o'n olti.`,
        r`To'qson olti.`,
        r`Javob: to'qson olti kvadrat santimetr.`,
      ],
    },
    {
      type: 'example',
      kicker: 'PIRAMIDA',
      title: 'Kvadrat asosli piramida',
      label: 'SPR SAVOLI',
      question: r`A pyramid has a square base with side length 6 and a height of 10. What is its volume?`,
      steps: [
        {m: r`B=6^2=36`, note: r`asos yuzasi`},
        {m: r`V=\tfrac13\cdot36\cdot10=120`},
      ],
      answer: r`$120$`,
      say: [
        r`Piramida. Kvadrat asosining tomoni olti, balandligi o'n. Hajmi qancha?`,
        r`Asos yuzasi: olti kvadrat — o'ttiz olti.`,
        r`Hajm: uchdan bir karra o'ttiz olti karra o'n — bir yuz yigirma.`,
        r`Javob: bir yuz yigirma. Uchdan birni unutsangiz, uch yuz oltmish chiqadi — bu ham variantlarda bo'ladi.`,
      ],
    },
    {
      type: 'example',
      kicker: 'SAT MISOLI',
      title: 'Konus va silindr',
      question: r`A cone and a cylinder have the same radius and the same height. The volume of the cylinder is $45\pi$. What is the volume of the cone?`,
      choices: [r`$15\pi$`, r`$30\pi$`, r`$45\pi$`, r`$135\pi$`],
      steps: [
        {m: r`V_{\text{kon}}=\tfrac13V_{\text{sil}}`},
        {m: r`=\tfrac13\cdot45\pi=15\pi`},
      ],
      answer: r`A`,
      say: [
        r`SAT misoli. Konus va silindrning radiusi va balandligi bir xil. Silindr hajmi qirq besh pi. Konus hajmi qancha?`,
        r`Bir xil asos va balandlikda konus silindrning uchdan biri.`,
        r`Qirq besh pi ning uchdan biri — o'n besh pi.`,
        r`Javob: A.`,
      ],
    },
    {
      type: 'example',
      kicker: 'ALGEBRA + GEOMETRIYA',
      title: "O'lchamlar tenglama orqali",
      label: 'SPR SAVOLI',
      question: r`The length of a rectangle is 3 more than its width. The area of the rectangle is 40. What is its width?`,
      steps: [
        {m: r`w(w+3)=40`},
        {m: r`w^2+3w-40=0\Rightarrow(w+8)(w-5)=0`},
        {m: r`w=5`, note: r`uzunlik manfiy bo'lmaydi`},
      ],
      answer: r`$5$`,
      say: [
        r`Algebra va geometriya birga. To'g'ri to'rtburchakning bo'yi enidan uchga ko'p, yuzasi qirq. Eni qancha?`,
        r`Eni w, bo'yi w plyus uch: w karra w plyus uch teng qirq.`,
        r`Kvadrat tenglama: w kvadrat plyus uch w minus qirq teng nol, ajratsak — w plyus sakkiz karra w minus besh.`,
        r`Minus sakkiz — uzunlik bo'la olmaydi, demak eni besh.`,
        r`Javob: besh.`,
      ],
    },
    {
      type: 'example',
      kicker: 'MASSHTAB',
      title: 'Shar radiusi yarmiga kamaysa',
      question: r`The radius of a sphere is halved. The new volume is what fraction of the original volume?`,
      choices: [r`$\frac12$`, r`$\frac14$`, r`$\frac16$`, r`$\frac18$`],
      steps: [
        {m: r`V\propto r^3`},
        {m: r`\left(\tfrac12\right)^3=\tfrac18`},
      ],
      answer: r`D`,
      say: [
        r`Masshtab. Shar radiusi ikki marta kamaytirildi. Yangi hajm dastlabkisining qancha qismi?`,
        r`Shar hajmi radiusning kubiga proporsional.`,
        r`Yarimning kubi — sakkizdan bir.`,
        r`Javob: D. B — to'rtdan bir — sirt yuzasi uchun bo'lardi.`,
      ],
    },
  ],
  recap: [
    r`Uchburchak: $\tfrac12bh$ — $h$ perpendikulyar; formulalarga radius`,
    r`Konus/piramida $=\tfrac13$ silindr/prizma; shar $\tfrac43\pi r^3$`,
    r`Radius $\times2$ $\Rightarrow$ silindr hajmi $\times4$; quyishda hajm saqlanadi`,
  ],
  homework: r`platformada Geometriya moduli bo'yicha 20 ta aralash savol`,
  recapSay: [
    r`Xulosa.`,
    r`Uchburchak yuzasida balandlik asosga perpendikulyar. Formulalarga radius qo'yiladi, diametr emas.`,
    r`Konus va piramida — silindr va prizmaning uchdan biri. Shar — to'rt uchdan pi r kub.`,
    r`Silindr radiusi ikki baravar oshsa, hajm to'rt baravar oshadi. Suyuqlik quyilganda hajm saqlanadi.`,
    r`Hozir platformada Geometriya moduli bo'yicha yigirmata aralash savolni yeching. Keyingi darsdan yakuniy strategiya moduli boshlanadi: 750 plyus uchun qiyin savollar.`,
    r`Ko'rishguncha!`,
  ],
};

export default lesson;
