import {meta} from '../catalog';
import type {Lesson} from '../types';

const r = String.raw;

const lesson: Lesson = {
  ...meta(35),
  topics: ['Son qo\'yish', 'Variantdan yechish', 'Desmos hiylalari', 'Tuzilmani ko\'rish', '"Must be" savollari'],
  cover: [
    r`Assalomu alaykum! O'ttiz beshinchi darsga xush kelibsiz. Endi yakuniy strategiya moduli. Bugungi mavzu — 750 plyus uchun qiyin savollar strategiyasi.`,
    r`Qiyin savollarni yechishning to'rt universal qurolini — son qo'yish, variantlardan yechish, Desmos va tuzilmani ko'rishni — hamda ikkinchi qiyin moduldagi tipik tuzoqlarni o'rganamiz.`,
  ],
  goals: [
    r`Harfli savollarda son qo'yish usuli`,
    r`Variantlarni tenglamaga qo'yib yechish`,
    r`Desmos bilan algebrani chetlab o'tish`,
    r`Ifoda tuzilmasini ko'rib, qisqa yo'l topish`,
  ],
  goalsSay: [
    r`Darsning maqsadlari.`,
    r`Birinchi: harflar bilan to'la savollarda oddiy sonlar qo'yib, javobni tez topish.`,
    r`Ikkinchi: variantlarni tenglamaga qo'yib, teskari yo'ldan yechish.`,
    r`Uchinchi: Desmos bilan murakkab algebradan qochish.`,
    r`To'rtinchi: ifoda tuzilmasini ko'rib, uzun hisob-kitobsiz javob topish.`,
    r`Yetti yuz ellik va undan yuqori ball qiyin moduldagi savollarning deyarli hammasini yechishni talab qiladi — bu qurollar aynan shu uchun.`,
  ],
  goalsResult: r`qiyin modulda ham bosimsiz ishlash`,
  slides: [
    {
      type: 'cards',
      kicker: 'QUROLLAR',
      title: "Qiyin savollar uchun 4 qurol",
      cards: [
        {title: "Son qo'yish", text: r`Harflar o'rniga oddiy sonlar ($2$, $3$, $10$) qo'ying va variantlarni tekshiring`, icon: 'calc'},
        {title: 'Variantdan yechish', text: r`Variantlarni tenglamaga qo'ying — o'rtadagisidan boshlang`, icon: 'flag'},
        {title: 'Desmos', text: r`Tenglama, sistema, parametr — grafik bilan`, icon: 'chart'},
        {title: 'Tuzilma', text: r`$(x+y)^2$, $a^2-b^2$, karralilik — qisqa yo'lni qidiring`, icon: 'bulb'},
      ],
      say: [
        r`Qiyin savollar uchun to'rtta universal qurol.`,
        r`Son qo'yish: savolda harflar ko'p bo'lsa, ular o'rniga oddiy sonlar qo'yib, variantlarni tekshiring.`,
        r`Variantdan yechish: variantlar son bo'lsa, ularni tenglamaga qo'yib ko'ring. O'rtadagi variantdan boshlang — natijaga qarab katta yoki kichigiga o'tasiz.`,
        r`Desmos: tenglama, sistema yoki parametrli savollarni grafik orqali yeching.`,
        r`Tuzilma: ifodada tanish shablon — yig'indi kvadrati, kvadratlar ayirmasi, karralilik — bormi? Ko'pincha javob bir qadamda chiqadi.`,
      ],
    },
    {
      type: 'example',
      kicker: "SON QO'YISH",
      title: 'Harflar o\'rniga sonlar',
      question: r`If $a=2b$ and $b>0$, which of the following is equivalent to $\dfrac{a^2-b^2}{a+b}$?`,
      choices: [r`$b$`, r`$2b$`, r`$3b$`, r`$a+b$`],
      steps: [
        {m: r`b=1,\ a=2`, note: r`oddiy sonlar tanlaymiz`},
        {m: r`\frac{4-1}{2+1}=1`},
        {m: r`A:\ b=1\ \checkmark`, note: r`faqat A $1$ beradi`},
      ],
      answer: r`A`,
      tip: r`Algebra bilan: $\frac{(a-b)(a+b)}{a+b}=a-b=2b-b=b$. Ikkalasi ham to'g'ri — tezini tanlang.`,
      say: [
        r`Son qo'yish usuli. If a equals two b and b is positive, which is equivalent to a squared minus b squared over a plus b?`,
        r`Oddiy sonlar tanlaymiz: b teng bir, demak a teng ikki.`,
        r`Ifoda: to'rt minus bir, bo'lingan uch — bir.`,
        r`Endi variantlarga b teng bir, a teng ikki qo'yamiz: A — bir, B — ikki, C — uch, D — uch. Faqat A to'g'ri keladi.`,
        r`Javob: A.`,
        r`Algebra bilan ham tez: kvadratlar ayirmasi, a minus b, ya'ni b. Son qo'yish esa algebra qiyin bo'lganda ham ishlaydi. Faqat nol va birdan qochishga harakat qiling — ular ba'zan bir nechta variantni to'g'ri qilib qo'yadi.`,
      ],
    },
    {
      type: 'example',
      kicker: 'VARIANTDAN YECHISH',
      title: 'Teskari yo\'l',
      question: r`When a number is increased by 20% and the result is decreased by 10, the final value is 98. What is the number?`,
      choices: [r`$80$`, r`$90$`, r`$100$`, r`$120$`],
      steps: [
        {m: r`C:\ 100\cdot1.2-10=110\ \text{— katta}`, note: r`o'rtadagidan boshlaymiz`},
        {m: r`B:\ 90\cdot1.2-10=98\ \checkmark`},
      ],
      answer: r`B`,
      say: [
        r`Variantdan yechish. Son yigirma foizga oshirilib, natijadan o'n ayirilsa, to'qson sakkiz chiqadi. Son qancha?`,
        r`Tenglama tuzish o'rniga variantlarni sinaymiz. O'rtadagi variantlardan biri — yuz: bir yuz yigirma minus o'n — bir yuz o'n. Kerakli natijadan katta, demak kichikroq son kerak.`,
        r`To'qson: bir yuz sakkiz minus o'n — to'qson sakkiz. To'g'ri!`,
        r`Javob: B. Ikki urinishda topildi.`,
      ],
    },
    {
      type: 'example',
      kicker: 'DESMOS',
      title: 'Kub tenglamaning yechimlari soni',
      question: r`How many real solutions does the equation $x^3-3x=1$ have?`,
      choices: [r`Zero`, r`One`, r`Two`, r`Three`],
      steps: [
        {m: r`y=x^3-3x,\quad y=1`, note: r`Desmos'da ikkala tomonni chizamiz`},
        {m: r`\text{kesishishlar: }x\approx-1.53,\ -0.35,\ 1.88`},
      ],
      answer: r`D`,
      tip: r`Algebraik yo'l bu yerda juda qiyin — Desmos 15 soniyada javob beradi.`,
      say: [
        r`Desmos. How many real solutions does x cubed minus three x equals one have?`,
        r`Kub tenglamani algebraik yechish SAT darajasidan tashqarida. Desmos'da chap tomonni va y teng birni chizamiz.`,
        r`Chiziq kub grafigini uch nuqtada kesadi.`,
        r`Javob: D — uchta yechim.`,
        r`Algebraik yo'l qiyin bo'lsa, Desmos o'n besh soniyada javob beradi. Qiyin modulda Desmos — eng yaqin do'stingiz.`,
      ],
    },
    {
      type: 'example',
      kicker: 'TUZILMA',
      title: 'Yig\'indi kvadrati',
      label: 'SPR SAVOLI',
      question: r`If $(x+y)^2=49$ and $xy=10$, what is the value of $x^2+y^2$?`,
      steps: [
        {m: r`(x+y)^2=x^2+2xy+y^2`},
        {m: r`49=x^2+y^2+20`},
        {m: r`x^2+y^2=29`},
      ],
      answer: r`$29$`,
      say: [
        r`Tuzilma. If x plus y squared equals forty nine and x times y equals ten, what is x squared plus y squared?`,
        r`Yig'indi kvadratini ochamiz: x kvadrat plyus ikki x y plyus y kvadrat.`,
        r`Qirq to'qqiz teng x kvadrat plyus y kvadrat plyus yigirma.`,
        r`X kvadrat plyus y kvadrat — yigirma to'qqiz.`,
        r`Javob: yigirma to'qqiz. X va y ni topishga urinish ancha uzoq yo'l bo'lardi.`,
      ],
    },
    {
      type: 'cards',
      kicker: 'QIYIN SAVOL SHABLONLARI',
      title: 'Qiyin modulda tez-tez uchraydi',
      cards: [
        {title: '"For all $x$"', text: r`Koeffitsiyentlarni tenglash (11-dars)`},
        {title: "No / infinitely many", text: r`Koeffitsiyent nisbatlari (4, 10-darslar)`},
        {title: 'Kvadratda parametr', text: r`Diskriminant, Viyet, parabola uchi (14, 15, 21)`},
        {title: 'Model talqini', text: r`Eksponensial va chiziqli modellar (8, 17)`},
        {title: "O'xshashlik va aylana", text: r`$k$, $k^2$; to'liq kvadrat (30, 33)`},
        {title: "Statistika mantig'i", text: r`Outlier, SD, xulosa chegaralari (25, 28)`},
      ],
      say: [
        r`Qiyin modulda eng ko'p uchraydigan oltita shablon. Har biri biz o'tgan darslardan.`,
        r`"For all x" — koeffitsiyentlarni tenglash.`,
        r`"No solution" yoki "infinitely many" — koeffitsiyent nisbatlari.`,
        r`Kvadrat tenglamada parametr — diskriminant, Viyet va parabola uchi.`,
        r`Modellarni talqin qilish — eksponensial va chiziqli.`,
        r`O'xshash shakllar va aylana tenglamasi.`,
        r`Va statistika mantig'i: chetki qiymat, standart chetlanish va xulosa chegaralari. Qaysi shablonda qiynalsangiz — o'sha darsni qayta ko'ring.`,
      ],
    },
    {
      type: 'example',
      kicker: 'QIYIN MISOL',
      title: 'Parabola va ildizlar',
      label: 'SPR SAVOLI',
      question: r`The graph of $f(x)=(x-a)(x-b)$ has its vertex at $x=3$. If one zero of $f$ is $x=1$, what is the value of $ab$?`,
      steps: [
        {m: r`\frac{a+b}{2}=3\Rightarrow a+b=6`, note: r`uch — ildizlar o'rtasi`},
        {m: r`a=1\Rightarrow b=5`},
        {m: r`ab=5`},
      ],
      answer: r`$5$`,
      say: [
        r`Qiyin misol. F of x teng x minus a karra x minus b grafigining uchi x teng uchda. Bir noli x teng bir. A karra b nimaga teng?`,
        r`Parabola uchi ildizlar o'rtasida: a plyus b, bo'lingan ikki, teng uch. A plyus b teng olti.`,
        r`Bitta ildiz bir bo'lsa, ikkinchisi besh.`,
        r`A karra b — besh.`,
        r`Javob: besh. Bu savol uch darsni birlashtiradi: ko'paytuvchi ko'rinishi, simmetriya va ildizlar.`,
      ],
    },
    {
      type: 'example',
      kicker: 'QIYIN MISOL',
      title: 'Eksponensial tenglama',
      label: 'SPR SAVOLI',
      question: r`If $3^{2x}=81\cdot3^{x}$, what is the value of $x$?`,
      steps: [
        {m: r`3^{2x}=3^4\cdot3^x=3^{x+4}`},
        {m: r`2x=x+4`},
        {m: r`x=4`},
      ],
      answer: r`$4$`,
      say: [
        r`Yana bir qiyin misol. If three to the two x equals eighty one times three to the x, what is x?`,
        r`Sakson bir — uchning to'rtinchi darajasi. O'ng tomon: uchning x plyus to'rt darajasi.`,
        r`Asoslar teng — darajalar teng: ikki x teng x plyus to'rt.`,
        r`X teng to'rt.`,
        r`Javob: to'rt.`,
      ],
    },
    {
      type: 'trap',
      title: '"Must be" va "could be"',
      question: r`If $x^2=16$, which of the following **must** be true?`,
      wrong: r`$x=4$`,
      why: r`$x=-4$ ham mumkin. "Must be" — **har qanday** holatda rost bo'lishi kerak.`,
      right: r`**$|x|=4$** — ikkala holatda ham rost. "Could be" bo'lsa, $4$ ham, $-4$ ham to'g'ri bo'lardi.`,
      say: [
        r`Tuzoq. If x squared equals sixteen, which must be true?`,
        r`X teng to'rt — "could be", ya'ni bo'lishi mumkin, lekin "must be" emas: x minus to'rt ham bo'lishi mumkin.`,
        r`To'g'risi: x ning moduli to'rt — bu ikkala holatda ham rost. "Must be" savollarida har bir holatni tekshiring, "could be" savollarida esa bitta mos holat yetarli.`,
      ],
    },
    {
      type: 'cards',
      kicker: 'VAQT',
      title: '2-modulda vaqt strategiyasi',
      cards: [
        {title: 'Tartib', text: r`Savollar taxminan osondan qiyinga — boshida tez, oxirida vaqt qoldiring`},
        {title: '2 daqiqa qoidasi', text: r`Qotib qolsangiz — belgilang, o'ting, qayting`},
        {title: 'Tekshiruv', text: r`SPR va "trap" savollarini oxirida qayta ko'ring`},
        {title: 'Hech qachon bo\'sh emas', text: r`Oxirgi daqiqada barcha bo'sh savollarni belgilang`},
      ],
      say: [
        r`Ikkinchi, qiyin modulda vaqt strategiyasi.`,
        r`Savollar taxminan osondan qiyinga qarab boradi. Boshidagi savollarni tez yechib, oxiridagi qiyin savollarga vaqt qoldiring.`,
        r`Ikki daqiqa qoidasi: qotib qolsangiz — belgilang, keyingisiga o'ting va keyin qayting.`,
        r`Oxirida SPR va tuzoqqa o'xshagan savollarni qayta tekshiring.`,
        r`Va hech qachon bo'sh savol qoldirmang — jarima yo'q.`,
      ],
    },
    {
      type: 'example',
      kicker: 'MUSTAQIL MASHQ',
      title: "O'zingiz yeching",
      label: 'MASHQ',
      question: r`If $x+\dfrac1x=5$, what is the value of $x^2+\dfrac{1}{x^2}$?`,
      steps: [
        {m: r`\left(x+\frac1x\right)^2=x^2+2+\frac{1}{x^2}`},
        {m: r`25=x^2+\frac1{x^2}+2`},
        {m: r`x^2+\frac1{x^2}=23`},
      ],
      answer: r`$23$`,
      say: [
        r`Mustaqil mashq — klassik qiyin savol. Videoni to'xtating. X plyus x dan bir teng besh. X kvadrat plyus x kvadratdan bir nimaga teng?`,
        r`Ikkala tomonni kvadratga oshiramiz. O'rtadagi had: ikki karra x karra x dan bir — ikki.`,
        r`Yigirma besh teng x kvadrat plyus x kvadratdan bir plyus ikki.`,
        r`Demak, yigirma uch.`,
        r`Javob: yigirma uch. Yana tuzilma: yig'indi kvadrati.`,
      ],
    },
  ],
  recap: [
    r`Son qo'ying, variantlardan yeching, Desmos'dan foydalaning`,
    r`Tuzilmani qidiring: $(x+y)^2$, $a^2-b^2$, karralilik`,
    r`"Must be" — har bir holatda; 2 daqiqa qoidasi`,
  ],
  homework: r`Bluebook'da bitta to'liq mock test (2-modul diqqat bilan)`,
  recapSay: [
    r`Xulosa.`,
    r`Qiyin savolda to'xtab qolsangiz — son qo'ying, variantlarni sinang yoki Desmos'dan foydalaning.`,
    r`Ifoda tuzilmasini qidiring: yig'indi kvadrati, kvadratlar ayirmasi, karralilik.`,
    r`"Must be" savollarida har bir holatni tekshiring va ikki daqiqa qoidasini unutmang.`,
    r`Hozir Bluebook'da bitta to'liq mock test topshiring. Keyingi — yakuniy darsda mock test natijasini tahlil qilishni va imtihon kuni rejasini o'rganamiz.`,
    r`Ko'rishguncha!`,
  ],
};

export default lesson;
